### ISSUE TITLE
Can't change font size

### ISSUE THREAD

**Issue by dmitriiweb** [johnfactotum/foliate#10]
Can't change a font size
Operating System: Manjaro Linux 
KDE Plasma Version: 5.15.5
KDE Frameworks Version: 5.58.0
Qt Version: 5.12.3
Kernel Version: 4.19.45-1-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-6200U CPU @ 2.30GHz
Memory: 7.2 GiB of RAM
![Screenshot_20190531_191842](https://user-images.githubusercontent.com/21336025/58705403-488f3f00-83d9-11e9-9e19-8540968c9f43.png)

**Comment by johnfactotum** [comment]
Are you using the 1.0.1 release? If so, could you try the latest version on master? I've added more aggressive style overrides with 395b0b2.

If this still happens with master, please provide more details about the book so I can investigate this issue.

**Comment by dmitriiweb** [comment]
@johnfactotum Thanks a lot!
