### ISSUE TITLE
Small caps support

### ISSUE THREAD

**Issue by efermi** [johnfactotum/foliate#100]
In comparison, bottom: `foliate-git` from AUR, top: [QiuReader](https://github.com/bubble-Q/QiuReader) (here as a browser extension, also uses epub.js). The book is https://github.com/standardebooks/mary-shelley_frankenstein.
![Screenshot_20190703_165920](https://user-images.githubusercontent.com/3966555/60598521-80611c00-9db5-11e9-9ad6-a7123ae82148.png)

**Comment by johnfactotum** [comment]
I'm not sure what I can do about this. The rendering is controlled by the book's CSS and WebKit. If you try QiuReader in a WebKit based browser I think you'll find that the same problem happens there, too.

**Comment by efermi** [comment]
So it's a WebKit bug then, good to know. Looks like this one https://bugs.webkit.org/show_bug.cgi?id=25000 ?
