### ISSUE TITLE
Segmentation fault (com.github.johnfactotum.foliate_2.6.4_all.deb)

### ISSUE THREAD

**Issue by flrnd** [johnfactotum/foliate#1000]
As title says, crashes with a seg fault few seconds after initializing.

System: Ubuntu 22.04
dmesg crash output: `[  776.119443] com.github.john[7923]: segfault at 0 ip 00007f364cdbe5a6 sp 00007ffe989b05e8 error 4 in libwebkit2gtk-4.0.so.37.57.8[7f364c883000+2684000]`
command line message after crash: `Job 1, 'com.github.johnfactotum.Foliate' terminated by signal SIGSEGV (Address boundary error)`

Steps to reproduce:

Install Foliate from the .deb file.
Open the application, select Catalog. The app tries to connect to online catalogs and freeze. After this, every time you launch crashes with a segmentation fault.

**Comment by johnfactotum** [comment]
Looks like a WebKitGTK issue. Probably not something that can be fixed in Foliate.

**Comment by flrnd** [comment]
Yes, seems so. I just tested the .deb on another machine with Debian and works fine.

In any case, I just sent the crash report with the stack trace to Ubuntu. I'm going to close the issue since it points more to Ubuntu side than Foliate itself.

Cheers.
