### ISSUE TITLE
What about webkit 6.0?

### ISSUE THREAD

**Issue by tuxfollower** [johnfactotum/foliate#1003]
I use archlinux and webkit 6.0 is becoming the default. Can the actual dev version work with webkit 6.0?

 - Foliate version: gtk4 branch
 - OS/Distribution and version: archlinux testing
 - Desktop environment: GNOME 44
 - Installation method: tried both with flatpak builder and regular meson build.

**Comment by johnfactotum** [comment]
Not yet. Will need to be port it to the new API.
