### ISSUE TITLE
App crashes (Segmentation fault) when closing book info window in the catalog

### ISSUE THREAD

**Issue by JamesL813** [johnfactotum/foliate#1005]
**Describe the bug**
App crashes (Segmentation fault) when closing book info window in the catalog, but only after downloading the book and closing it again. I tried multiple installation methods with the same result.

**To Reproduce**
1. Go to the Catalogs tab.
2. Find any book and click on it to open the book's info window.
3. Click one of the download options and the book opens in a reader window
4. Close the viewer window so it's back to the book info window.
5. Close the info window
6. App pauses and then crashes (Segmentation fault)

**Expected behavior**
The info window should close, and it should be back in the catalog

**Screenshots**
![Screenshot from 2023-03-25 03-01-58](https://user-images.githubusercontent.com/57780020/227702409-28c52642-93a7-4814-95b1-0cc2267a32bc.png)

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: EndeavourOS Linux x86_64, Linux 6.2.8-arch1-1
 - Desktop environment: GNOME Shell 43.3
 - Installation method: Flatpak, Arch Pacman Community repo, AUR

**Additional context**
Each installation method produces the same result

**Comment by Carlitaki** [comment]
Same result in Manjaro (Arch too).

**Comment by msmit5** [comment]
I'm having the same issue on Fedora using the fedora repo, the flathub repo, and the fedora rpm package

**Comment by johnfactotum** [comment]
Closing as obsolete with the release of the GTK 4 version. Feel free to open new issues if you have problems with the new version.
