### ISSUE TITLE
I am unable to see where to reset the reading time.

### ISSUE THREAD

**Issue by ben2talk** [johnfactotum/foliate#1008]
**Is your feature request related to a problem? Please describe.**
Folate says '31 minutes' left in a chapter - I don't see where to reset this when my son reads.

**Describe the solution you'd like**
An option to reset the reading time and learn it anew (as with the Kindle).

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by johnfactotum** [comment]
The speed is currently hardcoded. It isn't based on the actual reading speed, and it can't be adjusted. See the [FAQ](https://github.com/johnfactotum/foliate/wiki#how-are-reading-time-estimates-calculated) and #341.
