### ISSUE TITLE
CSS Theme bug

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#101]
CSS User-made themes load slowly ([see attached video css_bug.zip](https://github.com/johnfactotum/foliate/files/3359096/css_bug.zip)) and only after book is displayed. What should happen is the book should be displayed only after the user-made theme CSS is applied. Once the book is finally displayed, everything is normal.

Note: It's a slow-motion video, to accentuate the bug more clearly. In reality it takes a second or less.

**Comment by johnfactotum** [comment]
Can you try with the latest commit and see if this still happens?

**Comment by itprojects** [comment]
Tested to be fixed in commit `c9866fe5f80a99fc399a5515dbbd536b9f136a5f` .
