### ISSUE TITLE
Online Wiktionary definitions broken

### ISSUE THREAD

**Issue by AesaraB** [johnfactotum/foliate#1010]
When using Foliate (both native Fedora and Flathub version 2.6.4), definition queries result in "no definitions found". sdcv definitions work as expected.

Per the terminal:

```
file:///usr/share/com.github.johnfactotum.Foliate/assets/client.html:35:26: CONSOLE ERROR TypeError: undefined is not an object (evaluating 'results.forEach')
```

No javascript errors are thrown in Foliate's dev console.

**Comment by johnfactotum** [comment]
Duplicate of #418
