### ISSUE TITLE
"Light style" is white font on white page

### ISSUE THREAD

**Issue by Oberonc** [johnfactotum/foliate#1012]
In the GTK4 branch the only way to actually read the text is to use "Dark Style".
"White Style" is basically a white colored font (you can see there is text there so it isn't a full white) on white page.
"Follow system style" is the same as "White Style".

Is there a way to control the font / page colors ?

- Foliate version: gtk4 branch
- OS/Distribution and version: Linux from scratch
- Desktop environment: GNOME 43
- Installation method: cloned, installed into a folder under home directory and manually run using "GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas ./bin/foliate".
    I also tried running in place with same results.

**Comment by johnfactotum** [comment]
You can use the inspector (F12) to inspect the CSS styles. Assuming this isn't some weird graphics problem, *something* is setting the color to white, and Foliate certainly isn't doing that right now.

**Comment by Oberonc** [comment]
I guess we can put that under "weird graphic problem".
Under light style the observer itself it a fully white block as seen in the pictures I've attached.

Dark Style is fine:
![Screenshot from 2023-04-08 18-38-25](https://user-images.githubusercontent.com/13750901/230730160-85e7260f-447b-416a-9cc1-2af5e15a7df9.png)

Same region of screen in "Light Style" (or "follow system style") .. not so much:
![Screenshot from 2023-04-08 18-38-46](https://user-images.githubusercontent.com/13750901/230730168-3ee3c180-ac58-471b-9531-27645828e607.png)

**Comment by johnfactotum** [comment]
Does this still happen?

**Comment by johnfactotum** [comment]
Apparently it does, according to this comment

> Nope. Intel igpu. I think it has to do with GTK4. The book is not blank, it's just always white on black even if I choose the light theme in the app. My desktop theme is dark, but you should be able to choose how your book is rendered independently of your desktop theme. The old Foliate app is much better in that respect.

http://disq.us/p/2wlp1x1

**Comment by johnfactotum** [comment]
If anyone can reproduce this, please try the following patch:

```diff
diff --git a/src/reader/reader.html b/src/reader/reader.html
index bd78314..51c5c51 100644
--- a/src/reader/reader.html
+++ b/src/reader/reader.html
@@ -1,6 +1,5 @@
 <!DOCTYPE html>
 <meta charset="utf-8">
-<meta name="color-scheme" content="light dark">
 <meta http-equiv="Content-Security-Policy" content="default-src 'self' blob:; script-src 'self'; style-src 'self' blob: 'unsafe-inline'; img-src 'self' blob: data:; connect-src 'self' blob: data:; frame-src blob: data:; object-src blob: data:; form-action 'none';">
 <style>
 html {
```

**Comment by johnfactotum** [comment]
Closing as <i>works for me</i>/<i>stale</i> for now. Feel free to comment if you're still having the same issue.
