### ISSUE TITLE
What is missing until you release a Gtk4 based version ?

### ISSUE THREAD

**Issue by Oberonc** [johnfactotum/foliate#1013]
Is there some kind of road map of features / bugs to be fixed?

**Comment by johnfactotum** [comment]
An incomplete list of missing things:

- [ ] save thumbnail
- [ ] get file location with Tracker
- [ ] open remote files
- [ ] shortcuts window
- [ ] navigation history
- [ ] import annotations
- [ ] dictionary, Wikipedia, translate
- [ ] custom themes
- [ ] TTS
- [ ] OPDS

I'm thinking that perhaps a release can be made without OPDS, as it would require the most effort. Probably will have to do without TTS as well.

Not sure about the rest. At the very, very least it should have thumbnails (currently it only reads old thumbnails, but no new thumbnails are saved) and use Tracker.

**Comment by Oberonc** [comment]
I believe a minimal official release will be a good thing.
People will start using it, find bugs and suggest fixes/improvements.

**Comment by azzamsa** [comment]
Hello,

Is there a possibility of releasing the GTK4 branch with the current features? The remaining features can be included in subsequent releases. I visit this issue weekly to track any progress, and I believe having multiple smaller releases would be better than one large release.

There are several features that I really need, especially the underline feature. As a devoted reader who frequently highlights text, the current state in Foliate results in messy pages with numerous highlights. I would love to have underlining, similar to what's available in Lithium on my Android. It would make the pages look clean even with multiple underlines on a single page.

Unfortunately, I'm unable to contribute to the code, as my previous attempt resulted in complications. Additionally, I can't currently afford the $5 monthly contribution. I just wanted to express my immense gratitude! Being able to read many epubs locally and mark them each day is helping me on my journey, and I hope that reading books can enhance my career in the future.

Thank you! ❤️
Stay safe.

**Comment by johnfactotum** [comment]
I will try to prepare a release soon.

**Comment by elcste** [comment]
Tangentially, I'd love a flatplak! If you don't want to replace the GTK3 version yet, there is the Flathub beta repo.

**Comment by johnfactotum** [comment]
v3.0.0 released.

Not on Flathub yet, though, cause for some reason the PR status check isn't completed despite the build being successful.

**Comment by azzamsa** [comment]
Thank you so much for this release! 🎖️
