### ISSUE TITLE
Foliate freezes while opening EPUBs

### ISSUE THREAD

**Issue by Nanda-G** [johnfactotum/foliate#1014]
**Describe the bug**
Once an EPUB file is opened, Foliate freezes while navigating around with the arrow keys. Clicking with the mouse unfreezes Foliate for a moment and moves past the pages depending on the number of times you pressed the arrow key. Eventually, Foliate stops responding to even mouse clicks and freezes completely and doesn't let you navigate the pages.

**To Reproduce**
1. Launch Foliate
2. Open an EPUB file
3. Navigate around the pages

**Expected behavior**
Expected behavior is that the EPUB file opens and its possible to read it without any hiccups

**Screenshots**
Here's a [video](https://user-images.githubusercontent.com/31374517/231264311-117e92ba-f406-4cff-9dc6-81d61932f6ca.mp4) of me launching an EPUB and navigating around it - you can clearly notice Foliate freezing unless I keep clicking on the screen.

Here's a [graph](https://user-images.githubusercontent.com/31374517/231264758-1604bbb5-3766-465e-95f9-2a74b6225808.png) of the CPU and memory usage of the process including its children, plotted with the command `psrecord $(pgrep "gjs.*") --interval 1 --plot foliate-usage.png --include-children`

**Version:**
 - Foliate version: 2.6.4-2
 - OS/Distribution and version: Fedora Linux 36
 - Desktop environment: KDE Plasma 5.27.3
 - Installation method: DNF

**Additional context**
There are also some other problems.
Once I open a book for the first time and quit Foliate and launch Foliate again, it doesn't load the book at all and the cog is spinning till forever. If I remove the book from the library and then open it again, the book loads just fine but the freezing and lagging is still there.

EPUB file size: 255.4 KB

**Comment by Tuba2** [comment]
Was your PC in Power Saving mode?

**Comment by Nanda-G** [comment]
Oh my god, it was. It didn't occur to me at all to check that. Thank you!

**Comment by Tuba2** [comment]
No problem, been there too! Hope someone can help with that issue soon enough.
