### ISSUE TITLE
Rebuilding and Fixing Snap Builds

### ISSUE THREAD

**Issue by CapeCrusader321** [johnfactotum/foliate#1017]
Hey there @johnfactotum  i wish to maintain and upkeep the foliate snap, so i request you to transfer the ownership of snap to me, i have filed request on the transfer please transfer it to me.

**Comment by johnfactotum** [comment]
Thanks. But do you have a fix for the failing build? If you make a PR I'd be happy to merge and release it.

**Comment by johnfactotum** [comment]
Thanks. So now I realize it's actually not possible to fix the current stable release (v2.6.4) because Snaps can only built from the default branch, which I've recently changed from `master` to `gtk4`.  But then, if you could fix that build, I can change the default branch to `master` to make a new Snap release, then change it back to `gtk4` afterwards.

**Comment by CapeCrusader321** [comment]
> Thanks. So now I realize it's actually not possible to fix the current stable release (v2.6.4) because Snaps can only built from the default branch, which I've recently changed from `master` to `gtk4`. But then, if you could fix that build, I can change the default branch to `master` to make a new Snap release, then change it back to `gtk4` afterwards.

I am seeing that, but there is one more solution for the snap one, we can simply repackage the foliate deb into snap and distribute, i will keep that in an alternate solution too..

**Comment by CapeCrusader321** [comment]
@johnfactotum  happy to say its at least building successfully, fixing the problem with gjs, i will update the pull request yaml in few days

**Comment by CapeCrusader321** [comment]
@johnfactotum  can you give me some insight on this error, and any remedy will be help-full, the snap is build but wont run giving these error -->

(gjs:10579): Gjs-ERROR **: 08:55:42.613: JS ERROR: Error: Requiring GjsPrivate, version none: Typelib file for namespace 'GjsPrivate' (any version) not found
require@resource:///org/gnome/gjs/modules/esm/gi.js:14:24
@gi://GjsPrivate:3:25

Trace/breakpoint trap (core dumped)

**Comment by johnfactotum** [comment]
No idea. The error comes not from the app but from GJS's internals. So probably GJS itself is not configured correctly or is missing some dependencies.

**Comment by CapeCrusader321** [comment]
> No idea. The error comes not from the app but from GJS's internals. So probably GJS itself is not configured correctly or is missing some dependencies.

Ok, i will try stuffing more gjs related dependencies and if still i dont get any results i will open this at snapcraft forum as the foliate snap is using gjs from snap gnome-platform sdk.

**Comment by CapeCrusader321** [comment]
@johnfactotum This is completed, i have successfully build the new yaml for foliate snap, please review accordingly, i have tested it works fine and also works fine with text to speech, i am willing and open to maintain the snap package for this project

**Comment by johnfactotum** [comment]
Now it says "Built, failed to release".

**Comment by CapeCrusader321** [comment]
> Now it says "Built, failed to release".

I know its due to some errors in the desktop file part of the snap, am fixing it.

**Comment by johnfactotum** [comment]
Thanks! It works now.

Any chance that you could also make it build for other architectures?

**Comment by CapeCrusader321** [comment]
> 

What architectures do foliate support ??

**Comment by johnfactotum** [comment]
Foliate itself is not architecture dependent. And GJS/GTK supports all the architectures supported by Snap, I think. Initially, the Snap worked for all the architectures, but IIRC, after fixing https://github.com/johnfactotum/foliate/issues/324, it started to only build for amd64 and armhf. So the rest have been stuck at v2.1.1.

**Comment by CapeCrusader321** [comment]
> Foliate itself is not architecture dependent. And GJS/GTK supports all the architectures supported by Snap, I think. Initially, the Snap worked for all the architectures, but IIRC, after fixing #324, it started to only build for amd64 and armhf. So the rest have been stuck at v2.1.1.

I will try for arm atleast, and will also see others, i think it will be possible for all architectures now since we are using latest core 22...

**Comment by CapeCrusader321** [comment]
@johnfactotum  i currently removed the arch part to let it try to build for all and it builds for three archs- arm64&hf and amd64 while fail for two others, i will limit the builds to these three archs in future, currently implement this temp solution

**Comment by CapeCrusader321** [comment]
@johnfactotum  Fixed, building for multiple archs

**Comment by CapeCrusader321** [comment]
@johnfactotum  Is this complete ?? Should I close this, the snaps issue with not building is fixed plus i upgraded the snap to latest core22 so in future it will be easy to maintain a snap, and some other fixes with gjs were also fixed, i think this issue is complete, the recent issue regarding crash isnt snap specific as several non-snap users experience it
