### ISSUE TITLE
Latest unstable commit ("Use WebKitGTK 6.0") Breaks a couple of things

### ISSUE THREAD

**Issue by Oberonc** [johnfactotum/foliate#1018]
When trying the "open .." menu option:
_Gjs-Message: 17:23:31.376: JS WARNING: [file:///home/oberon/tmp/foliate/src/app.js 185]: Too many arguments to method Gtk.CssProvider.load_from_data: expected 1, got 2

(com.github.johnfactotum.Foliate:38390): Gjs-CRITICAL **: 17:23:37.238: JS ERROR: TypeError: (intermediate value).FileDialog is not a constructor
open@file:///home/oberon/tmp/foliate/src/app.js:94:24
addMethods/</<@file:///home/oberon/tmp/foliate/src/utils.js:260:58
@file:///home/oberon/tmp/foliate/src/main.js:58:32
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:77:9
run@resource:///org/gnome/gjs/modules/script/mainloop.js:19:22
@file:///home/oberon/tmp/foliate/src/main.js:62:10_

When clicking a book I already opened in the library:
_(com.github.johnfactotum.Foliate:37971): Gjs-CRITICAL **: 17:21:51.979: JS ERROR: TypeError: this[#data] is undefined
vfunc_unroot@file:///home/oberon/tmp/foliate/src/book-viewer.js:908:9
connectWindowRemoved@file:///home/oberon/tmp/foliate/src/app.js:303:16
@file:///home/oberon/tmp/foliate/src/main.js:58:32
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:77:9
run@resource:///org/gnome/gjs/modules/script/mainloop.js:19:22
@file:///home/oberon/tmp/foliate/src/main.js:62:10_

**Comment by johnfactotum** [comment]
It requires GTK >= 4.10 and WebKitGTK >= 2.40.1.

**Comment by Oberonc** [comment]
I upgraded GTK to 4.10.3, now I have:
oberon [ ~ ]$ sudo porg -a | grep gtk-4
gtk-4.10.3
oberon [ ~ ]$ sudo porg -a | grep webkit
webkitgtk-2.38.3
webkitgtk-2.40.1

The second problem (when trying to open a book persists:
_oberon [ ~/tmp/foliate ]$ GSETTINGS_SCHEMA_DIR=data gjs -m src/main.js
CONSOLE JS ERROR SyntaxError: Importing binding name 'getPosition' is not found.

(com.github.johnfactotum.Foliate:10039): Gjs-CRITICAL **: 21:42:08.137: JS ERROR: TypeError: this[#data] is undefined
vfunc_unroot@file:///home/oberon/tmp/foliate/src/book-viewer.js:908:9
connectWindowRemoved@file:///home/oberon/tmp/foliate/src/app.js:303:16
@file:///home/oberon/tmp/foliate/src/main.js:58:32
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:77:9
run@resource:///org/gnome/gjs/modules/script/mainloop.js:19:22
@file:///home/oberon/tmp/foliate/src/main.js:62:10_

**Comment by johnfactotum** [comment]
>  CONSOLE JS ERROR SyntaxError: Importing binding name 'getPosition' is not found.

It looks like you have a more recent version of foliate-js. Try running `git submodule update` to reset it.
