### ISSUE TITLE
Is it possible to control the text foreground colour in epub-files?

### ISSUE THREAD

**Issue by SN-CH** [johnfactotum/foliate#1019]
**Question:**
The text colour of fb2-files I open in Foliate is set by the selected theme (I use Solarized dark). However, should I open an epub-file, the text colour would be black (not sure if it is true for every epub-file, but it is so for those I tested). As you can imagine it is next to impossible to read black text on the Solarized dark background. Is there any way to enforce rendering epubs with the theme-defined colour in stead?

And thank you very much for this marvellous piece of software. I have discovered it a couple of days ago and I like it a great deal.

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Lubuntu 20.04
 - Desktop environment: LXQt 0.14.1
 - Installation method: deb

**Comment by johnfactotum** [comment]
You can
- Edit the EPUB file,
- Use the invert theme, or
- Add a custom theme and enable the invert option.

**Comment by SN-CH** [comment]
I see, thank you!
