### ISSUE TITLE
No Popup event

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#102]
No pop-up appears when highlighting one exact full word. To solve the problem resize the Foliate window - then pop-ups work.

This is related to https://github.com/johnfactotum/foliate/issues/98#issuecomment-508449977 and likely to https://github.com/johnfactotum/foliate/issues/94

**Comment by johnfactotum** [comment]
Does it only happen when hiding the reading progress bar? If so then this is not _related_ to #94 -- it _is_ #94, as I mentioned in https://github.com/johnfactotum/foliate/issues/94#issuecomment-507000404.

**Comment by itprojects** [comment]
Not when hiding, but when hidden to start with. If you press Ctrl+P for progress bar, you then do see the pop-up.

**Comment by johnfactotum** [comment]
Yeah, that's #94.
