### ISSUE TITLE
Foliate crashes when oppening books in Manjaro / Arch

### ISSUE THREAD

**Issue by Carlitaki** [johnfactotum/foliate#1021]
**Describe the bug**
If you open Foliate and you open a book, in the second or third opening, the book doesn't open, and in a few seconds the program closes. In a fresh install of Manjaro do the same.

**To Reproduce**
1. Open Foliate. Add books
2. Click on a book. Opens normally. Open another book clicking on it, in the second or third one, the program crashes at all.

**Expected behavior**
Normally, you can open any book any time and the books opens. This is de behavior in Linux Mint, for example.

**Screenshots**

**Version:**
 - Foliate 2.6.4
 - OS/Distribution and version: Manjaro 22.1 (Talos)
 - Desktop environment: KDE
 - Installation method: Flatpak and from Arch repositorys, do the same issue.

**Additional context**
Probably is an issue with tracker2/tracker3, but not sure.

**Comment by ben2talk** [comment]
Would there be a possiblity to scan the 'History' items and remove items no longer in the location?

**Comment by puzanov** [comment]
Exactly the same issue on Debian Stretch and Foliate 2.6.4

Any workaround to suppress this bug? Sometimes the machine reboot helps, but not always.

**Comment by ben2talk** [comment]
Can you tell us locations of settings, so we can refresh it??? I've tried the git version and the standard 2.6.4 and the settings remain.

The git version has no colour adjustment.

**Comment by ricardofunke** [comment]
Same here:
1. Open Foliate. Add books
2. Click on a book. Opens normally. Open another book by clicking on it, in the second or third one, the program crashes.

Fedora Linux 38 (Workstation Edition)
Gnome 44.2
Foliate 2.6.4
Wayland
Linux 6.3.11

**Comment by johnfactotum** [comment]
Closing as obsolete with the release of the GTK 4 version. Feel free to open new issues if you have problems with the new version.

**Comment by ben2talk** [comment]
Sounds fair - but now we need Foliate to recognise when a book is not available, and instead of simply offering to open another one, it should also remove any unavailable from the history.
