### ISSUE TITLE
How does one control the color of the text in the GTK4 version ?

### ISSUE THREAD

**Issue by Oberonc** [johnfactotum/foliate#1022]
Hi John,

I can see only one control for the background/font colors (the selection between styles).
How does one control the background color / text color ?
The text color in dark style is a bit too white-ish.

- Foliate version: gtk4 branch
- OS/Distribution and version: Linux from scratch
- Desktop environment: GNOME 43

**Comment by johnfactotum** [comment]
You can't. It's listed among the [missing features](https://github.com/johnfactotum/foliate/issues/1013#issuecomment-1518663105) as "custom themes".

**Comment by Oberonc** [comment]
Surely there is a way to manually change it in some Gnome / WebKitGTK configuration file, no ?
The properties of "CanvasText" are hardcoded or in a configuration file somewhere ?

**Comment by johnfactotum** [comment]
You could ask the WebKitGTK devs. But if I have to guess, the answer is probably no.

**Comment by johnfactotum** [comment]
After ce180875527780fe1d8cdf75d4372ceec727d8a4, you can now add custom themes. Each theme is a separate JSON files in `~/.config/com.github.johnfactotum.Foliate/themes/`. The format is
```json
{
    "label": "My Custom Theme",
    "light": {
        "fg": "#999999",
        "bg": "#cccccc",
        "link": "#666666"
    },
    "dark": {
        "fg": "#666666",
        "bg": "#333333",
        "link": "#777777"
    }
}
```
