### ISSUE TITLE
Please support custom styling for FB2 tags

### ISSUE THREAD

**Issue by natewind** [johnfactotum/foliate#1023]
For example, I’d like to center `<title>` and italicize `<cite>`, not to metion picking a custom font for `<code>`. And more generally, FB2 markup is purely semantic, so the styling is supposed to be user-specific.

**Comment by johnfactotum** [comment]
Duplicate of #930.

> picking a custom font for `<code>`

This is #222.

**Comment by natewind** [comment]
Maybe at least center titles by default?

**Comment by johnfactotum** [comment]
It does in the `gtk4` branch.
