### ISSUE TITLE
change wiktionary source

### ISSUE THREAD

**Issue by maxorbase** [johnfactotum/foliate#1024]
i want change wiktionary from en to ar 
find lookup.js  in com.github.johnfactotum.Foliate.data.gresource but its hard to edit this file 
in source code lookup.js not found to edit for Building from source
how can change wiktionary base url

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: debian bookworm
 - Desktop environment: kde
 - Installation method: apt

**Comment by johnfactotum** [comment]
You can't. Wiktionary's definition API only supports English. See https://en.wiktionary.org/api/rest_v1/.
