### ISSUE TITLE
Get opened file's windowIDs and Paths using d-bus command

### ISSUE THREAD

**Issue by blueray453** [johnfactotum/foliate#1029]
**Question:**
Is there any dbus command which I can use to get the window IDs and paths of opened files.

I have used `dbus-monitor --session > dbus-log.txt` (the file is attached [here](https://github.com/johnfactotum/foliate/files/11431045/dbus-log.txt)) and found out that file path's are there. Not understanding how to extract them.

I have also found that `dbus-send --session --print-reply --dest=com.github.johnfactotum.Foliate /com/github/johnfactotum/Foliate org.freedesktop.DBus.Introspectable.Introspect` works.

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Zorin OS 16.2
 - Desktop environment: 3.38.4
 - Installation method: ppa:apandada1/foliate

**P.S.**

If you want to have some context to this question, please check https://unix.stackexchange.com/questions/745384/same-pid-for-multiple-windows-get-opened-files-window-id-and-path-using-d-bus

**Comment by johnfactotum** [comment]
I don't think that's possible. There's no D-Bus interface, or any other interface for that.

**Comment by johnfactotum** [comment]
> Then why does `dbus-send --session --print-reply --dest=com.github.johnfactotum.Foliate /com/github/johnfactotum/Foliate org.freedesktop.DBus.Introspectable.Introspect` command work.

You *can* interact with Foliate with D-Bus, but there isn't an interface that you could use to get file paths and window IDs.

> Why is there lines like bellow in the `dbus-monitor --session > dbus-log.txt` command output. I am attaching another log file.

This just shows that something is launching Foliate with the file URI as argument. This has nothing to do with window ID. It just passes the file to the app. The app could create a new windows for the file, or it might open it using existing windows, or it might not even open the file at all. Whatever the app does with the URI is not known by other programs.

**Comment by blueray453** [comment]
Thank you very much for the clarification.
