### ISSUE TITLE
Add Sidebar button

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#103]
Seems like a 'missing feature'. Can you add a button that shows/hides the sidebar before "Reading Progress Bar [tick/check]"?

**Comment by itprojects** [comment]
Evince has one.

**Comment by johnfactotum** [comment]
There is one. It's just that the sidebar mode cannot be enabled yet via the GUI. You need to set "use-sidebar" to true and restart the app. This and other settings will be in the preference window once I've reworked that part of the code.
