### ISSUE TITLE
Option for selection when length 1 behavior

### ISSUE THREAD

**Issue by mlouielu** [johnfactotum/foliate#104]
I remember the good days that when the selection contain only one word will popup the lookup, after f8c612f978229957f76487f86b17e065745d681b it only dispatch with 'selection'  wether the selection length.

It is good to have option to have the behavior changed if it can set to lookup, translate, or dispatch with 'selection'

**Comment by johnfactotum** [comment]
Yes, as I mentioned in https://github.com/johnfactotum/foliate/pull/99#issuecomment-507969171 and https://github.com/johnfactotum/foliate/issues/98#issuecomment-508366056, I will add back the option to restore the previous behavior in the preference window.
