### ISSUE TITLE
JS ERROR: ImportError: No JS module 'main' found in search path

### ISSUE THREAD

**Issue by WammKD** [johnfactotum/foliate#1046]
**Question:**
'Hoping the possible direction to look will be obvious but I'm packaging for Guix and this error happens upon execute; I have all the listed dependencies so I'm guessing that a path is wrong or missing in some place but I'm not familiar with the technology stack so I'm uncertain of what it might be.

In short, do you know what would cause such an error message? If a package is missing or not found in path, what dependency/package might it be?

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: GNU Guix
 - Desktop environment: XFCE, more or less
 - Installation method: building from source

**Comment by johnfactotum** [comment]
This could happen if you move the files to a different location than the specified prefix when running Meson. Another reason is that executable's name must be the app's ID (see #701).
