### ISSUE TITLE
Add Full-screen Button

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#105]
Would it make sense to add a full-screen button, to match the gnome apps trend?

![Full-screen button.](https://user-images.githubusercontent.com/2698054/60717379-22494b80-9f11-11e9-82bb-f10e8a7bc2e2.png)

**Comment by johnfactotum** [comment]
I'm not totally against this idea, but to me the headerbar already has too many buttons.

**Comment by itprojects** [comment]
You are right about the clutter. The prompt for this bug report was the fear that some users may complain that they don't know about or don't want to use the (F11) shortcut.
