### ISSUE TITLE
Foliate gtk-4 giving coredump

### ISSUE THREAD

**Issue by srini8080** [johnfactotum/foliate#1055]
I am trying to use foliate gtk-4. 

opt/foliate-gtk4/run/bin/foliate 

(gjs:64095): Gjs-ERROR **: 07:13:53.576: option parsing failed: Unknown option -m
Trace/breakpoint trap (core dumped)

Thanks,

Foliate 3.0
centos 8 stream
GNOME 3.32.2
meson build

**Comment by srini8080** [comment]
I tried re install,. here is what I got

com.github.johnfactotum.Foliate 

(com.github.johnfactotum.Foliate:64543): GLib-GIO-ERROR **: 07:17:21.380: Settings schema 'com.github.johnfactotum.Foliate' does not contain a key named 'store-uris'
Trace/breakpoint trap (core dumped)

**Comment by johnfactotum** [comment]
> option parsing failed: Unknown option -m

Your GJS version is probably too old. As stared in the readme, you need at least 1.72.

> does not contain a key named 'store-uris'

It looks like you're running the 2.x version against new settings schema or something like that. The current gtk4 branch codebase doesn't even contain the string "store-uris".
