### ISSUE TITLE
Does not correctly track the last pages of a book

### ISSUE THREAD

**Issue by WhiteBlackGoose** [johnfactotum/foliate#1056]
**Describe the bug**
When I read to the last pages of the book and close Foliate, it would revert a few pages back

**To Reproduce**
1. Download [this html](https://www.projekt-gutenberg.org/dostojew/spieler/chap01.html). Then open it with foliate or convert it into txt and open with foliate.
1. Then scroll to page "9 of 24". 
2. Close foliate
3. Open it. It should be on the correct page
4. Now jump to the last page "22 of 24"
5. Close foliate
6. Open it. Now it's on the page "19 of 24"

**Expected behavior**
Should also jump to the last page "22 of 24"

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: NixOS unstable
 - Desktop environment: i3
 - Installation method: nix

**Comment by WhiteBlackGoose** [comment]
Btw thanks for this software!

**Comment by johnfactotum** [comment]
I think this is #653.
