### ISSUE TITLE
Changing Theme in Manjaro / Arch doesn't register the change and foliate freezes

### ISSUE THREAD

**Issue by Gfreak412** [johnfactotum/foliate#1058]
**Describe the bug**
Inside the reader if you try to change the theme, to dark or gruvbox dark, etc. the foliate window freezes and from next launch text renders in light yellowish colour on white background. 

this also happens in regular archlinux but the theme change used to be reflected when launched again after the crash, but not the case in 

**To Reproduce**
1.Open an epub file
2. Click on theme and try to change theme
3. window freezes and from next launch text renders in light yellowish colour on white background. 

**Expected behavior**
the theme should be applied instantly to the reader without the window freezing or crashing

**Screenshots**
https://imgur.com/OXcK18z

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Manjaro 22.1.3
 - Desktop environment: Gnome 44.3
 - Installation method: Official Arch Repo

**Additional context**
While writing this issue , I tried taking a screenshot with gnome screenshot utility, which I very much DOUBT solved the issue but the Expected behaviour started working for a few minutes but then the issue arose again, I have experienced the issue on many versions of foliate and would be grateful if you looked into it.

**Comment by johnfactotum** [comment]
Closing as <i>obsolete</i> with the release of the GTK 4 version. Feel free to open new issues if you have problems with the new version.
