### ISSUE TITLE
Advertise for Debian/Ubuntu maintainers

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#106]
Can you change the README.md to include something like:

`Foliate is still looking for a debian/ubuntu maintainer. Is that you?`

under:

`Void Linux: xbps-install -S foliate`

**Comment by johnfactotum** [comment]
I don't think there's any need to "advertise". People can already see that there's currently no PPA or whatever available, and they may choose to create one if they're interested.

If you're interested in this, maybe try messaging some of the Debian/Ubuntu/PPA maintainers, or perhaps you can even try becoming a maintainer yourself.
