### ISSUE TITLE
Trying to change theme crashes Foliate

### ISSUE THREAD

**Issue by afduggirala** [johnfactotum/foliate#1060]
I changed (I think successfully) the theme to a dark theme variant a few days ago. It changed the theme, which actually looks really bad. I tried to change my theme back to the original one, but every time I try to change my theme back to the original, Foliate crashes. 
This has effectively rendered Foliate useless to me right now, because I can't read books using the current theme and can't change the theme.
I tried uninstalling and installing again, the theme persists and the problem too. I even tried removing some config files I found in my home folder, without avail.

I'm on Fedora 38 and installed from repositories. This is Gnome 44.3. Will now try to install the flatpak instead.
Edit: Tried the flatpak version and the problem persists. I am actually presented with the useless theme from the first start of the program. So I can't use it.

thank you,

**Comment by infinitewhileloop** [comment]
I am experiencing the same issue, using the Flatpak version on Linux Mint.

**Comment by johnfactotum** [comment]
Probably a duplicate of #719

**Comment by JorgeLdeOz** [comment]
I have the same problem with linux mint 21.2

**Comment by nocnoc94** [comment]
I am experiencing the same issue on Fedora 38, flatpak version

**Comment by johnfactotum** [comment]
Closing as *obsolete* with the release of the GTK 4 version. Feel free to open new issues if you have problems with the new version.
