### ISSUE TITLE
Open fb2 error |undefined is not a function 

### ISSUE THREAD

**Issue by WoodyWizard** [johnfactotum/foliate#1063]
**Describe the bug**
Some fb2 files won't open with foliate (not all)

**To Reproduce**
1. Open fb2 file with foliate

**Expected behavior**
Open fb2

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: fedora 38
 - Desktop environment: 44.3
 - Installation method: fedora reps and flatpak

**Additional context** OUTPUT:

(com.github.johnfactotum.Foliate:39416): Gjs-WARNING **: 19:01:43.123: JS ERROR: Error: undefined is not a function (near '...[output, childF, post = x => x]...')
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57
_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:886:22
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/com.github.johnfactotum.Foliate:9:17

**Comment by johnfactotum** [comment]
Could you try the gtk4 version, or the [online demo reader](https://johnfactotum.github.io/foliate-js/reader.html) for the new renderer?

**Comment by WoodyWizard** [comment]
> Could you try the gtk4 version, or the [online demo reader](https://johnfactotum.github.io/foliate-js/reader.html) for the new renderer?

GTK-4 and online version works fine, thanks.

**Comment by WoodyWizard** [comment]
also i have a question, should cover be available in library(now it's just name of book) or it's not available now?

**Comment by johnfactotum** [comment]
The gtk4 version doesn't save thumbnails yet, though it does show old thumbnails saved by the gtk3 version.
