### ISSUE TITLE
Keyboard navigation in gtk4 version

### ISSUE THREAD

**Issue by Yuanda-Dong** [johnfactotum/foliate#1068]
**Is your feature request related to a problem? Please describe.**
Hi, John. Would you be able to change the behavior j/k keys to scrolling instead of paging in scrolled layout ? I tried adding a keybinding to `reader.scrollBy()`, but it scrolls until a point then it doesn't page over. Thanks.

**Comment by johnfactotum** [comment]
`scrollBy()` is only meant to be used for implementing 1:1 touchscreen or touchpad gestures in paginated mode. Should probably change the name or add a comment to clarify this.

I guess in foliate-js, there should be an optional size parameter for `prev()` and `next()` that can be used instead in scrolled mode of `this.size` (see https://github.com/johnfactotum/foliate-js/blob/739a00f7f9dcded1172f585fca608a522fb4d17c/paginator.js#L879). Then Foliate can pass the default font pixel size * line-height.
