### ISSUE TITLE
Unable to keep foliate running for 2 mins or more...

### ISSUE THREAD

**Issue by benji88i** [johnfactotum/foliate#1069]
Firstly, my sincere thanks to the developer Mr. John Factotum for designing and building this incredibly amazing application!

Its the best book reader on any platform, it would be amazing on macos too. 

**Describe the bug**
Okay so I am running Foliate 2.6.4 (rpm version for Fedora)

Basically the application crashes and I am not sure why.

**To Reproduce**
1. Open the application
2. Start moving through a book
3. Scroll down or click through a book
4. Application crashes (closes)

**Expected behavior**
Stays open and allows me to read my book.

**Screenshots**
It crashes (the window just dissapears)

**Version:**
 - Foliate version: 2.6.4
 - OS/Distributionad version: Fedora 37 - workstation - Gnome ver
 - Desktop environment: [e.g. GNOME 3.36] Gnome 43.7
 - Installation method: [e.g. Flatpak] -  rpm (fedora repo)

**Additional context**

I have tried the flatpak version and have the same exact problem 

I shall try to change my window manager to wayland and see if that helps and report back...

**Comment by benji88i** [comment]
I thought I might add that this bug report has just come through..

gjs-console killed by SIGABRT 

I'm not entirely sure what that relates to as there is not enough details in my bug report.

**Comment by johnfactotum** [comment]
Closing as obsolete with the release of the GTK 4 version. Feel free to open new issues if you have problems with the new version.
