### ISSUE TITLE
Hide cursor feature doesnt work with gtk 3.24.9

### ISSUE THREAD

**Issue by monday15** [johnfactotum/foliate#107]
Fedora 30, gnome-wayland session, rpm package built using spec from fedora's repos. After a delay, instead of hiding, cursor moves (few pixels down and few pixels right), but remains visible.

**Comment by itprojects** [comment]
It works from meson build on Ubuntu 19.04 gnome-wayland session.
Can you try it that way, in your distro?

**Comment by monday15** [comment]
I've tried https://github.com/johnfactotum/foliate#build-and-run-from-source-without-installing result is the same. 

However, flatpak package 1.4.0 from flathub works fine, cursor is hiding. 

@johnfactotum, do you have any idea what can cause this issue?

**Comment by monday15** [comment]
Ok, I've figured out - problem appears only with gtk 3.24.9, downgrading to 3.24.8 fixes the issue.

**Comment by johnfactotum** [comment]
The cursor is actually hidden using CSS by setting `cursor` to `none`, so I'm pretty sure this is not our bug.
