### ISSUE TITLE
How can I rotate the page so I could hold the laptop like a book

### ISSUE THREAD

**Issue by naim5am** [johnfactotum/foliate#1074]
**Question:**
Foliate team, thanks for being.

- Most books are meant to be read vertically
- Most laptops are meant to be use horizontally

How come there's no way to rotate the view?
I read e-books on a 15.4" laptop with my daughter. Foliate is joy for us, but every time we want to read, we have to change the display's orientation to benefit of the full screen.
Maybe I should just create a shortcut on the OS level to rotate the display.

**Version:**
 - Foliate version: Many to current 2.6.4, long time user here.
 - OS/Distribution and version: Linux pop-os 6.4.6
 - Desktop environment: Gnome 42, X11
 - Installation method: Flatpak

**Comment by johnfactotum** [comment]
>  Maybe I should just create a shortcut on the OS level to rotate the display.

Yes, rotating the display is the job of the desktop environment. It should work out of the box in GNOME, though, if your device has the relevant sensors (you may need to manually install the `iio-sensor-proxy` package).

**Comment by naim5am** [comment]
What about if I want to rotate only some pages? Or If my device doesn't have an orientation sensor. It's just a function I expect from days of PDF .. not sure if that's a valid reason.

Sometimes I only need to rotate a few pages of the book.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by johnfactotum** [comment]
If you are rotating the whole screen, you need to rotate the whole UI, not just the page, to make it usable. So I don't think rotating in PDF viewers has anything to do with device orientation.
