### ISSUE TITLE
Why Foliate doesn't work anymore on my Librem 5

### ISSUE THREAD

**Issue by laconick** [johnfactotum/foliate#1075]
**Question:**
Need help to identify what's changed on my system, as it used to work. I get this output when opening an eBook:

`Portal call failed: Failed to start command: Failed to execute child process “dict” (No such file or directory)`
`Portal call failed: Failed to start command: Failed to execute child process “sdcv” (No such file or directory)`
`Failed to create /home/purism/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.`
`Failed to create /home/purism/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.`
`No provider of glFenceSync found.  Requires one of:`
`    Desktop OpenGL 3.2`
`    GL_ARB_sync`
`    OpenGL ES 3.0`
`    GL_APPLE_sync`

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: PureOS 10
 - Desktop environment: GNOME 3.38.5
 - Installation method: Flatpak

**Thanks for helping!**

**Comment by johnfactotum** [comment]
Looks like a GTK bug: https://gitlab.gnome.org/GNOME/gtk/-/issues/5749

**Comment by archisman-panigrahi** [comment]
> Is there a better workaround that launching the app with `GDK_GL=gl flatpak run com.github.johnfactotum.Foliate`?

Try the following. Add `alias foliate="GDK_GL=gl flatpak run com.github.johnfactotum.Foliate". Then, edit the .desktop file to execute it with `foliate`.
