### ISSUE TITLE
Is it possible to suggest a different theme colors ?

### ISSUE THREAD

**Issue by 0xMRTT** [johnfactotum/foliate#1082]
**Question:**
Is it possible to suggest a different theme colors ? Currently in gtk4 branch, you can only use some themes, but it'll be great if we can customize colors or add our own theme (either PR or prefs) 

**Version:**
 - Foliate version: 3 (latest commit)
 - OS/Distribution and version: Arch
 - Desktop environment: GNOME 45
 - Installation method: From source

**Comment by johnfactotum** [comment]
Yes, it will be customizable. "Custom themes" is in the [list of missing features](https://github.com/johnfactotum/foliate/issues/1013#issuecomment-1518663105).

**Comment by 0xMRTT** [comment]
That's nice thanks for making this app! The GTK4 version is awesome
