### ISSUE TITLE
The application can't open epub files anymore - Arch Linux

### ISSUE THREAD

**Issue by mauromotion** [johnfactotum/foliate#1085]
**Describe the bug**

Foliate can't open .epub files anymore, when trying to open them it hangs until I close it.

**To Reproduce**

Open an .epub file with Foliate.

**Expected behavior**

The ebook file would open.

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Arch Linux 6.5.5-arch1-1
 - Desktop environment: No DE, just i3 WM
 - Installation method: package from the official Arch Linux extra repository.

**Additional context**
It used to work perfectly until a few weeks ago. The rest of my system and applications work fine.

Output from the terminal:

`❯ foliate
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 1420x735: Invalid argument
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 1420x735: Invalid argument
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 1420x735: Invalid argument
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1`

**Comment by johnfactotum** [comment]
It's a WebKitGTK/Nvidia problem. See
- https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2498
- https://bugs.webkit.org/show_bug.cgi?id=259644
- https://bugs.webkit.org/show_bug.cgi?id=261874

**Comment by nestorwendt** [comment]
Adding the kernel parameter `nvidia_drm.modeset=1` fixed the problem for me.

**Comment by mauromotion** [comment]
> Adding the kernel parameter `nvidia_drm.modeset=1` fixed the problem for me.

I've tried adding that parameter and I get a different error now, and a different Foliate behaviour. It still doesn't show the eBook, though, but it doesn't hang. It's just blank.

`❯ foliate

(com.github.johnfactotum.Foliate:5349): Gjs-WARNING **: 12:21:11.202: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  @/usr/bin/foliate:9:17`
  
Is it still Nvidia's fault?

**Comment by nestorwendt** [comment]
> I've tried adding that parameter and I get a different error now, and a different Foliate behaviour. It still doesn't show the eBook, though, but it doesn't hang. It's just blank.

I'm using foliate-git from AUR, maybe you can try that.

**Comment by mauromotion** [comment]
> > I've tried adding that parameter and I get a different error now, and a different Foliate behaviour. It still doesn't show the eBook, though, but it doesn't hang. It's just blank.
> 
> I'm using foliate-git from AUR, maybe you can try that.

Thanks, using foliate-git works. Albeit in a weird way, as in I can't access any  preferences, I can only switch from light to dark mode and that's it. ALso the gtk buttons look different (which I don't care but still). At least the books are readable.

I'm not sure this is an Nvidia bug at this point. If it is, it only manifests itself with Foliate. 

I will have to look for an alternative.

**Comment by johnfactotum** [comment]
> It's just blank. [...] Is it still Nvidia's fault?

It's probably a WebKitGTK bug on Nvidia.

I don't have Nvidia, and v2.6.4 works for me on Arch Linux.

> I can't access any preferences, I can only switch from light to dark mode and that's it.

If you're talking about the "Preferences" item in the main menu of the library view, that indeed doesn't work, as it's not implemented yet (among other things that are still missing from the GTK 4 rewrite).

There are some preferences, though, that you can change in "Font & Layout Settings" in the view menu.

> ALso the gtk buttons look different

That's just GNOME's new Adwaita stylesheet for GTK 4, which looks different from the GTK 3 version.

**Comment by mauromotion** [comment]
Fair enough. Thanks.

**Comment by wenzezlaus** [comment]
Starting foliate with WEBKIT_DISABLE_COMPOSITING_MODE=1 fixed the problem for me.
Arch Linux 6.5.7-arch1-1

**Comment by nobane** [comment]
I ran into this issue trying use webkit2gtk on arch linux (with an nvidia card) and I was able to fix it **without** setting `WEBKIT_DISABLE_DMABUF_RENDERER=1`.

Here is how I fixed it:


1. Check if you have modesetting enabled via

        cat /sys/module/nvidia_drm/parameters/modeset

2. If you see printed `N` then you need to enable it with

        echo options nvidia_drm modeset=1 | sudo tee /etc/modprobe.d/nvidia_drm.conf

3. Restart your computer

**Comment by johanla0** [comment]
Faced this on Fedora 41. Straightforward but someone might found helpful.
1. Remove Foliate from Software
2. Install via terminal with `dnf install foliate`
3. Now it works
