### ISSUE TITLE
foliate crashes right away with error

### ISSUE THREAD

**Issue by Oberonc** [johnfactotum/foliate#1089]
Here is error:
$ foliate 

(com.github.johnfactotum.Foliate:56437): Gjs-CRITICAL **: 00:53:14.856: JS ERROR: TypeError: (new Application()).runAsync is not a function
@file:///usr/bin/foliate:56:30

(com.github.johnfactotum.Foliate:56437): Gjs-CRITICAL **: 00:53:14.856: Module file:///usr/bin/foliate threw an exception

Versions:
foliate: pulled from git on 9 oct 2023
gtk-4.10.3
glib-2.74.4
gjs-1.74.1
webkitgtk-2.40.1

**Comment by johnfactotum** [comment]
It needs GJS >= 1.76 and GTK >= 4.12.

**Comment by Oberonc** [comment]
You should probably update the meson script to check for correct versions of dependencies
