### ISSUE TITLE
Nonsensical folder names

### ISSUE THREAD

**Issue by ben2talk** [johnfactotum/foliate#1098]
**Question:**
I would like to know why, when I can find ~/config/strawberry, and ~/.config/blender, and ~/.config/calibre I cannot find ~/.config/foliate.

It seems the 'standard' for locating and naming files is ignored and some 'com.github.jonfactotum' must be appended.

**Version:**
 - foliate 2.6.4-3
 - OS/Distribution and version: Manjaro
 - Desktop environment: KDE 5.27.8
 - Installation method: Repo (Pacman)

This causes problems when the program bugs out, for example the library view containing books no longer present, which don't get removed - I want to simply clear the preferences by renaming ~/.config/foliate but find that there are many other folders and it is not so trivial or simple to do the job (as it is with most other software).

**Comment by johnfactotum** [comment]
> It seems the 'standard' for locating and naming files is ignored and some 'com.github.jonfactotum' must be appended.

The reverse domain name thing is pretty common. It's used by many GNOME apps, e.g. GNOME Text Editor.

> I would like to know why

I don't think there's any spec that says you should use the reverse domain name for the data/config/cache directories, but many apps (and some libraries, such as WebKitGTK) simply use the [application ID](https://developer.gnome.org/documentation/tutorials/application-id), which *must* be in reverse domain name notation, which is designed to avoid naming conflicts.

> This causes problems when the program bugs out, for example the library view containing books no longer present, which don't get removed - I want to simply clear the preferences by renaming ~/.config/foliate

- The issue has nothing to do with preferences. That's simply how it behaves now and you can't fix it by clearing the preferences. (You could almost say that it's working as intended, as Foliate deliberately avoids tracking files. But see https://github.com/johnfactotum/foliate/issues/582.)
- Preferences are stored using GSettings. For how to clear those settings, see #919.
