### ISSUE TITLE
The annotation syntax is "proprietary" or future proof?

### ISSUE THREAD

**Issue by felipehw** [johnfactotum/foliate#11]
I would like to know if the JSON syntax for annotations is a kinda standard format that I could import in others software (aka future proof).

This is important to me because I wanna use this for studies that I'll need access by the following years.

(Ps: I don't know if epub annotations have a standard syntax.)

**Comment by johnfactotum** [comment]
Here's a sample.

Doing this...

![image](https://user-images.githubusercontent.com/50942278/58710270-765d8f00-83ab-11e9-9759-847f14977ae8.png)

...produces the following:

```json
{
  "lastLocation": "epubcfi(/6/12[main2]!/4/2/2/2/1:0)",
  "annotations": [
    {
      "value": "epubcfi(/6/12[main2]!/4/2/2/2,/1:0,/1:286)",
      "color": "aqua",
      "text": "Good sense is, of all things among men, the most equally distributed; for every one thinks himself so abundantly provided with it, that those even who are the most difficult to satisfy in everything else, do not usually desire a larger measure of this quality than they already possess.",
      "note": "Very droll, René."
    }
  ]
}
```

The "epubcfi(...)" parts are [EPUB Canonical Fragment Identifiers](https://www.idpf.org/epub/linking/cfi/), so it's pretty standard. If all else fails, you still have the highlighted text and your note in plain text.

**Comment by felipehw** [comment]
Thanks! You explained this topic very well.
