### ISSUE TITLE
v3 missing in Flathub

### ISSUE THREAD

**Issue by niedzielski** [johnfactotum/foliate#1104]
**Describe the bug**
v3.0.0 just released but is not yet available in [Flathub](https://flathub.org/apps/com.github.johnfactotum.Foliate).

**To Reproduce**
1. Go to [Flathub](https://flathub.org/apps/com.github.johnfactotum.Foliate).
2. Scroll to changelog.

**Expected behavior**
v3.0.0 is distributed on Flathub.

**Comment by elcste** [comment]
> v3.0.0 released.
> 
> Not on Flathub yet, though, cause for some reason the PR status check isn't completed despite the build being successful.
> 

_Originally posted by @johnfactotum in https://github.com/johnfactotum/foliate/issues/1013#issuecomment-1807194979_

**Comment by johnfactotum** [comment]
Resolved now.

**Comment by niedzielski** [comment]
As near as I can tell, v3 is still unavailable on Flathub. I tried upgrading from the CLI as well but there's "nothing to do" and I'm still on v2.6.4.

![image](https://github.com/johnfactotum/foliate/assets/1071806/be81acdf-1e38-4421-8369-da446ddedd9a)

**Comment by johnfactotum** [comment]
Yeah, Flathub has a delay before any change is published. I think it's 3 hours. So apparently it's taking longer than usual. But I don't think there's anything I can do about that.

**Comment by johnfactotum** [comment]
So it seems that the publishing job failed with the following message:
```
Purging build https://hub.flathub.org/api/v1/build/63840
Api call to https://hub.flathub.org/api/v1/build/63840/purge failed with status 400, details: {'error-type': 'generic-error', 'message': "Can't prune build while in use", 'status': 400}
```

I rebuilt and republished it again, and it's still failing with the same message: https://buildbot.flathub.org/#/builders/6/builds/81258

**Comment by johnfactotum** [comment]
Tried publishing it again and it finally worked.

**Comment by niedzielski** [comment]
Thank you! Very excited to try it!
