### ISSUE TITLE
Crash when deleting a highlight

### ISSUE THREAD

**Issue by kdwk** [johnfactotum/foliate#1110]
**Describe the bug**
Foliate crashed when deleting a highlight

**To Reproduce**
1. Highlight a word in an ebook
2. Delete the highlight
3. Crashes

**Expected behavior**
Does not crash

**Version:**
 - Foliate version: 3.0.0
 - OS/Distribution and version: Fedora Silverblue 39
 - Desktop environment: Gnome 45
 - Installation method: Flatpak

**Additional context**
[gdb (bt full; c).txt](https://github.com/johnfactotum/foliate/files/13335983/gdb.txt)

**Comment by johnfactotum** [comment]
This looks like a GTK issue.
