### ISSUE TITLE
Add option to override publisher font

### ISSUE THREAD

**Issue by elmagio** [johnfactotum/foliate#1113]
**Describe the bug**
When a EPUB book has specific fonts designated by a style.css or similar file, Foliate 3.0 will not apply user chosen default fonts. I'm marking this as a bug as Foliate 2.6.4 used to automatically apply the user chosen font to all books regardless of style sheets, however if this is the desired behavior this can serve as a feature request for an optional "Force user fonts" setting. MOBI files made by converting the problematic EPUBs in Calibre do not exhibit the issue.

**To Reproduce**
1. Open a .epub book that has a style.css designated font (I've included an user-generated one, but I've experienced it with copyrighted books which I can't share here as well)
2. Go to Fonts & Layout settings
3. Alternate between Serif and Sans-serif as the default or change the specific font family for either
4. Foliate will not apply the desired font

**Expected behavior**
The selected font or font category (Serif/Sans-serif) should be applied

**Version:**
 - Foliate version: 3.0.0
 - OS/Distribution and version: Ubuntu 23.10
 - Desktop environment: GNOME 45
 - Installation method: Flatpak

**Additional context**
I had to zip up an example epub to share it, as Github would not let me upload an .epub file as is:
[Example.zip](https://github.com/johnfactotum/foliate/files/13336771/Example.zip)

**Comment by johnfactotum** [comment]
It's indeed by design, and that's why it's called "Default Font", i.e. the default if the book doesn't specify any. But it does need an option to override publisher fonts.

As a workaround, you can add the following to [`user-stylesheet.css`](https://github.com/johnfactotum/foliate/blob/gtk4/docs/faq.md#can-i-set-my-own-custom-css-styles):

```css
* {
    font-family: inherit !important;
    line-height: inherit !important;
}
```

**Comment by elmagio** [comment]
Thanks for the workaround !

**Comment by distefam** [comment]
Thank you for this workaround, however, applying it to a book with code blocks that are ordinarily rendered in a monospaced font makes those blocks also render with the default font, even when I've specified a monospaced font in Foliate's preferences.

**Comment by johnfactotum** [comment]
`revert` works for code blocks, which is usually marked up with `<pre>`, which is styled by the user agent (i.e. WebKit) with the default monospace font.

You can use the inspector (<kbd>F12</kbd>) to see what's happening.
