### ISSUE TITLE
Cannot close at the translation window after selecting a language

### ISSUE THREAD

**Issue by archisman-panigrahi** [johnfactotum/foliate#1118]
**Describe the bug**

**To Reproduce**
1. Select any word, and click on translation
2. Select any language (other than English, which is selected by default).
3. Translation appears, but Foliate does not receive click events anymore (only the translation window can be clicked on).
4. At this point, there is no way to close the translation window, or do anything in Foliate. The Foliate window cannot be even dragged.

**Expected behavior**
The translation window should be closed when the user clicks outside it.

**Screenshots**
![image](https://github.com/johnfactotum/foliate/assets/3063132/67cae23f-ef2d-4500-8afd-82a012254075)

**Version:**
 - Foliate version: 3.0.0
 - OS/Distribution and version: Kubuntu 23.10
 - Desktop environment: KDE Plasma 5.27
 - Installation method: Flatpak

**Comment by archisman-panigrahi** [comment]
Also, this translation window goes on top on other windows (e.g. Firefox in this picture). Foliate is behind.

![image](https://github.com/johnfactotum/foliate/assets/3063132/c164e91b-65d6-4fb8-ada7-c36d871af31b)

**Comment by archisman-panigrahi** [comment]
I compiled from source in Kubuntu 23.10, the bug is there. So, it is not flatpak specific.

**Comment by johnfactotum** [comment]
This is GTK bug: https://gitlab.gnome.org/GNOME/gtk/-/issues/5568
