### ISSUE TITLE
Flatpak TTS does not work

### ISSUE THREAD

**Issue by Nitrousoxide** [johnfactotum/foliate#1126]
**Describe the bug**
TTS does not work in the flatpak.

**To Reproduce**
1. Double click on some text to start TTS there
2. Select "Speak from Here"
3. Get error stating "Text-to-Speech Error:  Make sure Speech Dispatcher is installed and working on your system"

**Expected behavior**
TTS should start.

**Screenshots**
![image](https://github.com/johnfactotum/foliate/assets/1363931/3c398804-5e0c-4437-84fc-56b357b8259b)

**Version:**
 - Foliate version: 3.0.0
 - OS/Distribution and version: Fedora 39
 - Desktop environment: Gnome 45.1
 - Installation method: Flatpak

**Additional context**
I have speech dispatcher installed (via a distrobox container and exported to ~/.local/bin) on this host but the flatpak container does not pick it up.  Though the flatpak should probably have that dependency installed in its own container if it's an actual dep.

```
❯ which speech-dispatcher
/home/Brian/.local/bin/speech-dispatcher

Documents/Repos/distrobox-assemble 
❯ speech-dispatcher test
[Tue Nov 14 11:02:21 2023 : 109042] speechd: Speech Dispatcher 0.11.5 starting
```

**Comment by johnfactotum** [comment]
It should work if speech-dispatcher is actively running on the host, but it does appear that it can't activate speech-dispatcher automatically if it isn't running.

**Comment by fastrizwaan** [comment]
Are  there any good human like tts voices who can do tts with foliate?

**Comment by fastrizwaan** [comment]
Just found out https://github.com/rhasspy/piper

The voice samples, they are too good
https://rhasspy.github.io/piper-samples/

if we could get it working as a flatpak, that'd be nice.

**Comment by fastrizwaan** [comment]
I've installed `rpm-ostree install speech-dispatcher-utils` and ` spd-say Hello!` does output "hello" audio on fedora 39 silverblue.

but with flatpak foliate even with talkname and full system access, it is throwing error:

here's the error output:
```
rizvan@fedora:~$ flatpak run --talk-name=org.freedesktop.Flatpak --filesystem=host com.github.johnfactotum.Foliate 


(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-CRITICAL **: 02:01:41.528: Error: Error connecting to /run/user/1000/speech-dispatcher/speechd.sock: Gio.IOErrorEnum: Could not connect: Connection refused
connect@resource:///com/github/johnfactotum/Foliate/speech.js:28:19
init@resource:///com/github/johnfactotum/Foliate/speech.js:83:30
send@resource:///com/github/johnfactotum/Foliate/speech.js:114:20
stop@resource:///com/github/johnfactotum/Foliate/speech.js:146:21
#init@resource:///com/github/johnfactotum/Foliate/tts.js:64:21
speak@resource:///com/github/johnfactotum/Foliate/tts.js:79:19
#onSelection@resource:///com/github/johnfactotum/Foliate/book-viewer.js:879:34
selection@resource:///com/github/johnfactotum/Foliate/book-viewer.js:461:53
@resource:///com/github/johnfactotum/Foliate/book-viewer.js:215:23
registerHandler/<@resource:///com/github/johnfactotum/Foliate/webview.js:172:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
^C

```

**Comment by Nitrousoxide** [comment]
> I've installed `rpm-ostree install speech-dispatcher-utils` and ` spd-say Hello!` does output "hello" audio on fedora 39 silverblue.
> 
> but with flatpak foliate even with talkname and full system access, it is throwing error:

Just to test this some more.  
I gave spd-say a long bit of text to speak out and while it was still speaking started foliate's TTS.  
```
 spd-say Hello, this is a test to see how well things are working.  Id like to see how long they will continue to talk
``

It did successfully speak.  I've not added/removed any permissions for foliate's flatpak.   I would note there are no controls for TTS though, so once you start it you can't stop it unless you back out of the book entirely.

I assume it is trying to tap into the speechd.sock which only temporarily exists while an ongoing speech command is running.

If you try to start tts in foliate without first starting spd-say in a terminal with some text line you get this (on fedora 39 workstation)
```
❯ flatpak run com.github.johnfactotum.Foliate

(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-WARNING **: 17:28:46.322: Gio.IOErrorEnum: Access to service is disallowed 'SERVICE'
getURIFromTracker@resource:///com/github/johnfactotum/Foliate/library.js:30:30
get@resource:///com/github/johnfactotum/Foliate/library.js:56:42
getBookFromIdentifier@resource:///com/github/johnfactotum/Foliate/library.js:105:36
getBook@resource:///com/github/johnfactotum/Foliate/library.js:101:21
activate@resource:///com/github/johnfactotum/Foliate/library.js:394:63
activate@resource:///com/github/johnfactotum/Foliate/library.js:322:18
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by johnfactotum** [comment]
> I gave spd-say a long bit of text to speak out

You can use `spd-say -e` to keep the server running without speaking.

> I assume it is trying to tap into the speechd.sock which only temporarily exists while an ongoing speech command is running.

In older versions of speech-dispatcher, yes. But it supports socket activation starting from 0.11.4.

The Ubuntu package for speech-dispatcher installs a `/usr/lib/systemd/user/speech-dispatcher.socket` (see https://packages.ubuntu.com/mantic/amd64/speech-dispatcher/filelist). I just tried the Snap version on Ubuntu (which has strict confinement, so as with Flatpak it can't directly spawn speech-dispatcher), and TTS works.

But the packages for Debian (https://packages.debian.org/bookworm/amd64/speech-dispatcher/filelist) and Arch Linux (https://archlinux.org/packages/extra/x86_64/speech-dispatcher/files/) don't install this file. Presumably this is the case on Fedora as well.

> If you try to start tts in foliate without first starting spd-say in a terminal with some text line you get this

No, that warning is about Tracker. I think it happens if you don't have `tracker-miners` installed. `SERVICE` here refers to `dbus:org.freedesktop.Tracker3.Miner.Files`.

**Comment by johnfactotum** [comment]
Added a section in <i>troubleshooting</i> with an explanation and a workaround for this issue: https://github.com/johnfactotum/foliate/blob/gtk4/docs/troubleshooting.md#text-to-speech-doesnt-work

**Comment by fastrizwaan** [comment]
Thank you, starting `speech-dispatcher --timeout 0` in a terminal then asking foliate to play works. 

I'm really thankful for such a wonderful ebook reader, and you've really done a great job with foliate. 

Do you by any chance know how to change the speech-dispatcher to use "piper" voices which are really good. the robotic voice is not so cool you know.

**Comment by johnfactotum** [comment]
> Do you by any chance know how to change the speech-dispatcher to use "piper" voices which are really good.

See https://github.com/brailcom/speechd/issues/866

**Comment by RoyalOughtness** [comment]
> Thank you, starting `speech-dispatcher --timeout 0` in a terminal then asking foliate to play works.
> 
> I'm really thankful for such a wonderful ebook reader, and you've really done a great job with foliate.
> 
> Do you by any chance know how to change the speech-dispatcher to use "piper" voices which are really good. the robotic voice is not so cool you know.

Posting this here as well

https://github.com/Elleo/pied

**Comment by fastrizwaan** [comment]
@qoijjj thank you so much, I've installed voices using pied. they work.

in a terminal `speech-dispatcher --timeout 0` start foliate and select text and choose 'Speak from Here'

@johnfactotum could you integrate or suggest users to use pied to get great voices.

**Comment by cshaa** [comment]
I had the same problem as reported here – Foliate reporting "Text to Speech Error" and logging that it can't access the socket. However, if I try `spd-say -e` or `speech-dispatcher --timeout 0`, it fixes the error message, but I still get no speech. Upon pressing "play", Foliate starts scrolling forward and spamming the logs with `null is not an object`:

```
(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-CRITICAL **: 23:37:49.810: null is not an object (evaluating 'new Intl.Segmenter(lang, { granularity })')
Segmenter@[native code]
getSegmenter@foliate:///foliate-js/tts.js:25:41
getFragmentWithMarks@foliate:///foliate-js/tts.js:103:35
@foliate:///foliate-js/tts.js:214:59
next@foliate:///foliate-js/tts.js:255:45
@foliate:///reader/reader.html:1:40
@foliate:///reader/reader.html:1:71
global code@foliate:///reader/reader.html:1:72
reader.view.tts.next

foliate:///foliate-js/tts.js:25:41: CONSOLE JS ERROR Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'new Intl.Segmenter(lang, { granularity })')
```
I use Piper, and `spd-say` works just fine.

https://github.com/user-attachments/assets/6834abcf-fb9b-4da0-994f-26e04a4525c9

(You have to manually unmute the video to hear that `spd-say` works)

**Comment by cshaa** [comment]
Update: oh, it seems to be an issue with the e-book, other books work just fine.

**Comment by inktveer** [comment]
I have a similar situation. `spd-say` and Firefox read aloud both work perfectly, but my Flatpak install of Foliate fails to use TTS. When I press the "read from here" button, I get notified that speech-dispatcher is not installed. However, it is. I even checked if `/usr/lib/systemd/user/speech-dispatcher.socket` exists, which it does. Using Flatseal to allow access to literally all the toggles did nothing (it's unsafe, I know, but I wanted to try). Finally, `speech-dispatcher --timeout 0` told me that "Speech Dispatcher is already running."

I use Fedora 42, `speech-dispatcher` version 0.12.0 and Piper to improve how the TTS sounds. I updated my system before testing.
