### ISSUE TITLE
Please make .deb package.

### ISSUE THREAD

**Issue by AndKe** [johnfactotum/foliate#1127]
This is how trying 3.0.0 worked out for me:

```
ndre@Loke:~/Downloads/foliate$ gjs -m src/main.js

(com.github.johnfactotum.Foliate:114029): Gjs-CRITICAL **: 20:15:44.224: JS ERROR: ImportError: Unable to load file from: file:///home/andre/Downloads/foliate/src/foliate-js/epubcfi.js (Error opening file /home/andre/Downloads/foliate/src/foliate-js/epubcfi.js: No such file or directory)
loadURI@resource:///org/gnome/gjs/modules/internal/loader.js:88:21
loadURI@resource:///org/gnome/gjs/modules/internal/loader.js:290:30
resolveModule@resource:///org/gnome/gjs/modules/internal/loader.js:179:33
moduleResolveHook@resource:///org/gnome/gjs/modules/internal/loader.js:339:29


(com.github.johnfactotum.Foliate:114029): Gjs-CRITICAL **: 20:15:44.224: Module file:///home/andre/Downloads/foliate/src/main.js threw an exception
andre@Loke:~/Downloads/foliate$ 

```

**Comment by johnfactotum** [comment]
For now you can download the .deb package from this PPA: https://launchpad.net/~apandada1/+archive/ubuntu/foliate

As for the error, it's missing submodules, which you can get by cloning Foliate with `git clone --recurse-submodules`.

**Comment by archisman-panigrahi** [comment]
@AndKe The .deb package only works in Ubuntu 23.10 and 24.04 (in development). If you are using a previous version of Ubuntu (e.g. 22.04), you will have to use Flatpak/Snap, as the dependencies for Foliatev3 are not available there.

**Comment by natewind** [comment]
Especially considering the fact that Ubuntu 22.04 is currently the latest ~~non-experimental~~ LTS version.

**Comment by archisman-panigrahi** [comment]
> Especially considering the fact that Ubuntu 22.04 is currently the latest ~~non-experimental~~ LTS version.

It won't work because ubuntu does not update most of its packages during the lifetime of a release to increase stability, and Foliate (which uses the gtk4 and libadwaita) is incompatible with those old packages. None of the recently released libadwaita apps are compatible with ubuntu 22.04. Libadwaita and gtk4 have evolved a lot since 22.04 was released.

**Comment by natewind** [comment]
> It won't work because ubuntu does not update most of its packages during the lifetime of a release to increase stability, and Foliate (which uses the gtk4 and libadwaita) is incompatible with those old packages. None of the recently released libadwaita apps are compatible with ubuntu 22.04. Libadwaita and gtk4 have evolved a lot since 22.04 was released.

Oh, I see.

\*Sigh\* I hope the Flatpak version is not super bloated and slow...

**Comment by MikhailTNY** [comment]
> @AndKe The .deb package (PPA) only works in Ubuntu 23.10 and 24.04 (in development). If you are using a previous version of Ubuntu (e.g. 22.04), you will have to use Flatpak/Snap, as the dependencies for Foliatev3 are not available there.

The new version of Flatpak doesn't work well on PopOS 22.04 LTS either. It doesn't render anything with any of my epubs. 

```
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1600x1221: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1600x1221: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1600x1221: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
```

I opened the same one on Fedora 39 non-LTS and it works fine with the same epub.

**Comment by natewind** [comment]
> Update: Found the solution from here: [#1115 (comment)](https://github.com/johnfactotum/foliate/issues/1115#issuecomment-1809480892)
> 
> @natewind you might get hit by the same bug with flatpak, you may want to see that comment on how to resolve it with flatpak on LTS branches.

Thanks!

**Comment by johnfactotum** [comment]
I've uploaded a .deb package: https://github.com/johnfactotum/foliate/releases/download/3.0.1/foliate_3.0.1_all.deb

But I just noticed that the version requirements in `debian/control` is wrong. I guess it's too late to change it now...
