### ISSUE TITLE
PDF render bugs

### ISSUE THREAD

**Issue by lumingzh** [johnfactotum/foliate#1129]
**Describe the bug**
- The render result is blur
- Scrolled mode doesn't work with pdf

**Screenshots**
![截图 2023-11-15 07-20-24](https://github.com/johnfactotum/foliate/assets/89230850/f284647c-0d8c-4042-8f05-da32838a9a5b)

**Version:**
 - Foliate version: 3.0.0
 - OS/Distribution and version: Fedora Silverblue 39
 - Desktop environment: GNOME 45.1
 - Installation method: Flatpak

**Comment by johnfactotum** [comment]
Yes, that's why it's labeled <i>experimental</i>.

Fixing this would require reworking and probably rewriting the fixed layout renderer. I think I will wait until scroll anchoring is available in WebKit because doing scroll anchoring manually is kind a pain and unnecessary once the browser supports it natively.

**Comment by RealHoshyar** [comment]
pdf rendering is awful

**Comment by mikael-ros** [comment]
This is still an issue, is this in the works or not? Some books distributed to me by my university are given (graciously) as free pdfs and I would love to read them in foliate rather than other software.

**Comment by Jopp-gh** [comment]
Using Foliate 3.1.1
For some longer time now, we are waiting for an improvement of the PDF rendering engine. In its current state, Foliate is completely unusable with its blurred fonts on a 27 inch screen:
 
![Foliate-3 1 1](https://github.com/johnfactotum/foliate/assets/48620536/a94f8066-7e48-4057-957a-a7c3bc43770c)

Wouldn't be better to use another framework than electron and js? Foliate is an amazing project and I prefer it before any other PDF reader.
