### ISSUE TITLE
Custom themes don't show up

### ISSUE THREAD

**Issue by stpnwf** [johnfactotum/foliate#1138]
I am following the instructions posted [here](https://github.com/johnfactotum/foliate/issues/1022#issuecomment-1752462317) to add a custom theme to Foliate. I copied the template and created a .json file in `~/.var/app/com.github.johnfactotum.Foliate/themes/mytheme.json` but nothing new shows up under Color in the Layout tab in the Font and Layout Settings.

Am I doing something wrong?

**Version:**
 - Foliate version: 3.0.0
 - OS/Distribution and version: Fedora 38
 - Desktop environment: Gnome 44.6
 - Installation method: Flatpak

**Comment by Hou-Rui** [comment]
I believe for Flatpak, the correct path to put the json file would be `~/.var/app/com.github.johnfactotum.Foliate/config/com.github.johnfactotum.Foliate/themes/`. Works for me when put under this path.

**Comment by stpnwf** [comment]
> I believe for Flatpak, the correct path to put the json file would be `~/.var/app/com.github.johnfactotum.Foliate/config/com.github.johnfactotum.Foliate/themes/`. Works for me when put under this path.

Thank you! That did fix it.
