### ISSUE TITLE
RDNN is really too long — how do I shorten it at compile time?

### ISSUE THREAD

**Issue by lolilolicon** [johnfactotum/foliate#114]
I must confess, @not-chicken's issue #22 and @itprojects's comment in #60 resonate with me strongly. ([This guy at HN puts it better than all of us 😛](https://news.ycombinator.com/item?id=20391212).) The full RDNN everywhere is really too long. Is the namespace really so crowded? Why be so humble? While big corps are giving their little tools names like `hub` (GitHub), `lab` (GitLab), `code` (VS Code), et cetera.

Anyway, let's focus on Foliate. The default installation creates executable `/usr/bin/com.github.johnfactotum.Foliate`. After first run, I find it writes configurations under the dconf directory `/com/github/johnfactotum/Foliate/` (which is cool), bookmarks and notes under `~/.local/share/com.github.johnfactotum.Foliate/`, and cache under `~/.cache/com.github.johnfactotum.Foliate/`.

I'd like to `s/com.github.johnfactotum.Foliate/foliate/g` all of the above.
The justification is simple: there is no other application that uses RDNN under `/usr/bin/` or `~/.local/share/` or `~/.cache/`, not even one on my system. There are only `nautilus`, `gnome-calculator`, etc — short names.

However, if that doesn't convince you, may I request your assistance to achieve my goal with my own copy? To restate my goal, I'd like to keep the dconf path intact; the executable name is easily changed with a rename; so the question is:

**How do I make Foliate write bookmarks & notes under `~/.local/share/foliate/` and its cache under `~/.cache/foliate/`?**

Besides, are there other similar locations I missed?

**Comment by johnfactotum** [comment]
Thanks for opening this issue. I do agree it looks a bit ridiculous, but for now I think I will stand by the "RDNN everything" practice.

I suppose a way around this would be to simply add an alias, and maybe symlinking the directories. If you'd like to build with everything changed, then it's probably best to do a `s/com.github.johnfactotum.Foliate/foliate/g` to all files, including all the file names. Then, to keep the dconf path intact, edit this line: https://github.com/johnfactotum/foliate/blob/fe2d7b6ee5e39b60e74007c93af11e1d945094ee/src/main.js#L258

Change `pkg.name` in that line to `'com.github.johnfactotum.Foliate'`.

**Comment by itprojects** [comment]
@lolilolicon @johnfactotum This must be a zombie bug. It will keep rising up. It just doesn't know how to enjoy eternal peace.

**Comment by lolilolicon** [comment]
1. I have solved the user data directory names with this patch:

```patch
~/.local/share/com.github.johnfactotum.Foliate/ -> ~/.local/share/foliate/
~/.cache/com.github.johnfactotum.Foliate/ -> ~/.cache/foliate/
--- foliate-1.4.0/src/main.js	2019-07-09 14:00.00.000000000 +0000
+++ foliate-1.4.0/src/main.js	2019-07-09 14:00.00.000000000 +0000
@@ -266,7 +266,7 @@
             : type === 'config' ? GLib.get_user_config_dir()
             : GLib.get_user_data_dir()
 
-        this._destination = GLib.build_filenamev([dataDir, pkg.name,
+        this._destination = GLib.build_filenamev([dataDir, "foliate",
             `${encodeURIComponent(key)}.json`])
         this._file = Gio.File.new_for_path(this._destination)
 
```

2. Turns out you can't just rename the executable. For a shorter command, I suggest we take a leaf out of gnome-books: `/usr/bin/gnome-books` is a symlink to `/usr/share/gnome-books/org.gnome.Books`. So we can make `/usr/bin/foliate` a symlink to `/usr/share/foliate/com.github.johnfactotum.Foliate` – if we change `/usr/share/com.github.johnfactotum.Foliate/` to `/usr/share/foliate/`, that is.

    To that end, the following patch works for me,

```patch
--- foliate-1.4.0/meson.build	2019-07-09 14:00:00.000000000 +0000
+++ foliate-1.4.0/meson.build	2019-07-09 14:00:00.000000000 +0000
@@ -1,4 +1,4 @@
-project('com.github.johnfactotum.Foliate',
+project('foliate',
         version: '1.4.0',
   meson_version: '>= 0.40.0',
 )
--- foliate-1.4.0/data/com.github.johnfactotum.Foliate.desktop.in	2019-07-09 14:00:00.000000000 +0000
+++ foliate-1.4.0/data/com.github.johnfactotum.Foliate.desktop.in	2019-07-09 14:00:00.000000000 +0000
@@ -4,7 +4,7 @@
 Comment=View eBooks
 Categories=Office;Viewer;
 MimeType=application/epub+zip;
-Exec=com.github.johnfactotum.Foliate %F
+Exec=foliate %F
 Icon=com.github.johnfactotum.Foliate
 Terminal=false
 Type=Application
--- foliate-1.4.0/src/meson.build	2019-07-09 14:00:00.000000000 +0000
+++ foliate-1.4.0/src/meson.build	2019-07-09 14:00:00.000000000 +0000
@@ -20,7 +20,7 @@
   input: 'com.github.johnfactotum.Foliate.in',
   output: 'com.github.johnfactotum.Foliate',
   configuration: bin_conf,
-  install_dir: get_option('bindir')
+  install_dir: pkgdatadir
 )
 
 run_target('run',
--- foliate-1.4.0/com.github.johnfactotum.Foliate.json	2019-07-09 14:00:00.000000000 +0000
+++ foliate-1.4.0/com.github.johnfactotum.Foliate.json	2019-07-09 14:00:00.000000000 +0000
@@ -3,7 +3,7 @@
     "runtime": "org.gnome.Platform",
     "runtime-version": "3.32",
     "sdk": "org.gnome.Sdk",
-    "command": "com.github.johnfactotum.Foliate",
+    "command": "foliate",
     "finish-args": [
         "--share=network",
         "--share=ipc",
```
The above, plus `ln -s /usr/share/foliate/com.github.johnfactotum.Foliate /usr/bin/foliate`.

**Comment by itprojects** [comment]
@lolilolicon It's good to know it can be done.

**Comment by johnfactotum** [comment]
I don't think the bit in `com.github.johnfactotum.Foliate.json` is needed unless you're building Flatpaks. But anyway, I think this can be closed, now that you've got it working.

I agree the long RDNN can be very annoying sometimes, but most desktop users would probably never need to see or deal with these names. If they do, there's always the option to alias or symlink.

Until there's a change regarding this issue upstream, be it GNOME, elementary OS, Flatpak, FreeDesktop, or whatever, I will keep the current scheme as it does save some headache by having a consistent ID everywhere, at the cost of slight ugliness.
