### ISSUE TITLE
WSL version shows Chinese problem

### ISSUE THREAD

**Issue by lvzhenbo** [johnfactotum/foliate#1144]
**Describe the bug**
I set Chinese in wsl and added Chinese fonts, Freda software can display Chinese, but epub can't display Chinese, and the software flashes back after selecting fonts
**To Reproduce**
1. Setting up Chinese and adding Chinese fonts in wsl ubuntu
2. Follow here https://github.com/johnfactotum/foliate/issues/115#issuecomment-830005534 to install the software
3. open Freda
4. Open a Chinese book

**Expected behavior**
Should be able to display Chinese

**Screenshots**
![image](https://github.com/johnfactotum/foliate/assets/32427677/5f2670f6-16f9-4e0d-9301-ae7b284053e8)

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Ubuntu 22.04
 - Desktop environment: WSL2
 - Installation method: WSL2

**Additional context**

**Comment by lvzhenbo** [comment]
Supplement: I tried using version ubuntu 2310 and Freda 3.0 and found that it works

**Comment by johnfactotum** [comment]
I guess this can be closed, then.
