### ISSUE TITLE
can't enforce single page pagination since 3.0 update

### ISSUE THREAD

**Issue by solomspd** [johnfactotum/foliate#1147]
**Question:**
Since 3.0, I can't enforce single page pagination, there does not seem to be that kind of setting exposed in the menu nor does there seem to be any way of passing that setting.

I wanted to ask if this is intended behavior and if so this setting would be something I'd like to contribute.

Note, when setting the maximum number of columns to 1, it still always shows two pages sides by side when reading `.cbz.` files that are mostly images (manga). For that matter, changing the number of columns does not affect the number of pages displayed

**Version:**
 - Foliate version: 3.0.1
 - OS/Distribution and version: Arch Linux
 - Desktop environment: Hyprland
 - Installation method: pacman

**Comment by johnfactotum** [comment]
Currently it isn't possible unless you convert it to EPUB and set the `rendition:spread` property. If the property isn't set or is `auto`, it's treated as `landscape`, and it will render synthetic spreads if the viewport width is greater than the height.

To fix this there would probably need to be per-book settings. And the natural way to do that would be to save `dir` (#745) and `rendition` in the book data (these keys are the ones currently used in foliate-js; however it might be better to save them as `readingProgression` and `presentation` to match webpub).

Alternatively/additionally, it could save a set of default rendition settings globally. But maybe it would be okay to make it always default to `default`/`auto`.

**Comment by solomspd** [comment]
thank you! I'm going through the source code. Am I reading it correctly that I should start looking starting [`./src/foliate-js/comic-book.js`](https://github.com/johnfactotum/foliate-js/blob/2ea63929c73b6a3b98fc772abf6b9249b3bfadab/comic-book.js). Are there any other relevant files?

**Comment by johnfactotum** [comment]
No, `comic-book.js` is only relevant if you want to add support for CBZs that contain metadata on whether synthetic spreads should be used.

If one wishes to make it configurable then it needs to be implemented in `src/book-viewer.js` and `src/reader/reader.js`.

**Comment by johnfactotum** [comment]
Closing this in favor of #1396
