### ISSUE TITLE
How to enable text-to-speech support?

### ISSUE THREAD

**Issue by andresmessina1701** [johnfactotum/foliate#1148]
**Question:**
I would be delighted to use the built-in text-to-speech feature, as it helps me focus on the book better, but I have run across an issue that stops me from doing so.
![image](https://github.com/johnfactotum/foliate/assets/106823094/0c45d15b-3c6c-4dd8-9b3c-dca28beccc37)
I checked using `sudo dnf install speech-dispatcher` and it says that it is already installed. So I assumed that there was an issue with Flatpak sandboxing, and I tried to use the `override`command to give it access to the speech-dispatcher directories. But this did not help.

Please let me know if there is something I should do or if I did something wrong, and how to get text-to-speech to work.

**Version:**
 - Foliate version:3.0.1
 - OS/Distribution and version: Fedora 39
 - Desktop environment: GNOME 45.1
 - Installation method: Flatpak

**Comment by johnfactotum** [comment]
See #1126
