### ISSUE TITLE
Foliate Snap has issues with font search

### ISSUE THREAD

**Issue by JollyPanda** [johnfactotum/foliate#1149]
**Describe the bug**
As a Snap, Foliate fails to load user fonts store in either ~/.fonts or ~/.local/share/fonts. The Flatpak version does it fine.

Font search itself takes too long on the Snap version and makes the program unresponsive for a while, but it's instant on the Flatpak version.

**To Reproduce**
1. Open Foliate
2. Open an eBook
3. Configure font and layout
4. Search the name of a font stored in either ~/.fonts or ~/.local/share/fonts

**Expected behavior**
Fonts appear quickly in the list and can be used to display text.

**Version:**
 - Foliate version: 3.0.1
 - OS/Distribution and version: Ubuntu 23.10
 - Desktop environment: GNOME 45.0
 - Installation method: Snap

**Comment by johnfactotum** [comment]
Probably not our bug as the font chooser is a built-in GTK widget and there's nothing Foliate do to fix this.

**Comment by tecix** [comment]
@JollyPanda You should locate your fonts folder (e.g ~/.local/share/fonts) , then make symlink in the path ~/snap/foliate/current/ with this command: `ln -s ~/.loca/share/fonts ~/snap/foliate/current/.fonts`
