### ISSUE TITLE
Page turn is jittery and no longer smooth after I changed the font.

### ISSUE THREAD

**Issue by chillbreeze** [johnfactotum/foliate#1155]
**Describe the bug**
After I changed the font, the page turn is no longer smooth and looks jittery. I've changed the font to several other types, and I've tried closing the application and restarting it, and even restarting the computer, but the problem persists. I've also tried reinstalling the flatpak.

**To Reproduce**
Use the scroll wheel on the mouse or arrow keys to change to the next or previous page.

**Expected behavior**
It started off smooth until I changed the font

**Screenshots**

**Version:**
 - Foliate version: 3.0.1
 - OS/Distribution and version: Fedora 39 Workstation
 - Desktop environment: GNOME 45.1
 - Installation method: Flatpak

[Screencast from 2023-11-25 10-47-31.webm](https://github.com/johnfactotum/foliate/assets/31869754/1b5f8c8e-150f-423e-b5db-0b0139242325)

**Comment by chillbreeze** [comment]
I removed the configuration files using `rm -rf ~/.var/app/com.github.johnfactotum.Foliate
` and the problem seems to be resolved for now.

**Comment by johnfactotum** [comment]
Probably because you had "invert colors in dark mode" enabled. The filter makes the animation perform poorly.
