### ISSUE TITLE
 Add scrolling of dictionary / wikipedia popup window with keyboard keys 

### ISSUE THREAD

**Issue by mars4science** [johnfactotum/foliate#1156]
**Is your feature request related to a problem? Please describe.**
I cannot use `arrows` / `pageUp` `Down` keys to scroll dictionary window, using mouse/trackpad is much less convenient at times.

**Describe the solution you'd like**
Keys work and scroll the view.

**Describe alternatives you've considered**

**Additional context**
I've found the view is most likely `GtkScrolledWindow` from `dictionaryBox.ui` and to add this functionality maybe similar to below is needed:
https://stackoverflow.com/questions/59281749/how-to-scroll-a-scrolledwindow-with-arrow-keys-in-gtk-3-24-5

**Comment by johnfactotum** [comment]
- It looks like you are using v2, which I am not maintaining anymore. v3 doesn't have this problem.
- Page up and page down are working for me even in v2.
