### ISSUE TITLE
Translate -- Doesn't save selected language

### ISSUE THREAD

**Issue by GrigorijST** [johnfactotum/foliate#1159]
Translate -- Doesn't save selected language. Always reset to English.

**Version:**
 - Foliate version: 3.0.1
 - OS/Distribution and version: Linux Mint 21.2
 - Desktop environment: Cinnamon 5.8.4
 - Installation method: Flatpak
 
https://github.com/johnfactotum/foliate/assets/28841243/ce4ec347-7689-4242-8c96-148bcd7f9b52

**Comment by MikeMilliganUA** [comment]
in the old versions the translation function was great, but now I can't use it at all, it's broken

**Comment by Equity0** [comment]
That's what's bothering me. Now I'll have to use another program to translate. Like [crow-translate](https://github.com/crow-translate/crow-translate/)

**Comment by hoshython** [comment]
Wanted to fill an issue but find out others have the same request.

**Comment by ipeacocks** [comment]
Older Foliate versions (e.g. 2.6.4 which is in Ubuntu 23.10 repos) can do that.

**Comment by ludenticus** [comment]
No `gsettings` schema to select default language either.
