### ISSUE TITLE
Please add a darker dark mode

### ISSUE THREAD

**Issue by Lightspill** [johnfactotum/foliate#1160]
**Is your feature request related to a problem? Please describe.**

The dark mode is dark grey background not black. An actual black background is much easier for me to read against.

**Describe the solution you'd like**

I'd like it if the dark mode actually had a black background, or there were some theme that could make it so.

**Describe alternatives you've considered**

I don't know of any alternatives, the current dark-ish grey is not nearly dark enough and harder to read against.

**Additional context**

I have a visual impairment that makes me more sensitive to excess light.

**Comment by johnfactotum** [comment]
For now, you can add your own custom themes. See the FAQ: https://github.com/johnfactotum/foliate/blob/gtk4/docs/faq.md#how-to-use-custom-themes

In the future, it might be possible to add a new darker theme, though I fear that there would be too many built-in themes.

A related feature is that it should have a UI for creating custom themes. This will probably be added at some point but it's less of a priority at the moment.
