### ISSUE TITLE
Bring back brightness control (solved by working out new Theming)...

### ISSUE THREAD

**Issue by ben2talk** [johnfactotum/foliate#1164]
**Describe the bug**
The ability to individually set colours for paper and text disappeared.
Also, the Brightness slider disappeared.

**Expected behavior**
Expect to be allowed to set colours for paper and text, and to have a slider to adjust brightness to adjust for comfortable reading in the room conditions.

**Version:**
 - Foliate version: foliate 3.0.1-2
 - OS/Distribution and version: Manjaro
 - Desktop environment: KDE  - plasma 5.27.9
 - Installation method: 'extra' Repository

**Comment by johnfactotum** [comment]
The brightness setting was removed in v3. I guess we can bring it back, but it would probably need to apply to the sidebar as well, which I'm not sure how to do because the `brightness()` filter seems to work differently in GTK.

As for custom themes, see https://github.com/johnfactotum/foliate/blob/gtk4/docs/faq.md#how-to-use-custom-themes.

**Comment by ben2talk** [comment]
Sadly, my custom themes aren't visible now in Foliate - I still have them from the previous version.

```
{
  "themes": [
    {
      "theme-name": "Kindle",
      "fg-color": "rgb(42,42,42)",
      "bg-color": "rgb(140,140,116)",
      "link-color": "rgb(17,56,61)",
      "invert": false,
      "dark-mode": false
    }
  ]
}

```

**Comment by johnfactotum** [comment]
Yes, the old themes are incompatible with the new version.

**Comment by ben2talk** [comment]
HAHAHA excellent.

So we moved 'themes.json' into a new folder /themes.

Edited:
```
{
    "label": "Kindle",
    "light": {
        "fg": "#353535",
        "bg": "#696956",
        "link": "#11383D"
    },
    "dark": {
        "fg": "#353535",
        "bg": "#8C8C74",
        "link": "#11383D"
    }
}
```
![2023-12-06 12:23:22](https://github.com/johnfactotum/foliate/assets/6983154/6cb07c04-f47f-4894-a067-3058aacee463)

Thank you so much, it's a winner... I have a comfortably dim screen for reading (like readingi a Kindle at night).

So the brightness control is slightly redundant once we have a theme - it's trivial to edit for brightness and have some alternatives.
