### ISSUE TITLE
Visually track text as it is spoken aloud

### ISSUE THREAD

**Issue by HolographicX** [johnfactotum/foliate#1165]
**Is your feature request related to a problem? Please describe.**
It helps to have a caret-style tracker that follows the words as they are spoken aloud with TTS.  

**Describe the solution you'd like**
I'm imaging that the word that is being spoken aloud is highlighted in an accent color, and the line that is being read is highlighted with a neutral surface color. Something like this, where the red highlight moves along the TTS's read aloud:
![image](https://github.com/johnfactotum/foliate/assets/73580740/5d54f8b1-4ba7-42c1-b2ae-d6eedd73ad52)

**Describe alternatives you've considered**
I was not able to find any alternative to achieve this.

**Additional context**
As someone with ADHD, this accessibility feature would be incredibly helpful to be able to read while listening.

**Comment by johnfactotum** [comment]
Which version are you using? v3.0 does highlight the current word (though not the sentence), provided that the TTS engine supports `<mark>`s.

**Comment by HolographicX** [comment]
I was using foliate 2; Just updated to foliate 3 and it works! Thank you so much; sorry about that.

**Comment by Department-stack** [comment]
is there any way to get this working while using piper?

**Comment by Department-stack** [comment]
Also, because i changed it to piper the page doesn't automatically move to the next one anymore. Is there a way I can fix this?
