### ISSUE TITLE
Crash when pick custom fonts.

### ISSUE THREAD

**Issue by sommio** [johnfactotum/foliate#1167]
**Describe the bug**
Crash when pick custom fonts (*my system has tens of thousands of fonts installed)*.

**To Reproduce**
1. Go to 'Font & Layout Settings'
2. Click on 'Sans'
3. Scroll down to 'Pick a Font'
4. See error:
```
Gtk:ERROR:../gtk/gtk/gtkfontchooserwidget.c:2732:gtk_font_chooser_widget_merge_font_desc: assertion failed: (font_desc != NULL)
Bail out! Gtk:ERROR:../gtk/gtk/gtkfontchooserwidget.c:2732:gtk_font_chooser_widget_merge_font_desc: assertion failed: (font_desc != NULL)
zsh: IOT instruction (core dumped)  foliate
```

**Expected behavior**
'Pick a fonts' work properly.
It works fine with the GTK3 version.

**Screenshots *GTK3 Version***

![xjgA00nqP88U1PTE](https://github.com/johnfactotum/foliate/assets/64189793/006966b6-ae5d-4b0a-9fda-8a911de1d47b)

**Version:**
 - Foliate version: 3.0.1-2.1
 - OS/Distribution and version: Arch Linux
 - Desktop environment: GNOME 45.1
 - Installation method: pacman

**Additional context**
I have tens of thousands of fonts installed on my system, but in GTK3 version 'pick a font' works fine.
If you can't fix it, is it possible to provide options that don't pass 'pick a font'?
For example using json configuration.

**Comment by johnfactotum** [comment]
The font chooser is a widget provided by GTK. So you should file a GTK bug.

> If you can't fix it, is it possible to provide options that don't pass 'pick a font'?
> For example using json configuration.

Settings are stored with GSettings at, e.g., `com.github.johnfactotum.Foliate.viewer.font.serif` for the serif font, which you can change with the `gsettings` command or dconf editor (or edit the config file when using the text file backend).
