### ISSUE TITLE
Pdf file not opening as single page mode.

### ISSUE THREAD

**Issue by kesu33** [johnfactotum/foliate#1168]
**Describe the bug**
When I open pdf file in single page view mode it open in double page. But in case of epub file it opens in single page mode.

**Expected behavior**
The pdf file must open in single page view mode when its layout setup column no is 1.

**Screenshots**
![foliateBug](https://github.com/johnfactotum/foliate/assets/78337487/1174cf43-f215-4565-975d-47feb7498a9d)

**Version:**
 - Foliate version: 3.0.1
 - OS/Distribution and version: debain 12
 - Desktop environment: kde plasma 5.27.5
 - Installation method: Flatpak

**Comment by johnfactotum** [comment]
See #1147
