### ISSUE TITLE
flatpak-spawn: Invalid byte sequence in conversion input

### ISSUE THREAD

**Issue by silvasch** [johnfactotum/foliate#1169]
**Describe the bug**
When opening a \*.epub or a \*.pdf file, foliate loads infinitely.

**To Reproduce**
1. Open foliate
2. Click on 'Open...'
3. Select your file
4. Spinner spins infinitely and doesn't load

**Expected behavior**
File should load

**Screenshots**
![Screenshot from 2023-12-03 09-58-10](https://github.com/johnfactotum/foliate/assets/128063006/fe62a81b-1d90-4925-8bca-21f17cee16cf)

**Version:**
 - Foliate version: 3.0.1
 - OS/Distribution and version: Fedora 39
 - Desktop environment: GNOME 45
 - Installation method: Flatpak

**Additional context**
Logs:
```
(com.github.johnfactotum.Foliate:2): Gtk-WARNING **: 10:02:03.860: Locale not supported by C library.
	Using the fallback 'C' locale.
flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.

(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-CRITICAL **: 10:02:13.672: My name is Oh-No-WebKit-Crashed, bug of bugs!

(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-CRITICAL **: 10:02:13.673: Look on this line, Developer -- despair!
```

**Comment by johnfactotum** [comment]
This is https://github.com/flatpak/flatpak/issues/5564. See https://github.com/flatpak/flatpak/issues/3712#issuecomment-814084209 and https://github.com/johnfactotum/foliate/blob/gtk4/docs/troubleshooting.md#-and-im-using-flatpak
