### ISSUE TITLE
[Feature request] Add page zoom option

### ISSUE THREAD

**Issue by niedzielski** [johnfactotum/foliate#117]
It'd be fantastic to support zooming the entire page the way it works in browser. In the present implementation, it's possible to change the font size but it doesn't seem possible to scale the entire contents of a page including images. For graphic novels and many other works, this greatly inhibits legibility.

I think this can be done in CSS (zoom, transform) as needed.

Possibly related to #21 and https://github.com/futurepress/epub.js/issues/667.

**Comment by johnfactotum** [comment]
Currently, you can only zoom in on images individually, but if you're on Wayland, you can also pinch zoom the entire page (but blurry, because the brightness filter is always on even if you've not change the brightness).

I'll see what I can do to improve this.

**Comment by johnfactotum** [comment]
The master branch now has a zoom option that will zoom the whole page exactly like a browser would.

**Comment by niedzielski** [comment]
@johnfactotum, thank you!! I'm very excited to try it out next release (or when I get local Debian builds going)!
