### ISSUE TITLE
Show commit hash in about dialog

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#118]
It would be great for testing and bug reporting to know the commit string of the tested application build. Could this be added to the application "About" popup?

**Comment by johnfactotum** [comment]
I've toyed with this idea before, but in the end it didn't seem very useful. Most people would probably be using the released versions. For people building from source, it should be easy enough to check which commit they're on.

**Comment by itprojects** [comment]
One other idea would be to put the commit string in the command line:
`com.github.johnfactotum.Foliate --version`
to give:
`Foliate version 1.4.0 commit 5bf8f3ccc32603bf8daa57bcdd0806ca4bf085f0`
