### ISSUE TITLE
Love Foliate! Feature request: export annotations, and nested ToC view for nested items

### ISSUE THREAD

**Issue by AnthonyBronislavaGonzales** [johnfactotum/foliate#120]
Export annotations would make this a thoroughly perfect program, IMO. :)

Minor thing, currently ToC entries which are supposed to be nested just show up as if not in a list.

**Comment by johnfactotum** [comment]
Exporting annotations is tracked in #93.

What do you mean nested ToC entries? Do you mean displaying the ToC in a tree view? Because that's just how it works currently:
![image](https://user-images.githubusercontent.com/50942278/61023608-260a2180-a39a-11e9-917b-7442e0e619c0.png)

**Comment by AnthonyBronislavaGonzales** [comment]
Oh man, wonderful to hear!

Ahhhh you're absolutely right. I had created the nested ToC for my book with Sigil but didn't save the edit, and I guess I didn't bother to check one of my million other books.

**Comment by johnfactotum** [comment]
Thanks! If you have any further thoughts on the export function, like which format you'd like to see to have built-in support, etc., feel free to comment on #93.
