### ISSUE TITLE
Change TTS - Espeak-ng sounds like a robot

### ISSUE THREAD

**Issue by lamyergeier** [johnfactotum/foliate#1207]
**Is your feature request related to a problem? Please describe.**
espeak-ng sounds robotic : [[Robotic sound - difficult to understand · Issue #1852 · espeak-ng/espeak-ng](https://github.com/espeak-ng/espeak-ng/issues/1852)](https://github.com/espeak-ng/espeak-ng/issues/1852)

**Describe the solution you'd like**
Ability to change TTS or any suggestion on espeak-ng.

**Describe alternatives you've considered**
Is this applicable to new foliate: [[Is it possible to change Foliate's TTS client? · Issue #723 · johnfactotum/foliate](https://github.com/johnfactotum/foliate/issues/723)](https://github.com/johnfactotum/foliate/issues/723)

**Additional context**

**Comment by johnfactotum** [comment]
In theory it should work with any engine that is configured as the default output module for Speech Dispatcher.

**Comment by fastrizwaan** [comment]
try piper voices using pied. https://github.com/johnfactotum/foliate/issues/1126#issuecomment-1974927417
