### ISSUE TITLE
Book Cannot Be Opened: Error The I/O read operation failed

### ISSUE THREAD

**Issue by HosseinOJ** [johnfactotum/foliate#1222]
**Describe the bug**
The latest version 3.0.1 installed from Snap cannot open files, throwing "The I/O read operation failed" error.

**To Reproduce**
1. Go to application main page
2. Click on 'Open'
3. Select a file and open
4. See error in the main page "Book Cannot Be Opened"
5. Click on 'Details'
6. See detailed error "Error: The I/O read operation failed"

**Expected behavior**
it does not open ebooks.

**Screenshots**

**Version:**
 - Foliate version: 3.0.1
 - OS/Distribution and version: Ubuntu 22.04.3 
 - Desktop environment: GNOME 42.9
 - Installation method: Snap

**Additional context**
It seems Snap does not have sufficient permission.  Taken from syslog:
"audit: type=1400 audit(1705247889.759:1869): apparmor="DENIED" operation="open" profile="snap.foliate.foliate" name="/proc/zoneinfo" pid=41348 comm="PressureMonitor" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0"

**Comment by johnfactotum** [comment]
Does it only happen with the Snap package? What about Flatpak or deb? Is the file on a removable media? Or a network/remote location?

**Comment by Freak20** [comment]
![截图 2024-01-17 20-47-33](https://github.com/johnfactotum/foliate/assets/53994122/eaa907da-14ac-48f5-a3cb-d2bfb6433604)

**Comment by HosseinOJ** [comment]
Here is the new info:
The issue happened only when I installed the package from Graphical Snap package manager. I removed it, then installed it via Snap CLI and it works smoothly.
I have not tried the other installation methods e.g. deb package, Flatpak etc.

**Comment by HosseinOJ** [comment]
Here is the new info:
The issue happened only when I installed the package from Graphical Snap package manager. I removed it, then installed it via Snap CLI and it works smoothly.
I have not tried the other installation methods e.g. deb package, Flatpak etc.

**Comment by theoteno** [comment]
Had the same issue, after Bazzite update. It work with book jumping back to page after reopening, but still is an issue (using the Flatpak app).
