### ISSUE TITLE
blurry PDF rendering

### ISSUE THREAD

**Issue by herkhinah** [johnfactotum/foliate#1242]
**Describe the bug**
Text ist often rendered blurry in the gtk4 branch of foliate, whereas in other PDF readers (e.g. firefox, zathura, evince) they are not rendered blurry.

**Screenshots**
![2024-01-30_09-52-24](https://github.com/johnfactotum/foliate/assets/80211396/de8b988d-bac7-4f67-a7c8-601901f199be)

**Version:**
 - Foliate version: 1f6766a7e2f6ba9db97bc90fb8eaefdfc44ede6c
 - OS/Distribution and version: nixos
 - Desktop environment: hyprland
 - Installation method: build from source  code

**Comment by tjaartvdwalt** [comment]
Has this issue been resolved? I have `3.1.1` installed, and have the same problem.

Screenshot of rendering in evince:
![screenshot-2024-05-08-140903](https://github.com/johnfactotum/foliate/assets/2066766/9aee3fae-d459-460f-85bf-0008586f743c)

Screenshot of rendering in foliate:
![screenshot-2024-05-08-140914](https://github.com/johnfactotum/foliate/assets/2066766/8c5df42b-6f83-42b5-a8ef-ee6bdeaa98c2)

**Comment by johnfactotum** [comment]
This is a duplicate of #1129
