### ISSUE TITLE
Open file through CLI?

### ISSUE THREAD

**Issue by celsobenedetti** [johnfactotum/foliate#1249]
**Question:**

I've installed Foliate through Flatpak, and I'm failing to open files from the CLI. 
I've tried the following approaches, and all result in the app opening, but "Book cannot be opened - file not found".

```bash
flatpak run com.github.johnfactotum.Foliate "/home/me/book.epub"
flatpak run --file-forwarding   com.github.johnfactotum.Foliate "/home/me/book.epub"
echo "/home/me/book.epub" | xargs flatpak run  --file-forwarding  com.github.johnfactotum.Foliate
echo "/home/me/book.epub" | xargs flatpak run com.github.johnfactotum.Foliate 
``` 

Thank you!

**Version:**
 - Foliate version: 3.1.0
 - OS/Distribution and version: Pop!_OS 22.04 LTS x86_64
 - Desktop environment: GNOME 42.6
 - Installation method: Flatpak

**Comment by johnfactotum** [comment]
From the [documentation](https://docs.flatpak.org/en/latest/flatpak-command-reference.html):
> `--file-forwarding`
>
>    If this option is specified, the remaining arguments are scanned, and all arguments that are enclosed between a pair of `@@` arguments are interpreted as file paths, exported in the document store, and passed to the command in the form of the resulting document path. Arguments between `@@u` and `@@` are considered uris, and any file: uris are exported. The exports are non-persistent and with read and write permissions for the application.

So

```bash
flatpak run --file-forwarding com.github.johnfactotum.Foliate @@ "/home/me/book.epub" @@
```

**Comment by celsobenedetti** [comment]
Works great. Thank you for the awesome tool.

**Comment by celsobenedetti** [comment]
Works great. Thank you for the awesome tool.
