### ISSUE TITLE
Translate window hangs after changing the language.

### ISSUE THREAD

**Issue by ritulahkar** [johnfactotum/foliate#1270]
**Describe the bug**
The translate window hangs after changing language.

**To Reproduce**
1. open a epub file.
2. select a word and right click
3. select translate
4. change the language to Assamese
5. click outside the translate window, it will not go.
6. complete app freezes

**Expected behavior**
the translate window should have gone.

**Screenshots**
![image](https://github.com/johnfactotum/foliate/assets/105012118/4ea9fbd8-bc83-48e9-b1b7-5794c6dc3741)

**Version:**
 - Foliate version: 3.1.0
 - OS/Distribution and version: Linux mint 21.3
 - Desktop environment: Cinnamon 6.0.4
 - Installation method:  Flatpak

**Comment by johnfactotum** [comment]
It's a GTK bug: https://gitlab.gnome.org/GNOME/gtk/-/issues/5568

**Comment by stonega** [comment]
> It's a GTK bug: https://gitlab.gnome.org/GNOME/gtk/-/issues/5568

There is a solution at the end of the linked page. Can we try this?

**Comment by JumperLuko** [comment]
Just open the list menu, and click out, in the page. ;)

**Comment by archerallstars** [comment]
@JumperLuko Thanks!

For anyone who's facing this issue, here's how to deal with it in the screen recording below:


https://github.com/user-attachments/assets/04629299-b12f-481c-bdff-a4afdc70fb50


Open up the language list again, then click on the page to close the translation popup.
