### ISSUE TITLE
[Feature request] mobi, fb2 support

### ISSUE THREAD

**Issue by keybreak** [johnfactotum/foliate#128]
- [x] .mobi
- [x] .fb2

This is only thing that still helds me from deleting Calibre :laughing: 

Thank you for making great software, i really enjoy using it!

**Comment by johnfactotum** [comment]
.mobi support has been added: c2d23538755bcf3aa17445192c6a28892d95a1ea. It uses [KindleUnpack](https://github.com/kevinhendricks/KindleUnpack), which is the same one used by [Lector](https://github.com/BasioMeusPuga/Lector) and [Bookworm](https://github.com/BasioMeusPuga/Lector) (although Bookworm seems to be using a pretty old version, 0.47 -- the latest is 0.82).

- [x] .mobi
- [ ] .fb2

**Comment by keybreak** [comment]
@johnfactotum 
I know it's very early, but wanted to comment **.mobi** experience so far, tried **Foliate v1.5.2** Manjaro Deepin / aur - it works and works good, but very slow, for example 1.8 Mb book:
- Opening took 11 seconds
- Top panel program reports 1 of 1 pages, although there's a lot of pages

**Comment by johnfactotum** [comment]
Yes. Those two things are related. The top panel is showing the number of "spine items" or "chapters", basically the number of separate html pages inside a book. The output of KindleUnpack for those books contains only a single html page containing all its contents. And a long html page in general takes Epub.js a long time to process.

**Comment by rstar000** [comment]
Hi! Do you want some help with FB2 support? I'm writing an FB2 to EPUB converter in almost plain python right now. You can check it out in my profile. It's not really ready yet, but maybe in a few days it could be usable... Right now it produces valid epubs that Foliate can open without issues, but I haven't figured out images and footnotes yet. It uses a small LGPL library called Ebooklib. The converting takes only about a second even for heavy books.

**Comment by somepaulo** [comment]
There are two old efforts for parsing FB2 in js - https://github.com/mlanin/node-fb2 and https://github.com/chitalka/reader
And two newer ones too - https://github.com/Litres/FB3Reader and https://gitlab.com/viva-shared/viva-parser-fb2
Maybe one of these could help bring FB2 support to Foliate?
Having a large collection of FB2 books the lack of support for these is the only reason for keeping two reader apps installed. I'd love to stick with Foliate, which is perfect in all other aspects.

**Comment by johnfactotum** [comment]
Basic `.fb2` and `.fb2.zip` support has been added.

Note that annotations are currently disabled, and last location not remembered, because they rely on EPUB CFI, which is not reliable, because they are based on the rendered HTML output rather than the source.

**Comment by somepaulo** [comment]
Thank you!
I can now finally uninstall Bookworm.
Bet I'm not the only one :)
