### ISSUE TITLE
Add Space/Shift+Space shortcuts for turning pages

### ISSUE THREAD

**Issue by elcste** [johnfactotum/foliate#1283]
I miss being able to use Space to turn pages (and Shift+Space to turn backwards). The space bar is larger than the arrow keys and the central location makes it easier to to press.

Most (all?) other ebook reader apps I've tried support these shortcuts, such as Apple Books and Google Play Books. I believe the pre-GTK4 version of Foliate also supported this shortcut.

Note that I certainly don't want to *replace* any existing shortcuts, just add these.

**Comment by sefernet** [comment]
I second this request ... Thanks !
