### ISSUE TITLE
Scale interface and adapt to big screens

### ISSUE THREAD

**Issue by mmuruev** [johnfactotum/foliate#1285]
For now in 5k resolution book index looks small and can be scaled, book itself has alot of space around the text and text is also small ( which can be fixed with default font size, but its not convinient usually just Ctrl+scroll works much better), but its possible to do book a bit adaptive it has enough space it can open more then 2 pages at once( very useful for tech books), and on scale hide text. Probably also some magnify glass feature will be good.

**Comment by johnfactotum** [comment]
You can increase the maximum width/height/number of columns from the Font & Layout Settings window (<kbd>Alt</kbd>+<kbd>,</kbd>):

![image](https://github.com/johnfactotum/foliate/assets/50942278/bb28db4c-0089-4db2-91ba-3f955aebf127)
