### ISSUE TITLE
cant open any file on zfs if you use flatpak or snap install debian

### ISSUE THREAD

**Issue by gisueop** [johnfactotum/foliate#1289]
foliate open menu will list no files on zfs and trying to open a file in foliate says could not open file file not found. installing foliate 2 debian stable this does not happen. foliate 3 flatpak it does.

someone long time ago tried this on snap foliate 2.5 and same thing
it is not the empty response issue it is different
https://github.com/johnfactotum/foliate/issues/401#issuecomment-753636519

**Comment by gisueop** [comment]
--file-forwarding no use

F: Can't get document portal mount path

**Comment by johnfactotum** [comment]
Not familiar with zfs, but this would appear to be a problem with zfs and xdg document portals, and doesn't really have anything to do with foliate itself.
