### ISSUE TITLE
Wikipedia on other language.

### ISSUE THREAD

**Issue by ivan-tretyak** [johnfactotum/foliate#129]
Now the search in Wikipedia is only in English, why not use the func library (https://github.com/wooorm/franc) or any other to determine the language of the word to be searched?

**Comment by johnfactotum** [comment]
@tim77 I see you've included the patch for the Fedora package? Unfortunately I was in a hurry and ac51120f99e0cd4976b28db0498cb5dbf61816ff was not a proper fix, which should be c691b6b7a1ad1f6d63d88ece382133eddc95e4df. Apologies!

**Comment by tim77** [comment]
@johnfactotum :) no prob. Probably i should just wait for 1.4.1.
