### ISSUE TITLE
Book titles and button icons don't render correctly when in grid view

### ISSUE THREAD

**Issue by felipemarins** [johnfactotum/foliate#1296]
**Describe the bug**
Basically what the title says. The titles and window buttons don't render correctly when I am in grid view. The buttons and some title render correctly after passing the mouse cursor over them, so I don't think it is missing fonts.
It should be worth noting that when I enable list view and restart the program, it renders correctly.

**To Reproduce**
1. Open Foliate
2. Enable grid view
4. See 

**Expected behavior**
Texts and icons should render properly.

**Screenshots**
![image](https://github.com/johnfactotum/foliate/assets/53406701/f17323da-83fd-46a3-a15b-71d8a8e99e89)

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Manjaro Linux (Testing Branch)
 - Desktop environment: Xfce 4.18
 - Installation method: Flatpak

**Additional context**
This issue also seems to occur in the Foliate package from Manjaro repo (that is still in 3.1.0).

**Comment by felipemarins** [comment]
It somehow ended up being fixed after some package update. So I guess I will just close this issue.

**Comment by shadyalfred** [comment]
I have this same issue, version 3.1.1

Maybe there is some cache directory that I should clear?
