### ISSUE TITLE
Keyboard shortcut for toggling / pinning sidebars does not work when sidebar is not focused/shown

### ISSUE THREAD

**Issue by nekohayo** [johnfactotum/foliate#1298]
It seems the latest version provides a sidebar (in library and in book) that can be toggled on/off, a.k.a. "pinned". However, it seems like the standard `F9` shortcut does not work when the book's page contents are focused (which is also the case when the sidebar is toggled off); the shortcut only works while the sidebar is shown _and_ focused (ex: in the searchentry).

**Comment by johnfactotum** [comment]
This is the same as #1299. Closing this one as that one has more information.
