### ISSUE TITLE
Text is cutoff at bottom

### ISSUE THREAD

**Issue by Radrahil** [johnfactotum/foliate#1300]
![image](https://github.com/johnfactotum/foliate/assets/54015030/e3353a18-23a2-443e-a375-e1de6a4bf9bd)

This notably does not occur for the default serif font. I have forgotten what the default sans serif font is, but tell me and I'll check it.

**Comment by Radrahil** [comment]
NVM it was a problem with my epub file, for some reason line height didn't change on that.

**Comment by johnfactotum** [comment]
Duplicate of #1255
