### ISSUE TITLE
Non-obvious way to bookmark a page.

### ISSUE THREAD

**Issue by ghost** [johnfactotum/foliate#1305]
**Question:**
How should I bookmark my pages?

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Fedora 39
 - Desktop environment: GNOME 45
 - Installation method: Fedora RPM Repo

**Search for the bookmark button/shortcut:**
1. Click ctrl+b, no budge.
2. Search under the hamburger menu.
3. Search under options/vertical dots menu.
4. Right click the page.
5. Right click the selection.
6. Oh okay right clicking the selection hides the context menu. Just select the selection(not there).
7. Search on the hidden panel underneath where the TTS can turn an eBook into an audiobook, not there.
8. Try to drag and drop a Chapter/Named page into the bookmarks.

I really tried to find this functionality as best as I could.
Where is this functionality hidden?

**Comment by ghost** [comment]
![image](https://github.com/johnfactotum/foliate/assets/163762443/c6d110e2-a0cf-4fa4-9cd2-8a5244fcce9c)
...

**Comment by ghost** [comment]
Well uhmm, it would be nice if there was an obvious keyboard shortcut for it.

**Comment by johnfactotum** [comment]
The shortcut is <code><kbd>Ctrl</kbd><kbd>D</kbd></code>, which is the standard shortcut according to [GNOME HIG](https://developer.gnome.org/hig/reference/keyboard.html).

**Comment by ghost** [comment]
I see.
Is there a shortcut to show the keyboard shortcuts?
I didn't find that option either, likely wouldn't have opened the issue then, spent over 20 minutes searching for it.

**Comment by johnfactotum** [comment]
Unfortunately, no, currently it's missing the keyboard shortcuts window.

**Comment by johnfactotum** [comment]
I've opened #1310 for the shortcuts window.
