### ISSUE TITLE
Using Festival TTS with v3.1.1

### ISSUE THREAD

**Issue by AgamjotSB** [johnfactotum/foliate#1308]
**Question:**
Hi, I'd like to know if there's a way to use Festvox/Festival (or any other tts system except espeak-ng) with Foliate?
Thanks

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Arch (kernel 6.8.7)
 - Desktop environment: Hyprland 0.39.1
 - Installation method: arch/extra repository

**Comment by johnfactotum** [comment]
See https://github.com/johnfactotum/foliate/issues/1207#issuecomment-1883594144

**Comment by AgamjotSB** [comment]
I got it working and now ended up using [piper](https://github.com/rhasspy/piper) (a neural tts system) with [pied](https://github.com/Elleo/pied) to set it up with speech dispatcher. The faq suggested espeak-ng so I assumed it's the only one supported.

Thanks for the quick answer, and this amazing e-book reader :)
