### ISSUE TITLE
Is it possible to remove the border?

### ISSUE THREAD

**Issue by Nirodhiko** [johnfactotum/foliate#1319]
Is it possible to remove the border so that it can be displayed on fullscreen?

This is the screenshot now, my system is gentoo linux, and I am using Sway window manager. Note the white borders on all sides.
![last](https://github.com/johnfactotum/foliate/assets/8435488/a3a6c41f-c4f7-4452-9b19-ae6a88386f2a)

**Comment by buddhiko1** [comment]
I forgot to say, thank you so much for this project, let me have a very good epub reading experience. Thank you so much!

**Comment by johnfactotum** [comment]
The border is probably drawn by the window manager, or by a custom GTK theme, if you're using any, but that seems less likely. Either way, Foliate itself doesn't have any such borders. I'm not familiar with Sway but it's probably related to how GTK's fullscreen feature works under Sway. That is, the window manager is supposed to remove the border when the window is fullscreened, but for some reason, doesn't.

**Comment by Nirodhiko** [comment]
Sway's border has been removed. I can't find the cause of the problem either, it could be the configuration of the gtk theme. Anyway, thank you very much for this project, which made me have a good reading experience.

**Comment by Nirodhiko** [comment]
Add this config in $HOME/.config/gtk-4.0/gtk.css can remove the window border.

`
.background { 
   padding: 0;
}
`

**Comment by buddhiko1** [comment]
@johnfactotum 
Hello, I want to buy you coffee to support this project, but I have to sign up for an account first. I used to pay directly through PayPal and didn't need to sign up. Some people are very resistant to signing up for an account.
