### ISSUE TITLE
Possible to downgrade GTK dependency?

### ISSUE THREAD

**Issue by sbstn87** [johnfactotum/foliate#1321]
**Question:**
Hi,

would it be possible to downgrade the required GTK dependency from 4.12 to 4,8.3? This would enable Foliate to be available for Debian 12 (stable) as a native .deb package.

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version : Debian 12 (stable)
 - Installation method: .deb package

**Comment by johnfactotum** [comment]
I think `4.12` is only required for the `can-shrink` property on buttons (see 5f58a6917e43891d9a82fb5dc8defd2007e1aa9c), so the minimum is actually `4.10` after 155b94d70b823b84d79f07102ad12b35e4a2f932. `4.10` is required for the new dialog APIs. See 61358a9ec42dda7876c47142e2844b251b936116. It would be easy to make it fallback to the old API (but note that the old file chooser is buggy; see #1007).

The much bigger problem is Libadwaita. Debian 12 has `1.2`. Foliate requires `1.4`. Libadwaita is very actively developed, with many additions and deprecations in each version. In fact I find them a bit challenging to keep up with. It's true that one can revert to using the old APIs but that would be kind of contrary to the spirit of the library, and would make the app work less well on current versions of GNOME.

**Comment by sbstn87** [comment]
Understood. So rather no chances for a sort of "backport".

Luckily there's always a Flatpak version.

Thank you for your answer.
