### ISSUE TITLE
Icons not rendering properly in some parts of the application

### ISSUE THREAD

**Issue by daviduzondu** [johnfactotum/foliate#1326]
**Describe the bug**
Icons for "annotations", "bookmarks" and "catalogs" are not rendered properly

**To Reproduce**
1. Install the snap package.
2. Open the app.
3. Find missing icons.

**Expected behavior**
The icons are supposed to be there. This is a small issue that doesn't affect my reading experience, but it is an issue nonetheless.

**Screenshots**
![Screenshot from 2024-05-29 14-08-30](https://github.com/johnfactotum/foliate/assets/46460041/9d69d66f-965a-4ea2-9654-2fe8e869b0f9)
![Screenshot from 2024-05-29 14-08-07](https://github.com/johnfactotum/foliate/assets/46460041/be82a0b2-33ab-44d9-bf67-416c4678ef6f)

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Pop!_OS jammy 22.04 x86_64
 - Desktop environment: Gnome 42.9
 - Installation method: Snap

**Comment by johnfactotum** [comment]
The problem is most likely that, for whatever reason, the host icon theme is not exposed in the sandbox. Actually I'm not sure whether Snapd exposes icons themes at all. Unlike Flatpak, it seems that it's necessary to install the Snap version of the icon themes, if you're using a custom theme.

**Comment by daviduzondu** [comment]
Thanks. The issue has been resolved for me.

For anyone experiencing this on Pop OS with the snap version of foliate, try the following:

Run:
```bash
sudo apt install pop-gtk-theme pop-icon-theme
```

Then install the pop-themes snap package:
```bash
sudo snap install pop-themes
```

Lastly, connect the themes to all apps which have available plugs to gtk-common-themes:
```bash
for i in $(snap connections | grep gtk-common-themes:gtk-3-themes | awk '{print $2}'); do sudo snap connect $i pop-themes:gtk-3-themes; done

for i in $(snap connections | grep gtk-common-themes:gtk-2-themes | awk '{print $2}'); do sudo snap connect $i pop-themes:gtk-2-themes; done

for i in $(snap connections | grep gtk-common-themes:icon-themes | awk '{print $2}'); do sudo snap connect $i pop-themes:icon-themes; done
```
