### ISSUE TITLE
User stylesheet not working

### ISSUE THREAD

**Issue by paul1149** [johnfactotum/foliate#1327]
**Version:**
 - Foliate version:  2.6.4
 - OS/Distribution and version: MX Linux 23, (debian)
 - Desktop environment: KDE Plasma v: 5.27.5
 - Installation method: came with distro

I created a `user-stylesheet.css` at /user/.local/share/com.github.johnfactotum.Foliate because that is where I found the foliate hierarchy. The file is simple:

```
p span.redletter	{ color: #baa586 !important }
p	{background: blue !important }
h1	{color: red !important }
```

Yet it's not hitting anything.

I then created a hierarchy and copied the css file to /user/.config/com.github.johnfactotum.Foliate since that is where the wiki says it should reside. 

Still nothing.

I restarted Foliate after each .css change. Not sure if there's something obvious that I'm missing.

Thanks.

**Comment by johnfactotum** [comment]
You're using v2.6.4, which doesn't have this feature. User stylesheet support was added in v3.0.0 (efc2dd4be4aeebf35475708ca6d182dee2e21eb1).

**Comment by paul1149** [comment]
A ha. That would certainly explain it. I'll see if I can figure out a manual install. Or worst case I can access the flatpak. Thank you.

**Comment by paul1149** [comment]
The install failed regarding CMake and gjs-1.0, so I went with the flatpak.

I'm finding the font rendering much worse than the installed version was, and there's no way to access program settings.
