### ISSUE TITLE
How to change highlight color? (plase refer to the screenshot)

### ISSUE THREAD

**Issue by CipherCloak** [johnfactotum/foliate#1329]
**Question:**
How to change highlight color?

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Linux Mint 21.3
 - Desktop environment: Cinnamon
 - Installation method: Flatpak
 
Let me explain with an image:
![image](https://github.com/johnfactotum/foliate/assets/3332674/1e567409-a87e-4e38-b94c-0609756fbc50)

Thanks in advance!!!

**Comment by johnfactotum** [comment]
Create a [user stylesheet](https://github.com/johnfactotum/foliate/blob/gtk4/docs/faq.md#can-i-set-my-own-custom-css-styles) and change the color with the [`::selection`](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection) pseudo-element.

**Comment by CipherCloak** [comment]
Great!!!
Thank you so much!
