### ISSUE TITLE
FAQ section

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#133]
Please, let there be a 'wontfix' section in the Readme.md to help the users understand what the problems are, before filing a new bug. It can only help.

**Comment by itprojects** [comment]
@johnfactotum  One question may be:
What IDE do you recommend for Foliate? What are the setup steps, if any?

**Comment by johnfactotum** [comment]
1. It's generally accepted that before filing a new issue, one should always search existing issues first, and I think that should suffice. So I will mark this request to have a wontfix section as wontfix.
2. Generally it's more convenient to use Gnome Builder. The steps are in the readme.
