### ISSUE TITLE
Text to Speech language

### ISSUE THREAD

**Issue by mariolinux** [johnfactotum/foliate#134]
Can you add the language argument to get a better TTS?
You could use the language of the eBook, if available in the eBook's metadata, or, if not available, a sort of (but I don't know how) language discovery feature.
Thanks and congratulations for the project.

**Comment by itprojects** [comment]
You could switch the voice manually with `espeak-ng -v myvoice` , changing `myvoice` to whatever your system has. This isn't ideal, but it might do the job, for now.

**Comment by johnfactotum** [comment]
It should be possible to parse the output of `espeak --voices` and select one automatically.

**Comment by lelinhtinh** [comment]
Can you add a `{{ text }}` template for the case it's in the middle of command? For example:

[`gtts-cli '{{ text }}' -l fr | play -t mp3 -`](https://gtts.readthedocs.io/en/latest/cli.html#playing-sound-directly)

**Comment by johnfactotum** [comment]
@lelinhtinh The easiest way to use `gtts-cli` would be to write a script, something like:

```bash
#!/bin/bash
cat /dev/stdin | gtts-cli -l fr - | play -t mp3 - &
trap "kill $!; exit 0" INT
wait
```

And set this script as the TTS command.

**Comment by RichardJActon** [comment]
Hi I'm having some trouble getting a script to call a custom voice to work. I initially tried what you posted above. This works fine when invoked from the command line with `echo "test" | tts-script.sh`. But, when I place the script in the tts command box in foliate and press the read button it just rapidly moves the progress bar through the entire book and does not generate any sound. Do you have any suggestions as to how to make the script work? I'm a little unclear how exactly foliate invokes the command provided and how it chunks up the text to feed to it I took a look at the source but I don't know js.

**Comment by johnfactotum** [comment]
@RichardJActon Which TTS program are you using? Foliate turns the page after the command returns, and then gives it the text of the next page, so it's important that it only returns after it has finished reading.

**Comment by kupiqu** [comment]
> @lelinhtinh The easiest way to use `gtts-cli` would be to write a script, something like:
> 
> ```shell
> #!/bin/bash
> gtts-cli -l fr --file /dev/stdin | play -t mp3 - &
> trap 'kill $!; exit 0' INT
> wait
> ```
> 
> And set this script as the TTS command.

I was looking exactly for this, in my case I prefer using `mpv` instead of `play -t mp3` but it works the same :)

**Comment by johnfactotum** [comment]
On master, after a83696ff7b75f01fed8fa209d58f72a1222c75b1, the environment variables `FOLIATE_TTS_LANG` and `FOLIATE_TTS_LANG_LOWER` are now available. So one can use:
```bash
#!/bin/bash
gtts-cli -l $FOLIATE_TTS_LANG_LOWER --file /dev/stdin | play -t mp3 - &
trap 'kill $!; exit 0' INT
wait
```

For books that specify more precise language codes -- for example, the books from [Standard Ebooks](https://standardebooks.org/) -- it will even read British books with the British voice, and Australian books with the Australian voice, and so on. It's quite interesting.

**Comment by apandada1** [comment]
I had to modify the script slightly to make gTTs work in Foliate [installed in an Android phone](https://github.com/johnfactotum/foliate/issues/690).

Somehow, `play` from `sox` does not work there, and `mpv` does not work either. I had to use VLC instead.

Also, the output of `$FOLIATE_TTS_LANG_LOWER` was `en-gb`, and for some reason `gTTs` could not recognize this language code. In the script, I had to manually change the language to `en`.

I have written all the details here https://askubuntu.com/a/1336107/124466 .

**Comment by jsuarez314** [comment]
> Hi I'm having some trouble getting a script to call a custom voice to work. I initially tried what you posted above. This works fine when invoked from the command line with `echo "test" | tts-script.sh`. But, when I place the script in the tts command box in foliate and press the read button it just rapidly moves the progress bar through the entire book and does not generate any sound. Do you have any suggestions as to how to make the script work? I'm a little unclear how exactly foliate invokes the command provided and how it chunks up the text to feed to it I took a look at the source but I don't know js.

Hi have the same problem that @RichardJActon. I'm using the gtts program. When I invoked `echo "test" | gtts_script.sh` from the command line the script works. But when I try from foliate, this does not work.

**Comment by johnfactotum** [comment]
@jsuarez314 Can you post the content of the script? And error messages, if any? Also it might be better to open a separate issue, as this issue is only about TTS language.

@apandada1 I haven't tried it recently, but I can say that it did work before. I think it might be related https://github.com/pndurette/gTTS/pull/245. Maybe one can still get region tags to work with `--nocheck`. Maybe Foliate should provide a variable for language codes without region codes. Or one can just split on the `-` character [in the Bash script](https://stackoverflow.com/questions/19482123/extract-part-of-a-string-using-bash-cut-split).

**Comment by jsuarez314** [comment]
> @jsuarez314 Can you post the content of the script? And error messages, if any? Also it might be better to open a separate issue, as this issue is only about TTS language.
> 
> @apandada1 I haven't tried it recently, but I can say that it did work before. I think it might be related [pndurette/gTTS#245](https://github.com/pndurette/gTTS/pull/245). Maybe one can still get region tags to work with `--nocheck`. Maybe Foliate should provide a variable for language codes without region codes. Or one can just split on the `-` character [in the Bash script](https://stackoverflow.com/questions/19482123/extract-part-of-a-string-using-bash-cut-split).

I found a partial solution, when I launch foliate from Desktop the gtts script does not work, but when I launch foliate from the terminal the gtts script works fine.
