### ISSUE TITLE
Option to open PDFs in external app

### ISSUE THREAD

**Issue by zerodogg** [johnfactotum/foliate#1343]
**Is your feature request related to a problem? Please describe.**
On my tablet, the pdf.js renderer is somewhat slow (and touchpad interaction/swiping is currently missing). Evince is quite a bit faster, which on a low-powered tablet (mine is 1.6GHz) makes quite a bit of difference. I'd still like to have my "library" in Foliate, unlike what I have now which is epubs in foliate, and PDFs in evince.

**Describe the solution you'd like**
An option that will open PDFs in an external app (xdg-open?) instead of using the builtin PDF-support.

**Describe alternatives you've considered**
The alternative right now is just using evince directly. It works, but the result is that I have two "libraries" instead of one.

**Comment by johnfactotum** [comment]
This has been fixed with #1372.

**Comment by zerodogg** [comment]
Fantastic! Thanks @johnfactotum & @axlEscalada
