### ISSUE TITLE
how to change the theme from dark to light.

### ISSUE THREAD

**Issue by ahmad9059** [johnfactotum/foliate#1348]
**Question:**
I want to change theme from dark to light how to do that there is no option to select theme and I am using the archlinux with hyprland and gtk . Dark is my default theme .
![image](https://github.com/johnfactotum/foliate/assets/144830322/def3e74d-2870-4027-b6a7-9308ce599883)

**also I follow these steps did not work** 

How to use custom themes?
The themes can be configured from the menu. This is the recommended way.

If you want to manually edit themes, you can edit the file /home/user/.config/com.github.johnfactotum.Foliate/themes.json (or create the file if does not already exists). If you're using the flatpak version, the file should be placed in ~/.var/app/com.github.johnfactotum.Foliate/config/com.github.johnfactotum.Foliate.

Note that since v2.0, the underlying settings now store the colors directly, instead of referencing the themes. So you can change the theme with dconf-editor or, from the command line, with gsettings, without needing to modify themes.json at all. The themes from themes.json merely provide a way to quickly switch color schemes from the GUI.

**Comment by greed-d** [comment]
Hey sorry for necrobumping but did you find how to change theme and font in hyprland?

**Comment by Bai-Chiang** [comment]
I'm using Sway and flatpak version. To force Foliate use light theme I added `GTK_THEME=Adwaita:light` environment variable in Flatseal.

**Comment by GideonWolfe** [comment]
@greed-d did you ever figure this out? In `hyprland` on NixOS and there is no GUI to change the theme/colors and my json one doesnt seem to be working

**Comment by GideonWolfe** [comment]
Figured it out, it's `Alt+,` to show the options once you're in an actual book
