### ISSUE TITLE
unable show after open, need to go into library and select the book

### ISSUE THREAD

**Issue by vincentaxhe** [johnfactotum/foliate#1354]
**Describe the bug**
I'm using foliate in hyprland, when open epub in foliate, It always show nothing in pages, need to go into library and choose the book, after that the book start to show pages.

**Version:**
 - Foliate version:3.1.1-1
 - OS/Distribution and version: manjaro
 - Desktop environment: hyprland 0.41.1

**Comment by debug686** [comment]
Is this the same bug as shown here? https://github.com/johnfactotum/foliate/issues/1357

**Comment by vincentaxhe** [comment]
> Is this the same bug as shown here? #1357

no, every time it opens an epub book,it show nothing but toc, click toc item, it still show nothing,only after select from library I will show pages, weather os restart did not matter.

**Comment by FabianEscarate** [comment]
hi. i don´t know if it's the same problem but i did this step (previuly i install folliate from flathub).
1.- install Flatseal (form flathub)
2.- add this Variable in "Variable seccion" 
      WEBKIT_DISABLE_DMABUF_RENDERER=1
3.- try again to open foliate

**Comment by vincentaxhe** [comment]
I use arch, have not install any packages from flathub or snap, I try not to.I will add this to hyprland env and test it.

**Comment by vincentaxhe** [comment]
thank you, It works!
