### ISSUE TITLE
Foliate is unable to find books after #ecd9a15f

### ISSUE THREAD

**Issue by debug686** [johnfactotum/foliate#1355]
After commit #ecd9a15f (Remove Tracker policy (# 33)), Foliate is unable to find books. The following messages appear in the terminal:

```
(com.github.johnfactotum.Foliate:2): Gtk-CRITICAL **: 16:32:29.977: gtk_widget_measure: assertion 'for_size >= -1' failed

(com.github.johnfactotum.Foliate:2): Gtk-CRITICAL **: 16:32:29.977: gtk_widget_measure: assertion 'for_size >= -1' failed

(com.github.johnfactotum.Foliate:2): Gtk-WARNING **: 16:32:29.977: gtk_widget_size_allocate(): attempt to allocate FoliateBookItem box 0x5612092a40d0 with width -30 and height -18

(com.github.johnfactotum.Foliate:2): Gtk-CRITICAL **: 16:32:30.344: gtk_widget_measure: assertion 'for_size >= -1' failed

(com.github.johnfactotum.Foliate:2): Gtk-CRITICAL **: 16:32:30.344: gtk_widget_measure: assertion 'for_size >= -1' failed

(com.github.johnfactotum.Foliate:2): Gtk-WARNING **: 16:32:30.344: gtk_widget_size_allocate(): attempt to allocate FoliateBookItem box 0x56120a50e160 with width -30 and height -18

(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-WARNING **: 16:32:42.904: Gio.IOErrorEnum: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code1: Service 'dbus:org.freedesktop.Tracker3.Miner.Files' not found in Tracker policy
getURIFromTracker@resource:///com/github/johnfactotum/Foliate/library.js:83:60
get@resource:///com/github/johnfactotum/Foliate/library.js:121:42
getBookFromIdentifier@resource:///com/github/johnfactotum/Foliate/library.js:169:36
getBook@resource:///com/github/johnfactotum/Foliate/library.js:166:21
activate@resource:///com/github/johnfactotum/Foliate/library.js:860:63
activate@resource:///com/github/johnfactotum/Foliate/library.js:386:18
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
Failed to create /home/debugger/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.

(com.github.johnfactotum.Foliate:2): Gjs-CRITICAL **: 16:34:26.438: JS ERROR: TypeError: this[#data] is undefined
vfunc_unroot@resource:///com/github/johnfactotum/Foliate/book-viewer.js:995:9
connectWindowRemoved@resource:///com/github/johnfactotum/Foliate/app.js:392:16
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.johnfactotum.Foliate:2): Gjs-CRITICAL **: 16:34:26.451: Attempting to run a JS callback during shutdown. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
The offending callback was ListBoxUpdateHeaderFunc().
== Stack trace for context 0x56120829d9b0 ==
```

**To Reproduce**
Open Foliate
Click on a book
File not found
Downgrade Foliate to commit #2dc933069c77527a37e51489f51879db447aa73656b0dc6246a7540ae3a57d27 
Open Foliate
Click on a book
File found

**Version:**
 - Foliate version: since #ecd9a15f
 - OS/Distribution and version: Fedora 40
 - Desktop environment: Gnome
 - Installation method: Flatpak

**Additional context**
Foliate does not have network permission.

**Comment by johnfactotum** [comment]
Yes, that is the expected effect of that commit. See https://github.com/johnfactotum/foliate/issues/1209#issuecomment-2037770373

**Comment by debug686** [comment]
It's intended for Foliate to not find any books after an update? I really liked that feature.
I gave the the Foliate flatpak the file permission for the folder that the books are in, but that doesn't help.

**Comment by FabianEscarate** [comment]
hi. i don´t know if it's the same problem but i did this step (previuly i install folliate from flathub).
1.- install Flatseal (form flathub)
2.- add this Variable in "Variable seccion" 
      WEBKIT_DISABLE_DMABUF_RENDERER=1
3.- try again to open foliate

**Comment by debug686** [comment]
Thank you. This does not solve this issues unfortunately.

**Comment by johnfactotum** [comment]
To use Tracker to track the location of files, you need to have
- The permission for Tracker, `--add-policy=Tracker3.dbus:org.freedesktop.Tracker3.Miner.Files=tracker:Documents`
- The permission for the files, --filesystem=xdg-documents:ro, --filesystem=xdg-download:ro, etc. depending on where the files are located
- The files has to be indexed by Tracker. In GNOME, the files needs to be contained in the "Search Locations" in Settings.
