### ISSUE TITLE
ebooks lost after restart

### ISSUE THREAD

**Issue by tronta** [johnfactotum/foliate#1357]
**Describe the bug**

After a new start of the OS previously added  books are displayed, but cannot be opened anymore.

This video shows first a just added ebook and after that ebooks which have been added before the last OS restart:

[Bildschirmaufzeichnung vom 2024-07-15 17-24-40.webm](https://github.com/user-attachments/assets/9bc82804-7567-4b7c-883f-3cd8e4a2fb46)

After adding them, they are again available available (till they are again lost)

**To Reproduce**

* add books
* close Foliate
* restart OS
* start Foliate
* open ebook

**Expected behavior**

All books stay available, till they are deleted by purpose.

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Fedora Silverblue 40
 - Desktop environment: GNOME 46
 - Installation method: Flatpak

**Comment by debug686** [comment]
Could be the same issue: https://github.com/johnfactotum/foliate/issues/1355

I'm very puzzled by the response I got from johnfactotum in that issue.

**Comment by FabianEscarate** [comment]
hi. i don´t know if it's the same problem but i did this step (previuly i install folliate from flathub).
1.- install Flatseal (form flathub)
2.- add this Variable in "Variable seccion" 
      WEBKIT_DISABLE_DMABUF_RENDERER=1
3.- try again to open foliate

**Comment by tronta** [comment]
Thanks for the hint: I tried it:
![image](https://github.com/user-attachments/assets/2c07f822-9a31-41cb-a228-a976a5e28e18)
But I'm still having the experience of 'loosing' books.

**Comment by johnfactotum** [comment]
This is #942.
