### ISSUE TITLE
[Feature request] Simple editing 

### ISSUE THREAD

**Issue by Fanelia82** [johnfactotum/foliate#136]
It is possible to implement in foliate a simple text editor tool for ebooks? (for example correction of misprints and grammar errors)

**Comment by johnfactotum** [comment]
That is out of the scope of this project. If you need editing, you may consider using a dedicated editor like [Sigil](https://sigil-ebook.com/), or for simple editing tasks, it should suffice to simply unzip the EPUB file, make your edits, and then [repack it](https://ebooks.stackexchange.com/questions/257/how-to-repack-an-epub-file-from-command-line).
