### ISSUE TITLE
Open links in foliate

### ISSUE THREAD

**Issue by fa441907** [johnfactotum/foliate#1362]
I have a clicky-list of all the epub files on my computer in a file format epub.
If I open that epub in Okular, I can follow the links
But foliate does nothing.
So - How to open links in foliate ??

**To Reproduce**
1. Clicky-list entries look like this
2. <a href="file:///home/rch2/Downloads/482.epub">482.epub</a>

**Expected behavior**
foliate does much better than Okular everywhere but here

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Ubuntu 22.04.4 LTS

**Additional context**
Not so much a Problem, more a Request for help.

**Comment by fa441907** [comment]
Sorrry : I forgot the tildes
Clicky-list entries look like this
~~~
      <a href="file:///home/rch2/Downloads/482.epub">482.epub</a>
~~~

**Comment by fa441907** [comment]
Update
~~~
COMMAND
    $ foliate foobar.epub

RESULT
    ** (com.github.johnfactotum.Foliate:615746):
      WARNING **: 16:19:09.659: Could not open /sys/class/dmi/id/chassis_type:
      Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

    ** (com.github.johnfactotum.Foliate:615746):
      WARNING **: 16:19:09.659: Could not open /sys/firmware/acpi/pm_profile:
      Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

    ** (process:615849):
      WARNING **: 16:19:09.943: Could not open /sys/class/dmi/id/chassis_type:
      Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

    ** (process:615849):
      WARNING **: 16:19:09.943: Could not open /sys/firmware/acpi/pm_profile:
      Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

    (com.github.johnfactotum.Foliate:615746): 
      GLib-GIO-CRITICAL **: 16:19:38.651: g_task_return_error: 
      assertion 'G_IS_TASK (task)' failed

    (com.github.johnfactotum.Foliate:615746): 
      GLib-GObject-CRITICAL **: 16:19:38.651: g_object_unref: 
      assertion 'G_IS_OBJECT (object)' failed
~~~
For those two /sys/ files
"Only the owner can change permission"
Would that be safe to do?

**Comment by johnfactotum** [comment]
Do not change the permission. Those are just warnings that probably has nothing to do with your issue.

Are you using Snap? Flatpak?
