### ISSUE TITLE
no  javascript file in epub 3

### ISSUE THREAD

**Issue by drmhessler** [johnfactotum/foliate#1365]
I want to use some interactive 3D Plot via plotlyfy in an epub 3 file. I've included some .js files but foliate 3.3.1 (Desktop) is not including them properly according to 
![Screenshot_20240727_174330](https://github.com/user-attachments/assets/84b439f7-71b3-45d7-a5d9-b0cf35c0bb5b)
The two js files are  defintly included in the epub file as calibre viewer (and editor) shows.
![Screenshot_20240727_175306](https://github.com/user-attachments/assets/0e3ea026-34f6-4da3-84ae-4484676e75b2)
How can this be fixed?

**Comment by johnfactotum** [comment]
Scripting is not supported. See #1202.
