### ISSUE TITLE
Foliate doesn't show images via relative URL's

### ISSUE THREAD

**Issue by marcris** [johnfactotum/foliate#137]
My (epub) book has relative references to images e.g ../images/image.png. These images show when using the Calibre viewer or the (Ubuntu Linux) Atril document viewer, but not with Foliate.

Otherwise a great piece of work!

**Comment by johnfactotum** [comment]
This is probably an upstream issue with Epub.js.

If the book's license does not allow you to share the file with me, you can help debug this yourself by going to https://futurepress.github.io/epub.js/examples/input.html and see if it works with Epub.js. If not, you might have to report a bug to them.

Note that the prev/next button on their example is currently broken. However, if you open your browser's developer tools, you should be able to use the console and run rendition.next() and rendition.prev().

**Comment by johnfactotum** [comment]
Closing this for now, as there's not enough info to reproduce this issue. In any case it's most probably an upstream issue. Feel free to reopen if you have any further info.
