### ISSUE TITLE
How to store/backup library

### ISSUE THREAD

**Issue by afduggirala** [johnfactotum/foliate#1376]
Hello,

I wonder how one would store the Foliate library information as a backup in case my disk dies or when transfering to a new pc. I keep all my books in a single folder on my drive, but every time I reinstall my OS I find myself having to add all of my books to my library. I also loose all progress information for each book and bookmarks.

Is there a way to backup and restore all library information into a new installation of Foliate?

thank you,

**Comment by johnfactotum** [comment]
See the [FAQ](https://github.com/johnfactotum/foliate/blob/gtk4/docs/faq.md#how-are-notes-and-bookmarks-stored):

> Your reading progress, bookmarks, and annotations are saved in `~/.local/share/com.github.johnfactotum.Foliate`.
>
> If you're using the Flatpak version, they should be in `~/.var/app/com.github.johnfactotum.Foliate/data/com.github.johnfactotum.Foliate`.
