### ISSUE TITLE
Foliate Seems To Forget Locations Of Books

### ISSUE THREAD

**Issue by EveningComet** [johnfactotum/foliate#1377]
**Describe the bug**
After some time, it appears that Foliate seems to forget where it saves or references imported books. When this bug happens, the program will display the file not found screen.

**To Reproduce**
1. Download Foliate
2. Use it over the course of at least a week.

**Version:**
 - Flatpak (I only tried it on Flatpak through Fedora in case that could be the problem)

**Comment by johnfactotum** [comment]
Duplicate of #942
