### ISSUE TITLE
Strange Metainfo

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#1386]
**Describe the bug**
The application is described in two ways.
In this repositiry as "Foliate", however, application comes as "John Factotum", possibly due to bad `metainfo.xml`.
 

**To Reproduce**
1. Open terminal
2. `flatpak list`

**Expected behavior**
Expected name "Foliate"

**Screenshots**
![0](https://github.com/user-attachments/assets/aaaa7ee2-fa8f-4bbe-aedc-3eec236fdae7)

**Version:**
 - Foliate version: latest
 - OS/Distribution and version: Ubuntu 24.04
 - Desktop environment: GNOME 46
 - Installation method: Flatpak

**Additional context**
Could the problem be in [com.github.johnfactotum.Foliate.metainfo.xml.in](https://github.com/johnfactotum/foliate/blob/gtk4/data/com.github.johnfactotum.Foliate.metainfo.xml.in)

```
    <developer_name translate="no">John Factotum</developer_name>
    <developer id="io.github.johnfactotum">
        <name translate="no">John Factotum</name>
    </developer>
```

Perhaps consider using only the top one?

```
<developer_name translate="no">John Factotum</developer_name>
```

Compare with [Rnote](https://github.com/flxzt/rnote/blob/main/crates/rnote-ui/data/app.metainfo.xml.in.in)

```
  <developer_name translatable="no">@APP_AUTHOR_NAME@</developer_name>
```

**Comment by johnfactotum** [comment]
https://github.com/flatpak/flatpak/issues/5700
