### ISSUE TITLE
FYI: After Ubuntu upgrade, foliate locks up

### ISSUE THREAD

**Issue by fire-eggs** [johnfactotum/foliate#1387]
Upgraded to KUbuntu 24.04. When trying to open a book with foliate 2.6.3, foliate hangs/locks and has to be killed.

After invoking from within a terminal window, I got the following error message:
`bwrap: setting up uid map: Permission denied`

Googling this error got me to this:

https://github.com/DevToys-app/DevToys/issues/1198

I applied the solution as mentioned there, and now foliate runs happily again.

1. Not sure if foliate's startup could be improved so that the user isn't presented with a stuck window.
2. This issue and solution might be documented.

FYI.

**Comment by johnfactotum** [comment]
That looks like #1262.

**Comment by fire-eggs** [comment]
Righto. Sorry for duplication.
