### ISSUE TITLE
Missing deb package since 3.1.0 from releases?

### ISSUE THREAD

**Issue by kianmeng** [johnfactotum/foliate#1392]
**Question:**
I have noticed that since 3.1.0, the `deb` package have been missing from the release page, https://github.com/johnfactotum/foliate/releases?

Even the GitHub action have been fixed, https://github.com/johnfactotum/foliate/pull/1383, any chances to generate the `deb` build for the releases?

**Comment by johnfactotum** [comment]
https://github.com/johnfactotum/foliate/releases/download/3.1.1/foliate_3.1.1_all.deb

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:
