### ISSUE TITLE
When zoom in, the book keeps flushing

### ISSUE THREAD

**Issue by kuchaguangjie** [johnfactotum/foliate#1408]
Need to restore zoom, and reopen the book to fix it.

**Comment by johnfactotum** [comment]
Can you provide more information? What type of book are you opening? And what exactly do you mean by "flushing"?

Note that zooming is currently unsupported for fixed layout books.

**Comment by kuchaguangjie** [comment]
An `.epub` book with hundreds of pages. Flushing like when u press `F5` on desktop.
On `ubuntu 22.04`.

**Comment by johnfactotum** [comment]
Well, I'm still not entirely sure what you mean exactly, but I don't think I can reproduce the behavior. For reflowable books, if there are a lot of pages, that is, a lot of CSS columns, it does take some time to reflow when zooming, but that's it.

Which version of Foliate are you using? And is there a specific book or other conditions, such as the zoom level, window size, font, etc. that trigger the behavior?

**Comment by kuchaguangjie** [comment]
`<Programming.in.Lua 4th.epub>` This is the book, it's a big book.
Version `2.6.4` on ubuntu.
`ctrl +` to zoom a little bit will cause the issue. And it will flushing for more than 1 minute, then I just close it.

**Comment by johnfactotum** [comment]
In that case the issue would be essentially the same as #459 and fixed in version 3.
