### ISSUE TITLE
"Source Code" opens two browser tabs

### ISSUE THREAD

**Issue by o1Suleyman** [johnfactotum/foliate#1417]
**Describe the bug**
Clicking "Source Code" opens two browser tabs instead of one
**To Reproduce**
1. Open Foliate
2. Open the hamburger menu and click "About Foliate" or F1 on your keyboard
3. Click "Details"
4. Click "Source Code"
5. Your browser opens two GitHub pages instead of one

**Expected behavior**
Only one browser tab should open, not two

**Screenshots**
![image](https://github.com/user-attachments/assets/54c4648f-67e8-4ed0-9df4-8637ade08087)
![image](https://github.com/user-attachments/assets/4a96e71e-a114-46de-abf3-14b546b899f1)

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Ubuntu 24.04
 - Desktop environment: GNOME 46
 - Installation method: Snap

**Comment by o1Suleyman** [comment]
It isn't just "Source Code", this happens with all links in the Hamburger Menu like "Report an Issue"

**Comment by johnfactotum** [comment]
Seems to work fine for me. The dialog is a Libadwaita widget, so this is most likely not our bug.
