### ISSUE TITLE
Generating EpubCFI from E-reader's Database

### ISSUE THREAD

**Issue by orhnk** [johnfactotum/foliate#1425]
**Question:**
I'm trying to develop an script that will read from my e-book's database (KoboReader.sqlite) and fetch out the annotations to my foliate app. Stuck with the epubcfi standards.

KoboReader.sqlite includes a lot of information about your annotations under the table `Bookmark`. I just need some information about where to put what on the cfi. Could you help me please?

Here's the database in action:

https://github.com/user-attachments/assets/18a580b5-4694-4122-911f-801f2e352ddf

I checked out your -js library and there are some epubcfi algorithms there. (Also the document you've put on FAQ) But me and gpt was having some trouble with it.

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: NixOS 24.11
 - Desktop environment: dwm
 - Installation method: Normal (nixpkgs)

**Comment by johnfactotum** [comment]
See https://github.com/valeriangalliat/kobo-highlights-to-calibre

**Comment by orhnk** [comment]
I used https://github.com/pmstss/epub-cfi-generator

Good project.

But having problems with some edge case misdefined epubcfi... Foliate is too harsh when it comes to unambigious cfis. (like something is written incorrectly but fixable)
