### ISSUE TITLE
how to port themes from 2.0 to 3.0

### ISSUE THREAD

**Issue by gituser23234235234887** [johnfactotum/foliate#1428]
**Question:**
Hello I am moving from 2.6.4 ppa to flatpak 3.1.1 and want to know how to move my themes over.

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: ubuntu
 - Installation method: flatpak

**Comment by johnfactotum** [comment]
See the instructions for v2: https://github.com/johnfactotum/foliate/blob/master/faq.md#how-to-use-custom-themes, and v3: https://github.com/johnfactotum/foliate/blob/gtk4/docs/faq.md#how-to-use-custom-themes
