### ISSUE TITLE
How do I change the settings?

### ISSUE THREAD

**Issue by e00E** [johnfactotum/foliate#1435]
Looking through other issues, it seems that Foliate has application wide settings. For example, you can choose whether page turns should be animated. I cannot find a way to change these settings. I've tried clicking everywhere in the UI but could not locate the usual settings menu.

I use Foliate on Arch Linux via the foliate package. My desktop environment is Sway (Wayland).

**Comment by johnfactotum** [comment]
Although the settings are global, currently you can only change settings when a book is opened.

When viewing a book, either use the shortcut <kbd>Alt</kbd><kbd>,</kbd>, or hover or tap on the header area, which will reveal the headerbar, on which there is a "three dots" button, clicking on which will show a menu, where you can change settings such as dark mode, and where you will find "Font & Layout Settings".

**Comment by e00E** [comment]
Thanks! That worked. The problem for me here was that I did not guess that I needed to hover/tap the mouse near the top of the application. There is no way to find this beside guessing because this UI part is invisible until you find it.

**Comment by different-name** [comment]
> where you can change settings such as dark mode

I see where to change theme, but not where to toggle dark mode - from my understanding each theme has a dark and light variant, but I am stuck on the light currently
![image](https://github.com/user-attachments/assets/de36a796-c403-440f-8f5d-eb804261cf05)

**Comment by different-name** [comment]
Ah, there is a menu button that was hidden by the white page and my gtk theme clashing

**Comment by different-name** [comment]
However, when using the dark mode, the gtk theme I'm using gets overridden making the rest of the app a different theme :sob:

**Comment by t-c-acc** [comment]
This is very hidden (I think). I was trying to disable animation, and did it with dconf-editor because I could not find the settings. Maybe consider putting them on the three-lines menu on the left side? Also, since they include animation, maybe consider changing the name? It's not only "Font" and "Layout".
