### ISSUE TITLE
Any book opened just shows a blank page, contents don't load with "TypeError: location is undefined" error

### ISSUE THREAD

**Issue by ell1e** [johnfactotum/foliate#1438]
**Describe the bug**
Any book opened just shows a blank page, the contents don't seem to ever load:

![Screenshot_20241126_172522](https://github.com/user-attachments/assets/22547266-e0a3-4ac0-82e3-c52c080d3524)

**To Reproduce**
1. Install foliate from flathub: `flatpak install flathub com.github.johnfactotum.Foliate`
2. Open any e-book with foliate

**Expected behavior**
E-Book opens up fully, page contents show up. This doesn't seem to be the case, the content area remains blank. The close button for the entire window seems to be missing as well.

**Screenshots**
See above

**Version:**
 - Foliate version: 3.1.1 from Flathub
 - OS/Distribution and version: postmarketOS
 - Desktop environment: KDE Plasma 6 (Wayland)
 - Installation method: flathub

**Additional context**

**Comment by johnfactotum** [comment]
Have you tried https://github.com/johnfactotum/foliate/blob/gtk4/docs/troubleshooting.md#it-cant-open-books-it-hangscrashesshows-a-blank-page?

**Comment by ell1e** [comment]
I noticed it outputs an error when launching it via terminal:
```
$ flatpak run com.github.johnfactotum.Foliate

(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-WARNING **: 05:22:27.947: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Tracker was not provided by any .service files
getURIFromTracker@resource:///com/github/johnfactotum/Foliate/library.js:83:60
get@resource:///com/github/johnfactotum/Foliate/library.js:121:42
getBookFromIdentifier@resource:///com/github/johnfactotum/Foliate/library.js:169:36
getBook@resource:///com/github/johnfactotum/Foliate/library.js:166:21
activate@resource:///com/github/johnfactotum/Foliate/library.js:860:63
activate@resource:///com/github/johnfactotum/Foliate/library.js:386:18
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.johnfactotum.Foliate:2): Gjs-CRITICAL **: 05:22:32.688: JS ERROR: TypeError: this[#data] is undefined
vfunc_unroot@resource:///com/github/johnfactotum/Foliate/book-viewer.js:995:9
showLibrary@resource:///com/github/johnfactotum/Foliate/app.js:174:25
addMethods/</<@resource:///com/github/johnfactotum/Foliate/utils.js:281:58
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-CRITICAL **: 05:22:50.249: TypeError: location is undefined
update@resource:///com/github/johnfactotum/Foliate/annotations.js:156:25
updateBookmarks@resource:///com/github/johnfactotum/Foliate/book-viewer.js:774:37
#onBookReady@resource:///com/github/johnfactotum/Foliate/book-viewer.js:781:13
async*book-ready@resource:///com/github/johnfactotum/Foliate/book-viewer.js:468:54
@resource:///com/github/johnfactotum/Foliate/book-viewer.js:223:23
registerHandler/<@resource:///com/github/johnfactotum/Foliate/webview.js:176:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by johnfactotum** [comment]
Does the table of contents work? If so it's probably because you've previously opened a different book with the same unique identifier and now it's trying to restore the last location but fails.

**Comment by ell1e** [comment]
This happens no matter which book I open, I have dozens to try. The table of contents does show up, see above screenshot, but clicking any entry doesn't result in a visible change.

**Comment by johnfactotum** [comment]
Well, it's possible for dozens of books to have the same unique identifier.

Even if that is not the issue, it seems unlikely that all books fail to open with that error. It's most likely either the kind of issue that I've described, or it would be some other bug specific to the books.

The situation where truly all books fail to load would most likely be an issue with the WebView itself. If OPDS works, though, then it would almost certainly not be a WebView issue.

**Comment by ell1e** [comment]
Is this identifier something inside the epub files, like the ISBN? They are from different publishers so I'm not sure why they would share any identifiers.

Here's the additional error messages that come up when I click any table of contents entry:
```
~ $ flatpak run com.github.johnfactotum.Foliate

(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-CRITICAL **: 05:58:13.051: TypeError: location is undefined
update@resource:///com/github/johnfactotum/Foliate/annotations.js:156:25
updateBookmarks@resource:///com/github/johnfactotum/Foliate/book-viewer.js:774:37
#onBookReady@resource:///com/github/johnfactotum/Foliate/book-viewer.js:781:13
async*book-ready@resource:///com/github/johnfactotum/Foliate/book-viewer.js:468:54
@resource:///com/github/johnfactotum/Foliate/book-viewer.js:223:23
registerHandler/<@resource:///com/github/johnfactotum/Foliate/webview.js:176:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
foliate:///reader/reader.js:424:29: CONSOLE JS ERROR TypeError: undefined is not an object (evaluating 'heads.at(-1).innerText = tocItem?.label ?? ''')
foliate:///reader/reader.js:424:29: CONSOLE JS ERROR TypeError: undefined is not an object (evaluating 'heads.at(-1).innerText = tocItem?.label ?? ''')
foliate:///reader/reader.js:424:29: CONSOLE JS ERROR TypeError: undefined is not an object (evaluating 'heads.at(-1).innerText = tocItem?.label ?? ''')
foliate:///reader/reader.js:424:29: CONSOLE JS ERROR TypeError: undefined is not an object (evaluating 'heads.at(-1).innerText = tocItem?.label ?? ''')
foliate:///reader/reader.js:424:29: CONSOLE JS ERROR TypeError: undefined is not an object (evaluating 'heads.at(-1).innerText = tocItem?.label ?? ''')
foliate:///reader/reader.js:424:29: CONSOLE JS ERROR TypeError: undefined is not an object (evaluating 'heads.at(-1).innerText = tocItem?.label ?? ''')
foliate:///reader/reader.js:424:29: CONSOLE JS ERROR TypeError: undefined is not an object (evaluating 'heads.at(-1).innerText = tocItem?.label ?? ''')
foliate:///reader/reader.js:424:29: CONSOLE JS ERROR TypeError: undefined is not an object (evaluating 'heads.at(-1).innerText = tocItem?.label ?? ''')
```
The chapters in the table of contents look correct, so I'm assuming that means it has full filesystem access to the underlying book file or else I wouldn't know how it could possibly list the chapters.

**Comment by johnfactotum** [comment]
Some conversion tools would always output the same identifier, or have some other quirks. Anyway, you could check the identifier by clicking on the "About This Book" button (the one next to the title and author of the book on the sidebar, or Ctrl+I).

It could also be some other issue with the books themselves. You can perhaps try opening them in https://johnfactotum.github.io/foliate-js/reader.html. If that doesn't work, that would mean that there's some issue with rendering the books themselves.

**Comment by ell1e** [comment]
1. I tried multiple in https://johnfactotum.github.io/foliate-js/reader.html and all of them work fine.

2. I collected some "Identifiers" of books I tried: Twilight by Stephenie Meyer, 2d985536-9857-4e8c-8d00-c4cf50f4e639. Shatter Me by Tahereh Mafi, 9781780318684. Carve the Mark by Veronica Roth, 9d69a1d6-22ca-459b-bfda-5a9545890e24. It doesn't really look to me like the identifiers look suspiciously similar, but perhaps I'm checking the wrong field.

I hope some of that information is useful. Let me know if there's something else that might be worth poking.

**Comment by johnfactotum** [comment]
Well, you could try removing everything in `~/.var/app/com.github.johnfactotum.Foliate/data/com.github.johnfactotum.Foliate`. This will clear all reading data, including annotations and bookmarks. This should rule out the case where it's using data from another book.

The you might try opening books from [Standard Ebooks](https://standardebooks.org/) or [Project Gutenberg](https://www.gutenberg.org/). This would rule out that it's an issue specific to the books you have.

**Comment by ell1e** [comment]
I deleted `~/.var/app/com.github.johnfactotum.Foliate/data/com.github.johnfactotum.Foliate` and then verified this worked by launching Foliate without clicking on a book (just standalone), and it didn't list my previously opened books anymore. So it seems like the data wipe may have been applied. However, when opening any book, the content area remains blank as before.

Then I tested https://standardebooks.org/ebooks/georgette-heyer/these-old-shades/download?format=epub and the content area remains blank as with the others. In the terminal, I see the same error `(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-CRITICAL **: 06:39:57.077: TypeError: location is undefined` as before.

**Comment by ofaws** [comment]
I have the same issue like the author - no matter what book I try to open I get this error:
![image](https://github.com/user-attachments/assets/cd6bdb52-1104-414b-a707-e8e1d0d0e748)

System: Ubuntu Core 22
Desktop: ubuntu:GNOME
Session: ubuntu (x11)
Language: ru_UA.UTF-8

Versions:
- Foliate 3.2.0
- GJS 1.76.02
- GTK 4.12.3
- Adwaita 1.4.0
- GLib 2.78.1
- WebKitGTK 2.42.0

User directories:
- /home/olga/snap/foliate/1935/.local/share
- /home/olga/snap/foliate/common/.cache


Other readers open the books well. The issue appeared yesterday, after the update was installed by snap.
I have already tried to reinstall teh app - but no luck, the issue is still there.

It is sad that Foliate is no longer working, I liked it the most among all ebooks readers

**Comment by johnfactotum** [comment]
@ofaws That looks like a completely different issue. It's probably because the WebKitGTK packaged for the Snap is too old. I will roll back the Snap package for now.

**Comment by johnfactotum** [comment]
@ell1e I must say I'm a bit at a loss. Does the "Next" button work? The last button on the navbar (which shows on tap or hover on the bottom of the book area). If it does work, then the issue must be that it's still loading incorrect last location data from somewhere, though I'm not sure how. If that doesn't work, it would be an even more mysterious issue...

**Comment by ell1e** [comment]
When I click next nothing happens, the long progress slider doesn't move either:

![Screenshot_20241128_150602](https://github.com/user-attachments/assets/5dde4c01-5e66-4861-a66a-3e171ef9be5d)

The zoom buttons seem to be confused as well:

![Screenshot_20241128_150610](https://github.com/user-attachments/assets/92102c2e-b5e8-437f-a48f-73eb4966f4b6)

**Comment by johnfactotum** [comment]
Huh. The zoom level is displayed as "NaN%", but I believe the number comes straight from the WebView's `zoom-level` property (it's formatted correctly with "%" so that means the property itself is likely `null` or `undefined`). So I suppose this is an issue of the WebView after all and probably <i>not our bug</i>. But do other WebKitGTK WebViews work for you? For example the online OPDS catalogs in Foliate. Or do other apps like Epiphany (GNOME Web) work?

**Comment by ell1e** [comment]
I just installed and tested Epiphany Gnome Web, and it worked fine. But I'm using Foliate inside flatpak, so the GTK webview in there might be a slightly different version. But there doesn't seem to be some general issue with running a GTK webview on this system.

**Comment by ofaws** [comment]
> @ofaws That looks like a completely different issue. It's probably because the WebKitGTK packaged for the Snap is too old. I will roll back the Snap package for now.

Thanks for the quick action! App started to work well again after the update =)

**Comment by johnfactotum** [comment]
It's certainly a strange issue. Maybe try
- Checking whether OPDS catalogs are working. You can do this by clicking on the catalogs on the sidebar of the library view.
- In the book view, use the inspector, if it works, (F12; or from the view menu) and poke around, see what sort of state things are in. One can use the console and inspect the `reader` object, or run things like `await (await fetch(await reader.book.sections[0].load())).text()`, which will fetch the first section, or `await reader.view.goTo(0)`, etc.

**Comment by ell1e** [comment]
The update to 3.2.0 that shipped on Flathub seems to have fixed this problem.
