### ISSUE TITLE
Foliate freezes when I highlight inside an existing highlight

### ISSUE THREAD

**Issue by ConEstArthur** [johnfactotum/foliate#1441]
**Describe the bug**
When you select text to highlight for the first time, it works absolutely fine. 
But if I try to select text inside this highlight and try to highlight it as well (while highlighting context menu still open or not probably) and click multiple times on the side to remove that menu. 
I cannot do it. The entire app freezes.
and it keeps getting worse.

**Expected behavior**
Should be able to to highlight without it freezing. I think context menu might be the culprit here.

**Screenshots**

https://github.com/user-attachments/assets/294c0663-f7f3-410d-bfaa-85c34147bb1a

**Version:**
 - Foliate version: 3.2
 - OS/Distribution and version: Fedora  41
 - Desktop environment: Gnome 47
 - Installation method: Flatpak

**Additional context**
For example I highlight with 'aqua' color. (at this point I'm using mouse only) and next time when trying to highlight with different color, I cannot remove the menu by clicking on the side.
Only Esc key works.

**Logs**
[logs.txt](https://github.com/user-attachments/files/17964047/logs.txt)

**Comment by ConEstArthur** [comment]
@johnfactotum Hey John
Thanks for such a prompt fix..

Can you also take a look at highlight menu not closing by clicking away when you change the color of an exisiting highlight? (Or even new)

Happens only when you change highlight color.

Here's the video demonstration -

https://github.com/user-attachments/assets/a0523351-9712-48a4-934e-9452bcaff4de

**Comment by johnfactotum** [comment]
That's a GTK bug: https://gitlab.gnome.org/GNOME/gtk/-/issues/5568. See #1270.
