### ISSUE TITLE
Foliate 1.5.2: TOC navigation is still not working with a book I'm reading

### ISSUE THREAD

**Issue by aasril** [johnfactotum/foliate#147]
The issue exists since the previous releases. But since it's mentioned on the Release Notes that v1.5.2 fixed the issue on some books, I would like to mention that the issue is still happened on this particular epub file I'm reading.

The TOC navigation works on this book with Calibre ebook viewer and on Android with Moon+ Reader.

I'm on Ubuntu 18.04 Gnome and Foliate is installed through flatpak.

**Comment by johnfactotum** [comment]
By not working, do you mean that when you click on a TOC item, it doesn't go to that location? And prints some error message about "section not found"?

If so, can go to https://futurepress.github.io/epub.js/examples/input.html, input your file, and then open the browser's developer tools and run
```javascript
[book.packaging.navPath, book.packaging.ncxPath, book.navigation.toc[0].href, book.spine.spineItems[0].href]
```
and post the output?

**Comment by aasril** [comment]
There is no error message printed. After clicking on the TOC menu, the menu will disappear but then the book stays in the current position.

I don't know how to use that page. there is no button or menu where I can upload the file. And when I drop the file from file manager, the browsers (firefox and chrome) download the file instead.

**Comment by johnfactotum** [comment]
On the top of that page there should be a button that you can click to choose file. Try increasing the height of your browser window if you don't see the button.

**Comment by aasril** [comment]
Ah yes, my laptop has 1360x768 screen. I need to zoom out first.

Here's the output of the command.
https://gist.github.com/aasril/ec9989b7c0b38efd70223ab4c1c78f30

**Comment by johnfactotum** [comment]
That's weird. What happens if you run this:
```javascript
rendition.display("introduction01.html#how_to_use_this_book_intro")
```

**Comment by aasril** [comment]
![On Firefox](https://user-images.githubusercontent.com/37625377/61704023-0517d800-ad6d-11e9-8def-8280feba2665.png)

![On Chrome](https://user-images.githubusercontent.com/37625377/61704214-693a9c00-ad6d-11e9-80df-9acbc217a170.png)

**Comment by johnfactotum** [comment]
And does it navigates to the introduction after running that? If so then it's kind of mysterious. Well, if not, then it's still mysterious but at least we'd know that it's an upstream problem.

**Comment by aasril** [comment]
I realized that I missed a detail that I should have mentioned in the original post. Navigating through TOC by clicking on chapters works but not on sub-chapters on Foliate. Though, it does work on the other two epub readers I mentioned (I rechecked it).

To answer your question, yes it moves to the introduction after running the command.

**Comment by aasril** [comment]
Just in case this is being useful. Most of the text on the book, is rendered red instead of black.

**Comment by johnfactotum** [comment]
You can run `book.navigation.toc` and check the sub-chapters' href, and see if there's anything wrong with it or if works with `rendition.display()`. Perhaps it'd help if you post the whole output of `book.navigation.toc`, too.

Does the red text only happen in Foliate or is it an Epub.js problem?

**Comment by aasril** [comment]
The red text happens both in Foliate and Epub.js. For comparison, also a view of Calibre's reader.

![foliate-epubjs-calibre](https://user-images.githubusercontent.com/37625377/61759974-338cc600-adf4-11e9-8b8f-bb15cf110081.png)

The navigation does work with `rendition.display()`. 

The output of book.navigation.toc.
[futurepress.github.io-1563935295874.log](https://github.com/johnfactotum/foliate/files/3424767/futurepress.github.io-1563935295874.log)

**Comment by johnfactotum** [comment]
Just to clarify, you're saying that
- In Foliate's TOC popover, clicking on, say, "how to use this book: Intro" works, but clicking on "We know what your brain is thinking" does nothing.
- But in Epub.js, running
  ```javascript
  rendition.display("introduction01.html#we_know_what_your_brain_is_thinking")
  ```
  _does_ work.

Is that correct?

Well, I can't really think of a reason why it doesn't work. Can you test this with a WebKitGTK based browser like Epiphany (GNOME Web), or other WebKit browsers like Safari? Perhaps it's yet another Epub.js problem specific to WebKit.

**Comment by aasril** [comment]
Yes, both are correct.

`rendition.display()` also works on epiphany with sections (sub-chapters).

![epiphany](https://user-images.githubusercontent.com/37625377/61763670-63da6180-ae00-11e9-84c0-396e53aa2174.png)

Anyway, thanks for making Foliate that make reading ebooks much more joyous and your great responses.

**Comment by johnfactotum** [comment]
You can apply this patch to enable WebKit's developer tool in Foliate:
```diff
diff --git a/src/main.js b/src/main.js
index 479182b..9e72a37 100644
--- a/src/main.js
+++ b/src/main.js
@@ -1873,10 +1873,11 @@ class BookViewerWindow {
 
         this.webViewSettings = new Webkit.Settings({
             enable_write_console_messages_to_stdout: true,
-            allow_file_access_from_file_urls: true
+            allow_file_access_from_file_urls: true,
+            enable_developer_extras: true
         })
         this.webView = new Webkit.WebView({ settings: this.webViewSettings })
-        this.webView.connect('context-menu', () => true)
+        //this.webView.connect('context-menu', () => true)
 
         const viewer = settings.get_boolean('disable-csp')
             ? '/assets/viewer-nocsp.html' : '/assets/viewer.html'
```

**Comment by aasril** [comment]
I built Foliate with the patch and ran the developer tool successfully. Though, interestingly it's hard to work on the console because `j, k, n, p` keys (what I've found so far) are bound for scrolling and navigating to the next chapter.

**Comment by hp600** [comment]
I'm using version 1.5.3, and I'm experiencing the behavior aasril describes, but only when scrolled mode is turned on.

I can jump to to chapters, but clicking sub-chapters does nothing.

**Comment by hp600** [comment]
I just noticed that some of my epub files work fine!
I can jump to subsections on them while on scrolled mode, but others I have to keep the layout mode on single or auto.

**Comment by johnfactotum** [comment]
@hp600 That is actually a known issue:

In Epub.js, scrolling to within a chapter in scrolled-doc or continuous scrolled mode seems to only work when the book is rendered to the body element, but paginated mode only works when rendered to a div.

Currently, the scrolled mode is rendered to a div, so sub-chapter navigation doesn't work. In continuous scrolling mode on master, sub-chapter navigation does work.

@aasril Does the problem only occur in scrolled mode for you?

**Comment by hp600** [comment]
Yes, only in scrolled mode.

**Comment by johnfactotum** [comment]
Not being able to navigate to anchors within a chapter in scrolled mode is fixed in master.
