### ISSUE TITLE
Option to use epub font

### ISSUE THREAD

**Issue by HaasJona** [johnfactotum/foliate#15]
I have an epub with embedded fonts. Opening it in Foliate results in a weird mishmash between the user-chosen font (for standard paragraphs) and other elements that override this font.

Foliate should either display everything in the override font and if that's not sufficient also allow to use the publisher font.

**Comment by johnfactotum** [comment]
I'm not entirely satisfied with the UI, but the option is there now. I've also added the universal selector to force the custom font (with the exception of `<code>` and `<pre>`).

Feel free to open a new issue if you have further problems.
