### ISSUE TITLE
conjugations on offline dictionaries

### ISSUE THREAD

**Issue by hacktivista** [johnfactotum/foliate#156]
A lot of times offline dictionaries don't come with conjugations for words. It would be nice to change the word or matching strategy while using offline dictionaries, like manually deleting the conjugation part of the word and matching by prefix.

Are you interested in a PR for such feature? Would you prefer it enabled only for offline dicts or all of them?

**Comment by johnfactotum** [comment]
I don't think "manually deleting the conjugation part of the word" is a good idea, if by that you mean including all morphological rules of all known languages into Foliate's code.

A better solution would be to make use of suggestions ("No definitions found for ..., perhaps you mean: ..."), which are currently ignored. If a dictionary does not support conjugations or suggestions then it is really the dictionary's issue.

**Comment by hacktivista** [comment]
I don't mean including morphological rules, I mean really edit the word by deleting some characters in a textbox, and an option to change the matching strategy. Saying that an offline dictionary *must* have all possible conjugations for every word is not a serious take on the problem, since not all dictionaries are made with the same purposes and much of them have been done over the years with a lot of work and no funding, some simply have no interest in including conjugations since you can always "look for the verb".

Having this feature would save a lot of time for users which today need to leave the program to do the same thing.

**Comment by johnfactotum** [comment]
Ohh, you mean let the user edit the query and matching method. That would be good, I think.

I'm not familiar with the protocol, but if you ask dictd to define a word and there's no match, it would often give suggestions. I think it prints to stderr and is currently ignored. Parsing that output and give the user the ability to choose from the suggestions would be nice, if possible.

**Comment by johnfactotum** [comment]
The master branch now has a entry for editing the query:
![image](https://user-images.githubusercontent.com/50942278/68116019-b93f0800-fef1-11e9-9eb2-727da0afb287.png)
