### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#158]
@johnfactotum How do you feel about opening a permanent bug/issue that will contain speculative discussions?, so that if anyone (think gnomers) wants to contact @johnfactotum , they would just comment there. This could speed progress and adoption. The issue can be marked with the 'need info', 'question' or 'help wanted' tags.

**Comment by johnfactotum** [comment]
I'm not quite sure what you mean. People can already freely open question, discussion, or any other kinds of issues. What would be the advantage of having one permanent issue to contain them?

**Comment by itprojects** [comment]
Making such an issue would make it easier for the fans/testers/other to talk on topics, without starting a dozen bugs-that-are-not-bugs, just like people use forums for the development of ideas.

In essence a discussion-bug is a convenient and affordable replacement of a forum.

Q: Why should you @johnfactotum be the one to open this issue?
A: Because you are the chief of this project and it makes sense.

**Comment by johnfactotum** [comment]
What's wrong with "starting a dozen bugs-that-are-not-bugs"? Nothing says that issues need to be related to "bugs" or anything. And I think I would prefer having a new thread for each topic, which is much easier to read and manage than having everything in a single issue.

Some projects have strict rules when it comes to their issue tracker. Well, not this one. If anyone has anything to say, feel free to just use Github issues as a forum.

**Comment by johnfactotum** [comment]
I've enabled Github Discussions. So future discussions can now take place there: https://github.com/johnfactotum/foliate/discussions
