### ISSUE TITLE
Automatic Commit Builds

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#159]
Some gnome projects on gitlab have recipies that automatically make app packages.
Is this possible with github? Or is this a premium feature?

**Comment by johnfactotum** [comment]
Gitlab has [built-in CI](https://docs.gitlab.com/ee/ci/). On Github I think it's common to use [Travis CI](https://travis-ci.org).

**Comment by geek1011** [comment]
There's also GitHub Actions, which is in beta. My favourite is Drone CI (it starts faster than Travis, and is quite a bit more flexible and up-to-date).

**Comment by itprojects** [comment]
The idea is to make it easier to build packages for releases, so that @johnfactotum makes the code and tags the release commit.  Github makes deb, rpm, and the flatpak, snap.

@geek1011 Do you know how to setup deb or flatpak Github Actions?

**Comment by geek1011** [comment]
GitHub Actions is still in beta, but you can run any command with it, so whatever @johnfactotum usually runs to make the packages. Same for Drone.

**Comment by itprojects** [comment]
In practice, this project runs well enough, therefore closing.
