### ISSUE TITLE
Join spread

### ISSUE THREAD

**Issue by olivierberten** [johnfactotum/foliate#161]
When using 2 pages view, both pages are left aligned while one would expect them to be joined in the middle, like epub.js does it. This is especially annoying for fixed layout epub with images across the spread.

**Comment by johnfactotum** [comment]
Well, Epub.js renders fixed layout EPUBs like that by default, and I'm not sure how to fix it. As a workaround you can try resizing the window or adjusting the margins.

**Comment by johnfactotum** [comment]
This has been fixed in Epub.js 0.3.86.

**Comment by johnfactotum** [comment]
Reopening as the spread is not joined when there aren't `page-spread-*` properties

**Comment by johnfactotum** [comment]
Fixed in the new renderer (https://github.com/johnfactotum/foliate/issues/962).
