### ISSUE TITLE
[Feature Request] Vertical screen support

### ISSUE THREAD

**Issue by ajdintrejic** [johnfactotum/foliate#165]
Could you add an option in preferences to disable the "2 page layout"? When I open a book on a vertical screen it is divided and makes it hard to read as the columns are too narrow.

**Comment by johnfactotum** [comment]
There is one. Choose the "Single" layout, and it will only show one column. The default "Auto" layout will show only one column when the width is less than 800px.

**Comment by ajdintrejic** [comment]
I have no idea how have I missed that. Thanks.
