### ISSUE TITLE
Continuous scrolled content flashes

### ISSUE THREAD

**Issue by wnabil** [johnfactotum/foliate#167]
The content flashes randomly when trying to scroll to the top or the bottom in an epub file.
Also sometimes the page turns white until you move the scroll bar a little bit or it keeps flashing too much and never fixed until you reinitialize the application.
![70238930_405826060075875_1020173080623841280_n](https://user-images.githubusercontent.com/23165327/64782543-b7963b00-d565-11e9-8479-898e4c03b58a.png)

**Comment by damiencal** [comment]
@johnfactotum We haven't yet found a solution for the above issue.. We are willing to pay for a fix.
If interested please PM me at damien@ikointl.com

Thanks

**Comment by johnfactotum** [comment]
Closing as obsolete, as the new renderer (#962) doesn't support continuous scrolling anymore.
