### ISSUE TITLE
[Feature Request] Export annotation to markdown 

### ISSUE THREAD

**Issue by snpefk** [johnfactotum/foliate#180]
It would be nice if Foliate support annotation export in markdown format. E.g. something like: 

```markdown
# Annotations for **A Tour of C++ (C++ In-Depth Series)** by Bjarne Stroustrup

11 Annotations

---

epubcfi(/6/16[id480]!/4/2/18,/1:28,/1:186); **Aqua**
> For a program to run, its source text has to be processed by a compiler, producing object files, which are combined by a linker yielding an executable program

---

…

```

I can't came up with solution how to properly show color of annotation beside put it with annotation info. 

UPD. Add more info.

**Comment by itprojects** [comment]
Why no description?

**Comment by snpefk** [comment]
Or it's possible to use HTML injects to color text
