### ISSUE TITLE
[Feature Request] Follow in-document links directly

### ISSUE THREAD

**Issue by woky** [johnfactotum/foliate#184]
When you click on a link to another location in the document (e.g. some e-books have table of contents in chapters), Foliate presents you with a window with the link text and button for navigating to the link location at the bottom. The text in the window is usually (always?) the same as the rendered link text. The window seems to have fixed or minimum height and navigation button is too far away.

Please, make Foliate follow these kinds of links directly.

Nice piece of software, thanks!

**Comment by johnfactotum** [comment]
You can disable "Display non-EPUB-3 footnotes in a popover" in preferences.

It's enabled by default after ad8d25a2ebb4393cd7879a92045a2cdc0b4d1b40. I guess we should probably consider disabling it default, as it could be a bit confusing. And perhaps clarify what the option does in preferences a bit.
