### ISSUE TITLE
Toolbar buttons stay focused after clicking away

### ISSUE THREAD

**Issue by woky** [johnfactotum/foliate#185]
When you interact with dialog windows opened by toolbar buttons (i.e. text properties `>a<`, search, or settings menu) and then close it by clicking away into document, the focus is still on the toolbar button. User needs to click into document area once more to give it focus so that it can be navigated by keyboard (e.g. arrows).

This can be actually very confusing for users. When I was trying Foliate for the first time, I thought it just cannot navigate document by keyboard, because initially I was playing with settings and then focus stayed on a toolbar button.

**Comment by johnfactotum** [comment]
One thing to consider is that this behavior of popovers is consistent across all GTK applications. But I agree that it can be very confusing.

**Comment by johnfactotum** [comment]
I will close this for now, because this is just how buttons and popovers currently work in GTK. The shortcuts N and P will work even when the document area is not focused (same as Evince).
