### ISSUE TITLE
[Feature Request] Show content windows/menus below cursor

### ISSUE THREAD

**Issue by woky** [johnfactotum/foliate#186]
Foliate lets you zoom pictures in a document by clicking on it and displaying actions menu. But this menu is displayed at the bottom center of the image. Annotation window is also displayed at the bottom center of a link. It'd be much more ergonomic to just display these windows/menus below cursor.

I realize this is not that easy as it requires detecting if the window/menu can fit viewport.  I.e. if a link/image is at the bottom right of the viewport, then the window/menu should be displayed above and to the left.

**Comment by johnfactotum** [comment]
This point has came up before in #9:

> The main point of the current behavior, I suppose, is that the popover would not obstruct the text. The travel distance isn't that much, in my opinion.

> I think if the popover is triggered by selection, it should try its best not to obstruct the selection. If it's triggered by right click, like a context menu, then I agree, it should follow the cursor.
