### ISSUE TITLE
Foliate is beautiful

### ISSUE THREAD

**Issue by jleclanche** [johnfactotum/foliate#189]
Sorry for filing this as an issue but I just wanted to say, foliate is a fantastic piece of software. A really beautiful and simple ebook reader. I kinda wish there was a Qt port as currently there's no good Qt ebook reader but even so, integrates really well into KDE.

**Comment by jleclanche** [comment]
PS: I've added it to [community] in Arch Linux.

**Comment by johnfactotum** [comment]
Thanks for the kind words! No need to apologize for filing this as an issue, as discussions are allowed per #158.

I'm currently attempting a rewrite based on GtkBuilder UI definitions, which should make it much easier to build alternative UIs for people who don't use GNOME and want traditional menubars.
