### ISSUE TITLE
Settings Not Saved

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#190]
After the redesign, when installing with meson build Foliate does not save settings, (https://github.com/johnfactotum/foliate/commit/f76559f00e2ce14a1406d24255799ba0b4311b17) .

The installed gschema has no real settings in it.

Also causes the endless spinning wheel , when a book cannot be found.

**Comment by johnfactotum** [comment]
As mentioned in the readme, the master branch contains a _work-in-progress_. The project is being completely rewritten, although some small parts are re-used. The master branch is in a state of flux and the design may change at any time. It's also very far from complete. Tons of things are still not implemented or are buggy,

**Comment by itprojects** [comment]
@johnfactotum Yes, it's true that the master branch is work-in-progress. The missing ability for settings to persist is a massive problem, for anyone that wants to help test! Which means a needlessly increased workload for one particular inventor-and-tester of Foliate. Know anyone?

**Comment by johnfactotum** [comment]
The endless spinning wheel is not related to gschema. It's because it does not implement g_application_open() and has no handlers connected to the 'open' signal. For now you can click "Open..." in the menu or use Ctrl+O to open a file for testing purposes.
