### ISSUE TITLE
Text is rendered differently in dictionary lookup

### ISSUE THREAD

**Issue by shastry** [johnfactotum/foliate#191]
Text in dictionary lookups are blurry.
They don't seem to follow font the user's hinting/antialiasing settings.

Not sure if it matters, but I'm using dictd on localhost.

Example: ![Screenshot from 2019-10-13 09-26-40](https://user-images.githubusercontent.com/704140/66710784-9ca12b80-ed9c-11e9-9b46-2dbe0d4c8518.png)

**Comment by johnfactotum** [comment]
It's just normal GTK labels and buttons. It follows whatever settings you have for GTK.

**Comment by johnfactotum** [comment]
I'm pretty sure the dictionary popover is not being rendered differently. Please feel free to re-open if you have further information/questions.
