### ISSUE TITLE
[Feature Request] - auto margins in single-page mode

### ISSUE THREAD

**Issue by nphyx** [johnfactotum/foliate#192]
It would be nice to be able to set a desired content width in single-page mode instead of setting margin widths. For example, "Content width: 7 inches". I don't really care how wide the margins are - I care how wide the content is. 

Also, with fixed margin sizes the trouble is every time you resize the window you have to re-adjust the margins to get the desired column width.

Thanks for your work on this - I've been waiting for a good linux-native/GTK epub reader for ages.

Are you open to PRs? I didn't see any contributing notes/guidelines. Also, do you have a Paypal/etc for donations? I'd love to buy you a coffee/beer.

**Comment by johnfactotum** [comment]
I think it would make sense to add a max-width preference.

I do accept PRs, but currently I'm rewriting the entire project and the master branch is highly incomplete/unstable, so it might not be very convenient.

**Comment by nphyx** [comment]
Yeah I figured I'd wait for the rewrite to finish before trying to tackle that, but if I have time and I want it bad enough I'll circle back :)
