### ISSUE TITLE
Can't read epub with missing BookId

### ISSUE THREAD

**Issue by EmmanuelP** [johnfactotum/foliate#194]
I had an epub with an empty BookId I was not able to read using Foliate. In content.opf, I had:

```
<dc:identifier id="bookid"/>
```

Checked using epubcheck, I got:

```
ERROR(RSC-005): /home/pacaud/Documents/Bibliothèque/Lyonel Trouillot/Ne m'appelle pas Capitaine (97)/Ne m'appelle pas Capitaine - Lyonel Trouillot.epub/OEBPS/content.opf(13,33): Erreur lors de l'analyse du fichier: l'élément "dc:identifier" contient des caractères non valides ; doit être une chaîne de caractères avec une longueur d'au moins 1 (la longueur trouvée est 0)
```

I've fixed the issue, using NCX identifier as BookId:

```
<dc:identifier id="bookid">9782330111694</dc:identifier>
```

And I'm now able to read the epub.

I think for such not conformance to the epub standard, Foliate should still be able to open and display the book. May be there is some parameter in epub.js that makes it ignore this sort of errors ?

Thanks for this excellent epub reader !

Cheers.

**Comment by johnfactotum** [comment]
Opening files without an identifier has been merged upstream: https://github.com/futurepress/epub.js/pull/968

Opening them is one thing, I'm not sure how to handle storage of annotations and cache, because those currently relies completely on the book having an unique identifier.
