### ISSUE TITLE
Work-In-Progress Testing

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#197]
@johnfactotum Some 2.x test results, to help development.

- Last-file not saved to Gschema
- Progressbar is missing notches
- Dictionary define does not show anything (online or offline)
- No custom themes, (Menu > Themes > nothing happens)
- No preference dialog, (Menu > Preference > nothing happens)
- No keyboard shortcuts, (Menu > Keyboard Shortcuts > nothing happens)
- TTS is not working and has no Gschema
- No export (notes) button, (place it just like bookmarks button (+))
- Missing ability to delete note (trash icon) without going to the place, where the note is, just like in bookmarks

**Comment by johnfactotum** [comment]
Thanks. Also "about this book" is not implemented yet.

**Comment by itprojects** [comment]
Additionally:

- Translate popup button > nothing happens

- Wikipedia popup button > nothing happens

**Comment by itprojects** [comment]
Commit `9ef30148` has added an overlay bar.

**Comment by itprojects** [comment]
Fixed:

- <s>Dictionary define does not show anything (online or offline)</s> `eefbc9`

- <s>No keyboard shortcuts, (Menu > Keyboard Shortcuts > nothing happens)</s> `194042`

- <s>Missing ability to delete note (trash icon) without going to the place, where the note is, just like in bookmarks</s> `d574ef`

**Comment by itprojects** [comment]
Fixed:

- <s>Also "about this book" is not implemented yet</s> `96cb37`

**Comment by itprojects** [comment]
Fixed:
- <s>No export (notes) button, (place it just like bookmarks button (+))</s>
- <s>Progressbar is missing notches</s>

**Comment by itprojects** [comment]
Fixed:

- TTS is not working and has no Gschema `3ea071`

This feature requires the TTS Gschema to be correctly set, but the preferences' dialog is not yet re-implemented, so the user has to use dconf to set it manually.

**Comment by itprojects** [comment]
Fixed:

- <s>Last-file not saved to Gschema</s>
- <s>No preference dialog, (Menu > Preference > nothing happens)</s>

**Comment by itprojects** [comment]
Fixed:

-<s>No custom themes, (Menu > Themes > nothing happens)</s>
