### ISSUE TITLE
Screen Burn-in mitigations

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#202]
When reading an ePub for an hour, the chapter and page information (below page text) is still visible (burned in). This happens on LCD screens, which are still very popular.

Can you provide a switch to hide those in full-screen?

**Comment by itprojects** [comment]
@johnfactotum , if it's a question of producing the patch and offering a merge request - no problem. Give the order.

**Comment by johnfactotum** [comment]
1. LCD screens are not susceptible to screen burn-ins.
2. The text is not fixed; it changes constantly as one goes through the book.
3. The user is ultimately responsible for preventing screen burn-ins. It's not possible for an application to make sure that every pixel is changed constantly.

**Comment by itprojects** [comment]
1. It may not exactly be called "screen burn-in", but chapter header and footer images do persist, when the chapter takes takes too much time. Technical or foreign literature, for example, can require multiple page re-reads.

2. True.

3. The application prevents "screen burn-in" in fullscreen mode, but the headers and footers cause problems. Left over images  can be seen on screen even if lock screen is enabled, just like a ghostly top gnome-panel, when not in fullscreen. 

There are two more things to consider here:

4. The header and footer can be very distracting to the reading process. (Called eye regressions?) The reader can lose their reading flow more easily. 

5. Consider the future of the app - small (phone) form factors dictate that people might want to maximize their screen space in fullscreen.

**Comment by johnfactotum** [comment]
I do plan on adding an option for hiding the bottom bar. But not for mitigating screen burn-in, which I don't think should be a concern.

**Comment by itprojects** [comment]
@johnfactotum Does the bottom bar include the current page and chapter between the page text and the progress bar?

**Comment by johnfactotum** [comment]
Yes.

**Comment by itprojects** [comment]
So the `this._footer` will have a property `visible: false,` as simple as that?

**Comment by johnfactotum** [comment]
No. The navbar should be put into an overlay so that it remain accessible.
