### ISSUE TITLE
Current reading location keeps moving back a few pages every time I exit from full screen mode

### ISSUE THREAD

**Issue by ghost** [johnfactotum/foliate#204]
First, thank you so much, I really like this reader.
I am having a minor issue: I am reading an ePub E-book in full screen mode, but when I switch back to regular window size, the current reading location moves back by two to three pages. It keeps doing that every time. Also when I re-open the ePub file, it does not remember exactly where I left off, it always starts off a few pages back.

Screenshot Of Full Screen Size:
![1  full-screen](https://user-images.githubusercontent.com/57586732/68691315-d3bd5500-0573-11ea-9d9c-beed37beb081.png)
Screenshot Of Regular Window Size:
![2  regular-window-size](https://user-images.githubusercontent.com/57586732/68691324-d91a9f80-0573-11ea-85c6-36320a6105dd.png)

E-book link:
http://www.gutenberg.org/ebooks/7319.epub.images?session_id=c170c51773d8178221a02e85c8b61c5e08384d20

System Information:
System:    Host: mint-Latitude-E4310 Kernel: 4.15.0-66-generic x86_64 bits: 64 compiler: gcc 
           v: 7.4.0 Desktop: Cinnamon 4.2.4 wm: muffin dm: LightDM Distro: Linux Mint 19.2 Tina 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Laptop System: Dell product: Latitude E4310 v: 0001 serial: <filter> Chassis: 
           type: 9 serial: <filter> 
           Mobo: Dell model: 0XG3JF v: A00 serial: <filter> BIOS: Dell v: A15 date: 05/12/2017 
Battery:   ID-1: BAT0 charge: 30.0 Wh condition: 41.1/62.2 Wh (66%) volts: 11.8/11.1 
           model: SMP DELL MY99305 serial: <filter> status: Discharging 
CPU:       Topology: Dual Core model: Intel Core i5 M 540 bits: 64 type: MT MCP arch: Nehalem 
           rev: 2 L2 cache: 3072 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 20214 
           Speed: 1324 MHz min/max: 1199/2534 MHz Core speeds (MHz): 1: 1314 2: 1254 3: 1335 
           4: 1211 
Graphics:  Device-1: Intel Core Processor Integrated Graphics vendor: Dell driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:0046 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel Ironlake Mobile v: 2.1 Mesa 19.0.8 direct render: Yes 
Audio:     Device-1: Intel 5 Series/3400 Series High Definition Audio vendor: Dell 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:3b57 
           Sound Server: ALSA v: k4.15.0-66-generic 
Network:   Device-1: Intel 82577LM Gigabit Network vendor: Dell driver: e1000e v: 3.2.6-k 
           port: 6040 bus ID: 00:19.0 chip ID: 8086:10ea 
           IF: eno1 state: down mac: <filter> 
           Device-2: Intel Centrino Advanced-N 6200 driver: iwlwifi v: kernel port: 6000 
           bus ID: 02:00.0 chip ID: 8086:422c 
           IF: wlp2s0 state: up mac: <filter> 
Drives:    Local Storage: total: 232.89 GiB used: 48.49 GiB (20.8%) 
           ID-1: /dev/sda vendor: Seagate model: ST9250410AS size: 232.89 GiB speed: 3.0 Gb/s 
           serial: <filter> 
RAID:      Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci v: 3.0 
           bus ID: 00:1f.2 chip ID: 8086.282a 
Partition: ID-1: / size: 228.23 GiB used: 24.25 GiB (10.6%) fs: ext4 dev: /dev/sda1 
           ID-2: swap-1 size: 2.00 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/dm-0 
Sensors:   System Temperatures: cpu: 55.0 C mobo: N/A sodimm: 44.0 C 
           Fan Speeds (RPM): cpu: 0 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com tina main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ bionic partner
Info:      Processes: 225 Uptime: 50m Memory: 3.72 GiB used: 1.43 GiB (38.4%) Init: systemd v: 237 
           runlevel: 5 Compilers: gcc: 7.4.0 alt: 7 Client: Unknown python3.6 client inxi: 3.0.32

**Comment by johnfactotum** [comment]
Hmm. The location moving back when exiting fullscreen is a bit weird. I'm not sure I can reproduce it consistently, but it does seem to happen sometimes.

The location moving back when re-opening is a different issue that has been fixed in master.

**Comment by johnfactotum** [comment]
When you exit fullscreen, you can see the correct location flashing for a split second. It seems for some reason, when exiting fullscreen or unmaximizing the window, the content is actually resized twice, and the final view contains not the original starting location, but the starting location _after_ the first resize. So this is really the same problem as #152.
