### ISSUE TITLE
Is there a way to manually hide the scoll bar on the right in "scrolled layout" mode?  

### ISSUE THREAD

**Issue by Gauler** [johnfactotum/foliate#205]
Scroll bar pops up on scrolling and hide itself after a while. Continuous appearance and disappearance of the bar can be distracting. 

I would like a keyboard shortcut to show my progress, but otherwise the scrollbar to be stay hidden. Is there a way to do it?

**Comment by johnfactotum** [comment]
Toggling the scrollbar is easy with the none-standard `::-webkit-scrollbar` selector, or probably some settings in WebKit, but I'm a bit unsure whether we should introduce this option. GTK's overlay scrollbar is meant to minimize distraction while still showing progress when you need it, and I think it works really well in that regard (unless you're using a retro theme with very thick scrollbars, in which case I agree it can distracting), and I'd rather just stick to the default behavior.

This would be something that should be implemented as a plugin, if we had/ever get a plugin system.

**Comment by digitalethics** [comment]
I actually prefer the opposite, i.e. when in _scrolled_ or _continuous_ mode to have an option to make the scrollbar always visible, preferably even thicker than it currently is. For literary (not scientific) works, however, I usually switch to the skeuomorphic mode with two columns. Regarding the issue at hand: how about implementing something alongside the terminology and options used with panels: always visible, autohide, hide?

**Comment by johnfactotum** [comment]
I think I'm going with _won't fix_ for this one. GTK's default behavior already balance pretty well the need to scroll and the need to minimize distraction.
