### ISSUE TITLE
Cannot retrieve translation.

### ISSUE THREAD

**Issue by joshcanto** [johnfactotum/foliate#206]
**NO TRANSLATION**

I have a issue with the translation service, i can't translate a book.

Foliate 1.5.3
elementaryOS 5.0

![Captura realizada el 2019-11-15 04 13 10](https://user-images.githubusercontent.com/37526901/68939670-6a4d6a00-075e-11ea-98a4-8dc2c100685d.jpeg)

**Comment by johnfactotum** [comment]
Translation is working for me. Possibly network issues? Or that Google Translate itself is temporarily unavailable?

**Comment by johnfactotum** [comment]
Closing for now as translation has been working for me. Feel free to reopen with more info if you are still having issues.

**Comment by ngocnha** [comment]
I discovered that install foliate form _**snap store**_ get this bug
Install form .deb file is ok
