### ISSUE TITLE
Need help using non-minified jszip.min.js

### ISSUE THREAD

**Issue by highvoltage** [johnfactotum/foliate#208]
Hi, I'm working on packaging foliate for Debian.

This means that I have to exclude jzsip.min..js and either compile it elsewhere or use it from an existing package. I notice that jszip is available via the nodejs-jszip package in debian under /usrshare/nodejs/jszip, is it possible for foliate to use that, if available?

Or if you have any other tips, that would be appreciated.

**Comment by johnfactotum** [comment]
How is nodejs-jszip is packaged on Debian? Foliate needs JSZip to run in the browser, not Node.js. To produce a build for the browser from the Node.js package, you need to have the [devDependencies](https://github.com/Stuk/jszip/blob/20db7b05a250b4747738d5029951dc7f14a0fcd6/package.json#L39) installed and run `grunt` to generate the files. See https://stuk.github.io/jszip/documentation/contributing.html#building-the-project.

There's a pre-built non-minified version here: https://github.com/Stuk/jszip/blob/v3.2.2/dist/jszip.js

**Comment by highvoltage** [comment]
Thanks, maybe I can do that to build a minified version of jszip at build time, will check it out, thanks.
