### ISSUE TITLE
Foliate freezes system on Ubuntu 19.10

### ISSUE THREAD

**Issue by Janghou** [johnfactotum/foliate#209]
After upgrade to 19.10 starting the Foliate flatpak app [freezes my system](https://askubuntu.com/questions/1191755/flathub-packages-are-freezing-system-after-upgrade-to-19-10).

Seems Mesa 19.2 doesn't play well with Mesa 18.08 in flatpak on AMD GPU machines.

[Bug report](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1852865). 

AFAICS Building against 19.08 should [fix](https://discussion.fedoraproject.org/t/some-flatpaks-kill-the-machine-on-f31sb-beta-testing/7673/4) it.

**Comment by johnfactotum** [comment]
Closing as it's not our bug and there's nothing to be done.

**Comment by Janghou** [comment]
I absolutely agree it's not Foliates bug. 

And I don't know how flatpaks are build, so forgive my ignorance, but a fix is suggested by building Foliate against Mesa 19 instead of 18.0. 

I don't know how or where, but I'm willing to try such a build. Can you give some hints?

That or uninstalling Foliate is my choice at the moment. I really like the program.

**Comment by johnfactotum** [comment]
You should be able to use Mesa 19 if you upgrade the Freedesktop runtimes. See https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/893

**Comment by Janghou** [comment]
Thx. Can i do that myself? Didn't know, thought it was part of the Foliate flatpak.

Maybe I' try that someday, for the moment I uninstalled the flatpak and installed the snap app. 

Working fine again. 

Thank you for all.

**Comment by johnfactotum** [comment]
That's interesting. I didn't know somebody had packaged it as a snap app!

**Comment by Janghou** [comment]
Also tried:

flatpak uninstall org.freedesktop.Sdk//18.08
flatpak install flathub org.freedesktop.Sdk//19.08

But that also madse my system instable: I could open Foliate the first time, just a short freeze, but it froze completely the second time. (Maybe I should have tried 19.2)

There is still a dependency in Foliate for:

` html5-codecs      org.freedesktop.Platform.html5-codecs       18.08      system`

Not sure if that matters, anyhow these problems are out of my knowledge base. Hopefully they will be fixed with 20.04.
