### ISSUE TITLE
[Feature suggestion] Option to open source images

### ISSUE THREAD

**Issue by ndtoan96** [johnfactotum/foliate#21]
This app is a great alternative for calibre. But I would appreciate it if you can add option to open source images or somehow zoom in the images because sometime the images have text which is unreadable in the default size.

**Comment by johnfactotum** [comment]
Currently, if you have a touchpad (or a touchscreen, I assume), you should be able to pinch zoom. This is something that every application that uses WebKit webview sort of gets "for free". You can also do this in, e.g., [Bookworm](https://babluboy.github.io/bookworm/), as it also uses WebKitGTK. I'm not sure if this only works on Wayland.

But yes, I agree. It would be good to have an option to zoom or possibly copy images.

**Comment by sjkumar-india** [comment]
In epub files moving forward one page or backward one page works by left and right arrow keys.but if page size is bigger we have to move our hands to mouse for scrolling up and down. Can you Please add the up and down scrolling option within page. thank you
