### ISSUE TITLE
Not showing any content

### ISSUE THREAD

**Issue by madjoe** [johnfactotum/foliate#211]
I could open a book (epub) with Okular without an issue, but when I open the same book with Foliate, it shows no content. However, I could see all elements in its Table of Contents, but when I click on any of them, it displays an empty page.

This is the output of epubcheck:
```
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true
Validating using EPUB version 2.0.1 rules.
No errors or warnings detected.
Messages: 0 fatals / 0 errors / 0 warnings / 0 infos

EPUBCheck completed
```

**Comment by johnfactotum** [comment]
Can you follow the instructions here: https://github.com/johnfactotum/foliate/wiki#my-book-is-not-displayed-properly, and see if it's an upstream issue?

**Comment by madjoe** [comment]
I tried to open the epub file at the URL specified in my Chromium browser (tried Previous/Next buttons) and it behaves the same as in Foliate: the content is not displayed.

**Comment by johnfactotum** [comment]
In that case it is an Epub.js issue. You should [report it upstream](https://github.com/futurepress/epub.js/issues).
