### ISSUE TITLE
List foliate on LGTM for automated code review and security analysis

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#214]
Could you list foliate on https://lgtm.com/ for automated code review and security analysis? As I see it, this would have two major benefits. End users as well as distribution maintainers will be able to quickly assess the code quality in form of an automated code quality batch (ideally rated A+) displayed on GitHub, and secondly, you may prevent bugs from appearing in your project by already catching them in the review process.

**Comment by itprojects** [comment]
+1 All to gain, nothing to lose.

> LGTM is completely free for open source projects.

**Comment by johnfactotum** [comment]
Thanks for the suggestion. I've added the project on LGTM: https://lgtm.com/projects/g/johnfactotum/foliate/, and fixed the alerts (074cf8225f94b3a0ab61819467a804f6586eca83). Most of the alerts are actually from KindleUnpack and I've excluded them in the configuration (c0cfabdb701667b52667b4465026e1568571a01b).
