### ISSUE TITLE
Cannot open ebooks with a '#' in the file name.

### ISSUE THREAD

**Issue by kolgza** [johnfactotum/foliate#216]
# Sumary
Any epub or epub3 file with a '#' in the filename fails to open
# Steps to reproduce
1. Prepend a '#' to the filename of any epub or epub3 file.
2. Attempt to open said epub or epub3 file.
# Expected Results
The epub or epub3 file with '#' in filename opens as any other file would.
# Actual Result
Upon attempting to open the epub or epub3 file, the following is displayed:
![Screenshot from 2019-12-08 10-36-57](https://user-images.githubusercontent.com/46303203/70391767-c2b30880-19a6-11ea-85b8-4ad955e819dc.png)
# More Information
OS: Pop!_OS 19.10
<pre><font color="#4E9A06"><b>➜  </b></font><font color="#06989A"><b>~</b></font> flatpak info com.github.johnfactotum.Foliate

Foliate - A simple and modern eBook viewer

<b>          ID:</b> com.github.johnfactotum.Foliate
<b>         Ref:</b> app/com.github.johnfactotum.Foliate/x86_64/stable
<b>        Arch:</b> x86_64
<b>      Branch:</b> stable
<b>     Version:</b> 1.5.3
<b>     License:</b> GPL-3.0-or-later
<b>      Origin:</b> flathub
<b>  Collection:</b> org.flathub.Stable
<b>Installation:</b> system
<b>   Installed:</b> 1.3 MB
<b>     Runtime:</b> org.gnome.Platform/x86_64/3.34
<b>         Sdk:</b> org.gnome.Sdk/x86_64/3.34

<b>      Commit:</b> 200eea70dbd415deb27fab60aea92f3d672c0876831c1c5e5989480c04015801
<b>      Parent:</b> 8416d9d43cbe387f7c857634422fc39b41e1f7d702fa12201fd788fe56aa9bd4
<b>     Subject:</b> Fix appdata to validate: screenshots have been removed from the repository (df4fde80)
<b>        Date:</b> 2019-12-07 19:17:05 +0000
</pre>

**Comment by itprojects** [comment]
There may also be other chars that could cause this bug. (Non-ascii?)
