### ISSUE TITLE
[Suggestion] Shorten the name to "foliate"

### ISSUE THREAD

**Issue by not-chicken** [johnfactotum/foliate#22]
I don't know if that's the expected way of launching foliate, but right now I have to type "com.github.johnfactotum.Foliate" in order to launch it from terminal.

Shortening it to foliate would make it convenient for the users.

**Comment by johnfactotum** [comment]
As I understand it, the RDNN practice is increasingly adopted and is considered standard these days. It's mainly to avoid naming conflicts.

If you lunch it from the command line often, maybe you can set an alias? Or if this ever gets packaged by distros, I think it would be up to the distro to choose an appropriate name for their needs.

**Comment by not-chicken** [comment]
Ok. I understand that you want to avoid name conflicts, but currently I see only this program by said name.


Alias isn't an option as in appilication launchers like dmenu, rofi . one will still have to write that long name.

**Comment by johnfactotum** [comment]
Thanks for the suggestion, but I think I will stick to the reverse-DNS name for consistency and compliance with current practice within GNOME and its wider community.

If tools like rofi doesn't support aliasing, maybe you should open a bug report with them. Also, I'd assume launchers would have support for launching by the name or keyword provided in the .desktop file, which is the primary way GUI applications are supposed to be launched in a desktop environment, I think.
