### ISSUE TITLE
Font Size is Not Consistent with Every Book

### ISSUE THREAD

**Issue by 3N4N** [johnfactotum/foliate#220]
I need to flip back and forth from different book, and the font sizes in those different books doesn't remain consistent even though the font-style and font-size are set manually. How can that be?

I, then, need to adjust the font-size to that newly opened book. But, I have to do that same thing for the book I open next. It's really annoying. How can I force the font-size to remain same?

**Comment by johnfactotum** [comment]
Currently Foliate only overrides font-size on `body` and `p` with `!important`, and it may not work with some books' stylesheet. From your description I would guess that the book sets the font size to a relative size (for example, `120%` or `smaller`) on some element other than `p`. You can edit the book (either manually or with an editor) and view the stylesheet to see what's causing this, then we can see if we can override it without breaking other books. Ultimately, it is up to the publishers to not hardcode styles too much.

A possible way to mitigate this kind of problems would be to support per-book view settings, like Evince.

**Comment by johnfactotum** [comment]
Closing as I believe the question has been answered. I've also added a [note in the documentation](https://github.com/johnfactotum/foliate/wiki#custom-style-isnt-applied-consistently). Feel free to reopen if you have any further issues/suggestions.
