### ISSUE TITLE
[Feature request] Options to set default "Sans-Serif", "Serif", "Monospace" font and choose default base font

### ISSUE THREAD

**Issue by ghost** [johnfactotum/foliate#222]
Hi,
Currently we could use either publisher font or choose a base font for all book elements, but for some books which include monospace text like programming book, we need to be able to define a monospace font to be used for showing those elements.
I propose to have four options for customizing font:

- [ ] **Sans-Serif** (set default sans-serif font)
- [ ] **Serif** (set default serif font)
- [ ] **Monospace** (set default monospace font)
- [ ] **Default font** (set default font)

then we can use Monospace font for elements like `code`, `pre` which needed a monospcae font and we can use **Default font** for other elements. **Default font** option basiclly have only two or three option which is 

- **Sans** (use default sans-serif font)
- **Serif** (use default serif font)
- **Monospace** (use default monospace font)

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.
