### ISSUE TITLE
Setting margins in two-page view only affects outer margin

### ISSUE THREAD

**Issue by tokyovigilante** [johnfactotum/foliate#225]
Setting  a relatively wide margin on a 16:10 screen for comfortable viewing in landscape (two-page view) sets only the outer margin, leaving a narrow inner margin. This gives an uncomfortable reading experience.

**Comment by johnfactotum** [comment]
Design-wise, it's not uncommon for printed books to have larger outer margins; for wider screens, the smaller inner margin means that the eye doesn't have to travel too long from one page to another.

The technical reason is that Epub.js doesn't have an API for changing the margins, and the easiest way is to simply set the outer margin. It should be possible to make Epub.js change the margins but I haven't had the time to figure out how yet.

**Comment by tokyovigilante** [comment]
That's fair, but perhaps the inner margin needs to increase as a small fraction of the outer, as it looks quite unbalanced on wide screens to my eyes. The other thing is that the page and chapter markers at the bottom don't follow the text columns. 

I've also noted as a side issue that while the disappearing iBooks-like title bar is very cool, it isn't drawn on platforms that don't render CSDs in fullscreen (ie Sway WM on Wayland) and so there is no display of the title in fullscreen.

**Comment by johnfactotum** [comment]
> The other thing is that the page and chapter markers at the bottom don't follow the text columns.

This is now fixed with 97bf4a4ebab5af68bace72f8ee6d1d47ba616d9e.

> I've also noted as a side issue that while the disappearing iBooks-like title bar is very cool, it isn't drawn on platforms that don't render CSDs in fullscreen (ie Sway WM on Wayland) and so there is no display of the title in fullscreen.

GTK hides the titlebar when the window is fullscreened. It's not really related to window managers or auto-hiding.

**Comment by tokyovigilante** [comment]
Thanks, this actually makes more of an improvement to visual balance than I was expecting. Happy to close this now.
