### ISSUE TITLE
TTS-engine skips book chapters

### ISSUE THREAD

**Issue by winterwolf** [johnfactotum/foliate#228]
I use [RHVoice](https://github.com/Olga-Yakovleva/RHVoice/) in Foliate. It is a pretty good open source TTS-engine, much better than Festival.

I use `RHVoice-test -p alan` command for English books and `RHVoice-test -p anna` for Russian. They actually works fine, but after around 1 minute of reading, chapter skips to the next one.

The problem seems not in engine, because if I just select full chapter by mouse from start to end and then run command from terminal `xclip -o | RHVoice-test -p alan`, all chapter will be read.

**Comment by johnfactotum** [comment]
Are you using the scrolled layout? Currently TTS is not fully supported in scrolled and continuous modes.

**Comment by winterwolf** [comment]
@johnfactotum Yes, you are right. Your comment helped me a lot. Thank you!
