### ISSUE TITLE
Digital clock behind the text

### ISSUE THREAD

**Issue by RomanSedykh** [johnfactotum/foliate#233]
Clock like in Alreader for windows. This is very cool feature: you do not wasting screen space for that clock at all, and it is surprisingly easy to get used to.
It must be slightly brighter with a dark background, and slightly darker on bright one. Ability to set custom color for it in options will be nice.

Example:
![book_reader_08](https://user-images.githubusercontent.com/59629258/72545456-18c67600-389a-11ea-8268-0321b1937c90.png)

I must add that in alreader that clock redraws only when you flip the page. It does not change and does not distract you when reading.

**Comment by johnfactotum** [comment]
The git master version has a footer, and can now be set to display a clock:
![image](https://user-images.githubusercontent.com/50942278/72584497-27d11680-38e2-11ea-9b8d-90cafc652ff2.png)

![image](https://user-images.githubusercontent.com/50942278/72584362-a7aab100-38e1-11ea-854a-9d0ac5c76709.png)

The clock changes only when you flip the page.
