### ISSUE TITLE
warning on stderr

### ISSUE THREAD

**Issue by mcepl** [johnfactotum/foliate#235]
Running foliate from the command line (via ``xdg-open``) and so I am wee bothered by these warnings in stderr:

```
~@stitny$ CONSOLE ERROR Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'cfiOne.path.steps')
Gjs-Message: 12:27:01.151: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 2428]: reference to undefined property "isFullscreen"
Gjs-Message: 12:27:01.776: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 2135]: reference to undefined property "atStart"
```

**Comment by 7350206** [comment]
I have something similar in terminal (running /usr/bin/com.github.johnfactotum.Foliate)
system is  Linux Mint 19.2 --  4.15.0-76-generic. 
I make a .deb as was told and almost everything works fine.  The app in "Open With" list as well.

but:  No way to chose chapters to pass. Any click to any chapter line makes anything. ((

note: when running app window  has a red border as well as terminal window it ran from has error sign. maybe it helps.

Thanks in advance

`(com.github.johnfactotum.Foliate:3785): Gtk-WARNING **: 14:51:03.638: Could not find signal handler '_edit'.  Did you compile with -rdynamic?

(com.github.johnfactotum.Foliate:3785): Gtk-WARNING **: 14:51:03.641: Could not find signal handler '_edit'.  Did you compile with -rdynamic?

(com.github.johnfactotum.Foliate:3785): Gtk-WARNING **: 14:51:03.646: Could not find signal handler '_onFindRowActivated'.  Did you compile with -rdynamic?

(com.github.johnfactotum.Foliate:3785): Gtk-WARNING **: 14:51:03.646: Could not find signal handler '_onFindEntryActivate'.  Did you compile with -rdynamic?

(com.github.johnfactotum.Foliate:3785): Gtk-WARNING **: 14:51:03.646: Could not find signal handler '_onFindEntryActivate'.  Did you compile with -rdynamic?

(com.github.johnfactotum.Foliate:3785): Gtk-WARNING **: 14:51:03.646: Could not find signal handler '_onFindEntryActivate'.  Did you compile with -rdynamic?

(com.github.johnfactotum.Foliate:3785): Gtk-WARNING **: 14:51:03.646: Could not find signal handler '_onFindEntryChanged'.  Did you compile with -rdynamic?
Gjs-Message: 14:51:03.666: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/window.js 1084]: reference to undefined property "_loading"
Gjs-Message: 14:51:03.707: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/tts.js 33]: reference to undefined property "_epub"
file:///usr/share/foliate/assets/epub-viewer.js:352:22: CONSOLE ERROR TypeError: undefined is not an object (evaluating 'cfiOne.path.steps')
file:///usr/share/foliate/assets/epub.js:8655:31: CONSOLE ERROR Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'this.manager.currentLocation')`

**Comment by mcepl** [comment]
I think that’s something a wee different: I don’t observe any loss of functionality and no ERRORs, just WARNINGs.

**Comment by johnfactotum** [comment]
There are many kinds of error messages:
- **"reference to undefined property"** is not really an error; it's a warning specific to GJS (see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Undefined_prop)). This can be easily fixed, although personally I think it's more idiomatic in JavaScript to simply evaluate a property of an object for both undefined and falsy values.
- error about **"evaluating 'cfiOne.path.steps'"** - This is an error in or related to Epub.js; on the master branch this occurs when comparing CFIs. Epub.js sometimes output other logs/errors, and those can be suppressed if desired.
- **"Could not find signal handler [...]. Did you compile with -rdynamic?"** This is a different and serious error. I haven't seen these before, but it would only occur on the master version, as it's a problem with GtkBuilder. No idea what could be causing this. Perhaps you can try manually installing (without building a .deb) or manually building a Flatpak (as a workaround)? It's also possible that it's a Mint specific problem.

**Comment by 7350206** [comment]
sorry for saying this, but with `flatpak install com.github.johnfactotum.Foliate.flatpakref` one is cured but another one geting ill )).
I made an app with flatpak
so, flatpak build version is 1.5.3, version in .deb made earlier is 2.0.0, don't know why it may be

```> **flatpak install com.github.johnfactotum.Foliate.flatpakref**
The remote 'flathub', refered to by 'com.github.johnfactotum.Foliate' at location https://dl.flathub.org/repo/ contains additional applications.
Should the remote be kept for future installations? [y/n]: y
Required runtime for com.github.johnfactotum.Foliate/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.34) found in remote flathub
Do you want to install it? [y/n]: y
Installing in system:
org.gnome.Platform/x86_64/3.34                       flathub 12697f53c77f
org.gnome.Platform.Locale/x86_64/3.34                flathub 0b2ef68ac418
org.freedesktop.Platform.GL.default/x86_64/19.08     flathub 8383da7a813b
org.gtk.Gtk3theme.Mint-Y/x86_64/3.22                 flathub 853079368347
org.freedesktop.Platform.openh264/x86_64/19.08       flathub 3e4c12dc2a37
com.github.johnfactotum.Foliate/x86_64/stable        flathub 5fdc5444e24c
  permissions: ipc, network, fallback-x11, wayland, x11, dri
  dbus access: org.freedesktop.Flatpak
com.github.johnfactotum.Foliate.Locale/x86_64/stable flathub 996eed000914
Is this ok [y/n]: y
Installing: org.gnome.Platform/x86_64/3.34 from flathub
[####################] 1174 metadata, 22208 content objects fetched; 297130 KiB ^[[B
Now at 12697f53c77f.
Installing: org.gnome.Platform.Locale/x86_64/3.34 from flathub
[####################] 18 metadata, 75 content objects fetched; 1440 KiB transfe
Now at 0b2ef68ac418.
Installing: org.freedesktop.Platform.GL.default/x86_64/19.08 from flathub
[####################] 30 metadata, 78 content objects fetched; 88756 KiB transf
Now at 8383da7a813b.
Installing: org.gtk.Gtk3theme.Mint-Y/x86_64/3.22 from flathub
[####################] 8 metadata, 169 content objects fetched; 121 KiB transfer
Now at 853079368347.
Installing: org.freedesktop.Platform.openh264/x86_64/19.08 from flathub
[####################] Downloading files: 6/6 594,2 kB (198,1 kB/s)          
Warning: Failed to install org.freedesktop.Platform.openh264/x86_64/19.08: Error deploying: While trying to apply extra data: runtime/org.freedesktop.Platform/x86_64/19.08 not installed
Installing: com.github.johnfactotum.Foliate/x86_64/stable from flathub
[####################] 32 metadata, 51 content objects fetched; 307 KiB transfer
Now at 5fdc5444e24c.
Installing: com.github.johnfactotum.Foliate.Locale/x86_64/stable from flathub
[####################] 3 metadata, 1 content objects fetched; 1 KiB transferred 
Now at 996eed000914. ```  

in that (1.5.3) version sidebar is working fine and chapters can be chosen very well, but:
--fullscreen when toggled once no way to get back, remains fullscreen forever  
--app wigth is one-paged before ~800-850px and when getting wider becomes two-paged (( and i can't find a way to control this.
I never saw the reader better. If You kindly have a time and desire )) please make it fly ))
Thanks in advance
