### ISSUE TITLE
TOC navigation does not work on master (after release 1.5.3)

### ISSUE THREAD

**Issue by maksymilian-palka** [johnfactotum/foliate#238]
Hi,

I've checked version 1.5.3 and TOC navigation is working fine for 3 of my books.
When I take the current version from master (c403096 - Update Russian translation (#237) ), then it does not work. I've tried all 4 possible layouts (auto, single column, scrolled, continuous) - didn't help.

If you need a book for the bug reproduction - I can provide it.

**Comment by johnfactotum** [comment]
Are there any error messages, when doing TOC navigation or otherwise? As far as I can tell the code for TOC navigation hasn't changed from 1.5.3 to master, and I haven't encountered any problem myself.

**Comment by maksymilian-palka** [comment]
I do not get any error messages.

Here is the link to the book. The link is valid till the end of this week (don't wanna be accused by sharing copy-righted content :o )

[https://1drv.ms/u/s!AvSdMhKNcN0wheAMQkb8YQ0UwNmLtA?e=aOTlE5](url)

**Comment by johnfactotum** [comment]
Tried it and TOC navigation seems to be working fine for me.

**Comment by maksymilian-palka** [comment]
For me TOC works in version 1.5.3; but when going to the current state of the master branch (version 2.0) - it does not.
I can make a video to show that :)

What IDE are you using to develop this project? Maybe I could run it in debug mode or sth like that and deliver more data.

**Comment by johnfactotum** [comment]
You can use GNOME Builder. Also there's an option to enable developer tools in the "advanced" submenu; after that you can right click and select "Inspect Element" to access WebKit's devtools.

**Comment by johnfactotum** [comment]
I can reproduce this on Ubuntu 18.04. It's probably the same issue as https://github.com/johnfactotum/foliate/issues/235#issuecomment-579724462.

**Comment by maksymilian-palka** [comment]
That's great news - it will be better now :)
I'm using Linux Mint 19.3 which is based on Ubuntu 18.04.

**Comment by johnfactotum** [comment]
It seems that this is only a problem with GJS 1.52. Apparently, signals defined in the UI files are not connected in older versions of GJS, according to the `NEWS` file: https://gitlab.gnome.org/GNOME/gjs/-/blob/730332a9d2da5e99fb93a3e44a28b41483adb07e/NEWS#L973. So all signal handlers connected through UI files are broken on systems with GJS < 1.54.

Which means that all these things are currently broken on Ubuntu 18.04 and similar systems, according to `grep -rn "<signal " ./src/ui`:
```
./src/ui/imageViewer.ui:31:            <signal name="clicked" handler="copy"/>
./src/ui/imageViewer.ui:47:            <signal name="clicked" handler="saveAs"/>
./src/ui/annotationBox.ui:36:                <signal name="clicked" handler="_showColors"/>
./src/ui/annotationBox.ui:88:                <signal name="clicked" handler="_showMain"/>
./src/ui/annotationBox.ui:101:                <signal name="clicked" handler="_chooseColor"/>
./src/ui/dictionaryBox.ui:16:        <signal name="activate" handler="_lookupFromEntry"/>
./src/ui/dictionaryBox.ui:93:            <signal name="changed" handler="_lookupFromEntry"/>
./src/ui/navBar.ui:115:                    <signal name="activate" handler="_onSectionEntryActivate"/>
./src/ui/navBar.ui:155:                    <signal name="activate" handler="_onLocationEntryActivate"/>
./src/ui/navBar.ui:190:                <signal name="activate" handler="_onCfiEntryActivate"/>
./src/ui/navBar.ui:274:    <signal name="size-allocate" handler="_onSizeAllocate"/>
./src/ui/navBar.ui:352:                <!-- <signal name="value-changed" handler="_onlocationScaleChanged"/> -->
./src/ui/navBar.ui:353:                <signal name="button-release-event" handler="_onlocationScaleChanged"/>
./src/ui/selectionPopover.ui:4:    <signal name="closed" handler="_onClosed"/>
./src/ui/selectionPopover.ui:21:                <signal name="clicked" handler="popdown"/>
./src/ui/selectionPopover.ui:108:            <signal name="clicked" handler="popdown"/>
./src/ui/themeRow.ui:27:            <signal name="clicked" handler="_edit"/>
./src/ui/footnotePopover.ui:23:                <signal name="activate-link" handler="_activateLink"/>
./src/ui/footnotePopover.ui:48:                <signal name="clicked" handler="_goToLinkedLocation"/>
./src/ui/annotationRow.ui:54:            <signal name="clicked" handler="_remove"/>
./src/ui/contentsStack.ui:19:                <signal name="row-activated" handler="_onTocRowActivated"/>
./src/ui/contentsStack.ui:106:                    <signal name="row-activated" handler="_onAnnotationRowActivated"/>
./src/ui/contentsStack.ui:186:                    <signal name="row-activated" handler="_onBookmarkRowActivated"/>
./src/ui/translationBox.ui:73:            <signal name="changed" handler="_langChanged"/>
./src/ui/bookmarkRow.ui:45:            <signal name="clicked" handler="_remove"/>
./src/ui/findBox.ui:7:        <signal name="activate" handler="_onFindEntryActivate"/>
./src/ui/findBox.ui:8:        <signal name="search-changed" handler="_onFindEntryChanged"/>
./src/ui/findBox.ui:19:            <signal name="toggled" handler="_onFindEntryActivate"/>
./src/ui/findBox.ui:27:            <signal name="toggled" handler="_onFindEntryActivate"/>
./src/ui/findBox.ui:44:            <signal name="row-activated" handler="_onFindRowActivated"/>
```

**Comment by maksymilian-palka** [comment]
Thank you !! It's working for me now :)
