### ISSUE TITLE
Some characters seem to be rendered glitched

### ISSUE THREAD

**Issue by bernardosulzbach** [johnfactotum/foliate#239]
![foliate-issue](https://user-images.githubusercontent.com/8271090/74086320-82ccd800-4a60-11ea-8fc2-0fc7e1e0b359.png)

![foliate-issue-2](https://user-images.githubusercontent.com/8271090/74086396-3635cc80-4a61-11ea-9d0f-a4960e8712ac.png)

This happens in 1.5.3 (openSUSE Tumbleweed's version) and 2.0.0 (built from master).

**Comment by bernardosulzbach** [comment]
Update: when clicking these, the following screen pops up.

![image](https://user-images.githubusercontent.com/8271090/74086420-6e3d0f80-4a61-11ea-8e95-d739525e4ea1.png)

Are they encoded as images in the file (instead of Unicode code points)?

**Comment by johnfactotum** [comment]
Yeah, those characters are actually images. Some publishers do this, probably because some readers don't support those unicode characters. The worst part is that they don't even have proper alt texts.

**Comment by bernardosulzbach** [comment]
> The worst part is that they don't even have proper alt texts.

I see, so the one way out of this would be to embed a full-blown OCR algorithm into foliate, which seems like going too far.

Closing as I don't think this can be seen as foliate not doing enough.
