### ISSUE TITLE
Czech localization

### ISSUE THREAD

**Issue by pafri** [johnfactotum/foliate#24]
Hi,
I send the Czech translation file. Attached. Please commit it.
Greetings
[foliate_cs.zip](https://github.com/johnfactotum/foliate/files/3244623/foliate_cs.zip)

**Comment by johnfactotum** [comment]
Can you open a pull request?

**Comment by johnfactotum** [comment]
Added in 21ea83d5a7d7069137b3ed7a1320470ebd57d7b5
