### ISSUE TITLE
Snap package ownership transfer

### ISSUE THREAD

**Issue by galgalesh** [johnfactotum/foliate#240]
Hi

I've been maintaining the [Foliate snap](https://snapcraft.io/foliate) for a few months now and I think it's at a point where it's ready to be upstreamed. Like with Flatpak, snaps are ideally published by the software developer instead of the distro maintainers. A lot more people will trust a snap coming from "johnfactotum" than from a random stranger.

I'm happy to help out to fix any snap-specific issues that you encounter and to help maintain the automatic builds after transferring the snap to you. Feel free to tag me in issues etc.

Right now, Launchpad automatically builds the snap from the `master` and `1.x` branches of my repository. It pushes the built snaps to the `latest/edge` (master) and `latest/candidate` (1.x) [channels](https://snapcraft.io/docs/channels). I then manually publish the `latest/candidate` version to the `latest/stable` channel after testing. You can set this up however you like; have the automatic builds publish straight to `stable`, for example. If you want to have multiple "stable" versions, we can also create two tracks: `2.x` and `1.x`.

There are a few steps we need to do to transfer ownership.

* [x] Merge `snapcraft.yaml` into `master`: https://github.com/johnfactotum/foliate/pull/241
* ~~[ ] Merge `snapcraft.yaml` into `1.x`: https://github.com/johnfactotum/foliate/pull/242~~
* [x] Switch the auto-builds to track `johnfactotum/foliate` instead of my repo
* ~~[ ] Add your account to [the Launchpad project doing automatic builds](https://launchpad.net/foliate-snap). *(do you have a launchpad account?)*~~
* [x] Set up automatic builds the way you prefer
* [x] update README.md to explain how to test the latest code using snap
* [x] Transfer ownership of [the snap itself](https://snapcraft.io/foliate) to you

This issue is to track the progress of the transfer.

*Note: I used this snap for the ["Snapping a GTK3 app"](https://snapcraft.io/docs/gtk3-applications) tutorial. Check it out for more explanation on what the `snapcraft.yaml` does exactly.*

**Comment by johnfactotum** [comment]
Thanks a lot for your work! I will review this more thoroughly when I have time. One thing is that it should use the tagged releases, instead of branches, for the stable version; the 1.x branch is the unreleased development branch for the 1.x releases. Maybe I should just create another 1.x release.

**Comment by galgalesh** [comment]
@johnfactotum are you thinking of supporting a 1.x and 2.x release at the same time, or do you want all users to upgrade to 2.x immediately once you do the first release?

**Comment by johnfactotum** [comment]
The latter. I'm not very happy with the 2.x code, but as it is I think it's good enough to make a stable release. Just need to update the AppData file, and also the Debian files, which is a hassle.

**Comment by galgalesh** [comment]
@johnfactotum any update on making the first 2.x release? It looks really good!

**Comment by johnfactotum** [comment]
Thanks! Currently the main blocker is https://github.com/johnfactotum/foliate/issues/238. I'll try and make the release as soon as that's fixed.

**Comment by galgalesh** [comment]
@johnfactotum thanks for merging the PR and releasing 2.0.0 version! It looks really good!

I updated the automatic builds: it now builds from the master branch in this repository and pushes to the `edge` channel. After you make a release, you can then manually publish the package in `edge` to `stable` so all the users get the update.

The next step is to give you access to the Launchpad project and the app at snapcraft.io. Can you create an account here? https://snapcraft.io/account

**Comment by johnfactotum** [comment]
All right, I've created an account. How does the transfer work? Also I see that there's an option to build from GitHub, so there's no need to use Launchpad, right?

**Comment by galgalesh** [comment]
@johnfactotum I have to request the transfer on the snapcraft forum. Is your username on snapcraft also `johnfactotum`?

Yes, the GitHub build option works well. The reason why I used launchpad initially was to have two builds; one for 1.x and one for 2.x. But that is not required anymore. You will need to setup the GitHub build yourself once the snap is transferred; you need permissions to the repository on GitHub in order to do that. I'll start the transfer right away when you confirm your snapcraft username.

**Comment by johnfactotum** [comment]
Yep, that should be me.

**Comment by galgalesh** [comment]
Transfer request: https://forum.snapcraft.io/t/transfer-foliate-to-johnfactotum/16467

**Comment by johnfactotum** [comment]
I've confirmed the transfer in the e-mail. Thanks for all your work!

**Comment by johnfactotum** [comment]
Ownership transfer is complete now. Thanks again, @galgalesh!

**Comment by galgalesh** [comment]
Happy to help @johnfactotum! Feel free to ping me when you encounter snap-specific issues.
