### ISSUE TITLE
Support themes in YAML

### ISSUE THREAD

**Issue by gsbhasin123** [johnfactotum/foliate#246]
YAML is a much more readable format. It would surely motivate more users to make themes! (see also: https://www.npmjs.com/package/js-yaml)

**Comment by johnfactotum** [comment]
I'm inclining to closing this as _won't fix_.

The intended way of customizing themes is through the GUI. The vast majority of users will not be manually editing the files.

Supporting YAML would require additional packages, with little benefits.

**Comment by gsbhasin123** [comment]
Wait - there is a GUI?
Did not even realize that. 
This decision makes sense then.
