### ISSUE TITLE
Gnome sdk missing from flatpak on arm64

### ISSUE THREAD

**Issue by ruapotato** [johnfactotum/foliate#248]
Installed using flatpak on the Librem 5 running the latest version of PureOS. (More or less Debian)
After installing, I'm unable to run:
```
purism@pureos:~$ flatpak run --command=sh --devel com.github.johnfactotum.Foliate
error: runtime/org.gnome.Sdk/aarch64/3.34 not installed
purism@pureos:~$ 
```

**Comment by johnfactotum** [comment]
I think it needs the SDK if you run it with `--command=sh --devel`. Can you try installing the SDK with `flatpak install gnome org.gnome.Sdk 3.34`?

**Comment by johnfactotum** [comment]
Closing as this does not appear to be a bug.
