### ISSUE TITLE
Adopt the "Open Annotation" in EPUB format

### ISSUE THREAD

**Issue by felipehw** [johnfactotum/foliate#249]
Sorry, if I'm completely wrong. But I was searching if there is a standard way to implement annotations in EPUB format and I found this: http://idpf.org/epub/oa/

If this is a standard way to implement annotations?
Foliate follows this pattern?
If not ... could Foliate follow this standard?

Thanks in advance for answering this question :D

**Comment by johnfactotum** [comment]
The Open Annotation/Web Annotation standard is indeed a thing, and it's a very general and featureful format. As far as I know, though, it isn't really used anywhere apart from [Hypothesis](https://web.hypothes.is/).

Foliate uses its own format, and it only supports a very small subset of the features of the web annotation standard. But converting one format to another should be very straightforward.

**Comment by felipehw** [comment]
In the case of annotations for education purposes, many people will search for "future proof" solutions. Solutions that they know will enable them to carry their annotations between software along the years to come.

Maybe this is a good step to Foliate. But, as you say, this standard is not yet widespread :(

**Comment by itprojects** [comment]
> Solutions that they know will enable them to carry their annotations between software along the years to come.

@felipehw You mean BibTex? Foliate, has that.

**Comment by felipehw** [comment]
I was thinking in highlight, popup and inline notes. Like PDF readers (Okular, etc.) that you can use this annotations across readers.

**Comment by johnfactotum** [comment]
To clarify: currently, Foliate stores annotations like this:
```json
{
  "annotations": [
    {
      "value": "epubcfi(...)",
      "color": "aqua",
      "text": "A sentence from the book.",
      "note": "I think this is OK."
    },
    {
      "value": "epubcfi(...)",
      "color": "aqua",
      "text": "Another sentence from the book.",
      "note": "I think this is OK, too."
    }
  ]
}
```

If I understand the [draft spec](http://idpf.org/epub/oa/) correctly, the equivalent, in Open Annotation, should be:
```json
{
  "@context": "http://www.idpf.org/epub/oa/1.0/context.json",
  "@type": "epub:AnnotationCollection",
  "annotations": [
    {
      "@type": "oa:Annotation",
      "styledBy": {
        "@type": "oa:CssStyle",
        "format": "text/css",
        "chars": ".aqua { background: aqua; }"
      }, 
      "hasTarget": {
        "@type": "oa:SpecificResource",,
        "hasSource": {
          "@type": "dctypes:Text",
          "uniqueIdentifier": "...",
        }
        "hasSelector": {
          "@type": "oa:FragmentSelector",
          "value": "epubcfi(...)"
        },
        "styleClass": "aqua"
      },
      "hasBody": {
        "@type": "dctypes:Text",
        "format": "application/xhtml+xml",
        "chars": "I think this is OK."
      }
    },
    {
      "@type": "oa:Annotation",
      "styledBy": {
        "@type": "oa:CssStyle",
        "format": "text/css",
        "chars": ".aqua { background: aqua; }"
      }, 
      "hasTarget": {
        "@type": "oa:SpecificResource",,
        "hasSource": {
          "@type": "dctypes:Text",
          "uniqueIdentifier": "...",
        }
        "hasSelector": {
          "@type": "oa:FragmentSelector",
          "value": "epubcfi(...)"
        },
        "styleClass": "aqua"
      },
      "hasBody": {
        "@type": "dctypes:Text",
        "format": "application/xhtml+xml",
        "chars": "I think this is OK, too."
      }
    }
  ]
}
```

But, Open Annotation is obsolete, and replaced with the [Web Annotation spec](https://www.w3.org/TR/annotation-model/) (so much for "future-proof solutions").

Now, the Web Annotation spec doesn't really talk about how it should be used for EPUBs (nothing beyond the type of selectors that must be used), but, if I read the spec currently, it should translate more or less straightforwardly to the following in Web Annotation:
```json
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "type": "AnnotationCollection",
  "first": {
    "type": "AnnotationPage",
    "items": [
      {
        "type": "Annotation",
        "stylesheet": {
          "type": "CssStylesheet",
          "value": ".aqua { background: aqua; }"
        },
        "bodyValue": "I think this is OK.",
        "target": {
          "source": "/* This should be the unique ID of the book, I think */",
          "selector": [
            {
              "type": "FragmentSelector",
              "conformsTo": "http://www.idpf.org/epub/linking/cfi/epub-cfi.html",
              "value": "epubcfi(...)",
            },
            {
              "type": "TextQuoteSelector",
              "exact": "A sentence from the book."
            }
          ],
          "styleClass": "aqua"
        }
      },
      {
        "type": "Annotation",
        "stylesheet": {
          "type": "CssStylesheet",
          "value": ".aqua { background: aqua; }"
        },
        "bodyValue": "I think this is OK, too.",
        "target": {
          "source": "...",
          "selector": [
            {
              "type": "FragmentSelector",
              "conformsTo": "http://www.idpf.org/epub/linking/cfi/epub-cfi.html",
              "value": "epubcfi(...)",
            },
            {
              "type": "TextQuoteSelector",
              "exact": "Another sentence from the book."
            }
          ],
          "styleClass": "aqua"
        }
      },
    ]
  }
}
```

I have no idea if this is correct (I don't even know any reading system that currently supports Web Annotation). You can see, though, that Foliate's own format is, at least in theory, completely interoperable with the Web Annotation format. The `note` field in Foliate is exactly equivalent to `bodyValue`. And `text` and `value` are exactly equivalent to `TextQuoteSelector` and `FragmentSelector` (the two types of selectors used for EPUB files, per the spec). So if it makes you feel better, you can think of Foliate's format as an extremely simplified subset of the standard.

**Comment by felipehw** [comment]
Thank you for the careful research.

Now I know that it isn't hard to adapt it in the future (if I need it).

It's sad the actual lack of a consistent and spread standard for this :/
