### ISSUE TITLE
Support CBZs ($50 Bounty)

### ISSUE THREAD

**Issue by anthonyajumelles** [johnfactotum/foliate#254]
Hello there,
I am deeply appreciative of all the work that has gone into making Foliate the premier eBook reader. The ground up rewrite looks stellar. 

My only request is for CBZ support to be considered. I know Komikku is available for manga however I would much prefer to be able to utilize my collection of legally purchased CBZs.  

KOReader is also an alternative but the UI is nowhere near as good as Foliate.

Normally I try not to request new features, however both EPUBs and CBZs are zips and the main work for this would be displaying images in sorted order, something that I wouldn't say is trivial but that fits within the scope of the applications current features.

The only extra features I can conceive of are cropping margins, inverting images for night mode, and converting white space to background color. Baseline of just fitting the image to display width would do the trick.

$50 USD to start: https://www.bountysource.com/issues/90789000-request-support-cbz-comic-books-manga-w-bounty

**Comment by habenamare** [comment]
I have created PR #314 which implements this issue. I would appreciate any feedback, especially on how the pages are displayed.

**Comment by habenamare** [comment]
This issue is not closed at Bountysource. @johnfactotum Can you check the integration? Maybe using [Bountysource Tools](https://www.bountysource.com/tools)?

**Comment by johnfactotum** [comment]
Okay, I've installed the plugin. I've also sent a request to claim the foliate "team", which should be "processed within 2 business days."
