### ISSUE TITLE
Dictionary Bugs

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#26]
Double-clicking a word in foliate automatically spams the dictionary server for a word description, in a decentralised manner.

Wouldn't it be best if the dictionary function was implemented through the internal [dictd](https://wiki.archlinux.org/index.php/Dictd)?

If not, then maybe this behavior should be controlled with a button ('check online' over an initial popup) to avoid an unecessary Distributed Denial of Service.

Also - What if the ePub is a very private document? Sending an online query is a data leak, users might not know that. Best warn them in the description?

Network charges can cost money, too.

Thanks making the best ePub software!

**Comment by johnfactotum** [comment]
Funny enough, I've just add the option in 5c9c9bc3ceccd42429acaeef1bd81dafa6a49cf7 before even seeing this issue.

I think it's extremely unfair to call it "spamming" or "Distributed Denial of Service". It's simply querying one page (two at most, if the word contains capital letters and was not found, it tries for an all lowercase version), based on explicit, well-defined user action.

I'm also very clear about the data coming from Wiktionary -- noted both on the website as well as in the lookup popover.

I do plan on adding more dictionary options eventually, although this is a relatively arduous task, so it might not happen very soon. See also #5. As for the lookup-on-selection behavior, it's related to highlight-on-selection discussed in #9.

**Comment by itprojects** [comment]
Thanks for the quick reply! Apologies for the DDoS remarks...

**Comment by itprojects** [comment]
@johnfactotum Bug testing results:

After removing the old flatpak, cleaning the '.var' folder for leftover app settings, and installing the 1.1.0, there is now a new bug that prevents the disabling of dictionary, although the checkbox exists in UI:

Step 1. Click on 'Enable dictionary', but it stays always checked

Commentary: The gschema in dconf  does not seem to have 'lookup-enabled' ( data/com.github.johnfactotum.Foliate.gschema.xml). maybe an old file or resource is the problem?

Console messages:

flatpak run com.github.johnfactotum.Foliate
Gjs-Message: : JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 1086]: reference to undefined property "webView"

(com.github.johnfactotum.Foliate:2): Gjs-WARNING **: : JS ERROR: TypeError: this.webView is undefined
scriptRun@resource:///com/github/johnfactotum/Foliate/js/main.js:1086:9
buildMenu/<@resource:///com/github/johnfactotum/Foliate/js/main.js:1582:17
main@resource:///com/github/johnfactotum/Foliate/js/main.js:1861:12
run@resource:///org/gnome/gjs/modules/package.js:225:12
@/app/bin/com.github.johnfactotum.Foliate:9:1

**Comment by johnfactotum** [comment]
dconf-editor will not show the `lookup-enabled` key if you're using flatpak and doesn't have a value set for that key, because the flatpak version installs the schema in a private directory.

Is this the full output? Something is seriously wrong with your install, as the script couldn't even find the webview. If it's a schema problem it should say `Settings schema 'com.github.johnfactotum.Foliate' does not contain a key named 'lookup-enabled'` or something along those lines. So it doesn't seem to me that that is the problem here.

**Comment by itprojects** [comment]
Thanks for the feedback.

Yes, flatpak was the problem. Directly building and installing with the meson build system is a fix. 'lookup-enabled appeared'.

You can mark this issue closed, if you want.
