### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by spitocco** [johnfactotum/foliate#262]
Hello
![1](https://user-images.githubusercontent.com/63195094/78499842-70ff6c80-7753-11ea-940e-554c9365615a.png)
![2](https://user-images.githubusercontent.com/63195094/78499843-71980300-7753-11ea-8b15-f33c4b1c9136.png)
![3](https://user-images.githubusercontent.com/63195094/78499844-72309980-7753-11ea-9580-2a93be566c58.png)

!
Today, after the update of Foliate to version 2.0.0 I can't see the icons in the menu anymore (attachments).
I'm using Zorin OS 15.2 (all details in the attachment as well) and I downloaded Foliate from Flathub.
Since a couple of weeks I'm having the same issue with another Flathub app, Lollypop... maybe it helps!

Thank you for your help
Simone

**Comment by galgalesh** [comment]
Hi Simone

The icons automatically hide when you're not using them. You should be able to see them again by moving your mouse over the top of the window, where the name of the book is. Can you try this?


![Peek 2020-04-05 16-09](https://user-images.githubusercontent.com/1492981/78500637-ea995980-7757-11ea-858c-0b49c912736c.gif)

**Comment by johnfactotum** [comment]
@galgalesh I think @spitocco is talking about the missing icons in the menu and the navbar.

@spitocco Since it affects GTK's built-in widgets (the spin buttons in the primary menu), and also other Flatpak applications, I'm fairly certain this is not our bug. From the icons which are not missing, it seems that the icon theme used is not Adwaita, but something based on Paper. So this is probably something wrong with the icon theme used by Zorin OS in Flatpak.

**Comment by spitocco** [comment]
Hi, and thanx for the answer!
I saw that now I have to move the mouse over the top of the window, and it works smoothly.
What I can't see are the + and - icons in the menu (e.g. for spacing and margins).
I add another screenshot.
Thanx again
![1_1](https://user-images.githubusercontent.com/63195094/78501278-50d3ab80-775b-11ea-9dfb-6353ac01be21.png)

**Comment by spitocco** [comment]
@johnfactotum thanx!
I was thinking about something similar... I'll try to contact them and let them aware of the issue!

**Comment by spitocco** [comment]
Yes, I wrote a post on Zorin Forum and they just confirmed me @johnfactotum post.
Thank you for the help.
I mark the post as solved.

**Comment by johnfactotum** [comment]
For reference, it's in fact a bug with the Paper icon theme itself: https://github.com/snwh/paper-icon-theme/issues/737

**Comment by spitocco** [comment]
Thanx!
I let the Zorin team aware and they just published an icon theme update:
now it perfectly works as it should!
Thank you for your help and support.

Best regards
Simone

Il mar 7 apr 2020, 14:26 John Factotum <notifications@github.com> ha
scritto:
