### ISSUE TITLE
A niggle about your front-page

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [johnfactotum/foliate#264]
The page I mean is [this](https://github.com/johnfactotum/foliate/releases/tag/2.0.0).

The niggle: if you have to look up Kant on Wikipedia, then you are very unlikely to be reading that book or, if you _are_ reading it, to understand it!

:)

(I look forward to trying your software, which is getting - in its new release - a good reception on Reddit.)

**Comment by johnfactotum** [comment]
Thanks for pointing that out! You're probably right, although I've found that even if something appears totally impenetrable at first, taking baby steps to try and understand a little bit can be a rewarding experience. (Take the GTK documentations, for example!)

**Comment by LinuxOnTheDesktop** [comment]
Yes, but there's a lot of steps between the baby-step of a typical Wikipedia article and - by the look of it - that book!
