### ISSUE TITLE
Font's color is always dark even with dark themes.

### ISSUE THREAD

**Issue by aasril** [johnfactotum/foliate#265]
I have the same problem both with manually compiled and from flatpak install (Ubuntu 18.04), that the text is unreadable on dark themes (aside from the invert mode). The text's color is stays dark even with those dark themes.

======

Thanks for the version 2.0. I'm really enjoying of the new header bar auto-hide feature.

**Comment by johnfactotum** [comment]
See [the wiki](https://github.com/johnfactotum/foliate/wiki#custom-style-isnt-applied-consistently):

> Currently Foliate only overrides font-size on body and p with !important, and it may not work with some books' stylesheet. You can edit the book (either manually or with an editor) and view the stylesheet to see what's causing this, then we can see if we can override it without breaking other books.
>
> Generally, it's kind of hard to strike a balance between user control and publisher control. Ultimately, it is up to the publishers to not hardcode styles too much.
>
> See: #2, #34, #67, #173, #220

The invert theme is aimed exactly at working around the problem of hardcoded colours. 

Note that you can add a custom theme and set nicer colours, and turn on "Invert". It will use the custom colours, but hardcoded dark texts will be inverted. (This is new in 2.0; previously it simply invert the whole page once, so you need to manually invert your colours first; now it inverts the custom colours first, then invert the whole page, so the custom colours will come out as intended.)

**Comment by aasril** [comment]
That works! Thank you, I'm closing this issue.

**Comment by johnfactotum** [comment]
Can you post a screenshot? What GTK theme are you using?

**Comment by aasril** [comment]
![Screenshot from 2020-04-07 09-48-47](https://user-images.githubusercontent.com/37625377/78625268-d2d7e780-78b5-11ea-8897-2789010186e3.jpg)

The GTK theme is Qogir.

**Comment by johnfactotum** [comment]
That's weird. It works for me.

No invert:
![image](https://user-images.githubusercontent.com/50942278/78625612-0bf36600-787c-11ea-9ebe-85911b0adc58.png)

Invert:
![image](https://user-images.githubusercontent.com/50942278/78625635-1f063600-787c-11ea-910f-1ecacb1d8482.png)

Also using Qogir.

**Comment by aasril** [comment]
Okay, I see the problem. I used the same color for both *background* and the *text*. I solved the issue by changing the text color to a light color.
