### ISSUE TITLE
[Request] Option to apply an overriding stylesheet

### ISSUE THREAD

**Issue by anthonyajumelles** [johnfactotum/foliate#267]
I like to read fan translations of foreign books. However the issue with a lot of these projects is they tend to be written in Google Docs which, when exporting to epub, doesn't produce a file that respects Foliate's font setting for <p>. 

I'd love to be able to use [any of the default CSS stylesheets](https://github.com/sw4/revert.css) from browsers implemented or KOReader's default CSS stylesheets, over each epub's individual CSS implementation. This should address some of the visual issues with inconsistent font sizing that users are reporting.

**Comment by johnfactotum** [comment]
I think this is actually the same as #947.
