### ISSUE TITLE
Minor icon update?

### ISSUE THREAD

**Issue by bertob** [johnfactotum/foliate#268]
The current icon is nice overall, but the "fold" at the bottom is a bit odd. I was playing with this book shape with a proper spine, and I feel like it could work:

![image](https://user-images.githubusercontent.com/1908896/78602153-3b8f7780-7856-11ea-998c-919acebe3e74.png)

If you're interested in pursuing this direction I'd be happy to iterate on this and try some variations.

**Comment by johnfactotum** [comment]
Yeah, I think I like this direction. It would give it a much more distinct outline, instead of just a dull rectangle. Although the steep and abrupt angle change of the fold kind of makes it look like the book is melting -- maybe that's just because I'm used to the old icon.

**Comment by bertob** [comment]
If you want I can do an MR so you can try it for real, and we can iterate from there.

**Comment by johnfactotum** [comment]
Sure!

**Comment by johnfactotum** [comment]
Thanks a lot for your work!
