### ISSUE TITLE
"Invert" color theme distorts sub-pixel font rendering

### ISSUE THREAD

**Issue by jspatz** [johnfactotum/foliate#269]
The "invert" option is very handy for dealing with ebooks that include hard-coded colors.  However, it appears to be inverting text colors _after_ sub-pixel font rendering is applied, causing the sub-pixel colors themselves to be inverted, and therefore creating significant color-fringing distortions.

Example:

Text with "light" theme":
![image](https://user-images.githubusercontent.com/12176759/78605548-c27a2b00-7829-11ea-9595-48bac9bd2118.png)

Same text with "invert" theme:
![image](https://user-images.githubusercontent.com/12176759/78605619-eb022500-7829-11ea-910b-c6b1afe46d01.png)

For comparison, "dark" theme, which does not exhibit this issue:
![image](https://user-images.githubusercontent.com/12176759/78605666-ff462200-7829-11ea-941e-0b6f5f3ace4c.png)

**Comment by johnfactotum** [comment]
I don't think there's much we can do, as the rendering is done using CSS filters. And unfortunately, that just seems to be how filters work. For example, if you pinch zoom after applying the filter, the text gets blurry. There's probably a WebKit bug about this somewhere, or maybe that's just how filters are supposed to work.

For the moment I'll mark this as not our bug. For other methods of overriding book styles, we'll track it in https://github.com/johnfactotum/foliate/issues/267.

**Comment by johnfactotum** [comment]
Actually I think this can be avoided by inverting only the text but not the background. This can be demonstrated with the following example:
```html
<div style="background: #fff; color: #000; filter: invert(1) hue-rotate(180deg);">
    <h1>Test</h1>
</div>
<div style="background: #000;">
    <h1 style="color: #000; filter: invert(1) hue-rotate(180deg);">Test</h1>
</div>
```

![image](https://github.com/johnfactotum/foliate/assets/50942278/3a5f1ce9-330f-459a-a868-3867c5283ebc)
