### ISSUE TITLE
building

### ISSUE THREAD

**Issue by rulet** [johnfactotum/foliate#27]
Hello, trying to build:
r@prime:~/foliate-master$ meson build --prefix=$PWD/fakeprefix
The Meson build system
Version: 0.37.1
Source dir: /home/r/foliate-master
Build dir: /home/r/foliate-master/build
Build type: native build

Meson encountered an error in file meson.build, line 1, column 0:
Not enough arguments to project(). Needs at least the project name and one language
r@prime:~/foliate-master$ ninja -C build
ninja: Entering directory `build'
ninja: error: loading 'build.ninja': No such file or directory
r@prime:~/foliate-master$

**Comment by johnfactotum** [comment]
I see you're using Meson 0.37.1. Can you try with a newer version?

The minimum version specified in the build file is 0.40.0. Although it warns about using a 0.50.0 feature and I never got around to see if I need to fix that.

**Comment by rulet** [comment]
With meson 0.49 builds, but something wrong at the end:

r@prime:~/foliate-master$ meson build --prefix=$PWD/fakeprefix
The Meson build system
Version: 0.49.0
Source dir: /home/r/foliate-master
Build dir: /home/r/foliate-master/build
Build type: native build
Project name: com.github.johnfactotum.Foliate
Project version: 1.0.1
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Program appstream-util found: NO
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Found pkg-config: /usr/bin/pkg-config (0.29)
WARNING: GLib compiled dependencies do not work reliably with 
the current version of GLib. See the following upstream issue: https://bugzilla.gnome.org/show_bug.cgi?id=774368
Program gjs found: YES (/usr/bin/gjs)
Configuring com.github.johnfactotum.Foliate using configuration
Program build-aux/meson/postinstall.py found: YES (/home/r/foliate-master/build-aux/meson/postinstall.py)
Build targets in project: 7
Found ninja-1.7.2 at /usr/bin/ninja
r@prime:~/foliate-master$ ninja -C build
ninja: Entering directory `build'
[3/3] Generating com.github.johnfactotum....ata.xml_data_merge with a custom command.
r@prime:~/foliate-master$ ninja -C build install
ninja: Entering directory `build'
[0/1] Installing files.
Installing subdir /home/r/foliate-master/src/assets to /home/r/foliate-master/fakeprefix/share/com.github.johnfactotum.Foliate/assets
Installing /home/r/foliate-master/src/assets/cheerio.js to /home/r/foliate-master/fakeprefix/share/com.github.johnfactotum.Foliate/assets
Installing /home/r/foliate-master/src/assets/viewer.html to /home/r/foliate-master/fakeprefix/share/com.github.johnfactotum.Foliate/assets
Installing /home/r/foliate-master/src/assets/epub.js to /home/r/foliate-master/fakeprefix/share/com.github.johnfactotum.Foliate/assets
Installing /home/r/foliate-master/src/assets/jszip.min.js to /home/r/foliate-master/fakeprefix/share/com.github.johnfactotum.Foliate/assets
Installing data/com.github.johnfactotum.Foliate.desktop to /home/r/foliate-master/fakeprefix/share/applications
Installing data/com.github.johnfactotum.Foliate.appdata.xml to /home/r/foliate-master/fakeprefix/share/metainfo
Installing src/com.github.johnfactotum.Foliate.src.gresource to /home/r/foliate-master/fakeprefix/share/com.github.johnfactotum.Foliate
Installing /home/r/foliate-master/data/com.github.johnfactotum.Foliate.gschema.xml to /home/r/foliate-master/fakeprefix/share/glib-2.0/schemas
Installing /home/r/foliate-master/data/com.github.johnfactotum.Foliate.svg to /home/r/foliate-master/fakeprefix/share/icons/hicolor/scalable/apps
Installing /home/r/foliate-master/data/com.github.johnfactotum.Foliate-symbolic.svg to /home/r/foliate-master/fakeprefix/share/icons/hicolor/symbolic/apps
Installing /home/r/foliate-master/build/src/com.github.johnfactotum.Foliate to /home/r/foliate-master/fakeprefix/bin
Running custom install script '/usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=com.github.johnfactotum.Foliate'
Installing /home/r/foliate-master/build/po/nl_NL.gmo to /home/r/foliate-master/fakeprefix/share/locale/nl_NL/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Installing /home/r/foliate-master/build/po/it.gmo to /home/r/foliate-master/fakeprefix/share/locale/it/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Installing /home/r/foliate-master/build/po/zh_TW.gmo to /home/r/foliate-master/fakeprefix/share/locale/zh_TW/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Installing /home/r/foliate-master/build/po/ru_RU.gmo to /home/r/foliate-master/fakeprefix/share/locale/ru_RU/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Running custom install script '/home/r/foliate-master/build-aux/meson/postinstall.py'
Updating icon cache...
Updating desktop database...
Compiling GSettings schemas...
r@prime:~/foliate-master$ GSETTINGS_SCHEMA_DIR=$PWD/fakeprefix/share/glib-2.0/schemas ./fakeprefix/bin/com.github.johnfactotum.Foliate

(com.github.johnfactotum.Foliate:3488): Gjs-CRITICAL **: JS ERROR: SyntaxError: invalid property id @ resource:///com/github/johnfactotum/Foliate/js/main.js:37
JS_EvaluateScript() failed
r@prime:~/foliate-master$

**Comment by johnfactotum** [comment]
This looks like a JS error, though. What version of GJS do you have?

**Comment by rulet** [comment]
That which in Debian stretch(stable) 1.46.0-1: 
https://packages.debian.org/stretch/gjs

**Comment by johnfactotum** [comment]
I think you'd need at least 1.50.x, although I haven't really tested, as I've been developing against 1.56.

**Comment by rulet** [comment]
I see, so there is no way to test it, in next Debian stable will be gjs 1.54.3-1, and I don't want to brake the system by installing unsupported version.

**Comment by johnfactotum** [comment]
In general, this is developed against the GNOME 3.32 environment. I think stretch is still on 3.22?

Maybe you could try the flatpak version?

**Comment by rulet** [comment]
flatpak package works with some issues(error when opening epub by default application for it), but I don't want to use flatpak.

**Comment by johnfactotum** [comment]
Well, in that case, there's really nothing I can do. The code relies heavily on ES6 features available only in later versions of GJS.

**Comment by rulet** [comment]
Why not to use different language?

**Comment by johnfactotum** [comment]
I suppose I could have, but I didn't. And I'm not going to rewrite the whole thing now.

**Comment by LoafingBunny** [comment]
Instead of opening a new issue, because the problem is the same:
on ubuntu 18.04 compilation is fine but wont start. 

```
./fakeprefix/bin/com.github.johnfactotum.Foliate 

(com.github.johnfactotum.Foliate:6139): Gjs-CRITICAL **: 13:44:05.136: JS ERROR: SyntaxError: invalid property id @ resource:///com/github/johnfactotum/Foliate/js/main.js:1884
Script ./fakeprefix/bin/com.github.johnfactotum.Foliate threw an exception
```
Gjs version is 1.52.5-0ubuntu18.04.1

**Comment by johnfactotum** [comment]
Yes, that specific line uses [spread in object literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_Syntax), which is only available in Firefox 55+, which means it's probably only available in GJS 1.53.9+.

The solution would be to either install a newer version of GJS, or possibly transpiling the code with something like [Babel](https://babeljs.io/). See #45. Of course one could also manually rewrite the code, but I don't think anyone's got time for that.

Why is all this necessary? Well, it's just like newer versions of Meson require newer versions of Python in order to run. It just so happens that GJS isn't as popular as Python, so there's no convenient PPAs one could just use.

I'll add the version info in the readme.

**Comment by LoafingBunny** [comment]
ok I was able to manually compile the main.js with babel targeting to firefox 52. Now I can open books and foliate works fine.
I don't know how to integrate babel with your code, but for what might worth I write the steps I did:

```bash
> cd src
> npm install --save-dev @babel/core @babel/cli @babel/preset-env
# create a file .babelrc with inside:
{
  "presets": [
      ["@babel/preset-env", {
        "targets": {
          "firefox": "52"
        }
      }]
    ]
}

# copy the main
> mv main.js main.src.js
# compile
> npx babel main.src.js --out-file main.js
```

that's all.

**Comment by rulet** [comment]
Well, I successfully build your program(deb-package) on Debian 10(Gnome). It installs and works.
