### ISSUE TITLE
Add an option to disable going to the next/previous page on mouse click

### ISSUE THREAD

**Issue by mar04** [johnfactotum/foliate#270]
When I want to select a single word I just double click it - but Foliate instead turns a page.

**Comment by johnfactotum** [comment]
Double clicking should work as usual. There's a delay when clicking to check if you're double clicking, and the duration of the delay comes from GTK's double click time setting.

**Comment by mar04** [comment]
Well since updating to 2.0.0, I managed to trigger unwanted page flips a couple too many times, both by miss timing a double clicks or by clicking inside a window to focus or raise it. And I'm not using Gnome, so I don't even know how to access that GTK setting or if I even want to change it - it wasn't a problem before. I would appreciate adding an option to just disable that behaviour.
