### ISSUE TITLE
Czech translation update

### ISSUE THREAD

**Issue by pafri** [johnfactotum/foliate#271]
Hi, I've updated the Czech translation file. Attached. Please commit it.
[cs_CS.zip](https://github.com/johnfactotum/foliate/files/4446577/cs_CS.zip)

**Comment by itprojects** [comment]
@pafri Please, please, in the future just submit a pull request.

It's very easy:

1. Login to Github
2. Click on a foliate file you want to edit
3. Make some changes. Copy/paste from cs_CS.po is even quicker.
4. Commit the changes. If approved (in the most likely case) you will see the changes soon.
