### ISSUE TITLE
Change project milestones for v3.0

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#272]
Since v2.0 is now released, can you please update [the project link](https://github.com/johnfactotum/foliate/projects/1) for v2.1 or v3.0 or the next one?

**Comment by johnfactotum** [comment]
I've simply closed the project.

**Comment by itprojects** [comment]
@johnfactotum  That's one way, but how do we know what bugs to lookout for in v3.0?

**Comment by johnfactotum** [comment]
I suppose we don't. There aren't really any definite plans at the moment.
