### ISSUE TITLE
Changing locale has no effect

### ISSUE THREAD

**Issue by jony0008** [johnfactotum/foliate#274]
Where can I find the setting to switch languages in foliate 2.0?

**Comment by johnfactotum** [comment]
There's no such setting. The locale is set using the `LANG` environmental variable. However there seems to be a bug and it doesn't have any effect (except on the built in GTK strings).

**Comment by jony0008** [comment]
That explains the program not being translated. I will wait for a bug fix then.

**Comment by johnfactotum** [comment]
Huh, I just realized that it actually works fine in a regular install, but it doesn't work when using the "Build and run from source without installing" option, which is odd.

**Comment by johnfactotum** [comment]
Okay, I was wrong. The problem is this: https://github.com/johnfactotum/foliate/commit/b403420d169711e540d85271aa3fe12f4a330189#diff-969b60ad3d206fd45c208e266ccfed38R1.

**Comment by ismail** [comment]
> Okay, I was wrong. The problem is this: [b403420#diff-969b60ad3d206fd45c208e266ccfed38R1](https://github.com/johnfactotum/foliate/commit/b403420d169711e540d85271aa3fe12f4a330189#diff-969b60ad3d206fd45c208e266ccfed38R1).

This ends up with stuff getting installed into `/usr/share/com.github.johnfactotum.Foliate`, is that intended?

**Comment by johnfactotum** [comment]
Yes. It has been doing that since the beginning. The ID was unintendedly changed to `foliate` during the rewrite process (as the result of using Builder's project template), which is why the translations broke.
