### ISSUE TITLE
Unable to access menu after enabling experimental titlebar

### ISSUE THREAD

**Issue by aeonian-adroit24** [johnfactotum/foliate#278]
Is there a way to get back the menu or preferably the headerbar back? Tried purging but won't revert back to default settings. Anything I missed or is it something to be fixed?

```
elementary OS 5.1.2
DEB Package 2.0.0
```

![Screenshot from 08 Apr 2020 | 15:35:32](https://user-images.githubusercontent.com/46897914/78772096-dc914600-79ae-11ea-9eec-21e53faeefb6.png)

**Comment by johnfactotum** [comment]
You can run the following to revert the setting:
```sh
gsettings set com.github.johnfactotum.Foliate use-menubar false
```

It's strange that the menubar isn't showing, though. On GNOME, it looks like this:
![image](https://user-images.githubusercontent.com/50942278/78773573-f4eb6b80-7982-11ea-881a-386da348e364.png)

**Comment by aeonian-adroit24** [comment]
Maybe it's because Pantheon is going for a consistent UI and removed the legacy GTK elements?

Anyway, got the headerbar back.
Thanks.
