### ISSUE TITLE
[Feature Request] Add options to interact with Goodreads

### ISSUE THREAD

**Issue by morealaz** [johnfactotum/foliate#283]
Hi @johnfactotum 
Again thanks for this wonderful work you done.
I wonder if we can have an option to use [goodreads](https://www.goodreads.com/) services. For example to being able to sync our reading with our goodreads account and many other things that goodread offeres!!

**Comment by johnfactotum** [comment]
Unfortunately it seems Goodreads doesn't have an API anymore. See
- https://help.goodreads.com/s/article/Does-Goodreads-support-the-use-of-APIs
- https://debugger.medium.com/goodreads-is-retiring-its-current-api-and-book-loving-developers-arent-happy-11ed764dd95.

So I don't think it's possible to fix this.

If you still have an API key or is able to use Goodreads' private APIs, you can write your own script that reads/writes data from/to Foliate's data directory (see https://github.com/johnfactotum/foliate/blob/gtk4/docs/faq.md#how-are-notes-and-bookmarks-stored).
