### ISSUE TITLE
Strange close window icon

### ISSUE THREAD

**Issue by jony0008** [johnfactotum/foliate#291]
I am using Gnome 3, and the close icon for Foliate looks strange. Is it on purpose?
![Skärmbild från 2020-04-10 12-14-05](https://user-images.githubusercontent.com/23194385/78983782-2ac85580-7b25-11ea-8b7f-6c85f5f65929.png)

**Comment by johnfactotum** [comment]
This is a Snap issue; seen for example in this thread: https://www.reddit.com/r/gnome/comments/fk7i42/weird_exit_buttons_in_gnome_characters/

**Comment by johnfactotum** [comment]
This bug has been reported here: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1861558
