### ISSUE TITLE
Snap package, rectangles instead of text 

### ISSUE THREAD

**Issue by jkrass1** [johnfactotum/foliate#292]
![Screenshot_20200410_151434](https://user-images.githubusercontent.com/9212851/78990422-11340780-7b3f-11ea-9c38-709a93ff40fd.png)

**Comment by jkrass1** [comment]
looks like this helps 

`sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
`

![Screenshot_20200410_153417](https://user-images.githubusercontent.com/9212851/78991105-d632d380-7b40-11ea-8ace-93c155bf40c5.png)

Forgot to mention, I am using Manjaro KDE

**Comment by johnfactotum** [comment]
It's a Snap issues, and looks like they're working on a fix: https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484
