### ISSUE TITLE
The program 'WebKitWebProcess' received an X Window System error.

### ISSUE THREAD

**Issue by blade1989** [johnfactotum/foliate#295]
I can't seem to load a book, anymore. I executed Foliate from the terminal and this is the error I got:

> Gtk-Message: 21:23:47.465: Failed to load module "appmenu-gtk-module"
> Gjs-Message: 21:23:47.748: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/window.js 1119]: reference to undefined property "_loading"
> Gjs-Message: 21:23:47.776: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/tts.js 33]: reference to undefined property "_epub"
> Gtk-Message: 21:23:47.843: Failed to load module "appmenu-gtk-module"
> file:///app/share/com.github.johnfactotum.Foliate/assets/epub-viewer.js:352:22: CONSOLE ERROR TypeError: undefined is not an object (evaluating 'cfiOne.path.steps')
> file:///app/share/com.github.johnfactotum.Foliate/assets/epub.js:6348:23: CONSOLE ERROR Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'this.stage.bounds')
> libEGL warning: DRI2: failed to authenticate
> 
> (WebKitWebProcess:20): Gdk-WARNING **: 21:23:48.497: The program 'WebKitWebProcess' received an X Window System error.
> This probably reflects a bug in the program.
> The error was '167'.
>   (Details: serial 191 error_code 167 request_code 151 (unknown) minor_code 21)
>   (Note to programmers: normally, X errors are reported asynchronously;
>    that is, you will receive the error a while after causing it.
>    To debug your program, run it with the GDK_SYNCHRONIZE environment
>    variable to change this behavior. You can then get a meaningful
>    backtrace from your debugger if you break on the gdk_x_error() function.)
> 

When I closed Foliate this is the error that got added:

> Gjs-Message: 21:27:01.651: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/epubView.js 558]: reference to undefined property "_dataHandlers"
> 
> (com.github.johnfactotum.Foliate:2): Gjs-WARNING **: 21:27:01.651: JS ERROR: TypeError: this._dataHandlers is undefined
> _disconnectData@resource:///com/github/johnfactotum/Foliate/js/epubView.js:558:9
> _connectData/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:552:18
> main@resource:///com/github/johnfactotum/Foliate/js/main.js:183:24
> run@resource:///org/gnome/gjs/modules/script/package.js:222:19
> @/app/bin/com.github.johnfactotum.Foliate:9:17
> 

**System info**:
---

OS: Ubuntu 18.04.4 LTS x86_64 
Kernel: 5.3.0-46-generic 
Shell: bash 4.4.20 
Resolution: 1920x1080, 1680x1050 
DE: Budgie 
WM: Mutter(Budgie) 
Theme: Arc-Dark [GTK2/3] 
Icons: Numix [GTK2/3] 
Terminal: tilix 
CPU: Intel Xeon E5-1603 0 (4) @ 2.800GHz 
GPU: NVIDIA GeForce GTX 1050 Ti 
Memory: 10284MiB / 32031MiB 

executed form `flathub`, Foliate version: `2.1.1`

**Comment by johnfactotum** [comment]
Pretty sure this is not our bug. It's probably a problem with WebKit and/or Flatpak with NVIDIA/OpenGL or some other graphics problem. Maybe we can ask @TingPing to give us some pointers.

**Comment by TingPing** [comment]
The JS errors could be yours but I'm not familiar with X issues like this sorry.

**Comment by johnfactotum** [comment]
The JS errors are mine but quite harmless. The main problem is WebKitWebProcess crashed (I presume, or at any rate not functioning).

**Comment by blade1989** [comment]
Hmm, I didn't get a notification of any of theses replies.. .

I think it was my system. I rebooted my Ubuntu, and everything worked fine again.

Thanks for taking a look at this.
