### ISSUE TITLE
Problems when using natural scrolling

### ISSUE THREAD

**Issue by ivan-tretyak** [johnfactotum/foliate#30]
When using natural scrolling there is an exchange between gestures for paging. In my opinion it is not intuitive that the next page opens with a swipe to the left. In the same epiphany, swipe to the right with two fingers, this is similar to the back button (alt + back arrow). If possible then exchange the appointment of gestures.
Fedora 30.
Install from flatpak and copr.

**Comment by johnfactotum** [comment]
How do you mean it's not intuitive?

Natural scrolling:
- Swipe right - previous page
- Swipe left - next page

This is exactly the same behavior as Epiphany and it's how it's suppose to be, no?

**Comment by ivan-tretyak** [comment]
I'm sorry... I confused something .... I did it and somehow got confused. I apologize for the trouble ...
