### ISSUE TITLE
Font size and margins, depending on the window size

### ISSUE THREAD

**Issue by ghost** [johnfactotum/foliate#303]
Hello,

The laptop I'm using have a very high screen resolution (2560x1440) and, without tweaking, reading the text on full-screen is uncomfortable, because the screen is too small.

I don't know if such a thing is possible, but maybe Foliage could have an auto-adjust button that would try to adjust the font size and page margin depending of the current size of the window.

On that note, I think defining a "text width" would be more logical than a "page margin", simply because that would be easier to tweak the font size, as the maximum text width would be fixed.

Resizing the window with fixed size margins changes the width of the text area. This isn't logical, as the text area is critical, but the margins are not, since they don't contain any text.

Best regards.

**Comment by johnfactotum** [comment]
> I don't know if such a thing is possible, but maybe Foliage could have an auto-adjust button that would try to adjust the font size and page margin depending of the current size of the window.

I suppose it's possible, but what do you propose to be the formula of such an adjustment? The text would be too big when the window is big and too small when the window is small. We can make the adjustment non-linear, but one also needs to consider each font's different metrics, the line-height, the colour scheme, and each user's display device and preference.

It doesn't really make sense to adjust font size based on window size, anyway. Adjust for _screen_ size? _Maaaybe_. But screen size doesn't change regularly, so there's really not much use for that when the user can simply adjust the size to whatever they like.

> On that note, I think defining a "text width" would be more logical than a "page margin", simply because that would be easier to tweak the font size, as the maximum text width would be fixed.
>
> Resizing the window with fixed size margins changes the width of the text area. This isn't logical, as the text area is critical, but the margins are not, since they don't contain any text.

But the text width _is_ defined -- by the window size. It wouldn't make sense for the width to not resize with the window. A max-wdith option, though, would be welcome. See #192.
