### ISSUE TITLE
Misspelling in traditional title bar mode

### ISSUE THREAD

**Issue by J-J-Chiarella** [johnfactotum/foliate#312]
Hello. There is a small misspelling in a menu entry for the traditional title bar mode.

Under `Edit`, the word "preferences" is spelled `Prefernces`.

src/ui/menuBar.ui
line 68:
`<attribute name="label" translatable="yes">Prefernces</attribute>`

**Comment by J-J-Chiarella** [comment]
Apologies, but I have never used GitHub or done a merge request. Otherwise, I'd do this, but I am busy doing a paper, cannot now learn the ins and outs of GitHub and just thought I'd note this typo before I forgot. Thank you for the program. It's been great!

**Comment by johnfactotum** [comment]
No problem! Thanks for the catch. I'll fix it right away.
