### ISSUE TITLE
Transparent header bar and invisible buttons under some GTK themes

### ISSUE THREAD

**Issue by vatula** [johnfactotum/foliate#316]
This is how Foliate flatpak flathub application on stock Clear Linux looks like alongside two other flatpak applications from flathub. Can it be possible to have a default, system theme on start?
![image](https://user-images.githubusercontent.com/450851/80191705-6e5cac80-8659-11ea-8019-0d02cad2d8d2.png)

**Comment by johnfactotum** [comment]
Some themes, like Materia, which is used by Clear Linux by default, and elementary, don't work well with Foliate's auto-hiding headerbar.

Workarounds:
- Disable "Auto-hide header bar" in the preferences
- Choose a different GTK theme

**Comment by vatula** [comment]
Okay :) I was just suggesting a neutral default behaviour for Foliate. Basically the issue is that once you start Foliate, you can't tell if there's a menu because everything is white. If you can't tell if there's a menu, you can't get to the settings of the application to change it.
