### ISSUE TITLE
Arm / Alpine builds

### ISSUE THREAD

**Issue by alexanderi96** [johnfactotum/foliate#319]
Hi do you have any plan for adding alpine / arm support? thanks

**Comment by johnfactotum** [comment]
Foliate is architecture-independent. It will run on ARM as long as you have ARM builds for `gjs` and `webkit2gtk`. Not familiar with Alpine, but it should be very easy to create a package.

**Comment by alexanderi96** [comment]
Yep, I managed to build it! I was only missing the webkit2gtk package! this ebook app is a pleasure to use on postmarketos! It seems to adapt pretty well on small screen sizes! (I tested it on a my old nexus 5, and the performance were not so bad considering the hardware!)
