### ISSUE TITLE
Can't display switching.social epub properly

### ISSUE THREAD

**Issue by SISheogorath** [johnfactotum/foliate#32]
I'm not sure why exactly it happens, but when I try to open [this book](https://www.kobo.com/de/en/ebook/the-switching-social-handbook) written by the author behind https://switching.social it was only displaying the Table of content. Which I guess you will agree, is a bit disappointing.

I could open it in other ebook reader applications and it's DRM free, so I guess it's some kind of parsing bug. I would appreciate any hint on how to help to debug the problem and look forward to see this application evolving. :slightly_smiling_face: 

According to the author it was created with Sigil, just if that helps debugging :)

**Comment by johnfactotum** [comment]
If the book's license does not allow you to share the file with me, you can help debug this yourself by going to https://futurepress.github.io/epub.js/examples/input.html and see if it works with Epub.js. If not, you might have to report a bug to them.

Note that the prev/next button on their example is currently broken. However, if you open your browser's developer tools, you should be able to use the console and run `rendition.next()` and `rendition.prev()`.

Note also that the version of Epub.js used in their example is different from the one used in Foliate. The one used in their example seems to be an older version. (it's a bit hard to tell as `EPUBJS_VERSION` only outputs `0.3` -- not very helpful at all!) The one used in Foliate is the latest release, 0.3.84, downloaded from https://cdn.jsdelivr.net/npm/epubjs/dist/epub.js, with a one line patch to temporarily fix an image sizing problem. So you might want to download `input.html` and change the `<script>` tag to point to that version and see if it works.

**Comment by johnfactotum** [comment]
Closing as this is an upstream issue and not really something that can be fixed in Foliate.
