### ISSUE TITLE
Add dependency graph

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#320]
Could you add a dependency graph [here](https://github.com/johnfactotum/foliate/network/dependencies)? Would be great to be able to quickly track dependencies for potential security issues and it'll make it easier for package maintainers.

**Comment by johnfactotum** [comment]
The dependency graph feature requires the use of package systems, but we don't use any at the moment. Still I suppose we can add a `package.json` solely for the purpose of checking dependencies.
