### ISSUE TITLE
Snap cannot run TTS

### ISSUE THREAD

**Issue by molten-steel** [johnfactotum/foliate#324]
On the Foliate snap (v2.1.1) trying to run text to speech returns a warning `GLib.SpawnError: Failed to execute child process “espeak-ng” (No such file or directory)`

**Comment by johnfactotum** [comment]
Paging @galgalesh.

**Comment by galgalesh** [comment]
Thanks for this report @molten-steel 

Foliate supports TTS using many different programs such as `espeak-ng` and `festival`. I can add one or more of them to the snap, but I'd like to make an informed decision about what to add specifically. @molten-steel Do you have any experience with this TTS software? `festival` sounds much better than `espeak-ng` to me, for example. Do you have experience with some of the voices?

Also, what language do you want to use this for?

**Comment by molten-steel** [comment]
Since the default voice isn't great, I used to run it on flatpak with mbrola using the command `espeak-ng -v mb-en1 -s 210` which gives me a better voice and allows me to set the speed.

The `male;awb` voice on flite seems good, but I'm having trouble finding a list of voices on the full version of festival, so I'm not sure if that's an option. I'd be fine with whatever festival voice you think is best, but is there a way to allow changing the speed if festival is packaged in the snap?

**Comment by molten-steel** [comment]
If I'm reading [this](http://www.cstr.ed.ac.uk/projects/festival/manual/festival_24.html) correctly, it has my favorite mbrola voice as `voice_en1_mbrola`, so I'd recommend that one.
