### ISSUE TITLE
None of my books will open in Foliate

### ISSUE THREAD

**Issue by Amandaville** [johnfactotum/foliate#325]
I tried to install the .deb package on Linux Mint but it returned the following error:

Error: Dependency is not satisfiable: gjs (>=1.52)

So I installed the Flatpak version instead.  The application opens but none of my books will open.  I have tried many different books with the same result.  Mostly epub, but I tried others as well.  The error displayed is: 

Something's Wrong
The file cannot be opened.
Open Another File...

If you need an error log of some kind, let me know where to find it and I will post it here.

**Comment by Amandaville** [comment]
![Screenshot_2020-04-30_09-36-47](https://user-images.githubusercontent.com/37563017/80666424-573d1500-8ac6-11ea-8a58-8fd78a2480cb.png)

**Comment by johnfactotum** [comment]
Can you open the terminal, run
```
G_MESSAGES_DEBUG=all flatpak run com.github.johnfactotum.Foliate &> foliate-debug.txt
```
then try to open a file. Then find `foliate-debug.txt` in your home folder and post it here.

**Comment by Amandaville** [comment]
`(flatpak run:24942): flatpak-DEBUG: No installations directory in /etc/flatpak/installations.d. Skipping
(flatpak run:24942): flatpak-DEBUG: Opening user flatpak installation at path /home/amanda/.local/share/flatpak
(flatpak run:24942): flatpak-DEBUG: Opening system flatpak installation at path /var/lib/flatpak
(flatpak run:24942): flatpak-DEBUG: Opening user flatpak installation at path /home/amanda/.local/share/flatpak
(flatpak run:24942): flatpak-DEBUG: Opening system flatpak installation at path /var/lib/flatpak
(flatpak run:24942): flatpak-DEBUG: Opening user flatpak installation at path /home/amanda/.local/share/flatpak
(flatpak run:24942): flatpak-DEBUG: Opening system flatpak installation at path /var/lib/flatpak
(flatpak run:24942): flatpak-DEBUG: Cleaning up unused container id 2358300855
(flatpak run:24942): flatpak-DEBUG: Allocated instance id 2479903838
(flatpak run:24942): flatpak-DEBUG: Document portal not available, not mounting /run/user/1000/doc
(flatpak run:24942): flatpak-DEBUG: Allowing dri access
(flatpak run:24942): flatpak-DEBUG: Allowing wayland access
(flatpak run:24942): flatpak-DEBUG: Allowing x11 access
(flatpak run:24942): flatpak2-DEBUG: bwrap --args 31 = --ro-bind /sys /sys --ro-bind /root /root --ro-bind /lib32 /lib32 --ro-bind /media /media --bind /var /var --bind /run /run --ro-bind /bin /bin --ro-bind /mnt /mnt --symlink boot/initrd.img-4.13.0-41-generic /initrd.img --ro-bind /etc /etc --ro-bind /home /home --ro-bind /usr /usr --ro-bind '/lost+found' '/lost+found' --ro-bind /proc /proc --symlink boot/vmlinuz-4.10.0-38-generic /vmlinuz.old --ro-bind /lib64 /lib64 --symlink boot/initrd.img-4.10.0-38-generic /initrd.img.old --ro-bind /opt /opt --symlink boot/vmlinuz-4.13.0-41-generic /vmlinuz --ro-bind /srv /srv --ro-bind /lib /lib --ro-bind /sbin /sbin --ro-bind /boot /boot --bind /tmp /tmp --ro-bind /cdrom /cdrom --ro-bind /dev /dev --bind /run/user/1000/.dbus-proxy/ /run/user/1000/.dbus-proxy/ --file 27 /.flatpak-info
(flatpak run:24942): flatpak2-DEBUG: bwrap --args 33 = --fd=32 'unix:abstract=/tmp/dbus-5YbiDYij91,guid=1f3b3b89d114c22d63af331d5ea9e1b6' /run/user/1000/.dbus-proxy/session-bus-proxy-DC5KJ0 --filter '--own=com.github.johnfactotum.Foliate.*' --talk=org.freedesktop.Flatpak '--call=org.freedesktop.portal.*=*' '--broadcast=org.freedesktop.portal.*=@/org/freedesktop/portal/*' 'unix:abstract=/tmp/dbus-owKlLLXaVj,guid=7a90ff2663d1bb56e3f756b75ea9e1b7' /run/user/1000/.dbus-proxy/a11y-bus-proxy-T72KJ0 --filter --sloppy-names --call=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Embed@/org/a11y/atspi/accessible/root --call=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Unembed@/org/a11y/atspi/accessible/root --call=org.a11y.atspi.Registry=org.a11y.atspi.Registry.GetRegisteredEvents@/org/a11y/atspi/registry --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.GetKeystrokeListeners@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.GetDeviceEventListeners@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.NotifyListenersSync@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.NotifyListenersAsync@/org/a11y/atspi/registry/deviceeventcontroller
(flatpak run:24942): flatpak-DEBUG: Running '/usr/lib/flatpak/flatpak-bwrap --args 31 /usr/lib/flatpak/flatpak-dbus-proxy --args=33'
(flatpak run:24942): flatpak2-DEBUG: bwrap --args 27 = --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files /usr --lock-file /usr/.ref --ro-bind /var/lib/flatpak/app/com.github.johnfactotum.Foliate/x86_64/stable/21580cd350c8e43474f27d7112e8299f0c386d07fe1617ddb95a4a05fda4a160/files /app --lock-file /app/.ref --ro-bind /var/lib/flatpak/runtime/com.github.johnfactotum.Foliate.Locale/x86_64/stable/be9f693a334d7fcba98897b9ba09245ed8aa56b1f5534e4a3708a11a1fd661fa-en-th/files /app/share/runtime/locale --tmpfs /usr/lib/x86_64-linux-gnu/GL --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform.GL.default/x86_64/19.08/ea1850468dc2940df8f6544d157688a98bce3a8460a7a4fe672c0150e48ec627/files /usr/lib/x86_64-linux-gnu/GL/default --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/19.08/dbf5bfbde30ea484b67b4caa58fb831de16df91684f53fa8619a078d45f03e24/files /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform.openh264/x86_64/2.0/15266352ca7587793d013fdb17530a24d728e09be4f4cf315dc5bf99ad4323e8/files /usr/lib/x86_64-linux-gnu/openh264 --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform.Locale/x86_64/3.36/7c7bcf1427799b69fdfdbce67e4d8ea7ec5b21c172993a120a21b7a42d69bf2e-en-th/files /usr/share/runtime/locale --bind-data 11 /run/flatpak/ld.so.conf.d/runtime-001-org.freedesktop.Platform.GL.default.conf --symlink /usr/lib/x86_64-linux-gnu/GL/default/vulkan/icd.d/radeon_icd.x86_64.json /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json --symlink /usr/lib/x86_64-linux-gnu/GL/default/vulkan/icd.d/intel_icd.x86_64.json /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json --symlink /usr/lib/x86_64-linux-gnu/GL/default/glvnd/egl_vendor.d/50_mesa.json /usr/lib/x86_64-linux-gnu/GL/glvnd/egl_vendor.d/50_mesa.json --symlink /usr/lib/x86_64-linux-gnu/GL/default/OpenCL/vendors/mesa.icd /usr/lib/x86_64-linux-gnu/GL/OpenCL/vendors/mesa.icd --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/kms_swrast_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/kms_swrast_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/r300_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/r300_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/vmwgfx_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/vmwgfx_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/r200_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/r200_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/libgallium_drv_video.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/libgallium_drv_video.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/nouveau_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/nouveau_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/swrast_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/nouveau_drv_video.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/nouveau_drv_video.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/r600_drv_video.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/r600_drv_video.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/libmesa_dri_drivers.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/libmesa_dri_drivers.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/i965_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/i965_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/libgallium_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/libgallium_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/r600_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/r600_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeon_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeon_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/virtio_gpu_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/virtio_gpu_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/i915_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/i915_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_drv_video.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_drv_video.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/iris_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/iris_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/nouveau_vieux_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/nouveau_vieux_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/d3d/d3dadapter9.so.1.0.0 /usr/lib/x86_64-linux-gnu/GL/lib/d3d/d3dadapter9.so.1.0.0 --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/d3d/d3dadapter9.so.1 /usr/lib/x86_64-linux-gnu/GL/lib/d3d/d3dadapter9.so.1 --symlink /usr/lib/x86_64-linux-gnu/GL/default/vulkan/explicit_layer.d/VkLayer_MESA_overlay.json /usr/lib/x86_64-linux-gnu/GL/vulkan/explicit_layer.d/VkLayer_MESA_overlay.json --bind-data 12 /run/flatpak/ld.so.conf.d/runtime-002-org.freedesktop.Platform.VAAPI.Intel.conf --bind-data 13 /run/flatpak/ld.so.conf.d/runtime-003-org.freedesktop.Platform.openh264.conf --unshare-pid --proc /proc --dir /tmp --dir /var/tmp --dir /run/host --dir /run/user/1000 --setenv XDG_RUNTIME_DIR /run/user/1000 --symlink ../run /var/run --ro-bind /sys/block /sys/block --ro-bind /sys/bus /sys/bus --ro-bind /sys/class /sys/class --ro-bind /sys/dev /sys/dev --ro-bind /sys/devices /sys/devices --bind-data 15 /etc/passwd --bind-data 16 /etc/group --bind-data 17 /etc/pkcs11/pkcs11.conf --ro-bind /etc/machine-id /etc/machine-id --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/krb5.conf /etc/krb5.conf --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/xml /etc/xml --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/issue /etc/issue --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/dbus-1 /etc/dbus-1 --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/ssh_config /etc/ssh_config --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/fonts /etc/fonts --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/dconf /etc/dconf --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/nsswitch.conf /etc/nsswitch.conf --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/pulse /etc/pulse --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/alsa /etc/alsa --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/xdg /etc/xdg --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/profile.d /etc/profile.d --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/services /etc/services --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/mke2fs.conf /etc/mke2fs.conf --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/ssl /etc/ssl --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/gtk-3.0 /etc/gtk-3.0 --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/rpc /etc/rpc --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/protocols /etc/protocols --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/issue.net /etc/issue.net --bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.36/b3ca798e260d6e17b5dcfc27e8303d902e03704db51e4a84cc53dbe43ff25da0/files/etc/vdpau_wrapper.cfg /etc/vdpau_wrapper.cfg --bind /var/lib/flatpak/run(gjs:2): GVFS-RemoteVolumeMonitor-DEBUG: 07:25:20.816: Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(gjs:2): GVFS-DEBUG: 07:25:20.816: cannot open directory /usr/share/gvfs/remote-volume-monitors: Error opening directory “/usr/share/gvfs/remote-volume-monitors”: No such file or directory
(gjs:2): GVFS-DEBUG: 07:25:20.826: org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

(gjs:2): GLib-GIO-DEBUG: 07:25:20.826: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
(com.github.johnfactotum.Foliate:2): GLib-GIO-DEBUG: 07:25:20.906: _g_io_module_get_default: Found default implementation keyfile (GKeyfileSettingsBackend) for ‘gsettings-backend’
(com.github.johnfactotum.Foliate:2): GLib-DEBUG: 07:25:20.936: posix_spawn avoided (fd close requested) (child_setup specified) 
Portal call failed: Failed to start command: Failed to execute child process "dict" (No such file or directory)
(com.github.johnfactotum.Foliate:2): GLib-DEBUG: 07:25:20.968: unsetenv() is not thread-safe and should not be used after threads are created
(com.github.johnfactotum.Foliate:2): GLib-DEBUG: 07:25:21.044: unsetenv() is not thread-safe and should not be used after threads are created
Gjs-Message: 07:25:21.408: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/window.js 1119]: reference to undefined property "_loading"
Gjs-Message: 07:25:21.463: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/tts.js 33]: reference to undefined property "_epub"
(com.github.johnfactotum.Foliate:2): Gtk-DEBUG: 07:25:29.356: Failed to create D-Bus proxy: Could not connect: No such file or directory`

**Comment by johnfactotum** [comment]
Just to confirm, this is the whole output, after you tried to opened a file and the error screen showed up? There's not a single `Foliate-DEBUG` message, and the error screen is shown, so that can only mean one thing: `g_file_query_info ()` failed; GLib failed to get the file's info.

Unfortunately, we don't log the GIOErrorEnum so we don't know the exact reason why the query failed. But most likely the file simply could not be found. So I think either Flatpak is not configured correctly on your system, or perhaps it's a problem like https://github.com/johnfactotum/foliate/issues/13.

**Comment by Amandaville** [comment]
Okay, then let's go back to the .deb install and see if we can get that working.  I've never seen the following error before.  If anything, there are usually dependencies listed that need to be installed.  In this case it seems to imply there is no solution.  Any help would be appreciated.

Error: Dependency is not satisfiable: gjs (>=1.52)

**Comment by johnfactotum** [comment]
I'm not sure if GJS is available on Linux Mint. They have their own fork of GJS called CJS. You can try asking the Linux Mint guys if there's a way to install GJS.

If that's not possible, you might also try running Foliate with CJS. I've never tried this before, so it might not work, but my understanding is that the current version of CJS should be compatible with GJS 1.52. To do that, I think you just have to change this line:
https://github.com/johnfactotum/foliate/blob/681c7dfe1f6c97c9d218a79d3b333cc4354e5eb6/src/meson.build#L19
Change `find_program('gjs')` to `find_program('cjs')`, then you'll have to build and install it (or build a .deb package) manually (see README.md).

**Comment by johnfactotum** [comment]
> Error: Dependency is not satisfiable: gjs (>=1.52)

I don't know what tool you're using to install the .deb (you should use `sudo apt install ./com.github.johnfactotum.foliate_2.1.1_all.deb`), but I think this messeage means the package is not available.

I would suggest that you try to fix the Flatpak install. Maybe try updating your system packages. Or ask around Linux Mint's forum. Since I have an active Foliate Flatpak install on Ubuntu 18.04, I'm fairly certain that this is a problem with Mint or your specific setup.

**Comment by Amandaville** [comment]
Okay, I don't think I'm going to spend any more time on it since I'm moving to MX Linux next week.  I'll see if I have better luck with Foliate then.

**Comment by johnfactotum** [comment]
Foliate is in the offical MX Linux repo. In fact, I think it's the first and, to date, the only Debian-based distro to have added an official package.

Anyway, thanks for reporting the issue. I will close this for now. Feel free to comment or open a new issue if you have any further information.
