### ISSUE TITLE
zech translation update

### ISSUE THREAD

**Issue by pafri** [johnfactotum/foliate#328]
Hi, I've updated the Czech translation file. Attached. Please commit it.
The previously suggested method for editing the file directly on Github is outside my competence and rights (for editing) -  it simply doesn't work for me, when clicking the file and trying to delete/add characters, it makes nothing (of course).

[cs_CS.zip](https://github.com/johnfactotum/foliate/files/4568948/cs_CS.zip)

**Comment by johnfactotum** [comment]
I've committed the changes.

> The previously suggested method for editing the file directly on Github is outside my competence and rights (for editing)

If you'd like, you can see https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request for how to create a pull request.
