### ISSUE TITLE
TTS reading continues after Foliate quits

### ISSUE THREAD

**Issue by galgalesh** [johnfactotum/foliate#330]
# Steps to reproduce

1. Configure TTS using `espeak-ng `
1. Click the TTS button on the bottom right to start reading the entire book
1. Exit Foliate

I expect the TTS sound to stop immediately. However, it continues reading until the entire page is read.

*Note: when TTS is reading the page and I click the TTS button again, it stops immediately as expected*

**Comment by johnfactotum** [comment]
Thanks for reporting this. I could've sworn that it would stop as expected but apparently I've completely neglected to do this in the 2.x branch.
