### ISSUE TITLE
Library Bug: duplicates

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#335]
When reading with Foliate:

- Duplicate entries of the epub being read can be found in the Library.

- You remove one of the duplicate epubs, then the progress and notes are deleted for all duplicate copies, not just for the one.

- This bug may related to the fact that Foliate lets the last closed window override "currently reading", which adds an extra book before closing.

(Icon View in Library doesn't even have a working menu triple dots, like the list view. But you probably know about this bug.)

**Comment by johnfactotum** [comment]
Can you provide a way to reproduce the problem?

**Comment by itprojects** [comment]
1. Open epub, by clicking on it form file browser.
2. Open "Library", you see two of the currently read epub.

![Icon View](https://user-images.githubusercontent.com/2698054/81311174-95ad7380-9074-11ea-9fb1-d843c86e9c96.png)

![List View](https://user-images.githubusercontent.com/2698054/81311181-97773700-9074-11ea-892e-aa21541a9d42.png)

**Comment by itprojects** [comment]
@johnfactotum Still a problem with Icon View (first screenshot), pressing the three dots automatically removes the book. Seem like a bug, is it a feature? To compare with the second screenshot, there you get a menu.

**Comment by johnfactotum** [comment]
The three dots indicate that its loading the cover image. Since currently that's not implemented, it's stuck with the loading icon forever. When clicking on it, it should open the book.

**Comment by itprojects** [comment]
@johnfactotum Foliate uses a rotating circular icon for file loading. Use that to avoid the confusion?

**Comment by johnfactotum** [comment]
The icon is called `image-loading-symbolid`. It's an icon specifically for indicating that an image is loading. Using spinners is technically cumbersome (need to pack a separate widget) and visually too busy.
