### ISSUE TITLE
Allow font size adjustment when using publisher fonts

### ISSUE THREAD

**Issue by HaasJona** [johnfactotum/foliate#34]
Allowing to use the the publisher fonts works fine since #15, but that also causes the font size to be whatever the publisher chose.

My suggestion would be something like this:

Rename the option to "force custom font" or something along those lines.

- If "force custom font" is enabled, do pretty much the same as it does currently if a custom font is set.
- If "force custom font" is disabled, apply font-family and font-size to `body` (or maybe `html`?), but without `!important`, so the book may override it while still being able to provide a font and size for books that don't specify them.

**Comment by johnfactotum** [comment]
Hmm, I think you've raised a very good point. I think I would rather like to keep the option labeled as "use publisher font" (there's no real semantic difference here; "use pub. font" == "don't force", and "force" == "don't use pub. font"), or "use publisher font if available", for clarity.

I think the behavior should be:
- **Mode 1:** if "use publisher font" is on, set font-family only on `body`
- **Mode 2:** if "use publisher font" is off, set font-family on everything
- Everything else, including font-size, line-height, colors, is forced, in both modes

The thing I'm unsure about is whether or not to unset `serif_font_family` and `sans_serif_font_family` in WebKit. Some books only specify either "serif" or "sans" for the whole book. More rarely, they need both. If those are unset, it would break the former situation (this is the current behavior); if not, the latter.

**Comment by HaasJona** [comment]
> Everything else, including font-size, line-height, colors, is forced, in both modes

on what? I hope headers and so on can still use different font-size, line-size and so on than the one the user sets. Especially if the epub author specifies something like `h1 {font-size: 2em}` or `h1 {font-size: 200%}`.

I think font-size, colors and so on always should be allied only to the body.

Also it would be interesting to see what calibre and so on do to apply the styles. I believe it works well in most of the cases.

**Comment by johnfactotum** [comment]
Fix commited in 462b7889325a21b1258f13f61b06c135c6415f9b.
