### ISSUE TITLE
Add split-screen mode

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#340]
Could Foliate provide an efficient way to compare different editions of the same author (or a different publisher), and to read original and translated versions in parallel? I believe this could be functionally realized with tabs as suggested in #181, however, a more elegant solution for my specific use case would be a _split-screen mode_ with two (invisible) tabs opened in the same window. Ideally, the user should be able to scroll up and down and to compare texts _within the same tab or window_.

**Comment by johnfactotum** [comment]
As I've mentioned in #181, you can already open multiple windows. So this will probably not be worked on.
