### ISSUE TITLE
Add Sponsorship button

### ISSUE THREAD

**Issue by lpan** [johnfactotum/foliate#352]
Thanks so much for making foliate! I really love the app!

I am wondering if you can add a GitHub [sponsorship button](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository) or add a Patreon or https://www.buymeacoffee.com/ link in the README. So us users can support your work :slightly_smiling_face:

**Comment by JamesSwift** [comment]
I'd donate if I knew how :-)

**Comment by digitalethics** [comment]
I think [Liberapay](https://en.liberapay.com/) and [Open Collective](https://opencollective.com/) are better solutions than the ones mentioned so far. They both seem to be less data-extractive or more privacy-oriented, thereby protecting both supporters and creators.

**Comment by TechnicallyComputers** [comment]
This app is now part of my daily workflow with no viable alternative for use on a touchscreen 2-in-1 laptop with stylus, for studying side by side with xournal++.  I would feel a lot better if I could show my appreciation and encouragement for touchscreen support and improved UX updates with donations ;)

**Comment by lpan** [comment]
![image](https://user-images.githubusercontent.com/12106903/96377316-e0f6a280-1139-11eb-9593-04d59a444cc4.png)

@johnfactotum please set up Liberapay and take our money :sob:

**Comment by johnfactotum** [comment]
I don't currently have any plans for accepting donations. If anyone would like to support this project, I would suggest supporting instead the upstream projects that Folaite depends on, namely:

- [GNOME](https://www.gnome.org/), in particular [GTK](https://gtk.org/) and [WebKitGTK](https://webkitgtk.org/)
- [Epub.js](https://github.com/futurepress/epub.js/), the library for processing and rendering EPUB files

Foliate is really just a simple program that strings these components together. As long as these projects are alive and well, anyone should be able to write an e-book reader (perhaps one that's even better than Foliate) without great difficulties.

---

WebKitGTK is, I think, particular worthy of support, for a couple of reasons:
- A browser engine is a very complex piece of technology, and requires more resources to maintain, so it could really benefit from the support.
- WebKitGTK is used everywhere where there's need for web technologies; improvements to it will help improve countless downstream projects, including web browsers, e-book viewers, e-mail clients, feed readers, markdown editors, and even [login screens](https://github.com/Antergos/web-greeter).

**Comment by mendhak** [comment]
Many thanks for your work on this @johnfactotum    
Foliate is the best reader I've encountered, and I've tried a _lot_ of them.    
I love its simplicity of configuration, and how it gets out of my way.   
I genuinely appreciate it, and enjoy using it, and hopefully you enjoy using it too!

**Comment by johnfactotum** [comment]
Fixed with fdc1103d94480a598a5441ee9db6ecdab5496ed1.
