### ISSUE TITLE
Add a way to export annotations

### ISSUE THREAD

**Issue by klorophatu** [johnfactotum/foliate#355]
The reason why I want this as a feature is because most of my notes are taken in either markdown or org-mode format, so I'd be more convenient to export my annotations and integrate it into my workflow.

**Comment by johnfactotum** [comment]
Exporting to Markdown is already available (released in 2.0.0). See https://github.com/johnfactotum/foliate/issues/180.

I'm not familiar with org-mode. What sort of formatting do you have in mind?

**Comment by klorophatu** [comment]
I can't find the export to markdown option

**Comment by johnfactotum** [comment]
Open the primary menu (F10) > Book > Export Annotations. Then you can choose from various export formats.

**Comment by klorophatu** [comment]
Ah yes literally 10 seconds before you replied, I already found it, thank you
