### ISSUE TITLE
Crash with 'toggling down object GInotifyFileMonitor that's already queued to toggle up'

### ISSUE THREAD

**Issue by emnoor** [johnfactotum/foliate#357]
Foliate crashed on page turn. Happened for the first and only time of using it for more than a month.

The output of `journalctl /usr/bin/foliate` around the time the crash happened ([full log](https://pastebin.ubuntu.com/p/DG2nMT3gxS/)):

    May 15 16:58:15 enam-laptop com.github.john[115513]: toggling down object GInotifyFileMonitor that's already queued to toggle up
    May 15 16:58:15 enam-laptop audit[115513]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 pid=115513 comm="com.github.john" exe="/usr/bin/gjs-console" sig=5 res=1

Distro: Arch Linux
`uname -a`: `Linux enam-laptop 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64 GNU/Linux`
Installed from: repository (version 2.1.1-1)

**Comment by johnfactotum** [comment]
Never seen this before. To be honest I've no idea what this is.

**Comment by emnoor** [comment]
Should I pay attention to anything else (ie other logs) if it happens again?

**Comment by johnfactotum** [comment]
It'd be nice if you can find a way to reproduce the problem. You can myabe also enable the debug messages with the env `G_MESSAGES_DEBUG=all` to see more detailed logs.

**Comment by johnfactotum** [comment]
Marking this as _not our bug_ as it needs to fixed in GJS: https://gitlab.gnome.org/GNOME/gjs/-/issues/297

**Comment by johnfactotum** [comment]
It seems this has been fixed upstream.
