### ISSUE TITLE
[Feture Request] Tracker Mitigations

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#361]
The gnome Tracker entered usage with commit 5c40ae5fe3394016ba48ef4af001aa43ca9aece5 . Would you please add a setting to "Never Use Tracker", so that systems that cannot (bug/feature) or will not (choice) use the gnome Tracker, will still be able to use Foliate?.

**Comment by johnfactotum** [comment]
It runs fine without Tracker.

**Comment by itprojects** [comment]
> It runs fine without Tracker.

Exactly!

The idea is that Foliate wouldn't check, **since it works fantastically**, _without_ any Tracker.

**Comment by johnfactotum** [comment]
Just don't install Tracker?

**Comment by itprojects** [comment]
Other apps, mistakenly depending on it, may fail and cause faults.

**Comment by johnfactotum** [comment]
If you really don't want Tracker you should either don't install it at all, or mask Tracker's systemd services.

But, well, I support it wouldn't hurt to add a setting for this.

**Comment by itprojects** [comment]
Thank You!
