### ISSUE TITLE
Recent files list is always empty

### ISSUE THREAD

**Issue by JamesSwift** [johnfactotum/foliate#362]
When I open foliate (with the open last used book option turned off), the recent files list is always empty. Is this a flatpak issue?

**Comment by johnfactotum** [comment]
Yeah, I think it's a Flatpak thing. On master, Foliate now shows recent books based on the data stored in `~/.local/share/com.github.johnfactotum.Foliate`, rather than getting that data from GTK (See https://github.com/johnfactotum/foliate/issues/119). So this is not an issue anymore.

**Comment by JamesSwift** [comment]
Great work! So when the flatpak gets updated will the recent files work as expected, or will there still be issues with accessing the data?

**Comment by johnfactotum** [comment]
Yes, it should work as expected.
