### ISSUE TITLE
Search by metadata?

### ISSUE THREAD

**Issue by mcepl** [johnfactotum/foliate#364]
E.g., I would like to find all stories written by Northumbrian among my 1058 EPub files. Could Foliate do it for me?

**Comment by johnfactotum** [comment]
Up to the latest stable version (2.1.1), it's simply a "viewer" and does not have any "library" functionalities.

With the current git master version, yes, you can search by metadata.

**Comment by mcepl** [comment]
So, when you’ll release? 211 commits since release is pretty lot.

**Comment by johnfactotum** [comment]
When it's ready™

**Comment by mcepl** [comment]
OK, so I f****k off, when you so kindly ask.
