### ISSUE TITLE
[Feature Request] Mouse wheel to change pages in paginated mode

### ISSUE THREAD

**Issue by egazz** [johnfactotum/foliate#37]
Subject says it all pretty much.  I find I prefer to read in paginated mode due to the dual columns, but I don't like having to use the keyboard or the arrows at the bottom to change pages.  It would be nice if the mouse wheel could change pages in this mode.

**Comment by johnfactotum** [comment]
This should already be available in 1.1.0. Which version are you using?

**Comment by egazz** [comment]
I noticed that on the newest releases, and I think somehow I just missed the update or something when I ran it on my other machine.  It's updated and working on this one, so sounds like no issue!
