### ISSUE TITLE
Support Haiku OS

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#371]
I occasionally use operating systems that are not Linux-based and I run [Haiku OS](https://www.haiku-os.org/) on an older testing laptop. Haiku OS is a very fascinating project targeting personal or desktop computing which would match the user group that Foliate appeals to. Now that porting GTK to Haiku OS is in progress, it should be possible to make Foliate available via [HaikuDepot](https://www.haiku-os.org/docs/userguide/en/applications/haikudepot.html). This is by no means an urgent request but it would be great to be able to run a best-of-class application such as Foliate on Haiku OS and help make it known to more people.

**Comment by johnfactotum** [comment]
Foliate is certainly not limited to Linux. People have already packaged it for several BSD systems.

But this is more of an issue for Haiku and related projects. If there's any changes required in Foliate itself I would be happy to oblige.
