### ISSUE TITLE
Add help button and allow easy way to toggle keyboard shortcuts as cheat-sheet

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#374]
This is a request for several interrelated issues aimed at making Foliate more accessible to non-technical users and for introducing new Foliate features to users not following GitHub. 

- [ ] Add <kbd>Ctrl</kbd>+<kbd>?</kbd> to toggle Keyboard Shortcuts overview. This keyboard shortcut is intuitive and easy to remember and kind of a _meta_ shortcut or cheat-sheet to learn the others. 
~~It would be nice if the cheat-sheet slides down from the header bar and docks onto it (with no additional animation other than a very subtle slide to keep it minimalist and harmonious with the _sidebar_ slide*) to feel more responsive and integrated rather than just appearing as a centered window on top of the main window.~~
- [ ] Visually this could be complemented by a help button (hand or question mark icon) in the header bar which toggles the cheat sheet for those navigating by mouse or a combination of mouse and keyboard.
- [ ] Command-line options could be listed in a separate tab next to the keyboard shortcuts cheat-sheet. 
- [ ] [Wiki](https://github.com/johnfactotum/foliate/wiki) could be listed in a separate tab.
- [ ] GitHub changelog or even better a quick summary of new Foliate features could be listed in a separate _News_ tab. The idea for this stems from the _What's New_ feature in the Firefox menu which is extremely helpful for those not following changelogs and blogs to be quickly and efficiently introduced to new features. The latest Firefox releases even comes with a temporary icon at the right side of the Add-ons tray area that some may have noticed. Clicking on _What's New_ triggers the content but not the icon itself, otherwise I would have included a screenshot of how it looks like. I'm not entirely sure if it makes sense to combine _help_ and _news_ features from a functional point of view but they do feel related as learning about new features is certainly helpful.

~~*Currently the sidebar mode just kind of "pops" in without any "slide" effect. I like Foliate for its minimalist design without unnecessary animations. The only place where I'd wish for a very subtle slide effect would be the sidebar (left-right) and toggling the keyboard shortcuts (top-down).~~ [Moved to separate issue in #388]

**Comment by johnfactotum** [comment]
> Add Ctrl+? to toggle Keyboard Shortcuts overview.

<kbd>Ctrl</kbd>+<kbd>?</kbd> is already there, although it isn't listed in the list of keyboard shortcuts.

> It would be nice if the cheat-sheet slides down from the header bar and docks onto it (with no additional animation other than a very subtle slide to keep it minimalist and harmonious with the sidebar slide*) to feel more responsive and integrated rather than just appearing as a centered window on top of the main window.

As I've mentioned in https://github.com/johnfactotum/foliate/issues/369#issuecomment-631538955, the shortcuts window is a standard GTK widget. You might want to checkout [the GTK issues](https://gitlab.gnome.org/GNOME/gtk/-/issues?label_name%5B%5D=GtkShortcutsWindow), in particular ["Keyboard shortcut windows design updates"](https://gitlab.gnome.org/GNOME/gtk/issues/1176).

>  Visually this could be complemented by a help button (hand or question mark icon) in the header bar which toggles the cheat sheet for those navigating by mouse or a combination of mouse and keyboard.

The space in headerbar is too precious to give to a help button.

> Command-line options could be listed in a separate tab next to the keyboard shortcuts cheat-sheet.
> Wiki could be listed in a separate tab.

The shortcuts window doesn't support these. These should be implemented as proper help documentations that can be opened by [Yelp](https://wiki.gnome.org/Apps/Yelp).

> GitHub changelog or even better a quick summary of new Foliate features could be listed in a separate News tab.

We already ship an AppStream AppData file containing the full changelog. Apps like [GNOME Software](https://wiki.gnome.org/Apps/Software) support reading this information, although currently I think it only shows the release notes when you're upgrading. You might want to open an issue with GNOME Software. See also this GTK issue: ["about-dialogs: Show information from AppData, link to Software"](https://gitlab.gnome.org/GNOME/gtk/-/issues/1129).

It might be possible for Foliate to read and present its own AppData manually. But preferably this should be done automatically and consistently across GTK apps.

> Currently the sidebar mode just kind of "pops" in without any "slide" effect.

I don't think this is currently possible with GTK. It is possible with `libdazzle`. I guess we can use `libdazzle`, but I'll want to make it optional, like the way we use `libhandy` at the moment; I don't want to hard-depend on a library just to add a few animations.

**Comment by digitalethics** [comment]
> The space in headerbar is too precious to give to a help button.

I will read up a bit more about GNOME Human Interface Guidelines (I'm currently on Plasma but with a preference for GNOME applications). I agree that keeping the overall minimalist design is a good thing to do but it can easily lead to convoluted menus and much longer cursor travel distances. 

I think a help button is nicely integrated in Setzer: 

![setzer_togglehelp](https://user-images.githubusercontent.com/57445091/83297548-10405d80-a1f3-11ea-884e-4978ac3043a8.gif)

**Comment by johnfactotum** [comment]
The help button in Setzer shows documentations for LaTex, which is complex and often helpful to refer to while editing a document. On the other hand, Foliate doesn't have any extensive features and documentations, and also no need to keep referring to it when reading a book, so it doesn't make sense to add a help button.

I'll close this issue for now, since the most of suggestions conflict with and requires changes in GNOME and GTK design.
