### ISSUE TITLE
Add underline, squiggly and strikethrough as additional annotation options

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#378]
It would be nice to have _underline_ (straight line), _squiggly_ (jagged, zig-zagged line) and _strikethrough_ as additional annotation options next to _highlight_.

**Comment by johnfactotum** [comment]
Underlining is supported by Epub.js, however I'm abusing it to highlight search results, so it's not currently available. The others are not supported by Epub.js, which actually depends a separate package, [marks-pane](https://www.npmjs.com/package/marks-pane) for adding highlighting.

**Comment by azzamsa** [comment]
> Underlining is supported by Epub.js, however I'm abusing it to highlight search results, so it's not currently available

So, is this will stays the same. Or there will be underline annotation feature in the future?

Thanks for Foliate :heart:

**Comment by johnfactotum** [comment]
Underlining is already added in the `gtk4` branch, and squiggly is also in the [new renderer](https://github.com/johnfactotum/foliate/issues/962) now with https://github.com/johnfactotum/foliate-js/commit/c7a4f5ef462bf05252b2d02ebd3e0f7029015124.

Worth noting that search results aren't currently highlighted in the `gtk4` branch (only the active result is selected). But as the new renderer is more flexible than Epub.js it shouldn't be too hard to implement.
