### ISSUE TITLE
Make "Turn page on tap" inactive by default?

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#379]
When annotating text by mouse clicks, this very often inadvertently leads to page turns. I would prefer to have a default where the mouse wheel turns pages while clicking into the text does _not_. In order to accommodate those who annotate less but prefer to click to prompt page turns, there should be an option to manually enable page turns when clicking into the text.

**Comment by johnfactotum** [comment]
There's already an option to disable it.

**Comment by digitalethics** [comment]
> There's already an option to disable it.

Just saw it, thanks! Could it be named "Turn page on tap or click" and be rendered inactive by default?

**Comment by johnfactotum** [comment]
It needs be on by default, unless turning it off doesn't turn off "tap on the middle of the page to show/hide headerbar and navbar".

"Tap on the middle of the page to show/hide headerbar and navbar" will always be enabled by default, otherwise it's impossible to use headerbar and navbar without a mouse pointer.

**Comment by digitalethics** [comment]
> It needs be on by default, unless turning it off doesn't turn off "tap on the middle of the page to show/hide headerbar and navbar".

Is it technically possible to decouple these?

**Comment by johnfactotum** [comment]
> Is it technically possible to decouple these?

Yes. Technically, it's trivial. But design-wise, I'd rather not add a separate option for that. We can probably add some way to choose different layouts for the tapping, like the Kobo:
![image](https://user-images.githubusercontent.com/50942278/68356947-b0298300-010b-11ea-9b75-7dcb4747aa00.png)
And there'll be one option for completely disabling tapping, and one where the whole screen is mapped to "menu" (show headerbar and navbar).

**Comment by johnfactotum** [comment]
In the gtk4 branch, there's no "turn page on tap" anymore. It should still be possible to tap the header and footer area to get the headerbar and the navbar to show. So I think this can be closed now.
