### ISSUE TITLE
Add hand tool

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#380]
It would be nice to have a _hand_ tool. Activating it (via a button or shortcut, ideally both to be navigation-agnostic as much as possible) should allow click-and-scroll action through an ebook without any text markings. Secondly, clicking previously highlighted text should trigger the display of start and end pointers. Dragging these pointers would allow to modify the previously highlighted text area.

**Comment by johnfactotum** [comment]
Dragging will probably require some extensive modifications to Epub.js.

Selection handles would be nice, but it doesn't have anything with dragging, and it's also not easy to implement. For starters I don't even know how to get the _non_-rectangular area of the selected text. Can probably look at the code for [marks-pane](https://github.com/fchasen/marks).

**Comment by digitalethics** [comment]
Would [rehype-annotate](https://github.com/baldurbjarnason/rehype-annotate) be useful?

**Comment by johnfactotum** [comment]
I'm going to close this as _wontfix_ because a hand tool would probably require extensive modification of Epub.js and it's not clear how a hand tool would be useful.
