### ISSUE TITLE
Unable to scroll to the very bottom

### ISSUE THREAD

**Issue by JamesSwift** [johnfactotum/foliate#384]
I discovered today that I was unable to scroll to the very bottom of the document with certain text settings:

Spacing: 1.45 and above
Font Size: Serif 14

I found that reducing the spacing made the bottom accessible. If you go too far a gap appears at the bottom. I'm running a build form master (yesterday).

**Comment by johnfactotum** [comment]
Which layout are you using? Does it happen only with some books? Can you post a screenshot?

Sometimes Epub.js doesn't calculate the dimensions correctly. Generally it's more problematic with the continuous scrolled layout.

Perhaps similar or related to https://github.com/johnfactotum/foliate/issues/285.

**Comment by JamesSwift** [comment]
I'm using the scrolled layout. It happens with all ebooks that I have tested. If you alter the spacing you can see it in real time, but it seems that whatever spacing you set it to, when you go to a different page then come back, it chops off the same amount.

![deepin-screen-recorder_com github johnfactotum Foliate_20200525112316](https://user-images.githubusercontent.com/2080205/82804525-5bb4dd80-9e7a-11ea-9d29-b7a7fae160d3.gif)

**Comment by johnfactotum** [comment]
I think this a regression in Epub.js introduced by https://github.com/futurepress/epub.js/commit/7001f86eda8858c2dfd3ee72ae73f50265c20a52.

The problem can be fixed reversing this bit of that commit:

```diff
diff --git a/src/assets/epub.js b/src/assets/epub.js
index d5d46dd..9651a04 100644
--- a/src/assets/epub.js
+++ b/src/assets/epub.js
@@ -4335,6 +4335,10 @@ var Contents = function () {
 				height += border.height;
 			}
 
+			if (height && rect.top) {
+				height += rect.top;
+			}
+
 			return Math.round(height);
 		}
 ```

The bottom is no longer cut off, but it does cause some slight weirdness with vertical text books where, when at the end of a section and going to the next section, the page moves up instead of going to the next section.

**Comment by JamesSwift** [comment]
Yes, I can confirm that applying that patch fixes the issue. What's the plan then?

**Comment by johnfactotum** [comment]
I opened an issue upstream: https://github.com/futurepress/epub.js/issues/1065

**Comment by johnfactotum** [comment]
This has been fixed in Epub.js 0.3.88.
