### ISSUE TITLE
Hanging on start

### ISSUE THREAD

**Issue by chunis** [johnfactotum/foliate#385]
I've just got this issue today, in fact it's just the same as [#322](https://github.com/johnfactotum/foliate/issues/322), but looks no useful solution for me from that thread.
I really like Foliate, and I'd like to bring it back. So any suggestion would be welcome.

I installed Foliate about 2 weeks ago in my Debian Sid, and it works all right. But today it just showed a blank screen trying to load a book. Per #322, this is not a bug about Foliate, but some environment changing of my OS resulting this, so I checked my apt history, and I found I've installed just 2 software suits recently: **kicad** and **arduino**.

My error logs are:
```
Gjs-Message: 15:42:28.825: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/window.js 1119]: reference to undefined property "_loading"
Gjs-Message: 15:42:28.849: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/tts.js 33]: reference to undefined property "_epub"
(process:6924): GLib-GIO-DEBUG: 15:42:28.911: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ?gio-vfs?

(com.github.johnfactotum.Foliate:6906): Gjs-WARNING **: 15:42:29.095: JS ERROR: TypeError: jsResult.get_js_value is not a function
```

And my newly installed packages including:

Commandline: apt install kicad
Install: libocct-ocaf-7.4:amd64 (7.4.1+dfsg1-2, automatic), libocct-data-exchange-7.4:amd64 (7.4.1+dfsg1-2, automatic), libocct-visualization-7.4:amd64 (7.4.1+dfsg1-2, automatic), libocct-modeling-algorithms-7.4:amd64 (7.4.1+dfsg1-2, automatic), libocct-foundation-7.4:amd64 (7.4.1+dfsg1-2, automatic), libocct-modeling-data-7.4:amd64 (7.4.1+dfsg1-2, automatic)
Upgrade: kicad:amd64 (5.1.5+dfsg1-2+b1, 5.1.6~rc1+dfsg1-1+b1)
Remove: libocct-ocaf-7.3:amd64 (7.3.3+dfsg1-1), libocct-data-exchange-7.3:amd64 (7.3.3+dfsg1-1), libocct-visualization-7.3:amd64 (7.3.3+dfsg1-1), libocct-modeling-algorithms-7.3:amd64 (7.3.3+dfsg1-1), libocct-foundation-7.3:amd64 (7.3.3+dfsg1-1), libocct-modeling-data-7.3:amd64 (7.3.3+dfsg1-1)

Commandline: apt install arduino
Install: binutils-avr:amd64 (2.26.20160125+Atmel3.6.2-1+b1, automatic), avr-libc:amd64 (1:2.0.0+Atmel3.6.1-2, automatic), gcc-avr:amd64 (1:5.4.0+Atmel3.6.1-2+b1, automatic), avrdude:amd64 (6.3-20171130+svn1429-2+b1, automatic), libjna-jni:amd64 (4.5.2-2, automatic), libjna-java:amd64 (4.5.2-2, automatic), extra-xdg-menus:amd64 (1.0-4, automatic), arduino-core:amd64 (2:1.0.5+dfsg2-4.1, automatic), librxtx-java:amd64 (2.2pre2+dfsg1-2, automatic), arduino:amd64 (2:1.0.5+dfsg2-4.1)
```
Thanks in advance.

**Comment by chunis** [comment]
I just resolved this issue by installed **sudo apt install gir1.2-webkit2-4.0**.
Don't know  why it is needed now but not 2 weeks ago when Foliate run all right then; maybe this package is changed by some reason.
Anyway, hope my solution is useful for others with this same issue. :-)

**Comment by johnfactotum** [comment]
`get_js_value is not a function` looks like the same problem as https://github.com/johnfactotum/foliate/issues/149.

In general, getting stuck at the spinner means either
- there's something wrong with the WebKit WebView, which is usually something wrong in the setup and not our bug, or
- there's some error when opening the book that stopped Epub.js for some reaso, which could be our bug; previously, one was caused by applying styles before the rendering was ready.

I should also probably clarify the GI packages' names for Debian/Ubuntu based systems.
