### ISSUE TITLE
Bottom bar does not properly correspond to mouse wheel 

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#386]
When clicking onto the bottom bar to navigate to different positions, the page positions change accordingly. When using the mouse wheel to scroll, the bottom bar indicates visual change without the page positions changing. 

See also: 

![bottombar](https://user-images.githubusercontent.com/57445091/82885311-4c4e9680-9f45-11ea-952e-1ffcf02c6c25.gif)

**Comment by johnfactotum** [comment]
This is known (since even before the first release). It only respond to button release event, and not wheel or keyboard events. It's not ideal, but we can't simply connect to the `value-changed` signal, and connecting to `button-release-event` was the easiest workaround.

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.
