### ISSUE TITLE
no hyphenation in russian epub and fb2

### ISSUE THREAD

**Issue by wenzezlaus** [johnfactotum/foliate#387]
I have hyphen-en and hyphen-ru installed and auto-hyphenation turned on. However, there is no hyphenation in any russian epub and fb2 book and in any english fb2 book.

**Comment by johnfactotum** [comment]
There are a number of possibilities here:
- Are you using Flatpak or Snap? Sandboxed applications don't have access to the hyphenation rules on the host system.
- The language must be set correctly in the book. Open "About This Book" (Ctrl+I) to see the book's language. It must be a valid
- The hyphenation uses CSS hyphenation. If the book's stylesheet sets `-webkit-hyphens` to `none` or `manual`, then it won't have any auto hyphens.
- Does CSS hyphenation work in Epiphany or anything that uses WebKitGTK? If not, then it's probably a problem with the hyphen package or WebKitGTK or how they are built/setup. On Arch Linux, I've installed the `hyphen-ru` package from the AUR and I still don't get hyphenation for Russian. However I have `hyphen-en` and `hyphen-fr` installed from `extra` and both English and French hyphenation are working fine for EPUB and FB2 books.

**Comment by wenzezlaus** [comment]
-- foliate is built from git sources;
-- language is set correctly is the books;
-- -webkit-hyphens is not set in the books;
-- I have no WebKitGTK-based browsers, sorry.
I used hyphen-ru package from AUR too. Now I examined it and found that VERY old hyphenation table was used (with KOI-8 encoding!!!). I got deb package from ubuntu (https://www.ubuntuupdates.org/package/core/focal/main/base/hyphen-ru), replaced  /usr/share/hyphen/hyph_ru_RU.dic and -- voila -- hyphenation works fine.
Thank you!

**Comment by YaLTeR** [comment]
> Now I examined it and found that VERY old hyphenation table was used (with KOI-8 encoding!!!). I got deb package from ubuntu (https://www.ubuntuupdates.org/package/core/focal/main/base/hyphen-ru), replaced /usr/share/hyphen/hyph_ru_RU.dic and -- voila -- hyphenation works fine.

Thank you very much, I just used this to fix hyphenation on my Fedora system.

**Comment by YaLTeR** [comment]
I also made an issue to get the fixed file into the freedesktop Flatpak runtime: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1146
