### ISSUE TITLE
flatpack-info: read-only file system

### ISSUE THREAD

**Issue by ngirard** [johnfactotum/foliate#393]
Using latest 2.2.0 version from the pre-compiled package on Ubuntu 20.04.
Starting Foliate leads to a blank page with spinning cursor and the following error message:
```
bwrap: Can't create file at /.flatpak-info: Read-only file system
```

**Comment by johnfactotum** [comment]
WebKit sandboxing was enabled in 23b6b031b81b0fde481ff4ec646ba72365c71fb2. It seems that it might cause problems in some situations? Googling leads to this bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1781631, but it seems that no one knows why it happens.

As a workaround you can try setting `WEBKIT_FORCE_SANDBOX=0` to disable the sandbox (use `WEBKIT_FORCE_SANDBOX=0 com.github.johnfactotum.Foliate` to launch Foliate).

**Comment by ngirard** [comment]
Good catch John, setting the variable allowed Foliate to work properly.

Would it be possible to propagate this fix to a new package ?

Also congrats for the new library view, it's awesome !

**Comment by johnfactotum** [comment]
Ideally we'd want to fix the issue rather than disabling the sandbox. But if lots of people are having issues I guess it should be turned off by default.

**Comment by ngirard** [comment]
Hey @johnfactotum,

I'm about to bring an Ubuntu-based laptop to its owner, and I wish to have Foliate 2.2 installed on it.
What would you advice me to do for a temporary fix ?
To add a `export WEBKIT_FORCE_SANDBOX=0` to the user `bashrc` ? Or to add it to the `foliate.desktop` file ?

**Comment by johnfactotum** [comment]
> To add a export WEBKIT_FORCE_SANDBOX=0 to the user bashrc ?

This will disable sandboxing for all WebKit processes on the system. Don't do that unless you're also having problems with other WebKit apps.

> Or to add it to the foliate.desktop file ?

I think that's probably the best workaround for now.

**Comment by johnfactotum** [comment]
It seems this has been fixed upstream: https://bugs.webkit.org/show_bug.cgi?id=202880
