### ISSUE TITLE
Keep OPDS detail views in the main window

### ISSUE THREAD

**Issue by bertob** [johnfactotum/foliate#403]
Currently clicking the "Open" button on a section in the Catalogs view opens a second window.

![image](https://user-images.githubusercontent.com/1908896/83306236-7da7ba80-a202-11ea-87ff-f3ef9a5402aa.png)

This is a bit confusing, and I think an in-window sub-view with a back button would work better.

**Comment by digitalethics** [comment]
I was about to make the same suggestion. Currently, this creates navigational difficulties for users as many windows need to be brought into overview mode to keep track of or switch between them. I know that windowing is a work in [progress](https://github.com/johnfactotum/foliate/projects/2#card-38780836) and maybe you already have this on the road map.

**Comment by digitalethics** [comment]
@johnfactotum Thanks a lot for the changes to the navigation. They are much appreciated! It now already feels much more integrated than before. Your quick release processes also allow for more iterative feedback without having to build the application from source.

I'm just a bit unsure whether @bertob meant the same as I did with the "sub-view". Here's my interpretation: I think it would even be better if the "in-window sub-view" is actually a _sub-view_ and not just a _view_. For this to be realized the _main view-switcher_ buttons should always remain visible even when navigating deeper into the OPDS catalogues. I think a user should never feel "stranded" as to where they are in the navigational tree and be able to switch between main components even without having to click a _back_ button. Switching between the main components (library, catalog, viewer/reader) should also "remember" the exact position in the navigational tree (e.g. the OPDS catalogues) _if_ main components were switched without having pressed the _back_ button.

**Comment by digitalethics** [comment]
Only discovered this just now: 

![hiddennavigation](https://user-images.githubusercontent.com/57445091/85122564-0b396180-b227-11ea-863f-1a408236278e.png)

I think navigational elements should not be hidden away from the view of the user.
