### ISSUE TITLE
Make OPDS book details popover a dialog?

### ISSUE THREAD

**Issue by bertob** [johnfactotum/foliate#404]
The details popovers in the OPDS views have a lot of content, and scroll in most cases, making them feel a bit cramped. Perhaps a dialog would be a better fit here?

![image](https://user-images.githubusercontent.com/1908896/83307245-944f1100-a204-11ea-956c-9af73f1ee3a6.png)

**Comment by johnfactotum** [comment]
Yeah, especially when the OPDS feed provides "full entries", like https://www.feedbooks.com/book/45.atom, in which case it should open the full entry, which can often contain additional links to related books.
