### ISSUE TITLE
 Library loses initial file location when duplicate entry added from different location

### ISSUE THREAD

**Issue by GeoS-gh** [johnfactotum/foliate#406]
Using Foliate 2.2.0, I added a bunch of ePub books to the library.  I then copied one of these books (let's say it's at ~/mybook.epub) to a different location on the filesystem and used the file explorer to open this new file (let's say it's at ~/Documents/mybook.epub) in Foliate.  It opened fine and I advanced a few pages then closed the application.

I then deleted ~/Documents/mybook.epub and re-opened Foliate, which presented the 'file not found' error.  All fine and dandy so far.  However, on returning to the library to open the entry for ~/mybook.epub, I found that the displayed progress was that of the now-deleted ~/Documents/mybook.epub and attempting to open the entry presented the 'file not found' error.

EXPECTED BEHAVIOUR: Opening a file from the file explorer should not alter an existing (or add a new) library entry.  Furthermore, explicitly adding duplicate files to the library should create duplicate entries, perhaps appended with an integer.

ACTUAL BEHAVIOUR: It appears that the library replaces the original entry when opening another book which shares the same filename and metadata.  

Hope this is helpful.  Excellent program.  Much appreciated.

**Comment by johnfactotum** [comment]
Foliate does not support "duplicate entries". The file location is only for convenience -- for opening the book from the library view. For all other purposes, Foliate rely on the unique identifier of the book. If you move a book to another location, Foliate still recognizes it as the same book.

**Comment by GeoS-gh** [comment]
Ah, I see.  It's more of a 'quick access' feature.  I guess I was expecting the library to act more like GNOME Videos/Totem which appears to rely on a file's location as its unique identifier (whilst also keeping track of a file when it's renamed or moved).

I wonder whether the term 'library' is less appropriate than, say, 'recent reads'?  Maybe I'm too accustomed to the Rhythmbox library concept where the application aggregates files in given locations and continues to monitor those locations for changes.

Keep up the good work.
