### ISSUE TITLE
Need a function to control the same book to be opened only once

### ISSUE THREAD

**Issue by tony2038** [johnfactotum/foliate#408]
The library function is good, but there is a disadvantage. Clicking on an already opened book will open it in a new window. Many times, you will open many windows in the same book without knowing it, which is very inconvenient for use. Closing different windows of the same book can also cause confusion in reading progress.

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.
