### ISSUE TITLE
Declare libhandy version to import

### ISSUE THREAD

**Issue by shibotto** [johnfactotum/foliate#411]
Recently libhandy released version [0.80.0](https://gitlab.gnome.org/GNOME/libhandy/-/releases#v0.80.0), bumping its API to 1. I have both on my system, resulting in:

```
shiba ~ > ls /usr/lib64/girepository-1.0/Handy-*
/usr/lib64/girepository-1.0/Handy-0.0.typelib
/usr/lib64/girepository-1.0/Handy-1.typelib
```

This creates confusion in Foliate, ending up importing version 1 and crashing:

```
shiba ~ > foliate
Gjs-Message: 20:49:16.654: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 25]: Requiring Handy but it has 2 versions available; use imports.gi.versions to pick one

(com.github.johnfactotum.Foliate:7721): Gjs-WARNING **: 20:49:16.654: JS ERROR: TypeError: Handy.init is not a function
@resource:///com/github/johnfactotum/Foliate/js/main.js:26:18
@/usr/bin/foliate:9:1


(com.github.johnfactotum.Foliate:7721): Gjs-CRITICAL **: 20:49:16.654: Script /usr/bin/foliate threw an exception
```

Explicitly telling gi to import version 0.0 should solve the issue.

**Comment by johnfactotum** [comment]
I wonder if it's possible to specify 0.0 _or_ 1, since Foliate can run with 1 without any problems, apart from calling `Handy.init()` which isn't needed for 1.
