### ISSUE TITLE
Last update (2.2.0) stops rendering some fonts

### ISSUE THREAD

**Issue by gtms** [johnfactotum/foliate#413]
Some fonts that were rendered beautifully by foliate in version 2.0.0, such like Garamond Premier Pro (Adobe, otf) and Minion Pro (Adobe, otf), are now rendered as the default sans serif font since update to version 2.2.0 (see attached).
![foliate](https://user-images.githubusercontent.com/1262765/83358215-efe6df00-a369-11ea-8a59-45fd19b04253.png)

**Comment by johnfactotum** [comment]
Okay, but can you provide a screenshot with 2.0.0? I don't think anything was changed about fonts since 2.0.0.

Or even better, use git bisect and find the exact commit that caused this.

**Comment by gtms** [comment]
Hi, thanks for the reply. I haven't had the time to look at repo changes or to do a git bisect, but here is a screenshot of the same content as above with version 2.0.0. Strange as it seems, Garamond Premier Pro is correctly rendered here.

![foliate-redux](https://user-images.githubusercontent.com/1262765/83448087-5858bd80-a449-11ea-8c9a-fadd83f46e2e.png)

I'll keep adding to this thread if I can come up with more information.

**Comment by gtms** [comment]
So I ran a git bisect and found the commit that caused the issue (see below). Apparently sandboxing the WebKit processes messes up with font rendering?

Hope that helps

```
Head:     b5a1bd6 FB2: close tags
Tags:     2.1.1 (273), 2.2.0 (11)

23b6b031b81b0fde481ff4ec646ba72365c71fb2 is the first bad commit
commit 23b6b031b81b0fde481ff4ec646ba72365c71fb2
Author: John Factotum <50942278+johnfactotum@users.noreply.github.com>
Date:   Thu May 28 13:16:44 2020 +0800
    Sandbox WebKit processes
    
    Also disable a bunch things in WebKit settings, like auto-play,
    fullscreen (which doesn't work properly anyway due to something in
    Epub.js, I think)
 src/epubView.js | 11 +++++++++++
 src/main.js     |  5 ++++-
 2 files changed, 15 insertions(+), 1 deletion(-)

Bisect Rest (1)
23b6b03 * bad Sandbox WebKit processes

Bisect Log:
git bisect start '2.2.0' '2.0.0'
eca3aa7 bad Workaround for text being cut off in scrolled layouts
01d32d6 good Release 2.0.0

git bisect good 441006feb257ab8ab6d90ed3fe4e0e07247d6c96
441006f good Library: generate a cover when a book doesn't have one

git bisect good b4d234dc055331f016621bd7191e447ceeed80f5
b4d234d good Allow the same types as opening when adding books

git bisect good 7635b339866ddf9509d35b40ea6b9755e7f92089
7635b33 good Make locations popover available when locations aren't ready

git bisect good c7ca0696bd24bb9e4a3480b54f14b9158f8663ff
c7ca069 good Update Chinese and Spanish translations (#382)

git bisect bad 23b6b031b81b0fde481ff4ec646ba72365c71fb2
23b6b03 bad Sandbox WebKit processes

git bisect good 81db50e862e5d12a44d290a9928a1d42c64cf5ff
81db50e good OPDS: trim everything

git bisect good c7443db1482495f693e6d194d2713b0638cf6ff3
c7443db good Update translations

git bisect good b5a1bd65c7c27c64ac909ede1792a6f0953b0faa
b5a1bd6 good FB2: close tags

git bisect good b5a1bd65c7c27c64ac909ede1792a6f0953b0faa
# first bad commit: [23b6b031b81b0fde481ff4ec646ba72365c71fb2] Sandbox WebKit processes
# good: [b5a1bd65c7c27c64ac909ede1792a6f0953b0faa] FB2: close tags
# first bad commit: [23b6b031b81b0fde481ff4ec646ba72365c71fb2] Sandbox WebKit processes

```

**Comment by johnfactotum** [comment]
Hmm. So does the font work correctly if you run 2.2.0 with `WEBKIT_FORCE_SANDBOX=0`?

**Comment by gtms** [comment]
That is correct. With version 2.2.0,

`WEBKIT_FORCE_SANDBOX=0 ./run/bin/com.github.johnfactotum.Foliate`

will render fonts properly.

Let me know if you want me to test a commit to fix this.

**Comment by johnfactotum** [comment]
Kind of odd that sandboxing is breaking fonts. Can you also reproduce this in Epiphany, which I think also has the sandbox enabled by default? If so it's probably a WebKitGTK bug, and you should open an issue at https://bugs.webkit.org/ (prefix the issue title with "[GTK]").

I guess we'll provide an option to disable sandbox.

**Comment by gtms** [comment]
Yes, the same rendering issue appears in Epiphany as well—most likely a problem with webkit.
I'll try to follow up with them, with a link to this thread.

Meanwhile, I'll close this issue once you release the patch with the option to disable the sandbox. Thanks for helping me debug this.

**Comment by apandada1** [comment]
@gtms Does this issue still exist?

**Comment by johnfactotum** [comment]
WebKitGTK is planning on removing the option all together: https://bugs.webkit.org/show_bug.cgi?id=220117. So we probably should not add an option for it. Setting an environment variable seems good enough a workaround for these kind of issues.
