### ISSUE TITLE
On HiDPI, library covers display at lower resolution

### ISSUE THREAD

**Issue by AlicesReflexion** [johnfactotum/foliate#414]
As seen in this screenshot. Covers are rendered according to the number of virtual pixels rather than physical pixels, then upscaled. The result looks blurry.

![image](https://user-images.githubusercontent.com/6933425/83359200-5a822580-a33e-11ea-8a5d-61ffa1535b4b.png)

This is version 2.2.0, running on Fedora 32. This is an rpm installed from a repo, not a flatpak.

**Comment by johnfactotum** [comment]
Fixed with 7c299a6d4b778fd06d16a513224820e2c4e28821. Unfortunately, cover images were saved at 120px so will still look blurry; open or adding the books again will update the covers to 256px.
