### ISSUE TITLE
Epub Right to left fixed layout navigation cannot turn to next page when in landscape mode

### ISSUE THREAD

**Issue by hyhchan** [johnfactotum/foliate#415]
When reading fixed layout epub that progress from right to left in the landscape mode, the navigation to advance to the next page doesn't work. Pressing right arrow will go back to previous page, and pressing left arrow has no effect. Portrait mode (showing only one page) works.

In the previous version (2.1.2) the navigation in landscape mode works but pressing right arrow will advance while pressing left arrow will go back to previous page (looks like the progression direction was ignored). 

Further, when jumping to a particular page (say by entering the page number or selecting a chapter mark that links to an odd number page) the page will always shown on the right side. And then the pages afterwards will be shifted by one page. On Apple books if the chapter mark falls on an odd number page (the page should show up on the left side) the page will render on the right and the previous page (page i-1) will show up on the right side, so the fixed layout moving forward will be preserved.

attached a test epub file that I created to show the issues. The file works as intended on Apple Books app.

[test-rtl-epub.zip](https://github.com/johnfactotum/foliate/files/4708168/test-rtl-epub.zip)

Thanks

**Comment by johnfactotum** [comment]
These are Epub.js bugs (it only happens in more recent versions of Epub.js; the version used on their website is outdated).

About the second point, I did notice this with fixed layout books; see https://github.com/futurepress/epub.js/pull/927#issuecomment-629780838. Not sure why navigation is broken, but probably due to the same PR.

**Comment by hyhchan** [comment]
As you said maybe they haven't update their testing version on their website yet. I tried opening epub on https://futurepress.github.io/epub.js/examples/input.html and the
rendition.next() and rendition.prev() works as expected, although the rendition.display() call seems to make the called offset page always on the right panel and screw up the display.
I think I can help doing some testing but need some direction on where to start.

**Comment by johnfactotum** [comment]
The release builds is available on jsDelivr: https://cdn.jsdelivr.net/npm/epubjs/dist/, which is convenient when quickly testing the released versions.

To build it yourself, clone Epub.js's repo and run `npm install` then `npm run prepare`, then you can open `/examples/input.html`.

**Comment by hyhchan** [comment]
Tracked down some of the bugs in epub and reported 2 issues related to this https://github.com/futurepress/epub.js/issues/1069 and https://github.com/futurepress/epub.js/issues/1070 but looks like it is no easy fix ... it's related to how epub process books and probably will need some big overhaul to incorporate rtl book flows.

**Comment by hyhchan** [comment]
@johnfactotum I did some really dirty hack to epub.js to make the RTL fixed layout work for me, but no guarantee that it will work on other epubs nor will it break any working epubs.  Let me know if you want to take a look and see if you want to incorporate those into foliate before epub.js is fixed properly.

**Comment by johnfactotum** [comment]
@hyhchan Can you open a PR to Epub.js? You can add "WIP" in the title or make it a draft if you feel that it's not ready for merging.
