### ISSUE TITLE
Foliate 2.2.0 installed from Ubuntu PPA shows empty results in Wiktionary and Wikipedia searches 

### ISSUE THREAD

**Issue by elpraga** [johnfactotum/foliate#418]
On Ubuntu 20.04 I get the following error:

```
file:///usr/share/com.github.johnfactotum.Foliate/assets/client.html:36:26: CONSOLE ERROR TypeError: undefined is not an object (evaluating 'results.forEach')
```

**Comment by johnfactotum** [comment]
The error message simply means that, while Wiktionary has an entry for the word, it doesn't have definitions of the word in the book's language. This can happen when the language of the book isn't set correctly. Wikipedia lookup also depends on the book's language.

What's the language code of the book? (You can get it from "About This Book" [Ctrl+I].) And what word are you trying to look up?

**Comment by elpraga** [comment]
Thank you @johnfactotum for your reply. The language is set to : `UND` 

Is there a way to change from within Foliate? In case it is not, could you give me a hint how to set the language to English (Br)?

Thank you for your work and your reply!

**Comment by elpraga** [comment]
OK, I have to edit the file `content.opf` within the `.epub` file and change the **Language** field to `en-gb`.

After that I had to remove the book from the library and add it again. Now, the language is shown correctly, and dictionary lookup works as expected.

It would be nice to be able to do it from within Foliate, but I'm not sure if you'd be able to implement that. Refreshing the contents of the library could help.

In any case, do you think it would be a good idea to issue a warning if the language is unset in order not to give the impression that the dictionary lookup does not work in Foliate? It is hard to guess that the mistake is in the `.epub` file, as the text is in English and displayed correctly.

**Comment by johnfactotum** [comment]
Currently it's not possible to change it from within Foliate. If it's an EPUB file, you can either

- use an EPUB editor like Sigil or Calibre,
- or you can edit it manually:
  1. Decompress the file (an EPUB file just an Zip file, so you can just change .epub to .zip and unzip it)
  2. Edit the .opf file (usually in a folder called `OEBPS` or `EPUB`) and change the language.
  3. Repack the files back to an EPUB file with something like
      ```
      zip -rX ../my.epub mimetype META-INF/ OEBPS/
      ```

**Comment by elpraga** [comment]
Thank you @johnfactotum !!
