### ISSUE TITLE
Foliate 2.2.0 - Gutenberg Catalogue

### ISSUE THREAD

**Issue by vexillia** [johnfactotum/foliate#419]
Shows  in catalogue window but clicking open opens an empty window with the message "Unable to load OPDS feed".

The other two feeds work as expected.

**Comment by johnfactotum** [comment]
For some reason, WebKitGTK won't accept Gutenberg's certificate. Not sure why that happens. The preview works because it doesn't use HTTPS, which should probably be fixed.

**Comment by digitalethics** [comment]
Linking to https://github.com/edrlab/thorium-reader/issues/1075 and https://github.com/edrlab/thorium-reader/commit/4a1abf87bb23c3f73f551778dd8b94f5b2341fdb to evaluate whether https with expired certificate should be accepted. 

In Foliate 2.2.1 (Flatpak) it currently looks like this:

![gutenberg_unabletoloadopds](https://user-images.githubusercontent.com/57445091/84264188-0850b980-ab21-11ea-9d76-b6bad891b95c.png)

Clicking on any ebooks leads to double entries: 

![gutenberg_doubleentry](https://user-images.githubusercontent.com/57445091/84264213-14d51200-ab21-11ea-8eca-3f74801bcef4.png)

**Comment by digitalethics** [comment]
I think the double entries are probably introduced through adding the http option?

**Comment by danielweck** [comment]
I think that the Gutenberg feed provides publications with and without images, thus the two distinct EPUB variants.

**Comment by joshbowyer** [comment]
This is still happening in 2.6.1. Gutenberg's SSL cert is valid, did the commit adding http get undone or something?
