### ISSUE TITLE
OPDS with login

### ISSUE THREAD

**Issue by gorgobacka** [johnfactotum/foliate#421]
Great software!

It would be great, if Foliate would support ODPS that requires a login.

**Comment by digitalethics** [comment]
> ODPS that requires a login

Do you have examples that could be added as defaults to improve ebook discovery?

**Comment by gorgobacka** [comment]
@digitalethics No, I do not have an example that is freely accessable. I'm using Calibre-Web to manage my ebooks. It's a self-hostable solution and to restrict access, it requires a login, even for ODPS.

**Comment by milouse** [comment]
Same thing here. I use Calibre-Web with password protected opds feed.

Something which could be great at least, is the ability to provide uri like http://user:password@host:port/path

**Comment by milouse** [comment]
Oh, thank you very much!

**Comment by gorgobacka** [comment]
Thank you.
