### ISSUE TITLE
Snap does not launch on Ubuntu 20.04

### ISSUE THREAD

**Issue by yerbestpal** [johnfactotum/foliate#423]
It does not launch whatsoever. This is the output from running `snap run foliate` in the terminal:
```bash
~$ snap run foliate
/snap/foliate/922/snap/command-chain/desktop-launch: /snap/foliate/922/usr/bin/com.github.johnfactotum.Foliate: /usr/bin/gjs: bad interpreter: No such file or directory
/snap/foliate/922/snap/command-chain/desktop-launch: line 559: /snap/foliate/922/usr/bin/com.github.johnfactotum.Foliate: Success
```

**Comment by johnfactotum** [comment]
@galgalesh Can you take a look?

**Comment by yerbestpal** [comment]
I have tried launching it again and after some time it does launch. I don't have any idea what changed. I had found that I sometimes have to restart before snaps launch, but I thought I had done several times. I am posting the output from running from terminal _now_ just to be as thorough as possible:
```
~$ snap run foliate
Cannot get default EGL display: EGL_BAD_PARAMETER
WaylandCompositor requires eglCreateImage and eglDestroyImage.
Nested Wayland compositor could not initialize EGL

```

**Comment by galgalesh** [comment]
That is a very strange error. It seems as if the snap was launched before the layouts were set. This should not be possible :grimacing: 

Can you show the output of `snap --version`?

**Comment by yerbestpal** [comment]
```bash
~$ snap --version
snap    2.45
snapd   2.45
series  16
ubuntu  20.04
kernel  5.4.0-33-generic
```

**Comment by galgalesh** [comment]
@johnfactotum this seems to be a one-off hiccup of snapd itself. I suggest to close this issue. If anyone still has this issue, please let me know and I'll help you file the issue upstream.

**Comment by yerbestpal** [comment]
I recently reinstalled Ubuntu from scratch and, having noticed your message, installed Foliate. It launched no problem. I will close the issue.

**Comment by SlidingHorn** [comment]
I'm having this issue on 20.04 with the current snap as well

```
snap --version
snap    2.51.1
snapd   2.51.1
series  16
ubuntu  20.04
kernel  5.4.0-77-lowlatency
```

When I try to run `snap run foliate` (or just call `foliate` from bash):

```
snap run foliate
/snap/foliate/1167/snap/command-chain/desktop-launch: /snap/foliate/1167/usr/bin/com.github.johnfactotum.Foliate: /usr/bin/gjs: bad interpreter: No such file or directory
/snap/foliate/1167/snap/command-chain/desktop-launch: line 580: /snap/foliate/1167/usr/bin/com.github.johnfactotum.Foliate: Succes
```

I've tried at least 10 times after seeing this issue and hoping it was a one-time hiccup, but the issue persists.
