### ISSUE TITLE
Feature Request- Host the reader on a server

### ISSUE THREAD

**Issue by ishank-dev** [johnfactotum/foliate#425]
Its a wonderful reader and I would like to use this on my chrome browser and use various browser extension on it, without restricting myself to use it on linux.

**Comment by digitalethics** [comment]
> use various browser extension on it

What browser extensions for example?

**Comment by ishank-dev** [comment]
Summarise text, read out aloud etc

**Comment by johnfactotum** [comment]
There's now an in-browser reader: https://johnfactotum.github.io/foliate-js/reader.html
