### ISSUE TITLE
Integrate Open Textbook Library

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#427]
Could you make the [Open Textbook Library](https://open.umn.edu/opentextbooks) accessible from within Foliate? I'm not familiar with the [MARC (Machine-Readable Cataloging)](https://open.umn.edu/opentextbooks/discovery) records that they provide and wasn't able to locate any OPDS sources. Would this be an alternative to OPDS? In any case, I think this is a great resource which would benefit greatly from your upstream intervention to make OPDS sources available.

**Comment by johnfactotum** [comment]
As far as I know, MARC is used by libraries for cataloging books, whereas OPDS is a "Distribution System" -- for distributing books to readers, so their use cases are pretty different.

**Comment by danielweck** [comment]
Looking at both https://open.umn.edu/opentextbooks/textbooks/moving-pictures-an-introduction-to-cinema and https://press.rebus.community/makingopentextbookswithstudents/ , which are both powered by PressBooks ( see https://pressbooks.com and https://pressbooks.org ), and navigating down into their respective reader view: https://uark.pressbooks.pub/movingpictures/front-matter/steal-this-book/ and https://press.rebus.community/makingopentextbookswithstudents/front-matter/introduction/ ... to me this very much seems to fall within the realm of "distribution" (and "browsing" / "discovery"). Frankly it looks like a missed opportunity to leverage the OPDS catalog format.

However I don't think Foliate (or any other reading systems, for that matter) should have the burden of "filling the gap" by implementing support for browsing MARC, parsing the associated ad-hoc CSV format, or using the JSON API ( see https://open.umn.edu/opentextbooks/discovery and https://press.rebus.community/catalog/ ).

Interestingly, I notice that the PressBooks GitHub contains no references to OPDS: https://github.com/pressbooks/pressbooks/issues?q=opds and https://github.com/pressbooks/pressbooks/search?q=opds and https://github.com/search?q=org%3Apressbooks+opds&unscoped_q=opds

**Comment by danielweck** [comment]
Follow-up: the 2017 roadmap of PressBooks mentions OPDS :)
https://pressbooks.org/roadmap/roadmap-2017/

**Comment by freddrake** [comment]
MARC was considered a legacy nightmare when I was looking at it in the early 1990s.

**Comment by johnfactotum** [comment]
+1 for "don't think [reading systems] should have the burden of 'filling the gap'". There appears to be an upstream issue at https://github.com/pressbooks/ideas/issues/367.
