### ISSUE TITLE
Add Rebus Community catalogue

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#428]
Is there any way to add the Rebus Community [catalogue](https://press.rebus.community/catalog/) to Foliate? I couldn't find OPDS sources, so this might need your upstream intervention similar to the previous issue.

**Comment by johnfactotum** [comment]
It says "Powered by Pressbooks" so this would be the same as https://github.com/johnfactotum/foliate/issues/427#issuecomment-1841278255.
