### ISSUE TITLE
Integrate Tatoeba

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#431]
[Tatoeba](https://tatoeba.org/eng/) is a very promising free and collaborative translation project with a focus on example sentences. I think an [integration](https://github.com/Tatoeba/tatoeba2) into Foliate would be superb. There is a great introduction to the project on [YouTube](https://www.invidio.us/watch?v=ac9SmJuwHqk).

**Comment by johnfactotum** [comment]
Closing this as a special case of #791.
