### ISSUE TITLE
Integrate LibraryThing

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#432]
I use [LibraryThing](https://www.librarything.com/) to catalogue books and to connect with fellow readers. In March 2020 Tim Spalding, the founder, announced in a [blog post](https://blog.librarything.com/main/2020/03/librarything-goes-free/) that LibraryThing is now free to all. There are different [APIs](https://www.librarything.com/services/) that could be utilized to integrate it into Foliate, perhaps in a similar way to the [iOS app](https://apps.apple.com/us/app/librarything/id948824489) or [Android app](https://play.google.com/store/apps/details?id=com.librarything.librarything).

**Comment by johnfactotum** [comment]
Unfortunately, LibraryThing's APIs are currently unavailable:

>Notice: LibraryThing APIs currently disabled
>The LibraryThing APIs are disabled until further notice (last updated on 1/28/2021).

Similar to https://github.com/johnfactotum/foliate/issues/283#issuecomment-1841316645, such integration would probably work better as an external program, though one can reconsider this if/when the API becomes available again.
