### ISSUE TITLE
Add depedence appmenu-gtk3-module on PPA

### ISSUE THREAD

**Issue by costales** [johnfactotum/foliate#433]
Hi,

In Ubuntu 20.04 with PPA, launching the program from Terminal there is a warning about need this package: `appmenu-gtk3-module`.

I think it should be a depedence (?).

Best regards.

**Comment by johnfactotum** [comment]
I don't think it should be a dependency. It should be a dependency for whatever that is requiring that module, not Foliate itself, which does not depend on the module.

Also the PPA is not maintained by the author of this program. For questions and bugs the PPA please contact [Archisman Panigrahi](https://launchpad.net/~apandada1).
