### ISSUE TITLE
margin issues since version 2.2 bug 

### ISSUE THREAD

**Issue by proppetto** [johnfactotum/foliate#434]
From version 2.2 the margins from 14.0 to 0.0 remain graphically unchanged at 14.0, only from 14.0 and up they change.
Installed via the .deb package on Kubuntu 20.04. I also tried through repositories but the result does not change.

The installed version is 2.2.1
![foliate1](https://user-images.githubusercontent.com/13276689/83968889-85cfbc00-a8cc-11ea-874b-3921fffe5454.png)
![foliate2](https://user-images.githubusercontent.com/13276689/83968892-8700e900-a8cc-11ea-9650-519b3cf28234.png)
![foliate3](https://user-images.githubusercontent.com/13276689/83968893-88321600-a8cc-11ea-9292-bca79927104f.png)
![foliate4](https://user-images.githubusercontent.com/13276689/83968894-88caac80-a8cc-11ea-8930-60911375f531.png)
![foliate5](https://user-images.githubusercontent.com/13276689/83968895-89634300-a8cc-11ea-83f0-e14afa2f7d9d.png)
![foliate6](https://user-images.githubusercontent.com/13276689/83968898-89fbd980-a8cc-11ea-8d74-260e75b9ebd7.png)
![foliate7](https://user-images.githubusercontent.com/13276689/83968899-8b2d0680-a8cc-11ea-99fc-d14bb300946f.png)

**Comment by johnfactotum** [comment]
This is because in 2.2.0 there's now a max width setting. Margin has no visual effect when `window width - margin > max width`.

**Comment by proppetto** [comment]
Ah ok, thanks for the reply. I preferred it as before because the size of the full screen window was more practical for me. Is there a possibility that you will come back as before and / or change in the next releases?

**Comment by johnfactotum** [comment]
You can just set max width to something larger than your screen width to get the previous behavior.

**Comment by proppetto** [comment]
Thank you very much
