### ISSUE TITLE
Make Ngram Viewer graphs available within Foliate 

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#436]
It would be great to be able to utilize the Google Books [Ngram Viewer](https://books.google.com/ngrams) and its [graphs](https://books.google.com/ngrams/info) from within Foliate when looking up specific terms or phrases. [Datasets](https://storage.googleapis.com/books/ngrams/books/datasetsv2.html) are available under a Creative Commons Attribution 3.0 Unported License. Background reading: [Google Books Ngram Corpus (PDF)](https://www.aclweb.org/anthology/P12-3029.pdf).

The most basic way to implement this would be to add it to the "About this Book" metadata window "Find on..". This would only allow to look it up externally and limit its immediate functionality to searching for the book title. The benefit, however, would be to give readers more options to discover background information about the texts they read and many may not have heard about the Ngram Viewer. A more useful implementation would be to integrate it alongside the dictionary and annotation features in a popover window but I'm not sure how this would look like graphically. The most useful way would probably be via an option to toggle these graphs directly in the sidebar.

**Comment by johnfactotum** [comment]
Closing as a special case of #791.
