### ISSUE TITLE
Remove focus outline in book metadata popover

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#437]
![findon_preselection](https://user-images.githubusercontent.com/57445091/84011858-01864300-a977-11ea-93e4-0659516af554.gif)

**Comment by johnfactotum** [comment]
Why? That's just the focus outline. There's nothing special about that menu. It behaves the same as any other menu in GTK.

**Comment by digitalethics** [comment]
> Why? That's just the focus outline.

I mean the small box around "Amazon". I think it's not necessary as clicking on "Find on..." should be agnostic as to what option a user will select next.

**Comment by johnfactotum** [comment]
It simply indicates that the menu item currently has focus. It's drawn by the GTK theme for _every_ menu item (and every single other focusable widget). It's necessary for keyboard navigation.

**Comment by digitalethics** [comment]
Thanks a lot for clarifying this.
