### ISSUE TITLE
Evaluate Wolfram|Alpha Summary Box API

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#438]
The [Wolfram|Alpha Summary Box API](https://products.wolframalpha.com/summary-boxes-api/documentation/) returns configurable, pre-generated boxes that summarize the available [Wolfram|Alpha knowledge](https://www.wolframalpha.com/) for a subject. Among the many different APIs they offer, this one seems to be the most useful. The Full Results API is capped at 2000 API calls per month. They offer a free non-commercial development account but I'm not sure whether this includes unlimited API calls for the feature-limited Summary Box. 

![wolframalpha_publishingintegration](https://user-images.githubusercontent.com/57445091/84032306-69e51c80-a997-11ea-9399-d4316213b1c4.png)

**Comment by johnfactotum** [comment]
Closing this as a special case of https://github.com/johnfactotum/foliate/issues/791.
