### ISSUE TITLE
Please provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [johnfactotum/foliate#44]
> If a Snap app, PPA, or an AppImage should pop up after I publish this, do let me know so I can add it in.

https://www.omgubuntu.co.uk/2019/05/foliate-ebook-reader-linux

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines
- Decentralized

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by johnfactotum** [comment]
I'm interested in providing an AppImage, but I'm also at a complete loss as to how to make one.

Foliate uses Meson and follows the [GJS Application Packaging Specification](https://gjs-guide.gitlab.io/guides/gtk/application-packaging.html). With Flatpak, this pretty much _just works_, which is why I was able to get it on Flathub very quickly and easily. Making Snaps, debs, and AppImages is much more involved, particularly because there aren't any templates that I can follow and also of the fact that I don't use Ubuntu personally, and I'm not very familiar with it.

I'd appreciate it if anyone can provide any help with this.

**Comment by itprojects** [comment]
@johnfactotum Since this thread is under "help wanted", the following bash script has been made. It produces binary .deb files which have been tested and work. Minimal effort required!
[package.deb.sh.txt](https://github.com/johnfactotum/foliate/files/3343446/package.deb.sh.txt)

**Comment by itprojects** [comment]
@probonopd Can you make a Debian/Ubuntu PPA with the script in the comment above?

**Comment by johnfactotum** [comment]
Is it possible to build a source package instead? I think the -- whatever tool you'd use to make debs -- does support Meson? Or maybe configure Meson to install things inside a directory and then build the deb from there?  Redoing all what's currently done by Meson by hand seems a bit unsatisfactory to me.

**Comment by itprojects** [comment]
> -- whatever tool you'd use to make debs -- 
Do you mean the package.deb.sh? It has a (file)name, you know...

If the meson can produce the folder (and it possibly can) than packaging should be easy.

Work on deb source making has started.

**Comment by johnfactotum** [comment]
> Do you mean the package.deb.sh? It has a (file)name, you know...

No, I mean like Debhelper, or maybe other related tools.

**Comment by itprojects** [comment]
Those ones we might not need. Meson should be able to handle it entirely.

**Comment by johnfactotum** [comment]
@probonopd Foliate should now be able to build and run on Bionic without any problem. I've also added the `debian/` directory for building .debs. I know that ideally we should try and make it work on Xenial, but maybe we can target Bionic first and go from there?

**Comment by probonopd** [comment]
Hello @johnfactotum please always build on the oldest, not the newest, operating system releases that your users might be running. We recommend no newer than the oldest still-supported LTS release of Ubuntu, which at this time is xenial. Otherwise the AppImage will not run on all still-supported LTS releases of Ubuntu, and will fail the automated tests on https://github.com/AppImage/appimage.github.io.

So I suggest to first make it build on xenial, then I can help you with turning it into an AppImage.

**Comment by johnfactotum** [comment]
Understood. Thanks for the clarification.

**Comment by itprojects** [comment]
Can you add the following Debian/Ubuntu instructions:

Prepare the environment:

`sudo apt-get install meson gettext build-essential devscripts`

Download foliate form github

Unarchive foliate-master.zip

`cd foliate-master`

`dpkg-buildpackage -us -uc -nc`

Package is found in foliate-master:

com.github.johnfactotum.foliate_1.3.1_amd64.deb

Install with:

`sudo dpkg -i ./com.github.johnfactotum.foliate_1.3.1_amd64.deb`

**Comment by probonopd** [comment]
Did you test this in xenial @itprojects?

**Comment by itprojects** [comment]
Tested with Ubuntu 19.04

**Comment by probonopd** [comment]
Can you please test with Ubuntu 16.04? That is what it needs to build on if we want to make an AppImage that runs on all still-supported Ubuntu versions.

**Comment by itprojects** [comment]
Attempted tested Ubuntu 16.04. Failed.

16.04 has:
meson version = 0.29.0 (Required meson_version: '>= 0.40.0')
gjs = 1.44.0 (bigger problem!)

**Comment by itprojects** [comment]
Attempted to test on Ubuntu 18.04 (Bionic). Success.

**Comment by probonopd** [comment]
That's exactly the [experience I'm having with Meson](https://github.com/AppImage/AppImageKit/issues/205#issuecomment-495308243) all the time. Someone needs to ensure it works on anything but the latest bleeding edge systems.

**Comment by itprojects** [comment]
For Ubuntu 16.04, the support left seems to be for security patches, not new packages. To make it worse that version of Ubuntu does not use the gnome-shell by default, that's bad.

**Comment by itprojects** [comment]
@probonopd  Do you know how to make an AppImage for Bionic?

**Comment by probonopd** [comment]
Build on xenial. It will also run on bionic.

**Comment by TheAssassin** [comment]
I'd just build on bionic, and move on from there. As in, get something to work on a vast majority of systems, then try to make it work on older systems. Being annoying at first and preventing someone from building something that works for the vast majority of systems is counterproductive.

I hadn't heard of GJS before, but I guess it should be fairly easy to create a [linuxdeploy](https://github.com/linuxdeploy/linuxdeploy) plugin, if there's a need for one. Does GJS need a special runtime, or does meson automatically produce a binary that "just runs"? If the latter applies, then a simple `meson install` (or however that works) into a `DESTDIR` (CMake/autotools term) followed by an appimagetool call should bring you somewhere already.

**Comment by TheAssassin** [comment]
@itprojects @johnfactotum feel free to pass by on IRC, #appimage on Freenode, where we can interactively help you. Also see https://docs.appimage.org for more information (no specific GJS information (yet, if you want to make one, be our guest), but lots of other useful information).

**Comment by johnfactotum** [comment]
@TheAssassin Thanks a lot for the help! To be honest the documentation is a bit confusing to me, and there's very little on GTK apps.

There's no binary for Foliate itself, per se. It's really just a script that will be run by GJS. I suppose to make an AppImage one has to bundle GJS with all the GTK libs that it depends on? And then also WebKitGTK, which is the other runtime dependency.

I see there's an open issue on creating a GTK plugin for linuxdeploy? Because Foliate is really just a pretty standard GTK application. Well, maybe except the fact that it uses GJS. But there are plenty of GNOME apps that use GJS, notably Polari and Gnome Maps, among several others, and they all use Meson and follow the same standard package specification. So it'd be great if there's some tool that will "just work" for creating AppImages.

**Comment by TheAssassin** [comment]
@johnfactotum the issue you mention is about evaluating whether there's a need for a plugin to bundle resources aside from shared object libraries, which are already bundled just fine. We're making AppImages for many GTK based software already, a recent example is [Xournal++](https://github.com/xournalpp/xournalpp) (using [appimagecraft](https://github.com/TheAssassin/appimagecraft)).

For GJS, as you say, a runtime must be bundled as well. Therefore, there is the need for a specific plugin. If it's only one program that needs to be bundled with the libraries it depends on, it's really really simple.

As a first attempt, we could try to write a bundling script that uses linuxdeploy to create an AppDir and bundle GJS's binary, then copy in your scripts and call linuxdeploy a second time to make the AppImage.

I'm happy to help you, I'll be on IRC for the next hours (I guess at least ~6 hours from now), with minor interruptions. I can write the script quickly but I will need some input from you during the process.

**Comment by johnfactotum** [comment]
Thanks! I've actually never used IRC before, but I guess there's a first time for everything.

**Comment by TheAssassin** [comment]
It's still very popular among free software communities. You can just use the webchat, or get a real client.

**Comment by stevenpusser** [comment]
If you do still want a proper way to build deb packages with debhelper, there's my OBS repo:

https://build.opensuse.org/project/show/home:stevenpusser:Foliate

You can get the source files here:  https://download.opensuse.org/repositories/home:/stevenpusser:/Foliate/xUbuntu_18.04/

The OBS also has some mechanism to create AppImages, but I can't figure that out.

**Comment by probonopd** [comment]
> The OBS also has some mechanism to create AppImages, but I can't figure that out.

Please check https://docs.appimage.org/packaging-guide/hosted-services/opensuse-build-service.html

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by chromer030** [comment]
Any update on this ?

**Comment by Moonbase59** [comment]
Just a quick +1 from me: Many Linuxers will prefer an AppImage over Snap of FlatPak anytime!

**Comment by sdwolfz** [comment]
Does anybody actually have an example of a `gjs` application that's successfully packaged as an AppImage to showcase as an example?

I'm trying to build one but failing, between the segfaults I'm getting and the different behavior in Ubuntu 20.04 vs Manjaro; I don't really see how this can be done in practice....

**Comment by karam72** [comment]
Any updates?

**Comment by gerardbm** [comment]
+1 for the AppImage.

**Comment by johnfactotum** [comment]
Closing this as at this point it's not really planned anymore.

Note that if you do have a system that runs a recent enough version of GNOME, you can definitely run Foliate without root. In the stable version you can install to a local directory, and with new gtk4 branch you can even run directly from the source tree, no build step necessary.

If you run an old LTS system, I'm guessing that it might not be easy or possible to run a recent enough GNOME stack, even with AppImage. At any rate it seems to be against AppImage's philosophy to use the latest platform libraries. So in this case — since I'm not planning on supporting these older platforms — you would probably do better with a containerized solution like Flatpak.

Alternatively, if you have a recent enough web browser, you could try the new online reader: https://johnfactotum.github.io/foliate-js/reader.html. It's currently very lacking in features but it does work for opening and reading e-books, without having to install or download any software.

**Comment by johnfactotum** [comment]
That's fair. But at this point I honestly couldn't be bothered anymore to try to figure out what can or cannot run on all these different systems, much less figuring out what and how to bundle.

Compare this to Flatpak, where you're only developing against *one* environment, which will run the same way everywhere, on old and new systems alike. And in Foliate's case, everything is already included in the GNOME runtime, so the app literally builds and runs with zero configuration!

It would certainly be great if Foliate could be made available as an AppImage. But personally, I would rather just spend time developing the app itself instead.

**Comment by sid-the-sloth** [comment]
too bad, it's a great app, lots of people would have used the AppImage, but the vision (dev to dev opinion here) is rather limited (gnome, flatpak... latest & greatest)... so then --  "goodbye and thanks for all the fish!"

will continue using calibre.

**Comment by WojciechMigda** [comment]
FYI, due to dependency on `meson >= 0.59` foliate `2.6.1` is the latest that builds on xenial. (Kudos to @itprojects for step-by-step tutorial!)
