### ISSUE TITLE
Add ISBN lookup

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#440]
The idea is to add a function in the library component to check if there's a free ebook for any ISBN. Ideally, _positive_ search results should connect with OPDS sources and allow to download the ebook into the Foliate library.¹

[Unglue.it](https://unglue.it/api/help) offers such a function via their API. It would be great to integrate this _but_ not necessarily limit the ISBN lookup to this API. Maybe there is a way to have an even more global ISBN lookup which aggregates available feeds from more than the sources available to Unglue.it to determine whether there is a free ebook or not.

From Unglue.it:

![unglueit_isbnlookup](https://user-images.githubusercontent.com/57445091/84244031-5bb40f00-ab03-11ea-9800-f4c0d37b2b1a.png)

¹For _negative_ search results, i.e. no free ebook is available, I will raise a separate issue.

**Comment by johnfactotum** [comment]
It wouldn't really make sense to use a special API. This should be done in OPDS. (Using the generic search feature in OPDS should work. If for some reason a dedicated field is needed, in OPDS 1 you can add extra parameters in the OpenSearch template, and in OPDS 2 maybe you can add a parameter for `identifier`.)

Now, aggregated OPDS search would be an interesting feature. This could be implemented by setting up an OPDS feed that aggregates other feeds. But this can also be implemented on the client side. I think I'll open a new issue for this.
