### ISSUE TITLE
Make epub selection process easier

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#443]
In the _Catalogs_ component, the epub selection is a bit unclear. Why is the first one recommended over the second one? Both show _epub+zip_ in the popover. I think this is confusing for a user (at least for me it is). Why is the first one recommended? Could this be made clearer in the menu entries and perhaps some information added to the Wiki? 

![epubselectionunclear](https://user-images.githubusercontent.com/57445091/84266882-7d25f280-ab25-11ea-8c5c-2e0f969be178.gif)

**Comment by johnfactotum** [comment]
You can see the publisher by scrolling down?

**Comment by digitalethics** [comment]
> You can see the publisher by scrolling down?

Yes. I think it would be good to think about how to display ebook metadata without having to scroll.

**Comment by johnfactotum** [comment]
That's impossible. Scrolling will always be needed because you can't expect all metadata to fit inside a small window. As for making the window bigger, there's already an issue on that: https://github.com/johnfactotum/foliate/issues/404.

**Comment by digitalethics** [comment]
> That's impossible. Scrolling will always be needed because you can't expect all metadata to fit inside a small window.

Yeah, I rather meant to think of alternative modes to display book metadata. One possible way would be to use the sidebar for this as it would almost completely eliminate the need for scrolling, depending on the screen size of course. See: #400 and the second suggestion in #474. Surely, this should _not_ replace the metadata popovers which can be optimized a little on their own via #404.
