### ISSUE TITLE
Add citation sharing

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#445]
It would be great to have an option to share citations on social media, especially Twitter and Mastodon, and on instant messaging applications such as Telegram and Signal (both have desktop clients) directly from within the Foliate viewer component. Compared to merely _copying_ a selection of text _sharing_ should automate some processes: 

- to bring the external application or browser window into focus
- to include the previously selected text intended for sharing
- to include author name and ebook title

It may be more aesthetically pleasing to have it automatically formatted in exactly this way: 

> 'Painting is equal parts near and far: when near, the artist works to make his mark; when far, he assesses the work in order to analyze its qualities.'—Frank Chimero, "The Shape of Design"

Ideally, this should be complemented by an exact page number but I'm not sure how this would work with epubs. Any ideas?

**Comment by johnfactotum** [comment]
Ideally sharing should be something support by the toolkit and DE. AFAIK the whole XDG sharing portal thing hasn't gotten anywhere. Before that happens, being able to copy the formatted text (with title, author, and everything) and manually paste it into whatever app you're using would be nice.

> Ideally, this should be complemented by an exact page number but I'm not sure how this would work with epubs. Any ideas?

Some EPUBs do provide info on print version pages with `pageList`, so it's certainly possible.
