### ISSUE TITLE
Integrate ebook viewer component into view switcher

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#446]
Currently, an external window opens up when opening an ebook. While the idea behind this decision may be to keep the viewer component as clean as possible and actually separated from the other components, I feel it makes Foliate appear more fragmented than necessary. I would definitely prefer to be able to switch between all current major Foliate components via the view switcher with as little external windowing as possible.¹ 

¹Priority-wise this is probably my most-wanted feature as I believe it would make Foliate feel significantly more "integrated" as an application and better accommodate my workflow.

**Comment by johnfactotum** [comment]
The easiest fix is to just close the library window when opening a book. That's what GNOME Builder does with it's "Open a Project" window, for example.

**Comment by digitalethics** [comment]
Maybe it could look like this: 

![viewswitcher_reader](https://user-images.githubusercontent.com/57445091/85467359-695da000-b5ab-11ea-9943-db82a50a1ac5.png)

I think naming it _Reader_ would work better than _Viewer_ in order to distinguish it from the image viewer component and to emphasize the actual reading experience. It is also the core component. My favourite would probably be a centered position as most time is spent in this component, like this: Library | Reader | Catalogs

**Comment by digitalethics** [comment]
A few more ideas: I think it would be good:

- to add an option for users decide which component they prefer to be opened by default
- to open the _Reader_ as a separate, external window instead (multi-window workflow, minimalists, etc.)
- in case more components are added in the future to provide the option to selectively disable one or more of them

**Comment by johnfactotum** [comment]
- What exactly is the advantage of this?
- Even if they are in same window, why must the view switcher be visible at all times? The usual design pattern in GNOME (and GTK 3 apps in general) is to have a separate view with a back button, similar to how OPDS catalogs are opened now. Users of this pattern includes Totem, GNOME Books, GNOME Boxes, and GNOME Font Viewer, to give a few examples.
- Where would it put the book's title?
- How would it handle the bottom view switcher bar when the window is narrow? There's already an auto-hiding actionbar at the bottom of the reader.
- It kind of feels like what you really want is to open everything in tabs? For example, in Chrome pretty much everything is opened in a tab. In Firefox, traditionally there were separate windows, but now many things are put into tabs. Except the library window, which still remains as a separate window.

**Comment by digitalethics** [comment]
>     * Where would it put the book's title?

What about changing the alignment of the control buttons in _GTKStackSwitcher_ or _HdyViewSwitcher_ from horizontal to vertical like [here](https://stackoverflow.com/questions/47049271/how-to-change-gtk3-stackswitcher-controls-alignment) or using the _GTKStackSidebar_ instead for a vertical navigation? This would allow to use the header bar for the book title. 
From a pure desktop perspective vertical navigation is far more efficient, especially since it is better to use vertical screen space for navigational elements. From a convergence perspective, it is probably more difficult to use vertical navigation on mobile devices.

**Comment by johnfactotum** [comment]
In the gtk4 branch, there is now a library button on the sidebar, and the views are combined in the same window, which has addressed the problem, even though it doesn't use the view switcher pattern.
