### ISSUE TITLE
Please document how to build on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [johnfactotum/foliate#45]
Please document how to build on Ubuntu xenial, the currently oldest still-supported LTS release of Ubuntu.

Since this project is using Meson, I fear that it will require newer versions of Meson, Python and whatnot than what comes with the system by default.

**Comment by probonopd** [comment]
On Travis CI, something along the lines of

```
language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  - sudo add-apt-repository ppa:deadsnakes/ppa -y # Newer Python for Meson
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install python3.6-venv

script:
  # Install Meson "manually"
  - virtualenv -p python3 ./ # Create virtualenv
  - source bin/activate      # Activate the virtualenv
  - pip3 install meson       # Install Meson
  - hash -r                  # Refresh bash paths
  - ..
```

**Comment by johnfactotum** [comment]
Dependencies:
- `meson` - as you've mentioned. But I see there's a 0.40.1 version in `xenial-backports`. Would it be possible to use that?
- `libwebkit2gtk-4.0` - I think it should work. This is, however, untested
- `libsoup2.4` - same as above
- `gjs` - now this is the real problem. Would need to build it from source, as the version in xenial is ancient

Not sure if it needs anythings else. I don't use Ubuntu personally, and I'm not very familiar with it. I'd appreciate it if anyone can help build/test this.

**Comment by probonopd** [comment]
Running into

```
autoreconf: running: /usr/bin/autoconf --force
configure.ac:133: error: possibly undefined macro: AC_MSG_WARN
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

Please do some tests on systems other than the latest and greatest, so that your software is buildable on e.g., CentOS 6 and 7.

**Comment by johnfactotum** [comment]
Thanks for working on this!

If you're having trouble building gjs, I suggest you ask the gjs devs. Regardless, I think you should be able to build Foliate itself as long as meson is working. The rest are all just runtime dependencies.

**Comment by Vistaus** [comment]
> Please document how to build on Ubuntu xenial, the currently oldest still-supported LTS release of Ubuntu.
> 
> Since this project is using Meson, I fear that it will require newer versions of Meson, Python and whatnot than what comes with the system by default.

Meson and Python libraries can easily be updated, even older releases, with pip (sudo pip install --upgrade _nameofpackage_). You need to install pip first through Synaptic, though.

**Comment by shibotto** [comment]
meson and ninja from xenial-backports work fine, however as predicted gjs is the problem:
` (com.github.johnfactotum.Foliate:11367): Gjs-CRITICAL **: JS ERROR: SyntaxError: invalid property id @ resource:///com/github/johnfactotum/Foliate/js/main.js:37
JS_EvaluateScript() failed`

**Comment by probonopd** [comment]
So the question is, how do we get gis compiled on xenial?

**Comment by probonopd** [comment]
Out of curiosity, what does an eBook reader need a JavaScript library for, anyway?

**Comment by shibotto** [comment]
Foliate does, since it's based on Epub.js

**Comment by johnfactotum** [comment]
To clarify, GJS provides a JavaScript runtime as well as bindings for GTK and other GNOME libraries. So Foliate needs GJS in the same sense that Meson needs Python. Epub.js runs inside the WebView, not GJS.

**Comment by shibotto** [comment]
Thank you for the explanation :D

**Comment by shibotto** [comment]
I'm giving up for now, sorry.
I tried compiling GJS 1.56, had to remove the valgrind checks because of too old autoconf-archive (eventually I would have upgraded, it was faster ATM). However it still requires spidermonkey/mozjs-60 and at least glib-2.54, which thankfully it's the last one reported compatible with meson >= 0.38.1. So I grab glib-2.54.3, but during configuration meson very little graciously crashed :sweat_smile: 
Hoping someone with a bit more willpower than me will continue.

**Comment by johnfactotum** [comment]
Another possible solution would be to transpile the code with [Babel](https://babeljs.io/) so it can run in older versions of GJS. That might be easier than compiling GJS.

**Comment by stevenpusser** [comment]
I did manage to backport gjs, mozjs-60, and then Foliate on Debian Stretch-based MX 18, but that MX release already had a backported libglib2.0-0 I did to support GIMP 2.10.X, so half the work was already done.

**Comment by stevenpusser** [comment]
Gjs 1.52 requires a minimum of libgtk-3-dev 3.20 to build, and if you even manage to backport that to Xenial, that breaks everything related to GTK 3, since it's using 3.18.9. 

I would say that a backport is not feasible.

**Comment by johnfactotum** [comment]
So it needs Babel, then. Using the steps in https://github.com/johnfactotum/foliate/issues/27#issuecomment-502372231:
1. First one needs to install `nodejs` and `npm`. Probably best to install the latest versions. The [most official way](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages) to do that seems to be:
    ```bash
    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt-get install -y nodejs
    ```
2. Run the following:
    ```bash
    cd src
    npm install @babel/core @babel/cli @babel/preset-env
    echo '{"presets":[["@babel/preset-env",{"targets":{"firefox":"44"}}]]}' > .babelrc
    mv main.js main.src.js
    npx babel main.src.js --out-file main.js
    cd ..
    ```
3. Build Foliate as usual with Meson.

**Comment by probonopd** [comment]
So @johnfactotum did you succeed in building foliate for xenial? I think it would be easier if the developers were targeting the oldest LTS release as the tar, rather than retroactively having to backport it.

**Comment by johnfactotum** [comment]
It turns out that the above doesn't work. `{"targets":{"firefox":"44"}}` is too high. I'm not sure what version of SpiderMonkey is used in GJS 1.44, but it doesn't support Promise, which according to MDN, is supported in Firefox since 29. So short of rewriting every Promise with callbacks, we'll have to include a polyfill, either manually, or through Babel and Webpack.

**Comment by stevenpusser** [comment]
Debian used Firefox 24's SpiderMonkey (libmozjs-24-dev) for their gjs-1.44 build, so I assume that Ubuntu followed suit: https://snapshot.debian.org/package/gjs/1.44.0-1/

**Comment by galgalesh** [comment]
@johnfactotum I would also close this issue.

The snap version of Foliate runs on Ubuntu Xenial out of the box. Both the snap and Flatpak version run on the other distro's mentioned here. I think this gives enough options to people who want to run Foliate on older releases.

**Comment by johnfactotum** [comment]
Well, since v2.0 uses even more new features of JavaScript and GJS, most notably the [`GObject.registerClass` syntax](https://gjs-guide.gitlab.io/guides/gjs/legacy-class-syntax.html), it's now even harder to support GJS < 1.50.

And since it's also not feasible to build GJS > 1.50 on Xenial, I think this issue is simply unsolvable without massive labour. So in conclusion, I think I'll stick to supporting only Bionic, i.e. GJS >= 1.52.
