### ISSUE TITLE
Cursor stays hidden when the menu/dictionary pops over. 

### ISSUE THREAD

**Issue by SubatomicCat** [johnfactotum/foliate#450]
I have auto-hide cursor enabled. When I click on a word and have the menu pop over, the cursor stays hidden. It can only be seen inside the pop over/dictionary menu; it remains hidden everywhere else on the screen.

**Comment by johnfactotum** [comment]
Yeah, that's because the popover is _modal_, which means that when the popover is opened, the rest of the window does not receive any event.

**Comment by johnfactotum** [comment]
This doesn't happen anymore in GTK 4.
