### ISSUE TITLE
No icon on the window button on taskbar

### ISSUE THREAD

**Issue by TotalCaesar659** [johnfactotum/foliate#456]
On Lubuntu 20.04 (Foliate 2.2.1 from PPA), there is no [icon](https://github.com/johnfactotum/foliate/raw/master/data/com.github.johnfactotum.Foliate.svg) on the window button on taskbar.
![1](https://user-images.githubusercontent.com/14265316/84595048-8b924800-ae5e-11ea-8cd5-3d4aef479ab8.png)

**Comment by apandada1** [comment]
Could you install Foliate from the .deb file and check if the issue is present there as well? Does the icon show up in the menu?

Here is the download link. https://github.com/johnfactotum/foliate/releases/download/2.2.1/com.github.johnfactotum.foliate_2.2.1_all.deb

**Comment by TotalCaesar659** [comment]
No, same result.
