### ISSUE TITLE
Use NPM to build JavaScript dependencies

### ISSUE THREAD

**Issue by johnfactotum** [johnfactotum/foliate#460]
Currently all JavaScript dependencies are pre-built and bundled. It'd be better if there's an option to use NPM to build everything from source.

**Comment by apandada1** [comment]
After that will it be possible to turn the source into a .deb package with a single command which is possible right now?

**Comment by johnfactotum** [comment]
>  It'd be better if there's an _**option**_ to use NPM to build everything from source.

We can still bundle pre-built files, and the package maintainers can choose to build them themselves if they want.

**Comment by digitalethics** [comment]
Will this remove all blockers to enable distribution maintainers to make [reproducible builds](https://reproducible-builds.org/) for Foliate?

**Comment by johnfactotum** [comment]
It depends on what you mean by "reproducible". AFAIK the building process is -- and has always been -- already entirely deterministic and reproducible, though I haven't really tested it.

However, since the JavaScript libraries are themselves generated from another source, some people consider them to be akin to pre-compiled binaries. This is especially the case with minified files, and _literally_ the case with WebAssembly. In that sense, then, yes, this will make Foliate more "reproducible".
