### ISSUE TITLE
Clicking inside code moves to the next page

### ISSUE THREAD

**Issue by eksperimental** [johnfactotum/foliate#464]
This is a weird behaviour. If I click inside a box of programming code, it acts a if I hit the Page Down key.

version 2.2.1

**Comment by johnfactotum** [comment]
By default it will go to the next page and previous page when you click on the right and left part of the view. This can be disabled by disabling "Turn page on tap" in the preferences.

> it acts a if I hit the Page Down key.

I presume you're using the "Continuous" layout? I guess it turn page on tap should be disabled in scrolled and continuous modes.

**Comment by eksperimental** [comment]
Yes, I was in continuous mode. Anyways, you commit fixed it without having to change the preferences. Thank you
