### ISSUE TITLE
Remove visual indicator when using mouse wheel scroll-up

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#465]
When using a mouse wheel to scroll up to the very top, there is a visual indicator that the end of the scrollable area is reached. I'm not sure how useful this animation is (I find it unnecessary and not very elegant) and I suppose it is probably related to GTK. Is there a possibility to remove it? 

![mousescrollup](https://user-images.githubusercontent.com/57445091/85019270-d4077980-b16e-11ea-84d1-ecd4299b5915.gif)

**Comment by johnfactotum** [comment]
It's called _overshoot_. It's a GTK feature controlled by the theme/CSS. To disable it you can either make a new theme, ask the theme maintainer to remove it, or add custom styles to `~/.config/gtk-3.0/gtk.css`.

**Comment by digitalethics** [comment]
Thanks a lot for helping me clarify this. Very helpful to understand this better.
