### ISSUE TITLE
Flatpak theme inconsistencies with About dialogues

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#466]
When using the latest Flatpak under KDE Plasma, the _About Foliate_ window decorations and theme do not match the GTK ones that are shipped with the Flatpak. Instead it uses my Plasma theme. This is not just the case for Foliate but in fact a problem with all Flatpaks. I thought the _About_ dialogues are part of the individual applications and not the system. 

![flatpak_windowdecorations](https://user-images.githubusercontent.com/57445091/85019992-f352d680-b16f-11ea-9076-7fef67759c4a.gif)

**Comment by johnfactotum** [comment]
It doesn't have anything to do with Flatpak. I think it's just KDE and other DEs/WMs setting `gtk-dialogs-use-header` or something, and so it uses KDE's server-side titlebar. The widgets inside the window still use the same theme as the rest of the application.
