### ISSUE TITLE
Add horizontal scrolling in Catalog component

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#473]
It would be great to be able to scroll back and forth (< and >) among a wider range of book covers directly from the main Catalog component view without having to click _Open_. 

![addhorizontalscrolling](https://user-images.githubusercontent.com/57445091/85123279-425c4280-b228-11ea-817a-cade68bc215d.png)

**Comment by digitalethics** [comment]
Fantastic! You commit faster than I can type. Would you consider adding visual scroll buttons like < and > at the left and right border of the entries? In this way, users could see up to 12 items at all times yet still be able to scroll through more without having to click _Open_. It would be neat to navigate through more covers by pressing < and > similar to navigating a slide show.

**Comment by johnfactotum** [comment]
> Would you consider adding visual scroll buttons like < and > at the left and right border of the entries? In this way, users could see up to 12 items at all times yet still be able to scroll through more without having to click Open.

What does the presence of "<" and ">" buttons have to do with the number of items shown?

**Comment by digitalethics** [comment]
> What does the presence of "<" and ">" buttons have to do with the number of items shown?

The number of items would always stay the same regardless of whether the preview has a scrolling feature or not. I guess what I'm trying to say is whether you'd consider making the preview more capable of actually browsing the entire catalogue by adding navigational elements (< and >).

**Comment by johnfactotum** [comment]
I kind of get what you're saying, but the "<" and ">" buttons pattern is technically very cumbersome to implement. Much easier to just use scrolling. The preview is not really meant to be used for browsing the complete catalog (which is why it's called a "preview").

**Comment by digitalethics** [comment]
> I kind of get what you're saying, but the "<" and ">" buttons pattern is technically very cumbersome to implement. Much easier to just use scrolling.

I guess it would be more agnostic to whether one uses touch or keyboard/mouse and more aesthetically appealing than a scrollbar. 


> The preview is not really meant to be used for browsing the complete catalog (which is why it's called a "preview").

Yeah, you're probably right. Would be more difficult to justify having preview and view separated if this were implemented. I was just thinking of how the actual experience of browsing books can be optimized regardless of where you are in the navigational tree and didn't really make a difference between preview and actual view.

**Comment by johnfactotum** [comment]
> I guess it would be more agnostic to whether one uses touch or keyboard/mouse

That's not really the case. With the scrolling widget, touch, keyboard, mouse, etc., are all automatically handled correctly. With "<" and ">" buttons, you'd need to handle all that manually and and make sure they all work correctly, which is a lot of work.
