### ISSUE TITLE
Reduce visual density in acquisition feed view

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#474]
Currently it looks like this: 

![acquisitionfeed_toocrowded](https://user-images.githubusercontent.com/57445091/85123925-62d8cc80-b229-11ea-873d-18c980a76919.png)

It would be great to reduce visual density by two strategies: 

(1) You could add basic publisher and acquisition feed information (basically anything that can be automated, e.g. publisher logo, name, history, total amount of books available, etc.) on top right below the header bar and then list all book covers below. This kind of textual information would also provide a visual balance to the book covers and bring more calmness into this overview while providing useful information to the user. 

(2) You could consider introducing a sidebar mode (an element users are already familiar with from the viewer component and would provide more aesthetic consistency across all components) to display the book metadata when a user clicks onto a book cover. For example, when the sidebar mode is _not_ activated, the usual popover with metadata would appear. When the sidebar mode _is_ activated, however, popovers would be deactivated and metadata information is instead displayed on the left side.

**Comment by johnfactotum** [comment]
This has been more or less addressed in the gtk4 branch.
