### ISSUE TITLE
Add separate section to Wiki about how to configure Foliate Flatpak via Flatseal

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#477]
Could you add information to the Wiki for Flatpak users to describe how to configure `Flatseal` in order to: 

- access offline dictionaries
- how to use text-to-speech functionalities
- display names for languages and regions

Currently the information in the Wiki is a bit scattered thematically and there is no mention of `Flatseal` for Flatpak permissions management. I think it would be great to have a separate section geared particularly towards Flatpak users.

**Comment by johnfactotum** [comment]
> access offline dictionaries
> how to use text-to-speech functionalities

`--talk-name=org.freedesktop.Flatpak` is enabled by default. No further configuration is required for these to work.

> display names for languages and regions

This is included in the runtime so no need for the user to do anything.

> there is no mention of Flatseal for Flatpak permissions management.

`--talk-name=org.freedesktop.Flatpak` is really the only permission of note. The other permissions are just standard display access. Network and audio access are self-explanatory.

> I think it would be great to have a separate section geared particularly towards Flatpak users.

I'm not sure what one would put in such a section? Apart from the need to spawn processes on the host, there's not really any difference when using Flatpak.

**Comment by digitalethics** [comment]
> `--talk-name=org.freedesktop.Flatpak` is really the only permission of note. The other permissions are just standard display access. Network and audio access are self-explanatory.

Which entry corresponds to the ones in Flatseal? The last one of these?

![flatpak_permissions](https://user-images.githubusercontent.com/57445091/85146812-48651a00-b24e-11ea-8e03-98764c1a7974.png)


> > display names for languages and regions
> 
> This is included in the runtime so no need for the user to do anything.

Where are these displayed?

**Comment by johnfactotum** [comment]
> Which entry in Flatseal corresponds to the permission you mentioned?

It's not shown in Flatseal. Flatseal doesn't support `--talk-name` permissions, as far as I can tell.

> Where are these displayed?

It's displayed when showing book metadata. The names are also used in the Google Translate popover.

**Comment by digitalethics** [comment]
> It's not shown in Flatseal. Flatseal doesn't support `--talk-name` permissions, as far as I can tell.

I see. This is good to know. Will see if this can be solved upstream then. 



> > Where are these displayed?
> 
> It's displayed when showing book metadata. The names are also used in the Google Translate popover.

I don't see any of these in the 2.3.0 Flatpak.

**Comment by johnfactotum** [comment]
> I don't see any of these in the 2.3.0 Flatpak.

![image](https://user-images.githubusercontent.com/50942278/85150539-2fef0280-b242-11ea-936e-9a741c126ddd.png)

![image](https://user-images.githubusercontent.com/50942278/85150347-f1f1de80-b241-11ea-91ff-93879647cc59.png)

**Comment by digitalethics** [comment]
Ah, I see. This doesn't work with all ebooks. I looked at the metadata of two books by _Open Book Publishers_ and _Likemind_ and both do not display the regions/flags, the other ones do.

**Comment by digitalethics** [comment]
![regionflag](https://user-images.githubusercontent.com/57445091/85153004-f2947000-b255-11ea-86dd-0f8ca0e5016a.png)

**Comment by johnfactotum** [comment]
Region code is optional. `en` is displayed as "English", whereas `en-US` is displayed as "English (United States)". The name "English" also comes from `iso-codes`. Without `iso-codes` it will only show "en".

**Comment by digitalethics** [comment]
> Without `iso-codes` it will only show "en".

I have `iso-codes` installed. Most ebooks indeed show the flag (Standard Ebooks, etc.). Then is the metadata of this particular ebook publisher not standards compliant or is there a way get Foliate to display it nevertheless?

**Comment by johnfactotum** [comment]
To clarify, the behavior is:
| language code set by the book | expected display with `iso-code` installed | display without `iso-code` installed | how it would be displayed prior to 2.3.0 |
| -- | -- | -- | -- |
| EN-CA | 🇨🇦 English (Canada) | en-CA | EN-CA |
| en-AU | 🇦🇺 English (Australia) | en-AU | en-AU |
| eng | English | eng | eng |
| EN | English | en | EN |
| asdfghjkl | _invalid code; doesn't show anything_ | _invalid code; doesn't show anything_ | asdfghjkl |

As for the reason why no flag is shown when no region is set, this is because
1. it would require additional package to achieve
2. region ≠ language, so displaying a flag would be improper anyway
