### ISSUE TITLE
Fix search in OPDS catalogues

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#478]
<kbd>Ctrl</kbd>+<kbd>F</kbd> prompts a search dialogue in the OPDS catalogues but it doesn't work. I think it would be good to also add a _search_ button like in the library component.

![catalogue_search](https://user-images.githubusercontent.com/57445091/85155355-f249a400-b258-11ea-9880-3c712cf058f9.gif)

**Comment by johnfactotum** [comment]
The Standard Ebooks feed doesn't support searching. That is why there's no search button. Ctrl+F should also be disabled, so yes, this is a bug.

**Comment by digitalethics** [comment]
> The Standard Ebooks feed doesn't support searching.

Or to fix it upstream?

**Comment by digitalethics** [comment]
@johnfactotum Searching the OPDS feed should be implemented now in Standard Ebooks.
