### ISSUE TITLE
Add option to hide items in library

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#479]
When using Foliate in a screen-sharing session, it would be great to have the option to temporarily hide items in the library.

**Comment by Knepherbird** [comment]
It seems to me a "filter" feature that can show/hide library items based on various criteria (author, title, etc.) might fulfil this need, in addition to providing a beneficial feature for library management/discoverability.

**Comment by johnfactotum** [comment]
You can already filter the library items based on the various metadata, although the functionality is kind of basic at the moment.

**Comment by johnfactotum** [comment]
I guess it makes more sense to use either automatic filtering or manual grouping to achieve similar effects. And for hiding items temporarily, it'd probably be easier to just close the whole library window.
