### ISSUE TITLE
Fix auto-hide header bar in Flatpak

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#484]
It is not possible to enable the auto-hide header bar function in all Foliate components when using the Flatpak.

**Comment by johnfactotum** [comment]
Auto-hide header bar can't be enabled when sidebar mode or skeuomorphic mode is enabled.

**Comment by digitalethics** [comment]
I see, I wasn't aware of that. Then I think there should be a simple usability fix for this.

![auto-hide header bar](https://user-images.githubusercontent.com/57445091/85375364-7db38580-b536-11ea-863f-4c57ba11ee91.gif)

When the auto-hide header bar feature is _enabled_ and a user subsequently _enables_ the sidebar, this will automatically _disable_ the auto-hide header bar. This is great! 
Conversely, usability will be better if enabling the auto-hide header bar will automatically disable the sidebar if it was previously enabled.

**Comment by digitalethics** [comment]
I think it also makes sense to _functionally_ group the skeuomorphic mode with these two features so that it is more apparent to the user that these will be automatically adjusted.

**Comment by johnfactotum** [comment]
> When the auto-hide header bar feature is enabled and a user subsequently enables the sidebar, this will automatically disable the auto-hide header bar.

It doesn't. Technically, auto-hide header bar is still enabled. It just doesn't have any actual effect. And the toggle in the UI is set to show up as not enabled to indicate this.

> Conversely, usability will be better if enabling the auto-hide header bar will automatically disable the sidebar if it was previously enabled.

Too complicated to implement for what is really a minuscule gain.
