### ISSUE TITLE
Rename Realistic Shadows to Page Shadows

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#485]
The skeuomorphic mode is actually more than just realistic shadows as it also imitates the book form. As a name it is also more inviting and will prompt new users to experiment. Maybe something like this: 

Skeuomorphic Mode
<sub>Imitates realistic shadows and text blocks</sub>

**Comment by apandada1** [comment]
To me, Realistic Shadows makes more sense than Skeuomorphic Mode (I am a non-native speaker of English). Realistic Mode may be even better.

**Comment by digitalethics** [comment]
> Realistic Mode may be even better.

I think both "realistic" and "shadows" are too unspecific terms. How about _Book_ mode? Actually the idea is not to just replace _Realistic Shadows_ with _Skeuomorophic Mode_ but to additionally add a small text below to give it context.

**Comment by johnfactotum** [comment]
- **Realistic Shadows** - it might be a bit unclear as to what "shadows" means at first glance; it's not inaccurate, though. As it stands, the mode is _primarily_ about shadows.
- **Skeuomorphic Mode** - perhaps the most accurate; my issue with it is that it feels more like a technical term and probably not very friendly for many users.
- **Book mode** - I don't think this makes sense, because they are all "books", just not "real" (i.e. physical) books.
- **Realistic Mode** - I actually kind of like this one. Maybe **Realistic Pages**? But that kind of feel like it's referring to some kind of page turning effect, which it isn't.

**Comment by digitalethics** [comment]
> **Book mode** - I don't think this makes sense, because they are all "books", just not "real" (i.e. physical) books.

Yeah, agreed. 

> **Skeuomorphic Mode** - perhaps the most accurate; my issue with it is that it feels more like a technical term and probably not very friendly for many users.

Yes. However, it could have a positive effect and being picked up fairly quickly despite its terminology. In fact, omg! ubuntu! mentions it explicitly in the article [Foliate is an Epic eBook Reader for Linux Desktops](https://www.omgubuntu.co.uk/2019/05/foliate-ebook-reader-linux) as the "Skeuomorphic ‘page shadow’ option."

**Comment by digitalethics** [comment]
How about replacing **Realistic Shadows** with **Page Shadows** if implemented as an option in the _Preferences_ or its current position in the menu popover? Conceived of as an _additional_ part of a new reading mode overview, **Skeuomorphic Mode** ist probably more fitting. I still think that **Realistic Mode** essentially lacks an object (what is supposed to be realistic?), however when comparing it to a future **Minimalist Mode** (with all potential distractions removed) it might make sense again.

**Comment by digitalethics** [comment]
Renaming title to decouple this a bit from the discussion about introducing _reading modes_ which is really meant as an entirely separate, additional issue.

**Comment by johnfactotum** [comment]
I think instead of having a single toggle, maybe it should be like

> Page Style
> [ ] Simple
> [ ] Realistic

This has the additional advantage of accommodating further styles, or even custom styles.

Or it can be like the day/night toggle in elementary apps, like

> Simple    [toggle here]   Realistic

**Comment by digitalethics** [comment]
> I think instead of having a single toggle, maybe it should be like

This is it! Fantastic!

**Comment by johnfactotum** [comment]
Closing as there's no skeuomorphic mode anymore. Not that I don't find it useful but removing it does significantly reduce the maintenance burden.
