### ISSUE TITLE
Add reading ruler

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#488]
Reading rulers are not very common in digital reading applications yet, making ebooks less accessible than they should be. The idea is to have a mobile tinted overlay "floating" above the viewer component. Cursor movement is tracked and the reading ruler attached to cursor movement moves up- or downwards. 

This greatly helps young readers, people suffering from visual stress and can also be very beneficial for any type of research-oriented reading, especially philosophical works. How difficult would this be to realize technically? I didn't look much into what technical implementations are already out there but here are some initial ideas: 

1. This should be a horizontal ruler moving vertically of course.

![imageviewer](https://user-images.githubusercontent.com/57445091/85428969-45d03080-b57e-11ea-8411-8e28f0e3aad2.gif)

2. Demonstration on the website of the [Dyslexia Action Shop](https://dyslexiaactionshop.co.uk/virtual-reading-ruler-11-50-users.html).
![ruler](https://user-images.githubusercontent.com/57445091/85429558-2ede0e00-b57f-11ea-9363-f152649a5c65.gif)

**Comment by johnfactotum** [comment]
I think this probably makes more sense as a separate tool? Like a GNOME Shell extension or something.

**Comment by digitalethics** [comment]
> I think this probably makes more sense as a separate tool? Like a GNOME Shell extension or something.

Mhm, I'm not sure. Foliate probably has users from all three dominant design paradigms or environments, elementary OS/Pantheon, GNOME Shell, and KDE Plasma. In fact, I'm using Plasma but I have a strong preference for GNOME application design (but I'm not very familiar with them yet). An in-house solution would be great unless there is already an agnostic tool out there that works well regardless of what desktop environment is being used?

Maybe @danielweck has some more ideas about this?

**Comment by johnfactotum** [comment]
> unless there is already an agnostic tool out there that works well regardless of what desktop environment is being used?

This should be provided as a accessibility tool by the desktop environment. That way it can be used with all applications. In Wayland, applications can't access the global cursor location, so this requires support from the compositor; so there probably won't be an "agnostic" tool as such. But I don't really see the issue with that, since the DE is a natural place to implement universal access features.
