### ISSUE TITLE
FB2: Ampersand in titles causes error

### ISSUE THREAD

**Issue by Carmina16** [johnfactotum/foliate#496]
FB2 books with `&amp;` in a title tag do not load with "The string did not match the expected pattern" error message.

**Comment by johnfactotum** [comment]
I can't reproduce this. Are you running the master branch? Can you provide an example file?

**Comment by Carmina16** [comment]
I use the latest released version. If you replace ampersand in this file, it should open OK.

[fail.fb2.gz](https://github.com/johnfactotum/foliate/files/4833111/fail.fb2.gz)

**Comment by johnfactotum** [comment]
I can reproduce this with 2.3.0, but on master the book already opens normally.

FB2 parsing/rendering was almost completely rewritten in e594e47d07e20c4293906b5d3f6a1e97f882ce64. It'd be great if you can test with the latest master and see if there's any problems.
