### ISSUE TITLE
Add support for more dictionaries

### ISSUE THREAD

**Issue by dearfl** [johnfactotum/foliate#5]
Thx for this amazing ebook reader
I'm wondering if there will be chinese translation support
or how can I implement one. not familiar with js though.

**Comment by johnfactotum** [comment]
Do you mean a feature like: user selects a passage and the app displays a machine translation?

If that's what you mean, I don't think it would be hard to implement. It would be very similar to the existing dictionary feature.

But I'm not sure which translation service would best fit the need.

**Comment by dearfl** [comment]
Actually what I thought was english->chinese dictionary, which is more than enough, I think.

**Comment by johnfactotum** [comment]
Ah. Well, yes, currently it only supports https://en.wiktionary.org/, but there's a Chinese version at https://zh.wiktionary.org/. (174 language total currently, actually)

The Chinese version is a bit lacking in terms of its contents, though. And the formatting is a lot more inconsistent compared to the English Wiktionary, so getting good output out of it might be a bit more difficult.

It doesn't *have* to be Wiktionary, obviously. It'd be nice to add other online or offline dictionaries, **provided that the data is free, preferably *gratis* as well as *libre***.

**Comment by johnfactotum** [comment]
Oh other hand, it might be useful to consider a sort of *plugin* system. So anyone can create their own dictionary/translation plugin easily without.

**Comment by itprojects** [comment]
@johnfactotum  Offline multiple dictionaries' implementation with dictd

1. Required packages: dictd dict-gcide dict-wn dict-moby-thesaurus
2. Following code integrated into Foliate:

`
const ByteArray = imports.byteArray;
const GLib = imports.gi.GLib;

function dictd(word) {
    try {
        let definition = ByteArray.toString(GLib.spawn_command_line_sync("dict " + word)[1]);
        print(definition);
    } catch (e) {
        return -1;
    }
}

if (ARGV.length != 1) {
    printerr('Error: empty given word, nothing to define');
} else {
    dictd(ARGV[0]);
}
`

3. Test the above script with: gjs ./file.js

**Comment by itprojects** [comment]
Can any user please check if the code above works on their machine?

**Comment by itprojects** [comment]
@johnfactotum Can you check if the script in https://github.com/johnfactotum/foliate/issues/5#issuecomment-504656701, and comment?

**Comment by johnfactotum** [comment]
I didn't try the script, but it looks valid to me. Note that simply calling `ByteArray.toString` might not work in older GJS versions. See e274a21b25f660ac429a6cf50b8d2fd64c644de0.

**Comment by itprojects** [comment]
Can you confirm that to be the case?

**Comment by johnfactotum** [comment]
With GJS 1.52.5
```javascript
imports.byteArray.toString(imports.gi.GLib.spawn_command_line_sync('dict test')[1])
// => returns "[object GjsModule byteArray]"

imports.gi.GLib.spawn_command_line_sync('dict test')[1].toString()
// => works
```

See https://www.reddit.com/r/gnome/comments/a39xfg/psa_gjs_and_bytearrays/, "Backwards-compatible check & conversion".

**Comment by itprojects** [comment]
And did the offline wiktionary work?

**Comment by itprojects** [comment]
Confirmed to work on Ubuntu 10.94.
