### ISSUE TITLE
Allow automatic download from RSS subscription

### ISSUE THREAD

**Issue by JamesSwift** [johnfactotum/foliate#501]
A magazine I read has an RSS feed but no OPDS. Would it be possible to automatically download epubs from an RSS feed?

**Comment by johnfactotum** [comment]
Why not just use an RSS reader?

**Comment by digitalethics** [comment]
I think this is somewhat related to one of my earlier requests, see: #217 
Converting magazine or blog content which is distributed via RSS into epubs would be a great for two reasons I guess: 
- added security benefits
- ability to annotate

**Comment by JamesSwift** [comment]
I think I didn't explain properly earlier. The RSS feed in question is a list of epub files, so no conversion is needed. In the end I just wrote a PHP script to fetch them for me, but I still think it would be nice to have a similar feature embedded within foliate. In PHP it's only about 15 lines of code. But its not essential.

2 Jul 2020 16:26:50 Martin <notifications@github.com>:

**Comment by johnfactotum** [comment]
@JamesSwift Why not use a dedicated feed reader? A feed reader should allow users to download "attachments". Some might even support auto-download.

@digitalethics

> added security benefits

How would converting them to EPUB make anything more secure? If anything, I'd say it makes things _less_ secure; it just adds another layer which means another attack surface.

> ability to annotate

What does that have to do with EPUB? You can implement annotation for feed readers. Feedly, for example, supports annotations.

**Comment by JamesSwift** [comment]
I could, I just don't use one. It's not an important feature, just a nice to have.

2 Jul 2020 17:08:57 John Factotum <notifications@github.com>:

**Comment by johnfactotum** [comment]
Closing as out of scope.
