### ISSUE TITLE
Foliate will jump to wrong location in Japanese books

### ISSUE THREAD

**Issue by Arvamer** [johnfactotum/foliate#502]
**Describe the bug**
Resuming reading book, jumping to annotation or bookmark, or when resizing window foliate will open book on wrong page. For example, after clicking on bookmark instead of opening on page with `epubcfi(/6/20[x_p-001]!/4/2/24/1:0)` visible, foliate will open on chapter beginning (`epubcfi(/6/20[x_p-001]!/4/2/2/1:0)`).

**To Reproduce**
This bug can be observed on [*Kusamakura* from epub3 samples](https://github.com/IDPF/epub3-samples/releases/download/20170606/kusamakura-japanese-vertical-writing.epub). (there are also some other bugs related to page switching visible with this sample)

1. Go few pages after start of new chapter
2. Resize Foliate or reopen book
4. You will see beginning of chapter (or rather empty page before chapter in this epub sample)

This behaviour is much harder to reproduce on *Requirements for Japanese Text Layout* sample, potentially because of high number of words written in latin script.

**Expected behavior**
Book should be opened with resource referenced by EPUB CFI visible.

**Version:**
 - Foliate version: 2.3.0
 - OS/Distribution and version: Arch 
 - Desktop environment: GNOME 3.36
 - Installation method: from arch repos

**Comment by johnfactotum** [comment]
Yeah, I did notice this (among other issues with vertical writing). In general Epub.js currently doesn't support vertical writing that well, particularly on WebKit. Can you report this upstream? https://github.com/futurepress/epub.js/

To reproduce this with Epub.js, clone Epub.js and run `npm run prepare`, then open the file with `/examples/input.html`. From the console you can run `rendition.display(cfi)`.

**Comment by Arvamer** [comment]
Opened issue in epub.js repo: futurepress/epub.js#1093

**Comment by johnfactotum** [comment]
Fixed in the new renderer (https://github.com/johnfactotum/foliate/issues/962).
