### ISSUE TITLE
link in to EPUB Canonical Fragment Identifiers is dead 

### ISSUE THREAD

**Issue by eksperimental** [johnfactotum/foliate#506]
**Describe the bug**
link in to EPUB Canonical Fragment Identifiers is dead 
https://www.idpf.org/epub/linking/cfi/

**To Reproduce**
go to https://github.com/johnfactotum/foliate/wiki#how-are-notes-and-bookmarks-stored

**Expected behavior**
replace with the following link (no https)
http://idpf.org/epub/linking/cfi/epub-cfi.html

**Comment by johnfactotum** [comment]
Done.
