### ISSUE TITLE
Icon is not displayed on panel window buttons

### ISSUE THREAD

**Issue by ranayas** [johnfactotum/foliate#508]
There is no icon on Xfce Window Buttons panel plugin

![foliate-error](https://user-images.githubusercontent.com/65342923/86283257-497b3d00-bba6-11ea-9a87-0f33fa459619.png)

 - Foliate version: 2.3.0
 - OS/Distribution and version: Debian GNU/Linux 10 (buster) x86_64
 - Desktop environment: Xfce 4.12
 - Installation method: com.github.johnfactotum.foliate_2.3.0_all.deb
 file from releases page

**Comment by johnfactotum** [comment]
Duplicate of #456
