### ISSUE TITLE
Details, link, download progress bar and button colours

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#512]
I think it should be "details" instead of "detail": 

![opds_detail](https://user-images.githubusercontent.com/57445091/86379463-2b3b3d00-bc8b-11ea-8d80-5aaba215c669.gif)

I'm not sure if this is intended but the link colour changes from _blue_ to _grey_ after it was clicked:

![opds_linkcolour](https://user-images.githubusercontent.com/57445091/86380078-f976a600-bc8b-11ea-91ad-44e302fb7706.gif)

How about changing button, link and download progress bar colours to match the green-turquoise colour tones of the Foliate icon? Maybe something like #00CACA or #0BB8B8?

**Comment by johnfactotum** [comment]
> I'm not sure if this is intended but the link colour changes from blue to grey after it was clicked

It indicates that the link is _visited_. It's a GTK feature. The color is controlled by the theme.

> How about changing button, link and download progress bar colours to match the green-turquoise colour tones of the Foliate icon? Maybe something like #00CACA or #0BB8B8?

The color is controlled by the user's theme.

**Comment by digitalethics** [comment]
> The color is controlled by the user's theme.

Some solutions to this problem have been proposed by introducing [vendor **styles**](https://discourse.gnome.org/t/gtk-adwaita-and-vendor-styles/1641/9) and [custom colour **palettes**](https://etherpad.gnome.org/p/VendorThemes2019/timeslider#1619) as opposed to **[themes](https://stopthemingmy.app/)**.

**Comment by apandada1** [comment]
Currently, Foliate beautifully adapts a lot of third party themes (actually, all themes I have used so far) in Cinnamon/GNOME/KDE/XFCE, and so far no major bugs related to themes have shown up. Please don't lock it (using vendor styles) to a particular theme, as it would look totally out of place for those who would be using a different system theme.

**Comment by digitalethics** [comment]
> Please don't lock it (using vendor styles) to a particular theme

If I understand it correctly, actually the very opposite is intended with the introduction of vendor styles and they are not really related to themes either. The idea is not to hardcode values but instead to expose colour palettes as CSS variables. See this [discussion](https://gitlab.gnome.org/GNOME/Initiatives/-/issues/11) for example.

**Comment by johnfactotum** [comment]
Setting a "branding" color is already possible now for the elementary theme (not sure if it requires granite). Otherwise it's barely a proposal at the moment.

Anyway, it's not really that important, in my opinion. It's just a color without any semantic significance, only for branding, which I don't think is really needed in Foliate's case. In any case the end user will probably always be able to apply custom GTK stylesheets no matter how GTK's theming "API" changes in the future.
