### ISSUE TITLE
Theme setting is ignored while loading books

### ISSUE THREAD

**Issue by coderbot16** [johnfactotum/foliate#513]
**Describe the bug**
No matter what theme you have configured, the loading screen is always displayed in full white. This is pretty jarring, especially at night.

**To Reproduce**
1. Open any large MOBI / EPUB file with Foliate
2. Watch as the window opens in plain white
3. When the book fully loads, the theme is applied as expected.

**Expected behavior**
Foliate should use the configured theme immediately, preferably before the window is opened so it doesn't flash white (or in this case, display it for several seconds as the file is loaded).

**Screenshots**
![image](https://user-images.githubusercontent.com/22420959/86399231-c0bed880-bc5b-11ea-981b-8a88ca394b92.png)

**Version:**
 - Foliate version: 2.4.0
 - OS/Distribution and version: Ubuntu Budgie 18.04
 - Desktop environment: Budgie
 - Installation method: Flatpak

**Additional context**
This happens with all files, but it's more severe for large MOBI / EPUB files because they take a long time to load.

**Comment by johnfactotum** [comment]
The problem here seems be the same as #470. Also after porting to libadwaita we should probably colorize the whole UI with the theme color.
