### ISSUE TITLE
Preferences dialog is not opened

### ISSUE THREAD

**Issue by wenzezlaus** [johnfactotum/foliate#516]
**Describe the bug**
Preferences dialog is not opened from the primary menu

**To Reproduce**
1. Start foliate (either in library or in reading mode);
2. Click on primary menu button and then on "Preferences";
3. No preferences dialog is opened. The following message is shown:

(com.github.johnfactotum.Foliate:13480): Gjs-WARNING **: 14:47:52.526: JS ERROR: Error: GSettings key opds-action not found in schema com.github.johnfactotum.Foliate.library
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:576:23
_init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:528:30
preferences@resource:///com/github/johnfactotum/Foliate/js/main.js:95:44
main@resource:///com/github/johnfactotum/Foliate/js/main.js:474:24
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
@/usr/bin/foliate:9:17

**Expected behavior**
Preferences dialog is opened, no error messages

**Version:**
 - 2.4.0
 - Arch linux
 - Desktop environment: KDE Plasma 5.19
 - Installation method: binary package foliate-2.4.0-2-x86_64.pkg.tar.zst

**Additional context**
The same bug occurs in the current git version but not in release 2.3.
Presumably, it is related to the commit 733e5c3.

**Comment by wenzezlaus** [comment]
The bug is presumably caused by the changes in src/main.js (commit 733e5c3)

**Comment by johnfactotum** [comment]
> Error: GSettings key opds-action not found in schema com.github.johnfactotum.Foliate.library

I think something's wrong with your installation. The key should exist.

**Comment by wenzezlaus** [comment]
The key does exist in /usr/share/glib-2.0/schemas/com.github.johnfactotum.Foliate.gschema.xml. Nevertheless the error occurs.

**Comment by wenzezlaus** [comment]
Well, you are right... After recent update (dbus and lib32-dbus to 1.12.20,  glib2 and lib32-glib2 to 2.64.4) the issue is gone. So it was caused by my installation. Thank you, the issue is closed.
