### ISSUE TITLE
Why epub.js instead of readium-js?

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#517]
I looked around a bit but didn't find any satisfying information comparing these two libraries. Are epub.js and readium-js two competing rendering engines or do they aim at entirely different target groups and use cases? I'm curious as to why you opted for epub.js instead of readium-js and what the specific advantages and disadvantages are of one over the other. Was your choice of using JavaScript for the Foliate project also derived from these engines being written in JavaScript or would it also have made sense to write Foliate in a language such as Rust or Go?

**Comment by johnfactotum** [comment]
> I'm curious as to why you opted for epub.js instead of readium-js

I didn't really look very deeply into other EPUB backends. Epub.js is pretty popular and I sort of just went with it.

> what the specific advantages and disadvantages are of one over the other.

Like I said, I didn't really look into other EPUB backends, but in Readium's case, it seems to be very similar to Epub.js in terms of the main method of rendering (CSS columns in iframes).

> Was your choice of using JavaScript for the Foliate project also derived from these engines being written in JavaScript or would it also have made sense to write Foliate in a language such as Rust or Go?

It was mainly just that I personally am most familiar with JavaScript. There isn't really a technical advantage in using the same language for GTK and the web component. Although I did end up including a piece of Epub.js in the GJS part of the code, so there's that.
