### ISSUE TITLE
Navigation using arrow keys not working as expected on foliate

### ISSUE THREAD

**Issue by janaabpakaal** [johnfactotum/foliate#523]
LInux Desktop with Arch Linux:
Foliate is a nice software to read ebooks, but i have noticed arrow keys on my keyboard do not work as expected to move to next page or back page while in automatic read mode , I tried Bookworm , edr.thorium softwares and they work as expected, only issue with foliate .Please suggest .

**Comment by johnfactotum** [comment]
The arrow shortcuts only work when the view is focused. For the reason see https://github.com/johnfactotum/foliate/issues/308#issuecomment-616294886.
