### ISSUE TITLE
Cannot use offline dictionary 

### ISSUE THREAD

**Issue by Arcadio-Buendia** [johnfactotum/foliate#525]
I am not able to look up a word in offline dictionary. I have dict, dict-wn and dictd installed and can look up words with dict "word" from the terminal. Opening foliate from terminal and trying to look up a word gives me this:

> Gjs-Message: 16:57:08.690: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/lookup.js 373]: reference to undefined property "null"
> 
> (com.github.johnfactotum.Foliate:668242): Gjs-WARNING **: 16:57:08.691: JS ERROR: TypeError: dictionaries[dict] is undefined
> _lookup@resource:///com/github/johnfactotum/Foliate/js/lookup.js:373:9
> _lookupFromEntry@resource:///com/github/johnfactotum/Foliate/js/lookup.js:364:24
> lookup@resource:///com/github/johnfactotum/Foliate/js/lookup.js:358:14
> selection-dictionary@resource:///com/github/johnfactotum/Foliate/js/window.js:596:23
> _connectEpub/<@resource:///com/github/johnfactotum/Foliate/js/window.js:1064:64
> _handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:920:22
> _init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:615:18
> main@resource:///com/github/johnfactotum/Foliate/js/main.js:474:24
> run@resource:///org/gnome/gjs/modules/script/package.js:222:19
> @/usr/bin/com.github.johnfactotum.Foliate:9:17

 - Foliate version: 2.4.2
 - OS/Distribution and version: Debian Sid
 - Desktop environment: I3 WM
 - Installation method: .deb package, I tried flatpak earlier but couldn't access the dictionary even then.

**Comment by johnfactotum** [comment]
Looks like for some reason your current default dictionary is set to "null", which does not exist. Try running `gsettings reset com.github.johnfactotum.Foliate dictionary` to reset it to the default dictionary, or `gsettings set com.github.johnfactotum.Foliate dictionary dcitd_wn` to use WordNet.

I suppose this should be considered a bug as it should handle the non-existent of the selected dictionary more gracefully.

Also I just noticed now that the prefix `dictd_` was misspelled as `dcitd_` (this does not affect functionality, just looks weird).
