### ISSUE TITLE
Add "Check for updates" in menu

### ISSUE THREAD

**Issue by ranayas** [johnfactotum/foliate#528]
It would be great if Foliate notifies users that they have downloaded the .deb file from releases page or manually build it from source that there is a new release. an option to "check for updates" in "about foliate".

**Comment by apandada1** [comment]
That is why Foliate is also distributed through various [package managers](https://johnfactotum.github.io/foliate/#installation), where updates for all packages will be managed centrally. If the user decides to manually build from source/install from a .deb file, it is the responsibility of the user to manually check for updates. This is a standard practice in GNU/Linux distributions.

Adding "check for updates" in Foliate itself will somewhat unnecessarily bloat it.

**Comment by johnfactotum** [comment]
For what it's worth, I made a simple CLI app for checking updates for any app that uses AppData and GitHub releases: https://gist.github.com/johnfactotum/eb76ffae98540aca7563b5a1807903a0. It depends on `gir1.2-appstreamglib-1.0` and `gir1.2-soup-2.4`.

To check updates for Foliate, run:
```sh
gjs appstream-checkupdate.js /usr/share/metainfo/com.github.johnfactotum.Foliate.appdata.xml
```

You can check updates for all your apps with
```
gjs appstream-checkupdate.js /usr/share/metainfo/*
```

**Comment by apandada1** [comment]
@johnfactotum It may be a good idea to to add it to the Readme.

**Comment by ranayas** [comment]
Cool hack! I agree with @apandada1
