### ISSUE TITLE
Enhancement - Option to tweak Themes

### ISSUE THREAD

**Issue by Stele77** [johnfactotum/foliate#53]
Hi!
First of, big Kudos for this App! I Tried all ebook readers on Linux, and you just topped my list, beating Apps that have been developed for a far longer time than Foliate!
It is solid, great looking and integrating into my Adwaita GNOME 3 Desktop, and feels pretty polished already.

What i miss compared to e.g. Bookworm: The ability to tweak how the text is displayed:
-Option to increase/decrease the space between window border and text (like having the App fullscreen, but with the text only in the middle)
-Option to select background and text color
Those 2 options would go a big way in having a more comfortable reading environment, so thank you in advance for any consideration, for all the work you already did, and any future time you invest!
Best Wishes!

**Comment by johnfactotum** [comment]
Basic support for custom themes has been added (b12683e03374fa69d8e746fee02932ac0feff9bb).

To setup custom themes, make a JSON file called `themes.json`, and specify your themes like this:

```json
{
    "themes": {
        "Light": {
            "color": "#000",
            "background": "#fff",
            "link": "blue",
            "darkMode": false,
            "invert": false
        },
        "Nord": {
            "color": "#d8dee9",
            "background": "#2e3440",
            "link": "#88c0d0",
            "darkMode": true,
            "invert": false
        },
        "Nord Invert": {
            "color": "#171f27",
            "background": "#c0c8d1",
            "link": "#467381",
            "darkMode": true,
            "invert": true
        }
    }
}
```

Put this file in `~/.config/com.github.johnfactotum.Foliate` or, if using Flatpak `~/.var/app/com.github.johnfactotum.Foliate/config/com.github.johnfactotum.Foliate`.

The result looks like this:

![Image](https://user-images.githubusercontent.com/50942278/59148145-89e4a780-89f4-11e9-898a-a19a7c80404d.png)
[Nord](https://github.com/arcticicestudio/nord) colors works very well if you use the [Arc](https://github.com/NicoHood/arc-theme) theme.

Not configurable from the UI for now, but should be quite useful.

**Comment by johnfactotum** [comment]
Support for customizing page margin has been added (7ae979d03933c3c61e6199e0fd78ce073dbce71c)

**Comment by johnfactotum** [comment]
UI has been added in 5cee0e2164524ceae2f36eb87eb26afa5fa30673 and 746658eea825c9e49ef8d61d1845a88fa32c719b.

![image](https://user-images.githubusercontent.com/50942278/59548758-54cfdc00-8f43-11e9-8b4d-e99f5ed5f1d9.png)

**Comment by Stele77** [comment]
Hi John! I am sorry i did not reply earlier (my life is a bit of a mess right now ;) ). Just want to say thank you!
You are amazing, and so is Foliate!
I am still new to Linux, but things like this just make me even more happier for my move away from Windows!
Thanks again, and all the best for you and your projects!

**Comment by brymer-meneses** [comment]
Hello @johnfactotum, I wanted to do just this. However, I am using an installation from snap. How can I do this?
