### ISSUE TITLE
Foliate crashes when trying to import annotations

### ISSUE THREAD

**Issue by BogomilTomov** [johnfactotum/foliate#531]
First, I want to thank everybody involved in the development of this beautiful piece of software.

I was using Foliate v. 1.5 on my MX Linux desktop machine and annotating my books, all was working fine. Today I decided to upgrade to 2.4 using flatpak. After the re install my annotations didn't automatically appear on the books so I tried manually importing the JSON files (I haven't exported manually, I am copying the JSONs from .local/share/com.github.johnfactotum.Foliate).

Foliate recognizes the annotation but when I click on Import I get all kinds of strange behavior - sometimes it crashes immediately, sometimes it hangs for a few seconds and crashes, sometimes it says the identifier is different and crashes. 

I only managed to import properly once so I know it _can_ work.

Am I doing something wrong or is this a real issue?

Regards

**Comment by johnfactotum** [comment]
You should be able to manually copy all the files from `~/.local/share/com.github.johnfactotum.Foliate` to `~/.var/app/com.github.johnfactotum.Foliate/data/com.github.johnfactotum.Foliate`, which is where the annotations are stored for Flatpak. Although this won't work if the identifier is different (unique identifier extraction was changed in 2.4.0 so for some books the identifier will be different).

> Am I doing something wrong or is this a real issue?

I don't think you're doing anything wrong. There are some GTK critical warnings when importing, which is definitely a bug that needs to be fix. But it shouldn't crash, and at least it hasn't crashed so far for me. Can you run the app from the command line and post the output?

**Comment by johnfactotum** [comment]
From your description, I think it's probably the bug mentioned above that's causing it to hang and/or crash. It can work when the number of annotations is low, but it's definitely a lot more serious when importing more annotations.

**Comment by BogomilTomov** [comment]
Thanks for the answer. Tried manually copying all the files, it worked  on a few books but annotations still didn't show on most, although the app didn't crash either.

How can I run a flatpak app from the command line?

**Comment by apandada1** [comment]
Use the command `flatpak run com.github.johnfactotum.Foliate`

**Comment by BogomilTomov** [comment]
Portal call failed: Failed to start command: Failed to execute child process “sdcv” (No such file or directory)

(com.github.johnfactotum.Foliate:3): Gjs-CRITICAL **: 21:00:20.485: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.

(com.github.johnfactotum.Foliate:3): Gjs-CRITICAL **: 21:00:20.485: The offending callback was ListBoxUpdateHeaderFunc().
== Stack trace for context 0x5625778a91a0 ==
#0   7ffde0d92ee0 b   resource:///com/github/johnfactotum/Foliate/js/contents.js:193 (120a66a33ad8 @ 417)
#1   7ffde0d92f90 b   resource:///com/github/johnfactotum/Foliate/js/contents.js:203 (120a66a33cb8 @ 78)
#2   7ffde0d947a0 I   resource:///com/github/johnfactotum/Foliate/js/epubView.js:252 (120a66a1c790 @ 448)
#3   7ffde0d948a0 b   resource:///com/github/johnfactotum/Foliate/js/epubView.js:1147 (120a66a224c0 @ 25)
#4   7ffde0d94960 b   resource:///com/github/johnfactotum/Foliate/js/window.js:688 (120a66a09e20 @ 20)
#5   7ffde0d94a70 b   self-hosted:266 (19f9391ac268 @ 259)
#6   56257795a4d0 i   resource:///com/github/johnfactotum/Foliate/js/window.js:687 (120a66a09da8 @ 70)
#7   56257795a410 i   resource:///com/github/johnfactotum/Foliate/js/main.js:474 (19f9391c6718 @ 513)
#8   56257795a370 i   resource:///org/gnome/gjs/modules/script/package.js:222 (19f93918d538 @ 45)
#9   56257795a2e0 i   /app/bin/com.github.johnfactotum.Foliate:9 (19f93918d178 @ 53)

(com.github.johnfactotum.Foliate:3): Gjs-CRITICAL **: 21:00:20.486: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.

(com.github.johnfactotum.Foliate:3): Gjs-CRITICAL **: 21:00:20.486: The offending callback was ListBoxCreateWidgetFunc().
== Stack trace for context 0x5625778a91a0 ==
#0   7ffde0d92ee0 b   resource:///com/github/johnfactotum/Foliate/js/contents.js:193 (120a66a33ad8 @ 417)
#1   7ffde0d92f90 b   resource:///com/github/johnfactotum/Foliate/js/contents.js:203 (120a66a33cb8 @ 78)
#2   7ffde0d947a0 I   resource:///com/github/johnfactotum/Foliate/js/epubView.js:252 (120a66a1c790 @ 448)
#3   7ffde0d948a0 b   resource:///com/github/johnfactotum/Foliate/js/epubView.js:1147 (120a66a224c0 @ 25)
#4   7ffde0d94960 b   resource:///com/github/johnfactotum/Foliate/js/window.js:688 (120a66a09e20 @ 20)
#5   7ffde0d94a70 b   self-hosted:266 (19f9391ac268 @ 259)
#6   56257795a4d0 i   resource:///com/github/johnfactotum/Foliate/js/window.js:687 (120a66a09da8 @ 70)
#7   56257795a410 i   resource:///com/github/johnfactotum/Foliate/js/main.js:474 (19f9391c6718 @ 513)
#8   56257795a370 i   resource:///org/gnome/gjs/modules/script/package.js:222 (19f93918d538 @ 45)
#9   56257795a2e0 i   /app/bin/com.github.johnfactotum.Foliate:9 (19f93918d178 @ 53)

**Comment by BogomilTomov** [comment]
The new annotations I create import well on another computer so I guess I will test the export/import features when I update.

On a side note - I often read on my Android tablet, does anyone know a way to make annotations that are compatible with Foliate. 

Thanks

**Comment by johnfactotum** [comment]
Importing annotations has been redone in c09b9b53a068485783a12df008684e93e2bad681.
