### ISSUE TITLE
Reload doesn't work

### ISSUE THREAD

**Issue by fedelibre** [johnfactotum/foliate#544]
Reload (Ctrl+R shortcut) doesn't work.

Steps to reproduce:

- open the epub file
- update the content and regenerate the epub
- Ctrl+R to reload the document

I keep seeing the old content. I have to close Foliate and reopen it in order to see the new content.

**Version:**
 - Foliate version: 2.4.2
 - OS/Distribution and version: Fedora 32
 - Desktop environment: GNOME 3.36
 - Installation method: Flatpak

**Comment by jdbosser** [comment]
Hi! I am experiencing the same issue. I have never contributed to an open source project, but I would be interested in giving it a go and try to fix this.

**Comment by johnfactotum** [comment]
I'm not sure what's causing this either.

Might be that the file is cached by WebKit (files are fed to Epub.js as a file URI, which I think Epub.js then fetches with XMLHttpRequest). This seems plausible, as reloading after deleting the file works as expected, but not after merely modifying it.

But I'm not sure how to clear this cache. Calling [`webkit_web_context_clear_cache ()`](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebContext.html#webkit-web-context-clear-cache) does not appears to have any effect.

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.
