### ISSUE TITLE
Continuous scrolling is very slow for some epub books

### ISSUE THREAD

**Issue by dspacejs** [johnfactotum/foliate#545]
**Describe the bug**
Continuous scrolling is painfully slow for some epub books. I haven't noticed this in all books, it seems to depend on the size of the book.

**To Reproduce**
1. Download and open The Mind Illuminated by Culadasa epub book (I can't provide a source for this unfortunately)
2. Turn on continuous scrolling
3. Scroll down the page, it will be very choppy and slow
4. Try clicking on a section on the sidebar, it will take a very long time to load and jump to it

**Expected behavior**
Continuous scrolling should always be fluid and snappy, regardless of the size of the book.

**Screenshots**
This doesn't look or feel as choppy as it actually is because it's a gif:

![Peek 2020-07-30 15-42](https://user-images.githubusercontent.com/9282837/88887337-5d848e00-d27b-11ea-81ba-5a50dfb62b43.gif)

**Version:**
 - Foliate version: 2.4.2
 - OS/Distribution and version: Ubuntu 20.04 LTS
 - Desktop environment: Gnome 3.36.3
 - Installation method: apt

**Comment by apandada1** [comment]
It looks like continuous scrolling consumes a lot of CPU cycles.

**Comment by johnfactotum** [comment]
This is really an upstream [Epub.js](https://github.com/futurepress/epub.js/issues) issue.

**Comment by dspacejs** [comment]
Update: I've noticed this same issue with other books. It's also happening with the "scrolled" setting. This is a pretty big issue for me as a user, it inhibits the reading experience.

**Comment by Dreomite** [comment]
It was a problem half a year ago as well, when I started using Foliate.

The only related issue in epub.js repo I could find is https://github.com/futurepress/epub.js/issues/714 which was closed 2 years ago. Should we ask to reopen it?

**Comment by dspacejs** [comment]
@Dreomite I'd say so. I'll make a comment.

**Comment by dspacejs** [comment]
@johnfactotum as seen in this thread: https://github.com/futurepress/epub.js/issues/714

It looks like they're not going to fix this anytime soon, so we can't rely on them. However, there's a quick hotfix which can be used (mentioned in that thread). If the repo is forked, this can be used in the meantime until they fix it.

**Comment by johnfactotum** [comment]
If you're interested in working on this issue, Foliate currently uses Epub.js built from this fork: https://github.com/johnfactotum/epub.js. The workflow for now is basically running `npm run build` and manually copying `dist/epub.js` to Foliate's `src/web/epub.js`.

**Comment by dspacejs** [comment]
@johnfactotum thanks, I'll hopefully have some time to do that. If not, if anyone else is interested feel free to go ahead because I may be a while.

**Comment by johnfactotum** [comment]
I think this can be closed now. In scrolled mode, the [new renderer](https://github.com/johnfactotum/foliate/issues/962) only calculates current location after debouncing (see https://github.com/johnfactotum/foliate/issues/861#issuecomment-1021836410), which fixes the problem.

The new renderer doesn't support continuous scrolling yet, but that's a separate issue.
