### ISSUE TITLE
Unable to take annotations by selecting more than 1 word

### ISSUE THREAD

**Issue by anishmittal2020** [johnfactotum/foliate#552]
**Describe the bug**
When I select one word, a dialog box appears with the Highlight button and then I am able to add annotation.
But when I select multiple words, nothing happens, I don't get any dialog box.

For animation please look at the image at: [Highlight/annotation not working · Issue #77 · johnfactotum/foliate](https://github.com/johnfactotum/foliate/issues/77)

**Version:**
 - Foliate version: 2.4.2
 - OS/Distribution and version: [e.g. Ubuntu 18.04]  Ubuntu 20.04
 - Desktop environment: [e.g. GNOME 3.36] 3.36.3
 - Installation method: [e.g. Flatpak] PPA

**Comment by johnfactotum** [comment]
In the preferences, there's a "When multiple words are selected" option. Is it set to "Show menu"?
![image](https://user-images.githubusercontent.com/50942278/91527794-f566ad80-e8f5-11ea-9d23-72d300ef26ff.png)
