### ISSUE TITLE
Remove sidebar button in header bar and replace it with left-right-off toggle in menu

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#562]
I hope you're doing fine in the times of Corona. I needed a bit of distance to constantly evaluating Foliate and looking at the app afresh makes me see lots of things clearer than before. You know I love the sidebar. Having a sidebar button is neat and all. Yet it seems to limit integrating various Foliate components seamlessly into one window. How about removing it entirely from the header bar and replacing it with a left-right-off toggle in the menu instead? This would add additional flexibility to display the sidebar on the right while making it almost as easy to discover as before if placed prominently in the menu.

**Comment by johnfactotum** [comment]
One can add a button inside the sidebar that can be use to set the sidebar position, something like this:
![image](https://user-images.githubusercontent.com/50942278/91526027-45437580-e8f2-11ea-9efa-55af0acbb700.png)

**Comment by johnfactotum** [comment]
I think I'll close this as <i>wontfix</i>. Everything is now integrated in a single window. It's not clear what the use case for showing the sidebar on the right is. The sidebar now splits the whole window, so moving it would require rearranging half the buttons on the headerbar which is quite involved.
