### ISSUE TITLE
Header bar ideas 

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#566]
Perhaps the central question that needs to be solved in order to integrate all Foliate components into one window with a view switcher: where and how to display book _title_ (reader component) and publisher _name_ (catalogs component) instead?

1. Is it possible to introduce a secondary [custom](http://www.kcjengr.com/programing/2017/09/29/gtk-headerbar.html) bar right below the header bar where information like this could be displayed _and_ actually make it look good?

2. Does [GTK4](https://developer.gnome.org/gtk4/stable/GtkHeaderBar.html#gtk-header-bar-set-title-widget) offer new ways to solve this problem?

3. What about a button in the header bar to switch between "view switcher without title/name" and "title/name without view switcher"? Would such a hack even be possible and if yes, how to solve the navigational issues when the view switcher is not present?

**Comment by johnfactotum** [comment]
This is #446 and #509, right? I'm going to close this in favor of those two, otherwise there would be too many similar issues and things would be hard to track.

**Comment by digitalethics** [comment]
Yeah, wasn't very sure where to post it. Keeping it focused on these two issues sounds good.
