### ISSUE TITLE
Can't open epub on SMB shares anymore

### ISSUE THREAD

**Issue by LionelVallet** [johnfactotum/foliate#567]
**Description**
I used to open my epub files through a SMB share (files are stored on a NAS). After an update, Foliate can't open any remote file anymore.

**Screenshots**
![image](https://user-images.githubusercontent.com/67357826/90440891-47c6f380-e0d8-11ea-926f-16be1364fcaf.png)

**Version:**
 - Foliate version: 2.4.2-1
 - OS/Distribution and version: Manjaro 20.1
 - Desktop environment: GNOME 3.36.5
 - Installation method: Manjaro official repository (using Pamac)

**Comment by apandada1** [comment]
After which update did this feature break? Is the issue present when you build from source?

**Comment by johnfactotum** [comment]
This should be fixed with the new renderer (in the gtk4 branch). If not, it would be a WebKit bug. So I think it's safe to close this now.
