### ISSUE TITLE
Navigating not working properly after highlighting/annotation

### ISSUE THREAD

**Issue by nicolae-stroncea** [johnfactotum/foliate#568]
**Describe the bug**
Thanks for creating such an incredible eBook viewer, I now use it for all of the books I read!

What seems to be happening with this bug is that after annotating something, I can't navigate using left/right keys on the first key press. It will work only on a second key press which leads me to believe that after annotating something even if you close the box/menu, the focus is still somewhere else, and pressing navigation keys for the first time exits that focus instead of actually navigating.

**To Reproduce**
1. Open book in `epub` format.
2. Select some words, click the highlight button from the menu
3. Now click somewhere else on the page, or press `Esc` to exit the highlighting menu(i.e the box where you can annotate the highlight).
4. Press left or right arrow to navigate. Nothing happens.
5. Press left or right arrow once more for navigation to work properly

**Expected behavior**
Navigation works on the first key press

**Version:**
 - Foliate version: 2.4.2
 - OS/Distribution and version: [e.g. Ubuntu 18.04] Fedora 32
 - Desktop environment: [e.g. GNOME 3.36] Gnome 3.36
 - Installation method: Flatpak

**Additional context**
Only customization I remember I did is turn "turn page on tap" off.

**Comment by johnfactotum** [comment]
It seems to only happen with new annotations, and not when editing an existing annotation, which is strange. As a workaround you try using N and P to navigate instead of arrow keys.

**Comment by johnfactotum** [comment]
Still don't know why it happens, but it doesn't occur in the GTK 4 version, so I think this can be closed now.
