### ISSUE TITLE
Names Replacement

### ISSUE THREAD

**Issue by pwd-github** [johnfactotum/foliate#573]
**Is your feature request related to a problem? Please describe.**
A good feature that I have in my mobile epub reader is Name Replacement. It enables us to change names to make them readable and uncensor things. Any chance of getting such a feature in Foliate?

**Describe the solution you'd like**
Please see Moon Reader's Name Replacement feature.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by johnfactotum** [comment]
Unfortunately I think I'll mark this as _out of scope_ for now. I would suggest that you use an e-book editor (such as Sigil) if you need to change the content of the book.
