### ISSUE TITLE
Open URL 

### ISSUE THREAD

**Issue by afk-mario** [johnfactotum/foliate#58]
Is there a way to open a link in the broweser?

**Comment by johnfactotum** [comment]
Clicking on a link should open it in your default browser.

**Comment by johnfactotum** [comment]
If it doesn't, it might be caused by the same problem that caused #59. Try switching the layout to 'Single' or 'Scrolled' then back to 'Auto', then restart the app.

**Comment by afk-mario** [comment]
That fixed it, only now I can't have two pages at the same time

**Comment by johnfactotum** [comment]
"Auto" will use two-column layout when then window width is 800px or greater (should be exactly the same as "Paginated" was before 1.2.0)

**Comment by johnfactotum** [comment]
The fix has been released. Feel free to reopen or open a new issue if you have any further problems.
