### ISSUE TITLE
Duplicate entries in Library for same filepath

### ISSUE THREAD

**Issue by captn3m0** [johnfactotum/foliate#581]
**Describe the bug**

If a ebook file is edited and re-opened, it creates a new duplicate entry in the Library.

**To Reproduce**
1. Open a file in foliate
2. Read to some arbitary percent.
3. Close Foliate
4. Edit the EPUB file slightly, by doing a rebuild
5. Open the same file (with the same location) again
6. Read to some other location
7. Close and open foliate
8. The file shows up multiple times in the Library view.

**Expected behavior**
Only the most recent entry for a given filepath should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/584253/92124018-e4003280-ee1a-11ea-8d54-d8d37ca38827.png)

**Version:**
 - Foliate version: 2.4.2
 - OS/Distribution and version: Archlinux x86_64
 - Desktop environment: i3
 - Installation method: Arch package.

**Additional context**

I build EPUBs constantly, and this clutters up my Library view by taking up too many slots in the Library.

**Comment by johnfactotum** [comment]
How did you edit and build the EPUB file? If it generates a different identifier for each build, it will be treated as a different file. So if you're only making minor edits, you must make sure that the unique identifier is not modified.

Foliate relies only on the unique identifier of the file to, well, identify it; it does save the file path by default, but only as a convenience to allow you to click and open the file from the library without using Tracker.

**Comment by captn3m0** [comment]
Hmm, in this case, since the book isn't published - I didn't have an ISBN and pandoc was setting it to a random UUID.

>By default, pandoc will include the following metadata elements: [...] and <dc:identifier id="BookId"> (a randomly generated UUID).

(from pandoc man page).

This makes sense, thanks.
