### ISSUE TITLE
Increase/Set number of books shown in default Library View

### ISSUE THREAD

**Issue by captn3m0** [johnfactotum/foliate#583]
**Is your feature request related to a problem? Please describe.**
I don't like that the Foliate home screen only shows me *19* books in the Library View, when there is both space to show more and more books in my Library.

**Describe the solution you'd like**
The Library should default to showing more books, set to a configurable upper limit in the settings.

**Describe alternatives you've considered**
- No limit, just fill the screen completely before showing the "Load more" button.

**Additional context**

Here's a screenshot of how it looks on my 1080p display..

![image](https://user-images.githubusercontent.com/584253/92125671-e82d4f80-ee1c-11ea-9eb0-12615751de81.png)

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.
