### ISSUE TITLE
Unclear how to select highlight colour

### ISSUE THREAD

**Issue by dspacejs** [johnfactotum/foliate#592]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to highlight blocks of text that are right next to each other. They're different sentences and therefore should be highlighted separately, but since you can't change the colour, they blend together and it looks like it's a single highlighted block of text.

Another reason is to colour code different pieces of text for specific purposes.

**Describe the solution you'd like**
When you highlight text, it should default to yellow. But a panel should open up that lets you select a different colour (possibly with keyboard shortcuts for each colour).

**Describe alternatives you've considered**
There aren't any I'm aware of.

**Comment by johnfactotum** [comment]
> When you highlight text, it should default to yellow. But a panel should open up that lets you select a different colour

There _is_ a panel that let's you change the color. You can choose from the six built-in named colors or manually pick any color.

![image](https://user-images.githubusercontent.com/50942278/92551729-4196e380-f24e-11ea-99aa-cfeaa104edd7.png)

Currently, choosing a color will also make it the default highlight color for the next annotation.

> Another reason is to colour code different pieces of text for specific purposes.

Note that currently you can actually also show, for eample, red annotations by typing "red" in the annotations search box.

**Comment by dspacejs** [comment]
@johnfactotum oh, yeah you're right. I didn't even realise. It was a bit unclear this yellow button is used to change the highlight colour:

![Screenshot from 2020-09-10 10-27-03](https://user-images.githubusercontent.com/9282837/92669261-31672d00-f350-11ea-8af3-de99cc0d0091.png)

Perhaps the icon of this button could be changed or something? Such as changing it to something like a [colour palette](https://fontawesome.com/icons/palette?style=solid), which makes it more obvious to the user.

**Comment by johnfactotum** [comment]
Yes, I suppose you're right. A palette icon would probably be clearer.

**Comment by johnfactotum** [comment]
In the GTK 4 branch it's now a dropdown that looks like this:

![image](https://user-images.githubusercontent.com/50942278/222961536-6a80de9b-c3fa-4747-9825-3b10497a3489.png)

Which I think should be a lot clearer than before.
