### ISSUE TITLE
Hangs trying to add any book

### ISSUE THREAD

**Issue by singpolyma** [johnfactotum/foliate#594]
**Describe the bug**

When trying to add (via either GUI or CLI `--add`) any book (even tried a one-line txt file) Foliate remains stuck at 0% forever -- no significant CPU or IO usage, just stuck.

**To Reproduce**

```
echo hai > t.txt
foliate --add t.txt
```

See: `0%` never changing

**Expected behavior**

Should add or open a book.

**Version:**
 - Foliate version: 2.4.1 (also tried git `master`)
 - OS/Distribution and version: postmarketos on PinePhone
 - Desktop environment: sxmo (dwm)
 - Installation method: apk add, and also building from source in git

**Additional context**

I pulled git and built to try to chase down the bug.  I can add print statements and see that it gets through EbookView `.open(...)` call completely, but AFAICT it never runs the `open(...)` call in `ebook-viewer.js` -- in fact, I'm unable to find the code that would even trigger that to happen.  The HTML file is sent to load in the webview, but it does not reference the JS.  Elsewhere the JS is loaded into the webview, but I haven't found anyone calling `open(...)` yet -- probably I'm just dense and can't find it.

**Comment by johnfactotum** [comment]
It works for me. Maybe try setting the environment variable `G_MESSAGES_DEBUG=all` to see a more detailed log.

> AFAICT it never runs the `open(...)` call in `ebook-viewer.js` -- in fact, I'm unable to find the code that would even trigger that to happen.

This is where it calls `open()`:
https://github.com/johnfactotum/foliate/blob/40a6ea32aea9f3ebd9b68da6678d5cdc08fa4ea8/src/epubView.js#L804

If you enable the debug messages, it should output something like
```
(com.github.johnfactotum.Foliate:23961): Foliate-DEBUG: 16:26:47.094: run_javascript: open(
                    decodeURI("file:///home/user/t.txt"),
                    decodeURI("t"),
                    'text',
                    'viewer',
                    {"width":"10...
```

**Comment by singpolyma-shopify** [comment]
Here's what I get running a dev build from master:

```
$ run/bin/com.github.johnfactotum.Foliate  --add $HOME/unschoo
led.epub
(gjs:32481): GLib-GIO-DEBUG: 10:32:44.226: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
(com.github.johnfactotum.Foliate:32481): GLib-GIO-DEBUG: 10:32:44.513: _g_io_module_get_default: Found default implementation keyfile (GKeyfileSettingsBackend) for ‘gsettings-backend’
(com.github.johnfactotum.Foliate:32481): GLib-DEBUG: 10:32:45.458: unsetenv() is not thread-safe and should not be used after threads are created
(com.github.johnfactotum.Foliate:32481): Foliate-DEBUG: 10:32:45.546: failed to get file info: Gio.IOErrorEnum: Error when getting information for file “/home/mo/.local/share/com.github.johnfactotum.Foliate/library/uri-store.json”: No such file or directory
(com.github.johnfactotum.Foliate:32481): Foliate-DEBUG: 10:32:45.892: failed to get file info: Gio.IOErrorEnum: Error when getting information for file “/home/mo/.config/com.github.johnfactotum.Foliate/themes.json”: No such file or directory
(com.github.johnfactotum.Foliate:32481): Foliate-DEBUG: 10:32:46.061: failed to get file info: Gio.IOErrorEnum: Error when getting information for file “/home/mo/.local/share/com.github.johnfactotum.Foliate/catalogs/catalogs.json”: No such file or directory
(com.github.johnfactotum.Foliate:32481): GLib-DEBUG: 10:32:46.249: unsetenv() is not thread-safe and should not be used after threads are created
0%
(process:2074): GLib-GIO-DEBUG: 10:32:47.458: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
(process:2074): GLib-GIO-DEBUG: 10:32:47.481: _g_io_module_get_default: Found default implementation networkmanager (GNetworkMonitorNM) for ‘gio-network-monitor’
(process:2074): GLib-GIO-DEBUG: 10:32:47.484: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’

(WebKitWebProcess:3): dbind-WARNING **: 10:32:47.558: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-K4eQsMNp5l: Connection refused
(WebKitWebProcess:3): GLib-GIO-DEBUG: 10:32:47.611: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
```

**Comment by singpolyma-shopify** [comment]
Putting a `print` in before that 804 I never get my extra line printed, so I expect the ready event is just not firing...

**Comment by johnfactotum** [comment]
Well, what about simply opening the file? Opening and "importing" is almost exactly the same thing in Foliate. The difference is that when importing, the book is opened and rendered in a `GtkOffscreenWindow`.

**Comment by johnfactotum** [comment]
Can you provide a sample file? Also, what's the output if you run it with `G_MESSAGES_DEBUG=all` or `--verbose`?

**Comment by dankski** [comment]
My Foliate 2.6.3 on PopOS hangs to. I am not able to load EPUB.

**Comment by mimagind** [comment]
com.github.johnfactotum.Foliate --verbose <epub_file>
yields this same error for every file
`
(WebKitWebProcess:2): Gdk-ERROR **: <time> : The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 216 error_code 2 request_code 151 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
`
