### ISSUE TITLE
Add Internet Archive's Open Library OPDS catalog to Foliate as default

### ISSUE THREAD

**Issue by ghost** [johnfactotum/foliate#599]
I managed to add the Internet Archive's Open Library OPDS catalog to Foliate, and now I can download all of their books.
This is the page where I found it: https://openlibrary.org/dev/docs/ia
This is the OPDS URL: http://bookserver.archive.org/catalog/
And so I wanted to share this with you. Maybe you could add this catalog to the program and make it available to the users as default. I think anybody who uses this program is going to love this, because the Internet Archive has millions of books available, and besides free books, users can also borrow books which are not yet in the public domain by creating an account at archive.org, and then they can use those credentials everytime they wish to borrow a book with Foliate. Thank you very much for your consideration.
![Screenshot from 2020-09-24 17-43-32](https://user-images.githubusercontent.com/71838201/94168936-7762db80-fe8e-11ea-9b23-dc64ca7b5e60.png)
![Screenshot from 2020-09-24 17-43-42](https://user-images.githubusercontent.com/71838201/94168941-78940880-fe8e-11ea-8fcf-2f925861a623.png)
![Screenshot from 2020-09-24 17-43-52](https://user-images.githubusercontent.com/71838201/94168943-78940880-fe8e-11ea-9716-72840429534a.png)
![Screenshot from 2020-09-24 17-45-52](https://user-images.githubusercontent.com/71838201/94168946-792c9f00-fe8e-11ea-8def-a578df2ff2e4.png)

**Comment by johnfactotum** [comment]
Merging with #448
