### ISSUE TITLE
Support OPDS

### ISSUE THREAD

**Issue by nemobis** [johnfactotum/foliate#6]
Thanks for your work!

At some point in the future, it would be nice to support OPDS, so that it's easy to navigate books from the Internet Archive, Gutenberg.org etc.

**Comment by johnfactotum** [comment]
I'm not very familiar with OPDS. If I understand correctly, it's for *getting* books, rather than *reading* them?

If so, I'm a bit inclined to close this as *out of scope* for now. Foliate aims to be a eBook *viewer*. It doesn't have any book management featuers at the moment, and I don't have plans to add any.

Well, at least not in the short term.

**Comment by nemobis** [comment]
John Factotum, 31/05/19 09:39:
> I'm not very familiar with OPDS. If I understand correctly, it's for 
> /getting/ books, rather than /reading/ them?

Yes. It's supported by Calibre, FBReader and others for this purpose, so 
that one is not presented with an empty library when using them.

I understand if it's out of scope, it's useful to clarify that. Thanks 
for the consideration.

**Comment by johnfactotum** [comment]
Closing for now.

**Comment by digitalethics** [comment]
In addition to Gutenberg.org and the Internet Archive, access to the following would be great: 
- [directory of open access books](https://doabooks.org)
- [Project Muse](https://muse.jhu.edu/)
- [ScholarLed](https://scholarled.org/)
- [Feedbook's Public Domain](http://www.feedbooks.com/publicdomain)

Would you consider OPDS support as a "stretch goal"? Maybe partial OPDS functionality can be implemented or some open access publishers have APIs to fetch new publications remotely?

**Comment by johnfactotum** [comment]
Basic OPDS support has been added. It even supports facets:

![image](https://user-images.githubusercontent.com/50942278/81084692-be533300-8ee5-11ea-8af4-116244714bd8.png)

It's still missing some features, like pagination, search, indirect acquisition, and some others. But it should be usable. Also I've not implemented the ability to "add" OPDS feeds yet. For now it will open feeds from URIs.
