### ISSUE TITLE
Change project name?

### ISSUE THREAD

**Issue by johnfactotum** [johnfactotum/foliate#60]
It looks like there's already a "[FolioReader](https://github.com/FolioReader)". It's not exactly the same as "Foliate", but they do use a leaf as their logo. I think that's way too similar. I'm open to suggestions if anyone has any ideas.

Would also need to migrate all the settings and files, which I'm unsure how to best implement. Or just let users copy the files manually?

**Comment by paulcarroty** [comment]
It's really similar, yep, and "Folio" is very popular name. I'd recommend to call it ''Foliatus" if you want to save the original style/design.

**Comment by elcste** [comment]
I say only partly joking: (GNOME) Books

One meaning of **folio** is a certain type/size of book. Another type/size is **[quarto](https://en.wiktionary.org/wiki/quarto#Noun)**, so maybe some variation on that?

**Comment by johnfactotum** [comment]
Here's my joke: Exfoliate, as in "formerly foliate".

**Comment by elcste** [comment]
*> Exfoliate, as in "formerly foliate"*

That also has echos of [ex libris](https://en.wiktionary.org/wiki/ex_libris#English), making it even more appropriate ;-)

Ex Libris wouldn't be a bad name either, if it's not already used by something else.

**Comment by not-chicken** [comment]
Here's my joke: Name it Xfoliate as it currently works on Xorg only ( ig?), if there ever comes a wayland version we can call that one Wfoliate.

**Comment by elcste** [comment]
A **lectern** is a tool for reading books, so I think it would be a good ebook app name. I can't find any active projects using it, just some old ones that never got off the ground like https://github.com/duganchen/lectern

**Comment by johnfactotum** [comment]
I think Quarto would be a nice name. But what about the icon? I suppose one could just replace the leaf with a big "Q". Ex Libris is also a good name, but if the leaf is replaced with a big "X", I think that might be just a *tad* too Xorg-ish.

A quick search yields a book generation toolchain called [quarto](https://github.com/avdi/quarto). There's also a [Calibre plugin](https://www.mobileread.com/forums/showthread.php?t=188619) that allows you to insert *actual* ex libris into e-books (why would anyone want to do that?). Interestingly, [Quarto](https://boardgamegeek.com/boardgame/681/quarto) and [Ex Libris](https://boardgamegeek.com/boardgame/201825/ex-libris) are also names of two boardgames. Ex Libris also seems to be names of numerous companies. Not sure if that's a problem.

As for "Lectern", it's too similar to [Lector](https://github.com/BasioMeusPuga/Lector).

**Comment by not-chicken** [comment]
How about "Trefoil" ? There doesn't seem to be any other package on linux by this name.

**Comment by johnfactotum** [comment]
Funny story: the first names I came up with, before settling on "Foliate", is actually "Epubince" and "Convince", as in, *convince* the Evince devs to add EPUB support -- in fact that would probably have the opposite effect, as one of their wontfix reasons is "there are already many ebook readers available."

Another name I considered was "Paperback." I didn't choose it as a leaf is much easier to convey in icons. Now I see there's [another e-book reader](https://github.com/monospaced/paperback) by that name.

There's an e-book-related [Trefoil](https://github.com/magabriel/trefoil). But my main complaint with "Trefoil" is that its pertinence to book reading is a bit more tenuous than the others and not as catchy.

**Comment by monday15** [comment]
Quarto sounds great.

Republic or Reading Room (but there is an app, 'my reading room' in apple appstore) can be other options.

**Comment by elcste** [comment]
Others I've come up with:

Octavo (but https://octavo.blog/)
Codex (but https://github.com/jscholes/codex)
or maybe Codices, if you can handle most people mispronouncing the name

For an icon for any of them, I'm seeing an open book like now, with either a ruler (maybe tasseled) in the middle with the name or first letter on it or the first letter as a drop cap on the page (kind of like [this](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.howtogeek.com%2Fwp-content%2Fuploads%2F2015%2F04%2F04_drop_cap_options.png.pagespeed.ce.nufDdz8X2H.png&f=1)).

**Comment by itprojects** [comment]
@johnfactotum Would it be possible to change the executable filename from:

`com.github.johnfactotum.Foliate`

to:

`foliate`

In the sense of:

`a@b:~$ foliate`

and not:

`a@b:~$ com.github.johnfactotum.Foliate`

**Comment by johnfactotum** [comment]
See #22.

**Comment by itprojects** [comment]
Well - your code, your rules!

**Comment by johnfactotum** [comment]
Since changing the name is a very arduous task, I think I will just stick to the current name for now. Will reopen if there's enough demand for this.
