### ISSUE TITLE
[Minor] Some books' chapter sidebars don't work; regardless of subheader, they take you to beginning of chapter.

### ISSUE THREAD

**Issue by rubenmantecon** [johnfactotum/foliate#600]
**Describe the bug**
Any subitem of a chapter entry on the book sidebar takes you to the beginning of said chapter, instead of the subtitle location the chapter.

**To Reproduce**
1. Open book
2. Open sidebar
3. Click on any chapter title
4. You are now on the beginning of a chapter
5. Scroll a bit through the chapter
6. Click on any subtitle of the chapter you are in. 
7. See how you are going back to the beginning of the chapter, NOT to the subitem location

**Expected behavior**
Going to the subitem location in the chapter after clicking it.

**Screenshots**

**Version:**
 - Foliate version: 2.42 (package installed is folaite-git)
 - OS/Distribution and version: Arch Linux
 - Desktop environment: GNOME 3.36
 - Installation method: AUR helper (yay)

**Additional context**
I tested this using ["Eloquent Javascript 3rd Edition" by Marjin Haverbeke](https://eloquentjavascript.net/)

**Comment by johnfactotum** [comment]
Never figured out what caused this, but it doesn't happen with the new renderer anymore (see https://github.com/johnfactotum/foliate/issues/962). So I think this can be closed.

**Comment by rubenmantecon** [comment]
Thanks for the follow ups. Seems like a deeply buried bug!

Glad it's closed
