### ISSUE TITLE
Library questions

### ISSUE THREAD

**Issue by sketchbuch** [johnfactotum/foliate#601]
**Question:**

1. When reading a book can you add a "back to Library" button on the title bar?
2. Can you add some filtering/organising for books by language?
3. Add some sort of categorisation - like genres or tags or something?
4. Is there a way to import multiple books or search a folder and subfolders for epub books?
5. If I add a book from a collection (like standard ebooks) where are they downloaded to? Can they be saved to the folder I already use for books?

**Version:**
 - Foliate version: 242
 - OS/Distribution and version: Ubuntu 20.04
 - Desktop environment: GNOME 3.36.3

**Comment by apandada1** [comment]
5. The books are downloaded to `/home/<username>/.local/share/com.github.johnfactotum.Foliate/books/`.

**Comment by johnfactotum** [comment]
> When reading a book can you add a "back to Library" button on the title bar?

See #504.

Note that currently, to return to the library, there's a "Library" menu item in the primary menu. 

You can also use the desktop entry action to open the Library window without closing the book. In GNOME you can right click on Foliate's icon in the dash or application grid, and select "Library".

> Can you add some filtering/organising for books by language?

When searching in the library, you can already filter by language. Though currently you can only search with raw language codes (e.g. "en") and not localized language strings.

> Add some sort of categorisation - like genres or tags or something?

It already supports searching with tags (properly called "subjects" for EPUBs). But it doesn't support browsing or modifying tags.

> Is there a way to import multiple books or search a folder and subfolders for epub books?

You can import multiple books using the "Add Books" button or menu item, or by simply drag and drop files from the file manager. There's an command line option `--add` that can be used. Importing from folders is not supported at the moment.

> If I add a book from a collection (like standard ebooks) where are they downloaded to? Can they be saved to the folder I already use for books?

Open Preferences dialog. There's an option for what to do when downloading books from OPDS.

If you choose "Save to default directory" it will be saved to the directory displayed under the option (which will usually be `~/.local/share/com.github.johnfactotum.Foliate/books/`). The file will be named with its OPDS entry id and a timestamp, so when you navigate to the same OPDS entry again, you will have the option to open your previously downloaded book, or update the book (if available).

If you select "Ask what to do", every time you download a book, it will prompt you to either choose a destination or alternatively, open without saving the file.
