### ISSUE TITLE
Crash on startup (after upgrade gnome from 3.36 to 3.38.1)

### ISSUE THREAD

**Issue by weijarz** [johnfactotum/foliate#608]
**Describe the bug**
Crash on startup

**To Reproduce**
```bash
[~] $ foliate 
Gjs-Message: 16:35:46.640: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/library.js 37]: Requiring Tracker but it has 2 versions available; use imports.gi.versions to pick one
free(): invalid pointer
Aborted (core dumped)
```

**Version:**
 - Foliate version: 2.4.2
 - OS/Distribution and version: [e.g. Ubuntu 18.04] ArchLinux
 - Desktop environment: [e.g. GNOME 3.36] GNOME 3.38.1
 - Installation method: [e.g. Flatpak] pacman

**Additional context**

Same version works fine on gnome 3.36, but crashes on 3.38.

**Comment by johnfactotum** [comment]
This only happens when the book does not have a cover. Because apparently `GLib.base64_decode(undefined)` now crashes GJS instead of just throwing an error. Probably a GJS bug.

**Comment by kemelzaidan** [comment]
I'm having the same problem on version 2.5 of Foliate installed from pacman in Manjaro while trying to open a .mobi file. But the file does have a cover.

**Comment by johnfactotum** [comment]
@kemelzaidan Can you open a separate issue, with the file to reproduce the problem?

**Comment by kemelzaidan** [comment]
Yes, I can, but I believe I have found the problem, although you certainly know gnome development much better that. It seems that I have installed both gnome tracker 2 and 3 on the machine and by reading the gnome documentation I found out that you have to namespace the version of Tracker.

Trying to import Tracker on the Gjs shell shows the same error. Take a look at the section "Importing GObject-Introspection namespaces" at https://developer.gnome.org/seed/stable/seed-importer.html.

I forked the source and tried to fix it myself, but I don't know gnome that well and have no idea which version I should use... But my tries were successful for not showing the error message when trying to run the source. Besides that behavior haven't changed and the application hangs forever without finishing to load.

**Comment by johnfactotum** [comment]
In that case, can you open a separate issue, with the full error message? Does the problem go away if you disable Tracker in the preferences?

**Comment by demolg** [comment]
Now, maybe we can port to tracker3 [Port everything to Tracker 3.0](https://gitlab.gnome.org/GNOME/Initiatives/-/issues/17)

**Comment by marcoshdezcam** [comment]
So, no solution to use Foliate?
