### ISSUE TITLE
Better use of space on bigger displays (Catalogs)

### ISSUE THREAD

**Issue by Hergeirs** [johnfactotum/foliate#610]
I really like this application, but it's an eyesore on hidpi. I have a 4k monitor and the app renders like this. 
![image](https://user-images.githubusercontent.com/20126436/96356561-32764180-10e8-11eb-930a-d50c98b33818.png)
Would love to help with it, but won't find the time for a while.
Would be awesome if the catalog filled the width of the window.

**Comment by johnfactotum** [comment]
Not applicable anymore. In the gtk4 branch, there's no catalogs view. Instead the list of catalogs is shown in the sidebar.
