### ISSUE TITLE
multi-column text that spans several "pages" (screenful's?)

### ISSUE THREAD

**Issue by cjns1989** [johnfactotum/foliate#611]
It appears foliate does not handle multi-column text correctly. What I see is that with two columns and two-line "pages" for an alphabetically-sorted list with the following 8 items [AA, AB, AC, AD, AE, AF, AG, AH], the following happens:

**Page one:**

AA      |     AE
AB       |    AF

**Page two:**

AC       |     AG
AD      |    AH

The correct multi-column display of this list should be:

**Page one:**

AA       |     AC
AB       |    AD

**Page two:**

AE      |       AG
AF       |      AH

Imagining now that the list comprises 1400+ entries (my use case) spanning something like 40 pages (on an average 6" ereader), this means that when you get to the bottom of column 1 on the last page — entry 'Jeremy' - e.g. … you need to page back forty (39?) pages to find the 'John' entry.

The context is a basic index called a TABLE ALPHABÉTIQUE (in French) that is converted from the LaTeX version of the ebook.

What Foliate apparently does is not true multi-column but rather amounts to splitting this long list in the middle and displaying the two halves side by side (?)

Pretty easy to **reproduce:**

Just create an HTML source file with an alphabetically sorted list of items and wrap it in a '\<div>\</div>' with the following styling:

`.ind-00 {
    column-count:2;
    column-gap:1em;
    column-rule:1px solid #000;
    text-align:center !important;
    }
` 

**No screenshot** but otherwise with 'gruvbox dark' the index is rendered quite nicely, column separator and all…!

**Version:**

 - 2.4.2
 - automatically invoked by Mozilla Firefox
 - Installed via Flatpak

**Additional context**

Not to worrybut I thought I'd report this. I mostly use Foliate to take a quick peek at the epub's I create from markdown with pandoc to save me the trouble of downloading them to a tablet/ereader. I checked half a dozen android ereading app and among the few that actually bothered about multi-columing I only found two (Gitgen & Reasily) that did multi-column the way the reader would expect.

**Comment by johnfactotum** [comment]
I think this is actually an WebKit bug. Epub.js uses columns internally to render "pages", and apparently in WebKit that's how nested multi-columns are rendered. The [Chromium bug on this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=447718) includes a [test](https://bugs.chromium.org/p/chromium/issues/attachmentText?aid=121566):

```html
<!DOCTYPE html>
<p>The word 'PASS' should be seen below.</p>
<div style="float:left; orphans:1; widows:1;">
    <div style="-webkit-columns:2; -webkit-column-gap:0; columns:2; column-gap:0;">
        <div style="-webkit-columns:2; -webkit-column-gap:0; columns:2; column-gap:0;">
            P<br>
            A<br>
            S<br>
            S<br>
        </div>
    </div>
</div>
```

On Chromium and Firefox, you see "PASS", as expected. But when I open it in Epiphany 3.38 (with WebkitGTK 2.30.1), it shows "PSAS".

**Comment by cjns1989** [comment]
No offence meant but that's when I pretty much lost interest in programming... not much fun being an overpaid bricklayer is there? So I guess I'll have to live with it until you find a better provider... or the webkit people fix it. 

While I'm at it… I use <svg></svg> wrappers so some images are autmatically stretched to display full-screen... recent versions of pandoc do this by default with the epub's cover. I noticed that this does not work with foliate. Worth opening another issue to keep track of the problem… or is this webkit-related?

**Comment by johnfactotum** [comment]
This and some other bugs, for example #223, arise from the fact that the "pages" are not real pages. They are CSS columns. So as a result, one cannot expect CSS styles that works in normal environments to behave the same when paginated. Sometimes some browsers produce better results than others. Sometimes the problem can be fixed by Epub.js, others must be fixed by the rendering engine. Still others are perhaps inherent limitations of multicol.

It's possible to use alternative methods of pagination that does not involve using multicol. But this would require either upstream Epub.js implementing such a method, or we choose an different backend. And other methods have their drawbacks and quirks too; multicol is still probably the simplest and most popular solution. There's also always the chance that we switch to Chromium, which is what happened with QT and QT apps. But at the moment I don't think that's very likely.

> I use wrappers so some images are autmatically stretched to display full-screen... recent versions of pandoc do this by default with the epub's cover. I noticed that this does not work with foliate. Worth opening another issue to keep track of the problem… or is this webkit-related?

Generally, when it comes to rendering issues, it's better to—
- First see if you can reproduce the problem with Epub.js (see the [Wiki](https://github.com/johnfactotum/foliate/wiki#my-book-is-not-displayed-properly) for instructions)
- If the answer is yes, check whether there's any difference between different browsers. Sometimes Epub.js needs browser-specific workarounds. Other times it will be a browser engine bug that need to be fixed.
- If the answer is no, then it's more likely to be a Foliate bug.

As for this specific issue—I don't think it's even really a bug at all. I'm not sure how "full-screen" you expect it to be, but the SVG wrapper simply sets its width to 100%; when two pages are displayed simultaneously (this is called a _Synthetic Spread_), it will necessarily only stretch to the width of one page, and not across two pages. This is, I believe, the expected behavior. If you don't want it to show two pages simultaneously, then you need to set the relevant `rendition:` properties in the EPUB package. Now, these properties are not really well support, or at all, by Epub.js, however that is a different issue and has nothing to do with the wrapper per se.

Link to pandoc issue for reference: https://github.com/jgm/pandoc/issues/5638

**Comment by cjns1989** [comment]
I didn't report foliate's behaviour re: \<svg>\</svg> wrappers as a bug. It's merely an oddity since this trick I ran into makes just about every other epub reading software I have looked at display images using up the entire screen. A feature which is not necessarily a bad idea considering the usually tiny sizes of the screens of mobile devices. Obviously this only works 100% if the image's aspect ratio matches the device's screen. Otherwise you get some empty space and a smaller image. Thanks for referencing the issue I opened with the pandoc crowd a year and a half ago. I would have done so myself… except that my question relative to full-page/full-screen images was off-topic in the first place. As to what I mean by full screen... same thing... I didn't want to clutter up this issue with off-topic matter. The context here is just a case of mimicking a layout mode that was quite common in publications of a technical or semi-technical nature (botany, agriculture, anatomy, engineering, cuisine… etc.) way back when... where you would have running text and once in a while an illustration that takes up the entire page... diagrams… drawings… occasionally photographs... etc.  I just happen to be doing one such book at the moment with over 100 such illustrations that I lifted from the scanned copies or the book that I found online and that I created 4:3 1920x1440 copies of using _The Gimp_. And where I had no problem putting together a pdf reproduction of the original book with epub things become a lot more complicated. I imagine this is a case where I should be using fxepub since after all I'm doing some sort of hybrid reflowable/fixed epub but from what I have seen I would need to acquire some expensive software to do so. Interesting conversation indeed at least where I am concerned and thanks for taking the time to reply but I have a feeling such discussions really belong to a foliate-discuss forum or mailing list. Is there such a thing?

**Comment by johnfactotum** [comment]
> The context here is just a case of mimicking a layout mode that was quite common in publications of a technical or semi-technical nature (botany, agriculture, anatomy, engineering, cuisine… etc.) way back when... where you would have running text and once in a while an illustration that takes up the entire page... diagrams… drawings… occasionally photographs... etc.

The image can and does span the whole _page_. It cannot, however, span the whole _spread_. That's why I asked you what you meant by "full-screen".

Usually, it's okay, and indeed usual, for images to only span one page (this is the case even in print), not the whole spread (which means _two_ pages).

> I imagine this is a case where I should be using fxepub since after all I'm doing some sort of hybrid reflowable/fixed epub but from what I have seen I would need to acquire some expensive software to do so. 

Yes, you should consider using fixed layout if you want to have that level of control. You don't need expensive software if you code it by hand.

> I have a feeling such discussions really belong to a foliate-discuss forum or mailing list. Is there such a thing?

It has been requested in the past (#158), but I think it's easier to just use issues for discussions. There's a [label](https://github.com/johnfactotum/foliate/labels/discussion) and also an issue template for discussions.

**Comment by cjns1989** [comment]
Ah yes... typical use case might be when you have a landscape image... with plenty of details (flat map of the world... D. Mendeleev's periodic table of elements...and so forth) that clearly benefits by being spread over two pages that ** face each other** in printed books. Something that doesn't necessarily play well with typical 6" eReaders even when you change the orientation. In the book I'm doing (an excuse for taking my eBook building home-grown toolbox to the limit... mostly built around pandoc, GNU make etc.) many of the images are menus providing samples of the fare served to royalty in their 19th century to-do's. The reason I wanted them as images (mostly text with some basic frills initially done in LateX and later converted from single page PDF's to 1440x1920 4.8x6.4 images) is that when the eBook is a PDF the whole thing becomes a mess if I decide to switch my main font to a smaller/larger point size... change the size of the margins... increase interline space etc. As to HTML it would take a genius to get the layout right in the first place... and then since EPUB's are reflowable… we can imagine what would happen...! 

As to doing fixed EPUB (or a mix) just about every article I have seen on the subject starts with "fire up Adobe Indesign… blah". And what little I have read about coding them the old fashioned way didn't sound too promising. In any case I have not been able to find any documentation that describes the process. Could be wrong but my impression is that going down that road makes about as much sense as trying to "draw" SVG logos in one's favorite text editor. 

Anyway where full "page" images in EPUBs are concerned here's a link to an article by a rather opinionated indepent lady-publisher whose title says it all¹: _**Image handling in ePubs reaches new level of inanity**_ https://mademers.com/image-handling-in-epubs-reaches-new-level-of-inanity/ ... Even if she is not (her own admission) a technical type she writes well and she has given it more thought than me. 

Otherwise another reason I would wish these images to use up the entire "page" is that they are in black and white (and some grays?). As a result these medium size rectangles with a blinding white background all over the place look like a sore thumb in foliate when I switch to one of those rather attractive alternative themes that someone came up with. Maybe you could think of a clever trick to make these B&W diagrams match the theme? Simulating image transparency perhaps?

As someone who only uses tablets & eReaders to read stuff in bed or on the couch when my back hurts I have to say that Foliate is now an extra reason why I would love to be able to run a gnu/GTK + linux enviroment natively on these contraptions.

¹ Volume I (of two) of this rather large EPUB (27Meg) is almost done now. Proof of the pudding, another way to clarify the issue would be to take a look. I usually upload the books I put together (markdown source and EPUB, PDF, HTML output) as github projects but I still have work to do to fullly automate the generation of the eBooks. Not to mention that it's in French and that I would need some native speaker of that pesky language to proofread it. Good luck with that! Let me know if it's of any use and I could upload the beta version wherever suitable in the meantime. Another thing I have noticed is that foliate can be quite slow at loading files (images or moving to the next file/chapter).

**Comment by johnfactotum** [comment]
Even in print, images spanning the whole spread is often not used. Usually if the image is wide, it is simply printed in portrait. Fortunately, e-books readers have the advantage that one can quite easily zoom in on the images. So in general there's less need for worrying about orientation and sizing. The better and much easier approach is to just use a simple image, perhaps setting its width or height to 100%, if desired, and let the reading system or the user determine the rest.

> As to doing fixed EPUB (or a mix) just about every article I have seen on the subject starts with "fire up Adobe Indesign… blah". And what little I have read about coding them the old fashioned way didn't sound too promising. In any case I have not been able to find any documentation that describes the process. Could be wrong but my impression is that going down that road makes about as much sense as trying to "draw" SVG logos in one's favorite text editor.

I don't really know that much about fixed layout EPUBs, but I think you can learn a lot from examples, for example [EPUB 3 Samples](https://idpf.github.io/epub3-samples/30/samples.html), as well as from reading the spec. For what it's worth, editing SVGs with a text editor, though not particularly efficient for images with any complexity, is not as impractical as you might imagine (there are many tutorials on the internet that tells you how to code SVGs by hand).

> Maybe you could think of a clever trick to make these B&W diagrams match the theme? Simulating image transparency perhaps?

You can use a transparent image. Checkout the EPUB files by [Standard Ebooks](https://standardebooks.org/). The illustrations in their books are transparent and adapt well to theming.

**Comment by cjns1989** [comment]
After this long interruption I have another issue. Not sure if this is the right place to post but here goes...

At some point I noticed that the colors in Foliate on my system were sort of "off". One particular place was the covers of epub' where all of a sudden the colors appeared faded but it also affected the themes that "didn't look right". I do remember that while I was taking a look at the product's options I fiddled the theme's colors creating a couple of custom themes in the process. Since I couldn't find any way to fix this I tried reinstalling Foliate in my flatpak environment (uninstall + install) but that made no difference. 

Anyway. I had to let go of this for a while and then the other day I needed to start foliate and now it won't start.

The following message is displayed at the terminal:

`bwrap: Can't create file at /run/user/1000/pulse/native: No such device or address`

No idea what pulse has to do with it or if this has anything to do with my messing around with Foliate themes.

Do I need to reinstall the flatpak framework on that system and start from scratch?

Or is it foliate-specific… and if so how would I go about figuring out what's wrong and fixing it? 

Thanks,

CJ

**Comment by johnfactotum** [comment]
If you've encountered a different problem, feel free to [open new a issue](https://github.com/johnfactotum/foliate/issues/new/choose). You can also post in the [discussions](https://github.com/johnfactotum/foliate/discussions).

As for the Flatpak troubles you're encountering, well, I don't really have any ideas, but I'd say, try to make sure all your system packages and Flatpak packages are up-to-date. If all else fails, maybe try deleting all the contents of `/var/lib/flatpak/` or `~/.local/share/flatpak/`, and maybe also `~/.var/app/com.github.johnfactotum.Foliate` (warning: this will delete all annotations, reading progress, and other data).
