### ISSUE TITLE
A setting to not show book title on top of every page

### ISSUE THREAD

**Issue by aritorhamo** [johnfactotum/foliate#613]
Currently Foliate shows the title of the book on top of every page. I think it would be nice to be able to choose whether it shows or not. I'd mostly prefer to not see it on any page, but on the cover and title pages and other beginning pages it seems always out of place to me.

Could this be made a preference, perhaps with the additional choice of showing the title only on the actual text content of the book, and not on the initial pages?  

I'm using Foliate on Linux Mint 20 and Cinnamon 4.6.7

Foliate looks and feels very nice, thanks!

**Comment by wsdfhjxc** [comment]
An option to completely disable showing the book title when the titlebar is hidden would be great.

**Comment by johnfactotum** [comment]
Fixed in the `gtk4` branch in 010e61df6f9312a7dada91a792237562587962c8. It only shows the header if you're not on the first spread of the section.

**Comment by aritorhamo** [comment]
Great, thank you! I'll put it to test when the change comes to the stable version.
