### ISSUE TITLE
undefined symbol from libgjs - with workaround

### ISSUE THREAD

**Issue by enno-au** [johnfactotum/foliate#616]
Compiled OK on FreeBSD 12.1 from ports but when trying to run fails to start with undefined symbol error from libgjs 1.66. Uninstalled libgjs and reverted to older 1.55 version and all seems OK.

 Error likely in library rather than foliate, but in case anyone else hits this prob I thought I document it.

**Comment by johnfactotum** [comment]
Can you post the error message as well as what version of Foliate you're using?

**Comment by johnfactotum** [comment]
Closing due to lack of information.
