### ISSUE TITLE
How do I save permanent changes in css?

### ISSUE THREAD

**Issue by dg00GT00** [johnfactotum/foliate#619]
**Question:**
I would like to know if there are some support in the program to save the alterations made in the css file through Inspect Element.

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: Ubuntu 20.04
 - Desktop environment: GNOME 3.36

**Comment by johnfactotum** [comment]
Currently, no, it's not possible.

**Comment by xarthna** [comment]
@dg00GT00 You can make permanent changes to reflowable ebook formats that fall into the category of essentially zipped files with different mime type and extension. For instance, I made changes to epub format by:

```bash
mkdir /tmp/epub-chg
cp MyBook.epub /tmp/epub-chg
cd /tmp/epub-chg
mv MyBook.epub MyBook.zip
unzip MyBook.zip
# edit stylesheets and then repackage
zip -r MyBook.epub -x MyBook.zip .
```
There are overridden styles that this project changes through gtk, that you can further change. These keys are:

```
allow-unsafe
brightness
fg-color
invert
link-color
prefer-dark-theme
use-publisher-font
autohide-cursor
enable-devtools
font
justify
margin
skeuomorphism
zoom-level
bg-color
enable-footnote
hyphenate
layout
max-width
spacing
```
To change these you can do so for example: `gsettings set com.github.johnfactotum.Foliate.view link-color darkgoldenrod`

**Comment by billbeans** [comment]
Is there no way to save css changes until the window is closed? I have an epub that maintains some text in black even though I'm using the dark theme. I can go into DevTools and change these sections to white, but then as soon as I close DevTools my changes are reverted. Why even put the feature there if I can't use it?

**Comment by johnfactotum** [comment]
That sounds like you might be using v2, which uses Epub.js, which always reloads the page whenever there's a resize so everything would be reset. It shouldn't happen in v3, however.
