### ISSUE TITLE
problem with text width in automatic mode layout on 1.5.3 vs 2.5.0

### ISSUE THREAD

**Issue by karolszk** [johnfactotum/foliate#620]
Hi!

I am using foliate 1.5.3 and reading epub book http://onlinestatbook.com/Online_Statistics_Education.epub
the layout looks good (two page wide filled) like in the following example:
![Zrzut ekranu z 2020-10-31 20-06-21](https://user-images.githubusercontent.com/8544489/97787892-23e25c80-1bb5-11eb-892d-b34bcec1ba47.png)

but on newest 2.5.0 version the pages looks narrower
![Zrzut ekranu z 2020-10-31 20-05-58](https://user-images.githubusercontent.com/8544489/97787882-14fbaa00-1bb5-11eb-9d65-ab78e70f7c8d.png)

and I was unable to customize it and I can't read in this narrow columns - there are plenty of empty space on the screen.

**Comment by johnfactotum** [comment]
You can change the maximum width In the primary menu.
![image](https://user-images.githubusercontent.com/50942278/97802389-db6d8200-1c3a-11eb-87c2-97e587c95fba.png)

**Comment by karolszk** [comment]
Hi @johnfactotum 

thanks for fast response. I already tried. Width stuck on 1500 and do more nothing change. 
![Zrzut ekranu z 2020-11-01 14-19-23](https://user-images.githubusercontent.com/8544489/97804004-4e7ff400-1c4d-11eb-8f4e-5f25c21dcbdf.png)

when I disable left panel 2000 width added more column and looks like below:
![Zrzut ekranu z 2020-11-01 14-21-00](https://user-images.githubusercontent.com/8544489/97804026-7cfdcf00-1c4d-11eb-85bf-802282f96605.png)

**Comment by johnfactotum** [comment]
You have margins set at 15.5. You need to reduce the margins.

**Comment by karolszk** [comment]
Reduced margins to 1.5, and looks like below:

![Zrzut ekranu z 2020-11-01 14-57-49](https://user-images.githubusercontent.com/8544489/97804887-e3d1b700-1c52-11eb-8657-07d058143660.png)

**Comment by johnfactotum** [comment]
The only two changes from 1.5.3 is the introduction of max width and four columns.

If you set max width to some value higher, like one that's wider than the screen, then the behavior is essentially the same as 1.5.3 apart from four-column, which, at this moment, cannot be disabled (see #538).

The workaround, especially considering that you appear to be using an HiDPI display without scaling, is to increase zoom while setting the font size to a smaller, normal value (you can zoom in by pressing <kbd>=</kbd> or <kbd>+</kbd>, or by clicking on the zoom in button in the menu).

**Comment by karolszk** [comment]
Zoom / font tuning works as you suggested, but I have still four columns. I wait for #538 eventually. 

Thanks!
