### ISSUE TITLE
Unknown entity &copy;

### ISSUE THREAD

**Issue by fouvry** [johnfactotum/foliate#622]
**Describe the bug**

When I open the Python documentation Ebook with Foliate, the following error message is shown at the top (in a red box)

```
This page contains the following errors:  error on line 5318 at column 11: Entity 'copy' not defined
Below is a rendering of the page up to the first error.
```
![Screenshot from 2020-11-06 11-44-10](https://user-images.githubusercontent.com/3016068/98357509-9f189800-2025-11eb-8f50-5c38888c1bfd.png)

Since the content is HTML, the entity `&copy;` should be known since it is one of the predefined entities for HTML. I suspect that it will be necessary to include this list somewhere (https://www.w3.org/TR/html52/syntax.html#named-character-references, but they may be slightly different for HTML 4, and/or XHTML.)

**To Reproduce**

Download for instance https://docs.python.org/3.8/archives/python-3.8.6-docs.epub, and open it with Foliate.

**Expected behavior**
I expect no error message to appear, and the entity to be displayed.

**Version:**
 - Foliate version: 2.2.0
 - OS/Distribution and version: Ubuntu 20.04.1 LTS
 - Desktop environment: GNOME 3.36.4
 - Installation method: apt

I love Foliate - it's the best Desktop-Ebook solution that I've found until now. Thanks!

**Comment by johnfactotum** [comment]
Closing this one in favor of #699
