### ISSUE TITLE
Editable Annotations

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#626]
1. Often ePubs have superscripts and other artifacts that make the quotes in annotations look strange. i.e.

This is a template sentence1. One, two*, three.

[should be: This is a template sentence.]

This is a very very very very very very very long sentence.

[should be: This is a very ... long sentence.]

Multiple paragraphs appearing as one - harder to read.

2. The extracted plaintext (quotes), should be editable in  a popup.

3. Alternatively a popup dialog, from icon-button below trash icon-button of annotation in F9-menu list.

**Comment by johnfactotum** [comment]
The footnotes are part of the book itself, what you're asking is essentially the same as #136.

The real fix would be to improve footnote extraction.

**Comment by itprojects** [comment]
@johnfactotum This feature request is only aimed at changing the text that goes into the exported annotations. Although changing the notes can be done manually, at the cost of massive editing the JSON before exporting. It would be great if there was a way to edit the quotes from Foliate.

A more relevant example is the user editing the highlighted annotation:

The author, looking at his pen, thinking profusely, hearing sound of irrelevant noises in the background, finally decided to write the chapter.

TO:

The author, ..., finally decided to write the chapter.

Note: this doesn't change the highlighted text cfi's, just what will be exported. The modified text is not a note, at all. It comes from the author.

This way the quotes are kept very short, without losing the author's meaning. Also superscripts are **manually** removed, **only as appropriate**. (This is not always the case.)

**Comment by itprojects** [comment]
@johnfactotum The title of this feature request was chosen in error.

**Comment by johnfactotum** [comment]
Okay, sorry, I misunderstood your issue. Still, the quoted text comes from the book, and should normally not be edited, so editing the quoted text is a bit too niche of an use case, in my opinion.

If there's formatting problems—there's bound to be _some_ problems, since currently the HTML is converted to plaintext—then the solution should be fixing the formatting. Or maybe the raw HTML can be included in the output.

**Comment by itprojects** [comment]
@johnfactotum You are exactly right, that in practice there are many (unavoidable) formatting issues. As such, making algorithm for automatic formatting changes will not be easy.

Including-the-HTML has some problems worth debating:

1. Require CSS export per-quote or will produce strange looking code

2. Will require all affected export functions to be reworked and re-tested

3. May impede the HTML-import parser capability in https://github.com/johnfactotum/foliate/pull/593

So far as altering quotes is concerned - journalists do it all the time. It can definitely help increase readability. Many books have partial (edited) quotes on their book covers. With a manual-edit dialog/popup fix, it's users' choice; there's some liberty in that.

**Comment by itprojects** [comment]
@johnfactotum Screenshot with a mock-up, to illustrate the feature. [The user chooses how to edit/fix the quotation.]

![m](https://user-images.githubusercontent.com/2698054/100393148-9ddcf880-3030-11eb-9398-cf4eaae98893.png)

**Comment by johnfactotum** [comment]
I feel that this is too much trouble and it's just rarely useful to change this. And besides if you edit the text, it might interfere with its ability to act as text assertions, which is actually useful when correcting CFIs.
