### ISSUE TITLE
Map the "Esc" keyboard shortcut to "Go back to the library view"

### ISSUE THREAD

**Issue by nekohayo** [johnfactotum/foliate#631]
When inside a book, I'd like to be able to easily go back to the library/list of books without needing to munch through a hamburger menu.

I think the Escape key would be the standard/expected keyboard shortcut to use for this.

**Comment by JohannPopper** [comment]
Hmm. Yes. And/or a discoverable library button on the header. I agree accessing the library should be a quick function.

**Comment by itprojects** [comment]
There is a discussion for this. https://github.com/johnfactotum/foliate/discussions/656

**Comment by johnfactotum** [comment]
Fixed with 42388fd4bd1d1c98d0c8aa65b278d5df300c106d
