### ISSUE TITLE
Open file dialog window does not scale to fit screen on PinePhone (Manjaro-arm)

### ISSUE THREAD

**Issue by akg83** [johnfactotum/foliate#635]
**Describe the bug**
Having installed Foliate on a linux-arm powered PinePhone (Manjaro-arm beta3 for PinePhone), I am unable to use the "Open.." dialog window in order to open an ebook file, since the dialog window does not scale to fit the device's screen (although most other screens are displayed almost perfectly)

**To Reproduce**
1. On a PinePhone (or probably any Linux-arm powered device that has a relatively small touch screen):
2. Tap the upper right menu to see the menu options
3. Tap on "Open.."

**Expected behavior**
The "Open.." File browsing dialog window will scale and be displayed correctly on the available screen size of the mobile device (PinePhone), including the correct placement of icons, file browser list, textfield, buttons and etc..

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: Manjaro-arm Beta3 for PinePhone
 - Desktop environment: Phosh
 - Installation method: via GUI (Software application)

**Additional context**
Foliate seem to work out-of-the-box on the PinePhone linux-arm powered device, pretty nicely but with a few small set backs, maybe with a relatively small effort it could be possible to tweak Foliate to be PinePhone compatible.

**Comment by johnfactotum** [comment]
The file chooser dialog is not part of Foliate. It's [provided](https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html) by whatever [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal) backend you're using, or else it will use the [default GTK dialog](https://developer.gnome.org/gtk3/stable/GtkFileChooserDialog.html).

For the GTK bug, see https://gitlab.gnome.org/GNOME/gtk/-/issues/2194.

On the Librem5, I believe they're shipping a [patched version of GTK](https://source.puri.sm/Librem5/debs/gtk), the result of which can be seen in this [screenshot](https://puri.sm/wp-content/uploads/2020/11/librem-5-screenshot-document-opener-2020-11-15.png).

**Comment by akg83** [comment]
@johnfactotum Thank you for the reply, this information is very useful
