### ISSUE TITLE
Code examples for Math expressions not rendered, also some math rendered incorrectly

### ISSUE THREAD

**Issue by jmcastagnetto** [johnfactotum/foliate#637]
**Describe the bug**

Checking foliate on Ubuntu 20.04 LTS (using the snap version), and reading the epub version of the book on "Bookdown" (https://bookdown.org/yihui/bookdown/), I see that some of the code examples are not rendered and also some problems with the math equations

**To Reproduce**

1. Go to https://bookdown.org/yihui/bookdown/
2. Download the epub version of the book
3. Load the epub with Foliate, and go to section 2.1.3 and following

**Expected behavior**

Math equations and code examples rendered correctly

**Screenshots**

Here is what I see in Foliate, note the missing code examples and the issues with more complex math:

![Section 2.1.3 of the epub in Foliate](https://user-images.githubusercontent.com/364668/101678750-63119200-3a2c-11eb-8951-abe7b25fd209.png)

![Some more complicated math in Foliate](https://user-images.githubusercontent.com/364668/101678774-6ad13680-3a2c-11eb-9cb7-459d1542d45c.png)

For contrast, here is what I see in Calibre's `ebook-viewer`, which shows the code examples and the complex math looks OK:

![Section 2.1.3 of the epub in Calibre's ebook-viewer](https://user-images.githubusercontent.com/364668/101678993-be438480-3a2c-11eb-8d1c-51f1625c83e7.png)

![Calibre's ebook-viewer with more complex math](https://user-images.githubusercontent.com/364668/101678977-b4ba1c80-3a2c-11eb-977b-3695f634a8b1.png)

The comparison was done with `ebook-viewer` from Calibre 5.3

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: Ubuntu 20.04.1 LTS
 - Desktop environment: GNOME 3.36.3
 - Installation method: snap

**Comment by johnfactotum** [comment]
Can't reproduce this on Arch Linux:
![image](https://user-images.githubusercontent.com/50942278/102176246-eef64480-3e98-11eb-8252-72e0751ed84a.png)


Admittedly I have not tried this on a snap setup, but in any case this is most likely a WebKit related bug, as it seems to occurred with Apple Books as well: https://github.com/rstudio/bookdown/issues/908.

As for the math expressions, they are rendered as MathML, which again is rendered by WebKit, and seems to be mostly correct, though perhaps not completely (but there's probably nothing we can do on Foliate's side).

There _is_ the question of expression 2.2, which is rendered correctly in Calibre in your screenshot, but this particular expression is not an MathML element, so I'm a bit confused as to why it works in Calibre, or indeed, why it isn't rendered as MathML in the first place:
![image](https://user-images.githubusercontent.com/50942278/102176325-1816d500-3e99-11eb-8a6a-7c31f88d9b00.png)

**Comment by jmcastagnetto** [comment]
Removed the snap version and installed from the PPA, and I see the same behaviour as you've seen in Arch. So, it seems like there are might be an issue with the snap version, and also a problem with the epub I was using.

BTW, I've checked also with the epub files listed in https://www.dessci.com/en/reference/ebooks/, and, in particular with the one here: https://www.dessci.com/en/reference/ebooks/hindawi_article.epub, which has a fair amount of math in it, and foliate works fine.

![image](https://user-images.githubusercontent.com/364668/102678190-f0638d80-4174-11eb-9c82-7279b041725d.png)

Guess this can be closed now because using the PPA "works for me" :-)

**Comment by jmcastagnetto** [comment]
Hmm, checking more closely the equations, they do not render completely well in foliate. Here is an screenshot that shows how that page above, looks in Calibre's ebook reader

![image](https://user-images.githubusercontent.com/364668/102678380-fad25700-4175-11eb-8862-d429589f2717.png)

**Comment by johnfactotum** [comment]
I don't think there's anything we can do about this, as the math is rendered by WebKit. If you extract the zip file and open it in GNOME Web (epiphany) you'll find that it's rendered the same.

**Comment by jmcastagnetto** [comment]
Yep, you are right, installed epiphany just to test that, and the equations have rendering problems. So I guess there is nothing else to do with math support in Ubuntu, until Webkit fixes this issue.

Here is a screenshot of how the math looks in epiphany:

![image](https://user-images.githubusercontent.com/364668/102692974-31938600-41e5-11eb-9be5-1e4b5086004e.png)

Just to check, also used Firefox, and it looks a bit better but still with some spacing issues and problems:

![image](https://user-images.githubusercontent.com/364668/102693003-67d10580-41e5-11eb-9e5e-850d3a363219.png)

So I guess I will close this now. Hope to check this again in some time, to see this is fixed in Webkit.

Cheers
