### ISSUE TITLE
Import Google Play Books metadata

### ISSUE THREAD

**Issue by hirnschmalz** [johnfactotum/foliate#645]
**Question:**
Is there a way to import metadata (last reading position, annotations, comments) made in Google Play Books?

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: Arch Linux
 - Desktop environment: GNOME 3.38.2
 - Installation method: Arch Package

**Comment by johnfactotum** [comment]
Does Google provide a way to export those data? If so, what does the exported data look like?

**Comment by hirnschmalz** [comment]
This data can exported via [Google Takeout](https://takeout.google.com/settings/takeout). I can provide you some sample data if you want.

**Comment by johnfactotum** [comment]
The format used by Foliate is documented in the [wiki](https://github.com/johnfactotum/foliate/wiki#how-are-notes-and-bookmarks-stored). You can try writing your own script to convert from Google. The most important bit is the CFI. If Google provides CFI data, and you have the exact same EPUB file available to be opened by Foliate, then the conversion should, at least in theory, be straightforward. If not, then a direct import would not currently be possible.

**Comment by hirnschmalz** [comment]
Thanks for your answer. Since I only have one book to migrate it won't make sense to create a script. I was just wondering if such a migration script already exists.
