### ISSUE TITLE
No hyphenation on Ubuntu 20.04 snap install

### ISSUE THREAD

**Issue by Alex-Bujorianu** [johnfactotum/foliate#647]
**Describe the bug**
Foliate doesn’t seem to hyphenate justified text even though I have hyphen-en-* installed. 

**To Reproduce**
1. Install foliate from snap
2. Install hyphen-en packages.
3. Open a book with justified text
4. See that even large slabs of text are not hyphenated.

**Expected behavior**
Longer words should be hyphenated.

**Screenshots**
![image](https://user-images.githubusercontent.com/75983910/102826200-80593f80-43e0-11eb-8491-5c818a3583ce.png)

![image](https://user-images.githubusercontent.com/75983910/102825919-09bc4200-43e0-11eb-897e-b282edbd25af.png)

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: Ubuntu 20.04 LTS
 - Desktop environment: GNOME 3.36.8
 - Installation method: snap

**Comment by Alex-Bujorianu** [comment]
Note: I decided to try the flatpak version as well. **Hyphenation is working in the flatpak version.** So this is something related to snap.

**Comment by johnfactotum** [comment]
I don't think it can use hyphen rules installed on the host. Flatpak's runtime has some hyphen data installed, I think. 

Whether it can read host data or needs it in the runtime, this should be fixed either by Flatpak/Snap (who would mount the hyphen data inside the sandbox) or by whoever packages WebKitGTK and/or the GNOME environment.
