### ISSUE TITLE
Error clicking on Edit

### ISSUE THREAD

**Issue by dave-theunsub** [johnfactotum/foliate#649]
**Describe the bug**
Click on Edit, this error shows up: "JS ERROR: Error: Wrong type undefined; string expected"

**To Reproduce**
1. Go to '...' under an epub in Library
2. Click on 'Edit'
3. Nothing happens except error (see above)

**Expected behavior**
To edit the book

**Screenshots**
N/A

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: Fedora 33
 - Desktop environment: Xfce
 - Installation method: dnf from repo

**Additional context**
N/A

**Comment by dave-theunsub** [comment]
More info: the book is entitled "(1986) Title of Book". Maybe it doesn't like the "("?

**Comment by johnfactotum** [comment]
In the gtk4 branch, there's no "edit" anymore. And I think this makes sense. It's only used for editing the file's path, but you can do that by simply reopening the file from the new location.
