### ISSUE TITLE
Width of Library Books' Progress Bar

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#652]
**Describe the bug**
The widths of the progress bar in the library are very strange. See screenshot below.

**To Reproduce**
1. Go to Library Window

**Expected behavior**
The widths should go all the way and be consistent. Labels `46%` and `100%` should be vertically aligned.

**Screenshots**
![Screenshot for the description.](https://user-images.githubusercontent.com/2698054/103643271-4cd3f480-4f4c-11eb-84d4-8afcf4815bb5.png)

**Version:**
 - Foliate version: 2.5.0
 - Ubuntu 20.04.1
 - GNOME 3.36.8
 - Flatpak

**Comment by johnfactotum** [comment]
It's not a bug. It's a feature. The width of the progress bar is proportionate to the total length of the book. It's similar to how Kindle displays books. Screenshot:
![image](https://user-images.githubusercontent.com/50942278/103741816-aa6e4c80-4ff1-11eb-9eae-31b247fbf121.png)
(Image from [MakeUseOf](https://www.makeuseof.com/tag/organize-kindle-minimal-effort/))

**Comment by itprojects** [comment]
Foliate is superior to Kindle.
