### ISSUE TITLE
Festival --tts --language russian

### ISSUE THREAD

**Issue by kaia009** [johnfactotum/foliate#657]
**Question:**
I use Ubuntu 20.04 and installed Foliate 2.5.0 through snap channel.

I installed FESTIVAL and festvox.ru from repositories 
I also created a file ~/.festivalrc where I set my default russian voice.
This allows me to call, from the comande line the reading of a russian plain text file.

In FOLIATE settings, espeak-ng (default) reads the English exampple text, but not a word from an English epub file.
When I change to festival --tts, nothing happens at all. 
Since my system recognises that russian is my default language for text to speech synthesis, I wonder what I can do to get Foliate to do so as well.
I hpe somebody can help.

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: Ubuntu 20.04
 - Desktop environment: [e.g. GNOME 3.36.8
![Screenshot from 2021-01-17 18-30-56](https://user-images.githubusercontent.com/77581948/104850952-5406e500-58f2-11eb-91e3-7a642b71e0d6.png)

 - Installation method: snap

**Comment by johnfactotum** [comment]
The Snap package currently only has `espeak-ng` and the `mb-en1` voice packaged, I think. See #324. It can't access the `festival` instance on the host system.

**Comment by kaia009** [comment]
Ahhh ... thank you!
I now finally discovered that there is a ppa for Foliate, and indeed, now I get Russian text to speech.
