### ISSUE TITLE
Adding Books via Nautilus or CLI inteface fails with Flatpak.

### ISSUE THREAD

**Issue by ghost** [johnfactotum/foliate#658]
Foliate's flatpak appears to be broken when trying to drag and drop a file from Nautilus. Also --add from the command line fails in a similar fashion.  Non-flatpak version of the application works when dragging and dropping books. This is on Fedora 33.

(com.github.johnfactotum.Foliate:2): Gjs-WARNING **: 22:27:07.695: JS ERROR: Gio.IOErrorEnum: Error when getting information for file “/home/rjk/Documents/Books/Harlan Ellison/The Beast That Shouted Love at the Heart of the World_ Stories (76)/The Beast That Shouted Love at the Heart o - Harlan Ellison.epub”: No such file or directory
getFileInfoAsync/</<@resource:///com/github/johnfactotum/Foliate/js/utils.js:890:30
main@resource:///com/github/johnfactotum/Foliate/js/main.js:474:24
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
@/app/bin/com.github.johnfactotum.Foliate:9:17

**Comment by johnfactotum** [comment]
Yeah, for Flatpak, it can't access the files directly because it's sandboxed. The portal for drag and drop seems be supported by GTK 4 but not GTK 3. See https://github.com/flatpak/xdg-desktop-portal/issues/99.

**Comment by johnfactotum** [comment]
I don't think this is a bug. One should use the `--file-forwarding` option of the `flatpak` command.

As of v3.0, there's no `--add` option or drag and drop, but those are separate issues.
