### ISSUE TITLE
Custom themes aren't saved across sessions

### ISSUE THREAD

**Issue by VexedBlaze** [johnfactotum/foliate#660]
**Describe the bug**
Custom themes aren't properly saved across sessions.

**To Reproduce**
1. Make a custom theme
2. Close Foliate
3. Open Foliate
4. Go to themes section in the menu, switch theme, and then switch back to your custom theme (which should've lost its name and color settings)

**Expected behavior**
Colors switch to a default black on white theme. and your previous custom theme is now a default black on white theme with no name.

**Screenshots**
![1](https://imgur.com/mc732ni.png)
![2](https://imgur.com/l6lwI5s.png)
![3](https://imgur.com/VV7MfGT.png)
![4](https://imgur.com/dAncvf6.png)
![5](https://imgur.com/v4medjT.png)

**Video**
![gif of the problem](https://media.giphy.com/media/AD1hggS3UK9DLRAEIA/giphy.gif)

**Version:**
 - Foliate version: 2.5.0-1
 - OS/Distribution: Arch Linux
 - Desktop environment: i3wm 4.19-1
 - Installation method: Pacman

**Additional context**
The theme stays activated on restarting, it only switches to white after you switch to another theme and try switching to it again (or clicking on the theme itself).

**Comment by johnfactotum** [comment]
It happens when editing catalogs as well. I think it's due to changes in newer versions of GJS; GObject properties are no longer included when calling `JSON.stringify()` on them, so it only saves an empty `{}`.
