### ISSUE TITLE
Kindle Support

### ISSUE THREAD

**Issue by Uriegas** [johnfactotum/foliate#661]
Hi, I really like Foliate, it is a really usefull ebook reader.

I would like to be able to use it on the Kindle, I wonder if it is possible, I know that it is possible with Calibre.
It would be really great to have this feature.

**Comment by itprojects** [comment]
An Android port would be difficult, just like moving a web app in JavaScript to Java.

Duplicate of https://github.com/johnfactotum/foliate/issues/336 ?

**Comment by johnfactotum** [comment]
I assume you're talking about connecting to a Kindle device via USB? In which case it's a duplicate of #140
