### ISSUE TITLE
Foliate isn't translated in ru_UA locale

### ISSUE THREAD

**Issue by handicraftsman** [johnfactotum/foliate#662]
**Describe the bug**
On `ru_UA` locale Foliate falls back to English `.mo` file.

**To Reproduce**
Run the app with `LANG=ru_UA` environment variable.

**Expected behavior**
Using Russian `.mo` file on all Russian-language locales.

**Suggested fix**
Rename `ru_RU.po` to `ru.po` and update LINGUAS.

**Version:**
 - Foliate version: 2.5.0
 - Fedora 33
 - Desktop environment: GNOME 3.38
 - Installation method: Flatpak

**Comment by itprojects** [comment]
@handicraftsman Nickolay, can you open a Merge Request, with the changes you suggested? It can make it quicker to adopt you proposals.
