### ISSUE TITLE
Error launching Foliate with Kernel 4.4 in Manjaro: Here's how to fix

### ISSUE THREAD

**Issue by apandada1** [johnfactotum/foliate#668]
I am using kernel 4.4 in Manjaro, and installed Foliate from Manjaro repositories.
When I try to open a book, the window opens, but it keeps loading forever. When I launched it from command line, it showed following error message.

`bwrap: Creating new namespace failed, likely because the kernel does not support user namespaces. bwrap must be installed setuid on such systems.`

I found how to fix it [here](https://github.com/containers/bubblewrap/issues/324#issuecomment-517378834).

Enter the command
`sudo chmod u+s /usr/bin/bwrap`

I have verified that it fixes this issue, and I did not notice any regression.

(This is not a Foliate bug, but Foliate is affected by it, so I decided to share the solution.)

**Comment by archisman-panigrahi** [comment]
I came across the same issue in Foliate 3.1 in Ubuntu 24.04 beta, and the same workaround ` sudo chmod u+s /usr/bin/bwrap` fixed the issue.
