### ISSUE TITLE
Add spd-say for tts

### ISSUE THREAD

**Issue by jpenguin** [johnfactotum/foliate#669]
spd-say has become a pretty standard interface for Linux TTS.  Most TTS voices can be used by spd-say now, I use oralux-voxin, but it can use: espeak, flite, cepstral, ivona, rhvoice, ibmtts, and many others.

http://manpages.ubuntu.com/manpages/trusty/man1/spd-say.1.html

**Comment by itprojects** [comment]
@jpenguin You can already do that. Here's the steps you follow:

`Menu` > `Preferences` > `Text-to-speech command`

`spd-say -p 50 -e`

On the right there is a button `Configure`, where you press on `Other` radio button. You may need to restart the app once.

**Comment by jpenguin** [comment]
I though I tried "spd-say -e" and it worked with test button, but it made the pages in the book flip like crazy

**Comment by itprojects** [comment]
@jpenguin Put an extra flag `-w` to wait [for it].

`spd-say -e -w -p 50`

You can also add accent/voice with `-y sv` for Swedish. To list all the voices run `spd-say -L`.

**Comment by itprojects** [comment]
@jpenguin Did the `-w` work on your machine?

**Comment by jpenguin** [comment]
Yes, -we works

**Comment by itprojects** [comment]
@jpenguin Close bug?

**Comment by johnfactotum** [comment]
I think it probably makes sense to switch to speech-dispatcher. Ideally we should use the SpeechSynthesis Web API, which in Firefox and Chromium uses speech-dispatcher. Unfortunately WebKitGTK doesn't support the API. But we can, and probably should still use speech-dispatcher directly.

Currently Foliate relaunches the TTS command every time, which is sort of okay as it speaks one page at a time, which, however, is itself bad. In the future I'd like to implement more proper TTS support with sentence or word level highlighting, etc., not to mention SSML support, which will require something that has a nicer and more capable API like SpeechSynthesis or speech-dispatcher.

**Comment by johnfactotum** [comment]
Closing this as it's already possible to use speech-dispatcher. For switching to speech-dispatcher, I've opened #829.

**Comment by securegh** [comment]
@johnfactotum I was able to make[ mimic3](https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mimic-tts/mimic-3) and spd-say work on Foliate thansks to @itprojects command `spd-say -e -w -p 50`
I would like to mention that mimic3 is a game changer in terms of TTS, a deeper integration with Foliate would be very much appreciated. Right now, I have a weird bug where the narration would stop in the middle of a word, it seems like TTS queue is not word aware, so the word is split like 'sus picious'  that narration would continue though. 
The ideal scenario would be if TTS queue is period award, so it would stop loading on a period, not in the middle of a word.
