### ISSUE TITLE
[UX issue] As a user, I think the popup when clicking a link is unnecessary.

### ISSUE THREAD

**Issue by vinliao** [johnfactotum/foliate#671]
When I click a link on the table of content page, please take me to where I want to go.

![Screenshot from 2021-02-13 12-25-14](https://user-images.githubusercontent.com/34117807/107842640-6db72180-6df7-11eb-8d54-744238febf8d.png)

I don't know why this popup exist at all, it doesn't seem to serve any function. Sometimes it has snippets on what the chapter looks like, but I'd rather just read it "there" rather than reading it on that teeny-tiny popup.

**Comment by itprojects** [comment]
This is not a bug/issue.

There is a Foliate feature in the Preferences called "Do nothing" used with "When a word is selected" and "When multiple words are selected", it will remove the popup.

**Comment by vinliao** [comment]
Choosing "do nothing" on the preference that you mentioned doesn't get rid of the popup when I click a link to a certain chapter.

**Comment by itprojects** [comment]
@vinliao The specific popup that "has snippets on what the chapter looks like" is a footnote getting function. It is necessary for some older (format) or irregular epubs (typically from Gutenberg). Without it you would not have footnotes.

If you just want to go to a chapter, why not just press F9 and choose the chapter that you see in your book's contents page?

**Comment by johnfactotum** [comment]
This feature is called "Reference Preview", as can be seen on the bottom of the popover. You can disable it in the primary menu > Advanced > Reference Preview.

I think this counts as a duplicate of #184. See also #124, #127, and #480.

**Comment by vinliao** [comment]
@johnfactotum 

Thank you, it works.

And thank you also for this piece of software. It's very delightful.
