### ISSUE TITLE
Search results in sidebar

### ISSUE THREAD

**Issue by lightonflux** [johnfactotum/foliate#674]
**Is your feature request related to a problem? Please describe.**

One advantage over other apps like PDF readers is the highlighting, which is much nicer in foliate. 
But when using the search (nice layout! :+1: ) one problem when quickly searching a reference is that you have to reopen it all the time to jump between results. With the current layout the user needs to do one additional click for each result (open the pop-over) when searching through 50 results this is quite cumbersome. (Sometimes the immediate surrounding of the match is not enough to find the correct result.)

**Describe the solution you'd like**
Make it possible to break out the search results into a sidebar, so the user can use it to quickly jump between results. 

To compare: 
1. Open PDF in evince
2. Search for a keyword, like a name of character
3. Use the search results in the sidebar to quickly sift through the document

Try to do the same in foliate (not with a pdf obviously).

![Bildschirmfoto von 2021-02-15 10-29-10](https://user-images.githubusercontent.com/1377943/107928510-b3e7be80-6f78-11eb-8f3b-bbbeff9a37e9.png)
![Bildschirmfoto von 2021-02-15 10-29-24](https://user-images.githubusercontent.com/1377943/107928512-b4805500-6f78-11eb-8be6-27f7a7fae847.png)

**Alternatives**
Maybe a fast switch panel like with the navigation bar instead of sidebar?
Problem here: not enough space for the nice layout of the popover.

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.

**Comment by lightonflux** [comment]
Is there a flatpak build of the ftk4 branch by any chance? Or are PPAs the only way currently? Thanks.
