### ISSUE TITLE
Failed to load libwebkit2gtk-4.0.so and libjavascriptcoregtk-4.0.so

### ISSUE THREAD

**Issue by jmvalenciz** [johnfactotum/foliate#675]
**Describe the bug**
The application doesn't work. It crash when i try to open it and gives me the next error message:

```
** (com.github.johnfactotum.Foliate:131737): WARNING **: 08:39:23.004: Failed to load shared library 'libwebkit2gtk-4.0.so.37' referenced by the typelib: /usr/lib/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/libwebkit2gtk-4.0.so.37)

** (com.github.johnfactotum.Foliate:131737): WARNING **: 08:39:23.005: Failed to load shared library 'libjavascriptcoregtk-4.0.so.18' referenced by the typelib: /usr/lib/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/libjavascriptcoregtk-4.0.so.18)

(com.github.johnfactotum.Foliate:131737): Gjs-CRITICAL **: 08:39:23.005: JS ERROR: Error: Unsupported type void, deriving from fundamental void
@resource:///com/github/johnfactotum/Foliate/js/main.js:37:20
@/usr/bin/foliate:9:1


(com.github.johnfactotum.Foliate:131737): Gjs-CRITICAL **: 08:39:23.005: Script /usr/bin/foliate threw an exception
}
```

**To Reproduce**
1. Open foliate from a terminal
2. then crash with error message

**Screenshots**
This is the output when I look for the shared libraries in the error message:
![image](https://user-images.githubusercontent.com/39179298/107955447-cdced480-6f6b-11eb-9d6f-5a7fba15901b.png)
![image](https://user-images.githubusercontent.com/39179298/107958477-0b356100-6f70-11eb-83d1-de37faeddbab.png)

**Version:**
 - Foliate version: 2.5.0-1
 - OS/Distribution and version: ArchLinux
 - Desktop environment: i3-gaps
 - Installation method: pacman
 - webkit2gtk version: 2.30.5-1

**Comment by itprojects** [comment]
Does this also happen with the flatpak version?

**Comment by jmvalenciz** [comment]
I noticed that I haven't updated my system in a few days then I updated and now it's working. I don't know which package was the one that failed because webkit2gtk was up to date but now it doesn't matter.
