### ISSUE TITLE
Keyboard shortcut to Zoom in  and out are not working

### ISSUE THREAD

**Issue by anishmittal2020** [johnfactotum/foliate#677]
**Describe the bug**
Keyboard shortcut to Zoom in  and out are not working. Following are not working
Shortcut| Key
----|----
Zoom In |`+` / `Ctrl` + `+`  / `Ctrl` + `Mouse Scroll Forward`
Zoom In |`-` / `Ctrl` + `-`  / `Ctrl` + `Mouse Scroll Backward`

**To Reproduce**
See description

**Expected behavior**
See description

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: [e.g. Ubuntu 18.04] Ubuntu 20.04
 - Desktop environment: [e.g. GNOME 3.36]  GNOME 3.36.8
 - Installation method: [e.g. Flatpak] Meson Build

**Comment by itprojects** [comment]
@anishmittal2020 How is possible that you are using `v2.5.0` with a 'Deb file from Github', which is missing from the release (tags) page, according to #676 ?

Does this happen in the `.flatpak` version? [Here.](https://flathub.org/apps/details/com.github.johnfactotum.Foliate)

**Comment by itprojects** [comment]
@anishmittal2020 Does zoom work from the menu-buttons? (Menu opens with F10, it's on the top right)

What error messages are visible, when you open a terminal and type in `com.github.johnfactotum.Foliate`  ?

**Comment by anishmittal2020** [comment]
```
$ com.github.johnfactotum.Foliate 

(com.github.johnfactotum.Foliate:396580): Gtk-WARNING **: 14:24:51.929: Theme parsing error: gtk.css:10:4: Expected semicolon

(com.github.johnfactotum.Foliate:396580): Gtk-WARNING **: 14:24:51.930: Theme parsing error: gtk.css:12:4: Expected semicolon

(WebKitWebProcess:2): Gtk-WARNING **: 14:24:54.412: Theme parsing error: gtk.css:10:4: Expected semicolon

(WebKitWebProcess:2): Gtk-WARNING **: 14:24:54.412: Theme parsing error: gtk.css:12:4: Expected semicolon
```

> @anishmittal2020 Does zoom work from the menu-buttons? (Menu opens with F10, it's on the top right)

Yes, when I went to the menu option, I could click magnifying glass symbol with + and - to zoom in and zoom out. But pressing F10 does nothing.

**Comment by itprojects** [comment]
> Theme parsing error: gtk.css:10:4: Expected semicolon

Suggests a broken theme file. But which theme file?

Maybe you also have a broken installation?. Try uninstalling, cleaning all leftover files from the system, then download, compile, and install.

**Comment by johnfactotum** [comment]
> But pressing F10 does nothing.
> When I restarted the com.github.johnfactotum.Foliate from terminal, F10 worked, without moving the mouse I could see that the mouse pointer was very quickly going to the menu button and clicking, and weirdly it clicks About Foliate, just by pressing F10 (Even if the mouse pointer was far away from the menu).

It sounds like something is hijacking your keyboard or mouse. Does this happen with other applications? Have you set up global shortcuts or run other programs or GNOME Shell extensions that could interfere with key presses or pointer movement?

**Comment by anishmittal2020** [comment]
`Ctrl` + `+` , works for me in Firefox and I am able to zoom in. So, there is no global shortcut. And, my device is a workstation inside my room with no physical access, so I don't think that it got hijacked.

Today I was not able to start the foliate from Terminal, I get this error

```
$ com.github.johnfactotum.Foliate 

(com.github.johnfactotum.Foliate:562975): Gtk-WARNING **: 14:19:13.267: Theme parsing error: gtk.css:10:4: Expected semicolon

(com.github.johnfactotum.Foliate:562975): Gtk-WARNING **: 14:19:13.267: Theme parsing error: gtk.css:12:4: Expected semicolon

(WebKitWebProcess:2): Gtk-WARNING **: 14:19:13.653: Theme parsing error: gtk.css:10:4: Expected semicolon

(WebKitWebProcess:2): Gtk-WARNING **: 14:19:13.653: Theme parsing error: gtk.css:12:4: Expected semicolon

(WebKitWebProcess:2): Gdk-ERROR **: 14:19:16.187: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 216 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by johnfactotum** [comment]
Well, at any rate, it has nothing to do with zooming since <kbd>F10</kbd> doesn't even work for you at all (is there any shortcut that works?) when not launched from the command line, but works in an incredibly weird way when launched from the command line. I can't reproduce this, and I can't really think of anything in the app itself that could possibly cause the pointer to move around clicking stuff on its own.

> The program 'WebKitWebProcess' received an X Window System error.
> This probably reflects a bug in the program.
> The error was 'BadValue (integer parameter out of range for operation)'.

Copying from https://github.com/johnfactotum/foliate/issues/504#issuecomment-651505798:

Are you using NVIDIA? Can you try

- Rebooting,
- Updating your graphics driver,
- Re-installing your graphics driver,
- Installing a different graphics driver, or
- Switching to non-NVIDIA graphics?

Otherwise I don't really have any idea. People run into "'WebKitWebProcess' received an X Window System error" errors like these from time to time but I've never been able to reproduce them. And it always seems to be some kind of graphics problem.

**Comment by itprojects** [comment]
This bug **cannot** be reproduced on Ubuntu 20.10.

**Comment by anishmittal2020** [comment]
> Copying from [#504 (comment)](https://github.com/johnfactotum/foliate/issues/504#issuecomment-651505798):
> 
> > Are you using NVIDIA? Can you try
> > 
> > * Rebooting,
> > * Updating your graphics driver,
> > * Re-installing your graphics driver,
> > * Installing a different graphics driver, or
> > * Switching to non-NVIDIA graphics?
> > 
> > Otherwise I don't really have any idea. People run into "'WebKitWebProcess' received an X Window System error" errors like these from time to time but I've never been able to reproduce them. And it always seems to be some kind of graphics problem.

Rebooting helped

**Comment by itprojects** [comment]
@anishmittal2020 So this is not a bug anymore, for you? Zooming works?

**Comment by anishmittal2020** [comment]
@itprojects 

I am extremely sorry, to say that I was wrong. You were right there was a Gnome shortcut for F10, which I have disabled. I tested all shortcuts mentioned in the keyboard shortcut window, everything works except the zooming in and out. 


Note: `Ctrl` +  `+` works in Chrome, Firefox and Visual Studio Code.

**Comment by itprojects** [comment]
@anishmittal2020 The bug **cannot** be reproduced in Ubuntu 20.04.02 LTS. Could it be that you have a very broken OS install?

**Comment by anishmittal2020** [comment]
Everything else is working fine. But if you say so, it might be the case.

**Comment by apandada1** [comment]
I tried it in **KDE** Neon, based on Ubuntu 20.04 (Foliate from **PPA**), in a laptop. The shortcuts involving numpad does not work (irrespective of whether Num Lock is on or off), but their equivalents in other parts of the keyboard does work.

The `ctrl` + `(numpad) +` does not work. However, `ctrl` + `+` (the one near the backspace, bundled with `=`) works.

Also, `ctrl` + `(numpad) -` does not work, but `ctrl` + `-` (the one near the backspace, bundled with `_`) works.

Similarly, `ctrl` + `(numpad) 0` does not work, but `ctrl` + `0 (on top of the alphabets)` works.'

Other shortcuts which do not involve the numpad works.

**Comment by anishmittal2020** [comment]
> I tried it in **KDE** Neon, based on Ubuntu 20.04 (Foliate from **PPA**), in a laptop. The shortcuts involving numpad does not work (irrespective of whether Num Lock is on or off), but their equivalents in other parts of the keyboard does work.
> 
> The `ctrl` + `(numpad) +` does not work. However, `ctrl` + `+` (the one near the backspace, bundled with `=`) works.
> 
> Also, `ctrl` + `(numpad) -` does not work, but `ctrl` + `-` (the one near the backspace, bundled with `_`) works.
> 
> Similarly, `ctrl` + `(numpad) 0` does not work, but `ctrl` + `0 (on top of the alphabets, left to -,+ and backspace)` works.'
> 
> Other shortcuts which do not involve the numpad work.
> @anishmittal2020 Can you check this?

You are right.

**Comment by apandada1** [comment]
I can confirm that this is fixed in **KDE** Neon and Linux Mint **Cinnamon**.
Maybe time for a new release?
