### ISSUE TITLE
Shortcut for progress bar

### ISSUE THREAD

**Issue by monday15** [johnfactotum/foliate#68]
It would be nice to have a keyboard shortcut for "Reading Progress bar" option.

**Comment by johnfactotum** [comment]
What do you think the shortcut should be?

**Comment by monday15** [comment]
Any key is fine. Ctrl + P (progress) seems appropriate.

**Comment by itprojects** [comment]
Can you add ESC key as a secondary shortcut for toggling out of full-screen? It would be a very natural keyboard shortcut.

`accelerator: 'F11', title: _('Toggle fullscreen')`
