### ISSUE TITLE
Support option for spacing between paragrpahs

### ISSUE THREAD

**Issue by makeworld-the-better-one** [johnfactotum/foliate#681]
**Is your feature request related to a problem? Please describe.**

I find it easier to read when there are empty lines between paragraphs. I suppose I am used to Firefox's Reader Mode which does this to HTML pages.

**Describe the solution you'd like**

Another option where options like Margin and Spacing are, that controls the number of empty lines between paragraphs. Default set to 0.

**Describe alternatives you've considered**

Changing the spacing of all lines is related, but not the same.

**Additional context**

Here is an example of what I mean. This is Firefox Reader Mode on [this page](https://www.fadedpage.com/books/20190862/html.php).

![image](https://user-images.githubusercontent.com/25111343/109246178-c3a0a780-77af-11eb-9392-eb7011d56337.png)

**Comment by johnfactotum** [comment]
I don't want to add too many styling options, especially when the existing styles are already causing too many problems with the publisher style sheet. This probably makes more sense as custom user styles, if we ever add that option.
