### ISSUE TITLE
Shortcut help window doesn’t fit on narrower screens

### ISSUE THREAD

**Issue by afranke** [johnfactotum/foliate#687]
**Describe the bug**
The minimum width of the shortcut dialog window is too large, the close button is off screen and if you don’t have a keyboard then it’s impossible to close it without moving windows around.

**To Reproduce**
1. Open Foliate, maximised, on a 800px screen.
2. Click on the menu item for the keyboard shortcuts dialog
3. See how the dialog is too wide and the X is off screen.

**Expected behavior**
Content is rearranged to fit in 800 px or probably even less.

**Screenshots**
![foliate-shortcut-window](https://user-images.githubusercontent.com/117241/111062213-d4d3fe80-84a7-11eb-9450-ad4936749835.png)

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: Fedora 33
 - Desktop environment: GNOME 3.38
 - Installation method: Flatpak

**Comment by johnfactotum** [comment]
The shortcuts window is a widget provided by GTK, and unfortunately it's not adaptive. See https://gitlab.gnome.org/GNOME/gtk/-/issues/700 and https://source.puri.sm/Librem5/debs/gtk/-/issues/30

**Comment by afranke** [comment]
Indeed, I found out that the issue lies upstream later on. I’ll close this, as there is not much you can do about it.
