### ISSUE TITLE
Recently opened books list

### ISSUE THREAD

**Issue by monday15** [johnfactotum/foliate#69]
It would be handy to have a list of recently opened books (5 or something like that), instead of 'Continue reading' option on a welcome screen.

**Comment by Sparsa** [comment]
This is the best ebook reader I laid my eyes on for Linux systems. This enhancement will make this book even better. :D. Great work man @johnfactotum massive respect \m/

**Comment by itprojects** [comment]
@johnfactotum How do you evaluate the following workaround:

If the book name, author, and file location are stored in the JSONs, then all you'd have to do is loop over them, populating a list in Foliate with the book names.

On list item click: a popup asks if the user wants to read that book.

If yes: saves the progress in the current book (if any) to file; opens the new book.
