### ISSUE TITLE
Add Find Next 

### ISSUE THREAD

**Issue by dekay** [johnfactotum/foliate#693]
If I am searching for a word or phrase that comes up multiple times within the book, I need to continually re-click the search icon in the title bar.

A "Find Next" function with an associated keyboard shortcut as found in almost all text editors and web browsers would be a welcome feature addition.  This paired with a "Find Previous" function and shortcut would also be very welcome.

The current method of showing the search term in context is helpful but I miss the quick search from the keyboard as offered in other programs.

Otherwise, foliate is fantastic!  I just discovered it today and it instantly became my default epub reader.  Thank you!

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.

**Comment by dekay** [comment]
I'm late in saying this, but thank you!
