### ISSUE TITLE
Crashes with Fedora 34 and gnome 40

### ISSUE THREAD

**Issue by linusheinz** [johnfactotum/foliate#695]
I can open the app but when I choose a book it crashes instantly.
Version: 2.5.0
gjs:1.68.0
webkit2gtk3:-2.31.91-1
Best regards and thanks for the great app

**Comment by AlexCD17** [comment]
I had a similar problem in arch,  won't open any book. Downgraded gjs 1.68 to 1.66 and that fixed my issue.

**Comment by johnfactotum** [comment]
Duplicate of #689
