### ISSUE TITLE
Render page as HTML if it's is not valid XHTML

### ISSUE THREAD

**Issue by Rudo2204** [johnfactotum/foliate#699]
**Question:**
When Foliate encounters mismatching tag, it shows a big red box with these info. 
```
This page contains the following errors:
error on line 20 at column 40: Opening and ending tag mismatch: span line 0 and p
Below is a rendering of the page up to the first error.
```
Is there any way I can force Foliate to ignore these non-fatal errors? (aka no red boxes)
**Version:**
 - Foliate version: 2.6.2
 - OS/Distribution and version: MX 19.3
 - Desktop environment: xfce4
 - Installation method: dpkg

**Comment by Rudo2204** [comment]
I take back what I said about "non-fatal". I forgot that epub uses XHTML, so you have to close tags...

**Comment by Rudo2204** [comment]
I found a workaround which is to convert the bad formatted epub to a properly formatted one using calibre, then Foliate can read it normally. I'm not sure if this issue is still relevant but it would be nice if Foliate can render the bad one normally like calibre without having to convert first.

**Comment by johnfactotum** [comment]
I think maybe it can try detecting the error and try parsing as HTML instead. It would require patching Epub.js, though.

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.
