### ISSUE TITLE
How do I toggle header bar/whitepage mode on a touch screen?

### ISSUE THREAD

**Issue by afranke** [johnfactotum/foliate#702]
**Question:**
Using Foliate on a tablet, the window hides the header bar and status bar, which is great for reading. The header bar is useful however to access the menu. On a desktop computer I see that I can hover over the area where the header bar should be and it fades in, but on tablet I couldn’t find a way to bring it back. I tried single tap in the middle of the page, double tap, tapping at the top of the window on the book title…

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Fedora 33
 - Desktop environment: GNOME 3.38
 - Installation method: Flatpak from Flathub.

**Comment by afranke** [comment]
I have to mention I disabled tap-left/tap-right to change pages, I swipe as I was changing pages by accident all the time.

**Comment by johnfactotum** [comment]
Unfortunately, there's currently no way of doing that other than enabling "tap to turn pages", which, if enabled, enables you to tap the middle of the page to show the headerbar and navbar.

**Comment by afranke** [comment]
Is it just not currently suppor yet technically feasible?

**Comment by johnfactotum** [comment]
It's technically feasible, just not implement, yet. See https://github.com/johnfactotum/foliate/issues/379. I think in the future the whole "tap to turn" feature should probably be removed, and all taps would just toggle the headerbar and navbar.
