### ISSUE TITLE
After the latest update, the app is not opening ebooks

### ISSUE THREAD

**Issue by Vyshnav2255** [johnfactotum/foliate#707]
**Describe the bug**
After the latest update, the app Is not opening ebooks and is showing only the loading animating. The books are not opening.

**To Reproduce**
1. Click on an Ebook

**Expected behavior**
It will open the ebook in less than 10 seconds.

**Screenshots**
![image](https://user-images.githubusercontent.com/36617488/113531209-c29c3a80-95e5-11eb-826d-7596e4f872b1.png)

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Elementary OS 5.1.7 Hera
 - Desktop environment: GTK 3.22.30
 - Installation method: App Store

**Comment by apandada1** [comment]
Can you open the app from terminal (with the command `com.github.johnfactotum.Foliate`) and post the output here?

I am not very familiar to Elementary OS. Is the version from app store a flatpak package or a deb package?

You can use the commands `apt search foliate` and `flatpak list ` to determine how Foliate was installed.

Also, can you reproduce this error with the .deb package in the releases page?

**Comment by Vyshnav2255** [comment]
Comand is not working.

Flatpak

I tried and it is listed.

I deleted the flatpak version and installed the 2.6.2 deb file, it working perfectly.

**Comment by TenshiZer0** [comment]
Same problem here with the Flatpak version.

I deleted the flatpak and installed the version 2.6.3 deb package, it is working perfectly now

**Comment by anotherbugmaster** [comment]
Arch Linux 5.11.9 and 5.10.26, same issue here.
Tried foliate versions 2.5.0 from pacman repo and 1.5.3.r10.gd35e3e6 (2.6.3) from AUR, books don't open.

**Comment by anotherbugmaster** [comment]
Everything seems to work fine on Arch Linux 5.11.13 though.

**Comment by apandada1** [comment]
@anotherbugmaster Arch already has 2.6.3 in official repo. Is the bug present there? What is the terminal output?

**Comment by anotherbugmaster** [comment]
2.6.3 works fine on 5.11.13. I had a stale mirror in mirrorlist and the last version of foliate was 2.5.0. After regenerating a new one and updating all packages the issue has gone

**Comment by anotherbugmaster** [comment]
Seems like something was wrong with some dependency, but I don't know which one

**Comment by johnfactotum** [comment]
It's impossible to say for sure without more information, but this looks similar to, if not exactly the same issue as #322, #504, #627, #636. The problem seems to be that the WebKit process just won't function for some reason, and it usually goes away after restarting/updating the system.

**Comment by emiddleton** [comment]
I am getting the same issue with 2.6.2 on gentoo.  Running from the terminal I get

```
(WebKitWebProcess:3): Gdk-ERROR **: 00:22:37.728: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 214 error_code 2 request_code 150 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
   ```

**Comment by apandada1** [comment]
@emiddleton Is the error present in v2.6.3 or the code in latest master branch?

**Comment by emiddleton** [comment]
It looks like the above error I was having might have been caused by nvidia driver getting into a funky state due to a kernel upgrade.  After rebooting the OS, foliate loads books without errors.  v2.6.2 is the latest version with an ebuild for Gentoo linux.  I have made an updated ebuild and am not seeing this error with that either.

**Comment by JanuaryLimes** [comment]
Same endless loading state on Pop!_OS 20.10 Foliate 2.6.3 installed via flatpak

output from running `flatpak run com.github.johnfactotum.Foliate`

![image](https://user-images.githubusercontent.com/15075229/114452530-d55fd200-9bd8-11eb-8dc7-7c29eb4136b8.png)

**Comment by johnfactotum** [comment]
This looks like the same problem as https://github.com/flathub/org.gnome.Epiphany/issues/21.

I guess Foliate should connect to the `web-process-terminated` signal of the WebView, so that when the web process stops working for whatever reason it will at least show a more helpful error message instead of getting stuck at the spinner.

**Comment by sysarcher** [comment]
I get the following

```console
$ /usr/bin/gjs /usr/bin/com.github.johnfactotum.Foliate

(WebKitWebProcess:2): Gdk-ERROR **: 14:42:59.452: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 197 error_code 2 request_code 154 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by apandada1** [comment]
@sysarcher What is your OS and what is the method of installation? It is most likely due to an NVidia driver issue.

https://github.com/johnfactotum/foliate/issues/295
https://github.com/johnfactotum/foliate/issues/504#issuecomment-651505798

**Comment by sysarcher** [comment]
@apandada1 thanks for the hints.. the issue was indeed the NVidia driver. I only had to do a reboot.

**Comment by Oberdan51** [comment]
After the last update (2.6.3) on Ubuntu 18.04.5 LTS I can no longer add ebooks.
I can open ebooks and read it but when I close Foliate and and open it again, there is no trace of the last ebook.

**Comment by Oberdan51** [comment]
It doesn't matter which way. 
I tried both (adding or dragging & dropping.

**Comment by apandada1** [comment]
@Oberdan51 How did you install Foliate? Did you try a different installation method?

**Comment by Oberdan51** [comment]
The first time I installed Foliate with snap.
Yesterday, after verifying that it was no longer adding ebooks, I removed the snap and reinstalled it via apt. But unfortunately it still doesn't add ebooks.
