### ISSUE TITLE
One more question about font-size

### ISSUE THREAD

**Issue by phouchg42** [johnfactotum/foliate#709]
**Question:**

There is [stated](https://github.com/johnfactotum/foliate/wiki) that Foliate “overrides font-size on `body` and `p` with `!important`.” Can you make this optional (in settings) or provide the way to get rid of this (like hidden option in dconf)? I think, force _all_ well-formatted books to look poorer just because _some_ users or vendors ignores HTML semantics and standards is wrong.

Say, I have `blockquote p`, `.epigraph p`, `.poem p`, `header p` (for subheadings) etc. because I want them to look different from the rest of `p`. With your hardcoded thing all `p` font-sizes are the same and there is no way to fix this.

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Arch Linux
 - Desktop environment: GNOME 40
 - Installation method: pacman

**Comment by johnfactotum** [comment]
The current situation is a compromise. It's a bit too aggressive for well formatted books yet not enough for some really poorly formatted ones.

I think it would make sense to stop overriding those styles. That would be a much better default. And then maybe add an option to revert to the current behavior, or perhaps an option to remove all publisher styling (#267).

**Comment by phouchg42** [comment]
👍
