### ISSUE TITLE
Snap foliate + ubuntu 21.04 , The search box can not type words

### ISSUE THREAD

**Issue by ghost** [johnfactotum/foliate#710]
OS: Ubuntu 21.04 x64
I installed foliate via snap
```
sudo snap install foliate
```

The search box can not type words, I am using IME fcitx5-rime

and then i tested foliate via apt installed via sudo add-apt-repository ppa:apandada1/foliate

after installed from ppa, it works like a boss.

![Screenshot from 2021-04-08 08-37-35_edited](https://user-images.githubusercontent.com/278153/113951281-db0a9000-9845-11eb-84d0-0d5291658420.png)

Any problem about snap package ?

**Comment by johnfactotum** [comment]
Does this happen with other Snap apps, or just Foliate?

**Comment by cnmade** [comment]
Hello, I tried other apps, such as Jetbrains goland, But do not find problem.

Foliate itself has the problem.
Currently I should have to remove the snap version Foliate, Using apt install foliate instead.

**Comment by johnfactotum** [comment]
This is probably an issue with GTK and/or fcitx and/or Snap. But feel free to open a new issue if it persists in the GTK 4 version.
