### ISSUE TITLE
Adding EPUB problem: new books replace the last one

### ISSUE THREAD

**Issue by anightshade** [johnfactotum/foliate#714]
When adding epub files to the library, only one entry gets added, the subsequent epubs just keep replacing it. Debug log shows the same UUID for all the (different) files:
`Gjs-Message: 13:58:41.438: JS LOG: book list: updating urn:uuid:273fd756-62f2-4858-8d67-99e08f24bba9`

**Comment by johnfactotum** [comment]
If two books have the same identifier, Folaite treats them as the same book.

Duplicate of #406 and #435.

**Comment by anightshade** [comment]
Well, it's a show-stopper. There are simply too many such books on the web. Much easier to use other software than to patch them manually.
