### ISSUE TITLE
GTK 4 Port.

### ISSUE THREAD

**Issue by Tomoghno** [johnfactotum/foliate#716]
**GTK 4 Port**
A Modern GTK 4 Port with Rounded Borders Would Look Slick of Foliate.

**Comment by itprojects** [comment]
Yes, it would.
Foliate is slowly being adapted for GTK 4.
Read https://github.com/johnfactotum/foliate/issues/612 for more.

**Comment by johnfactotum** [comment]
It's not really possible to to port to GTK 4 until WebKitGTK is ported.

**Comment by itprojects** [comment]
Apologies for the misunderstanding, @johnfactotum , @Tomoghno .

**Comment by Tomoghno** [comment]
> It's not really possible to to port to GTK 4 until WebKitGTK is ported.

Thanks for Letting us Know.

**Comment by apandada1** [comment]
As of now, Foliate is awesome, and it does its job perfectly. GTK4/libadwaita does not have support for traditional menus, and does not match with the system theme outside GNOME. Most third party themes don't support GTK4 yet. Also, GTK3 is not going away anytime soon (apps like GIMP/Inkscape/Libreoffice would not work without traditional menus, and GTK4 does not support that).

Please reconsider whether the port to GTK4 is really needed.

**Comment by lumingzh** [comment]
@apandada1 Why do you think GTK4 don't support tradition menu? And no, GTK4 support theme as well. 

What GNOME done is move the default theme adwaita into libhandy and improved it to be libadwaita, which is the UI style for gnome apps. And this move turn GTK4 into a pure UI toolkit just like Qt, free GTK application developers from the GNOME HIG.

So, this is all your choice now. You can choose to use libadwaita to make your app unify with gnome platform, or you can do whatever you want with GTK just like evolution/gimp/inkscape/libreoffice and so on. The libadwaita thing is not a dependency require for non gnome core apps.

**Comment by rebokdev** [comment]
But it's possible to use webkit dev versions or make menus etc without book reader and then when webkitgtk4.0
will be released add book reader

**Comment by johnfactotum** [comment]
It's already mentioned elsewhere but I guess I should also say here that there is now a (highly incomplete but working) gtk4 branch: https://github.com/johnfactotum/foliate/tree/gtk4
