### ISSUE TITLE
What is the last know working version

### ISSUE THREAD

**Issue by eksperimental** [johnfactotum/foliate#720]
**Question:**
I would like to know what is the last known working version.
There is a bug #636 that prevents book from being loaded. 
 I haven't been able to use Foliate for months
Thank you.

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Arch Linux
 - Desktop environment: [e.g. GNOME 3.36]
 - Installation method: https://archlinux.org/packages/community/x86_64/foliate/

**Comment by itprojects** [comment]
@eksperimental Possibly `2.6.2` , if you **do not have** Gnome 40, yet. If you already have Gnome 40, then there still may not be a good enough version, because Gnome 40 affects many apps, including Foliate.

**Comment by apandada1** [comment]
Version 2.6.3 from the official repo works for me in Manjaro XFCE. Manjaro already have GNOME 40 apps, which work too.

Does disabling sandboxing work for you?

https://github.com/johnfactotum/foliate/issues/636#issuecomment-824780197

**Comment by eksperimental** [comment]
@itprojects thank you, It is working after uninstalling it and reinstalling it

**Comment by apandada1** [comment]
@eksperimental Please close the issue as it is solved.
