### ISSUE TITLE
Fonts are not deobfuscated

### ISSUE THREAD

**Issue by zchap26** [johnfactotum/foliate#721]
Hello,

I have got three ebooks that are not displayed properly when using either calibre on Windows or foliate on Linux.
Using the [EPUB.js Input Example page](https://futurepress.github.io/epub.js/examples/input.html) generates the same issue.

When opened in Adobe Digital Editions, the ebooks are readable. I do not want to use Adobe Digital Editions.

I am reporting the problem here because since submitting the issue on 01.03.2021, [there has only been scant activity ](https://github.com/futurepress/epub.js/issues/1179#issue-818894382) on futurepress/epub.js. Seeing that there are bug reports for epub.js on johnfactotum/foliate and that there is  johnfactotum/epub.js, I am hoping that maybe this is the right place.

The ebooks in question are:

1) [The Anesthetic Crisis Manual](https://leeuwinpress.com.au/collections/frontpage/products/the-acm-v2)
2) [The Resuscitation Crisis Manual](https://leeuwinpress.com.au/collections/frontpage/products/the-resuscitation-crisis-manual)
3) [The Perfusion Crisis Manual](https://leeuwinpress.com.au/products/the-pcm)

The issue occurs every time one of the ebooks is displayed and affects all pages.

Can this be fixed?

Regards,

zchap26

![Screenshot from 2021-03-01 15-02-29](https://user-images.githubusercontent.com/38397493/109507719-4f138480-7a9f-11eb-8c83-c60e8713e6d4.png)

![Screenshot from 2021-03-01 15-03-04](https://user-images.githubusercontent.com/38397493/109507741-55096580-7a9f-11eb-9e82-6805b7ceb33a.png)

![Screenshot from 2021-04-30 09-45-46](https://user-images.githubusercontent.com/38397493/116664565-f37b4f80-a998-11eb-931b-283c7c357914.png)

**Comment by itprojects** [comment]
There are many reasons for which a book can be unreadable.

**What is your Foliate version?** What is your install method?: meson, flatpak, snap, which other?

Does this happen with (free/libre) Gutenberg Books?

All of these books seem proprietary. Perhaps there is a problem with the DRM fonts? (if any)

Have you tried changing the default font? On the right in Foliate > Menu > Font button 

Maybe it's the spacing. You can change that in Foliate, too.

Consider unticking "Use Publisher Font" in Foliate.

One final option is if you are willing to edit the epub with calibre. Then you would remove the fonts entirely from the epub. This way any reader that is viewing the locally edited files will use the system font, which presumably solves the problem.

**Comment by johnfactotum** [comment]
Can't say for sure without seeing the file, but those look like a fixed layout books with hardcoded spacing designed to work with a specific font, and it looks broken when the font is not loaded. 

Now, as to _why_ the font failed to load, I haven't any idea. Might be that the format isn't supported by WebKitGTK, or maybe Epub.js isn't resolving the path properly, or some other issue.

**Comment by zchap26** [comment]
Foliate 2.6.3
flatpak
[Don Quixote](https://www.gutenberg.org/ebooks/996) seems to display without any issues
changing the default font does not resolve the issue
changing the spacing does not resolve the issue
Use Publisher Font was not ticked, changing this option does not seem to have any effect

**Comment by itprojects** [comment]
If other ePub's like Don Quixote display acceptably (enough), then Foliate is working.

Note:  If The books display (too) perfectly in Adobe products that can be an issue. Epubs are essentially html pages; some html pages optimised for Mac/Win browsers, can show defects when displayed in Linux browsers. Maybe the ePub's are perfect, but for the wrong OS or browser (webkit).

> Can this be fixed?

No.

**Comment by kushraj** [comment]
same issue here , ebub is good in other readers ( moon reader on android and calibre on linux ) ,

sample sshot  ( left foliate, right calibre )
![2021-06-27_14-02-22](https://user-images.githubusercontent.com/36916613/123538034-5185a280-d750-11eb-90e5-d43798152222.png)

font is roboto in both readers, changing font also doesn't help. broken rendering is constant with all fonts .

**Comment by johnfactotum** [comment]
I think I know why the fonts aren't loaded. It's probably because the fonts are [obfuscated](https://w3c.github.io/epub-specs/epub33/core/#sec-font-obfuscation). If you unzip the EPUB file, you should see a file called `encryption.xml` in the `META-INF/` directory. Obfuscated fonts need to be decrypted, which Epub.js doesn't do. So the fonts don't work.

**Comment by itprojects** [comment]
If it's true, then if you delete the encryption.xml file, delete the font files, zip the extracted files into a new zip with the same structure, and rename to file.epub, then this problem should disappear.

**Comment by johnfactotum** [comment]
@itprojects If it's true, doing those things will _not_ make the problem disappear.

First of all, currently obfuscated fonts are already ignored. So deleting them will do nothing.

But more importantly, in fixed layout books, the position of all the text is fixed, so the correct font is _required_. If you've ever opened a PDF that forgets to embed a specific font, you'd see the same kind of broken rendering.

**Comment by itprojects** [comment]
@johnfactotum You're probably right. No harm in trying, maybe we learn something for debug :)

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.
