### ISSUE TITLE
Persist TTS location when pausing

### ISSUE THREAD

**Issue by dspacejs** [johnfactotum/foliate#727]
**Is your feature request related to a problem? Please describe.**
I want to be able to save the TTS location, like an audiobook. So if I'm on a page and pause it, when I restart it'll be on the same word as when I paused it.

**Describe the solution you'd like**
Cache the TTS location, and reload it when resuming.

**Describe alternatives you've considered**
There are none.

**Comment by johnfactotum** [comment]
The current workaround for this is to select the word manually and choose "Speak from Here".

I think it's really the same issue as #726, so let's track it there.

**Comment by dspacejs** [comment]
@johnfactotum users shouldn't have to manually select the word and do that. It should happen automatically, like an audiobook.

**Comment by johnfactotum** [comment]
Sure. I don't disagree. TTS support is very basic at the moment, as stated in README.md.
