### ISSUE TITLE
Highlight not saved

### ISSUE THREAD

**Issue by LoafingBunny** [johnfactotum/foliate#74]
Hi, main issue I found is that notes and highlights are not saved.

```bash
(com.github.johnfactotum.Foliate:3277): GLib-CRITICAL **: 18:47:43.043: g_source_set_ready_time: assertion 'source->priv != NULL' failed
```

I have tested this with the latest tag and with the master branch. 
System is ubuntu 18.04 with 
gnome 3.28
gjs 1.52.5
meson 0.45.1
ninja 1.8.2

please, I've seen that in master you raised the requirements of meson: I manually changed them back and build works fine. Can you still use at most the ubuntu lts version? Otherwise meson won't build - I don't know whats happens with gnome "runtime-version" : doesn't seem to affect the behaviour.

**Comment by itprojects** [comment]
Maybe there should be an explicit 'Save' note button, as a new feature, to avoid temporary or accidental highlighting.

**Comment by johnfactotum** [comment]
I've seen this GLib warning, but I don't see how it's related to notes not being saved. I think your GJS version might be too old. But then you shouldn't be able to run Foliate at all (see #27) so I'm not sure what's going on. Can you provide more information?

Meson _seemed_ to work fine for some people with lower versions, however since it produced a warning, the minimum version was bumped. See #64. Since I've not have the time yet to properly test and support older platforms, in general I would recommend using the Flatpak version for now if you can't meet the newer dependencies.

**Comment by johnfactotum** [comment]
Ah, sorry, didn't realize you're the same person who tried transpiling with Babel. Is this the whole output? Are there no other messages? Are you seeing something like #77, or something different?

**Comment by LoafingBunny** [comment]
Hi, I rebuild using the version 1.3.0 and the same happens.

Here the log since I start foliate:
```
GSETTINGS_SCHEMA_DIR=$PWD/fakeprefix/share/glib-2.0/schemas ./fakeprefix/bin/com.github.johnfactotum.Foliate
Gjs-Message: 17:27:18.082: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 2079]: reference to undefined property "isFullscreen"

(com.github.johnfactotum.Foliate:14456): Pango-CRITICAL **: 17:27:18.425: pango_layout_set_width: assertion 'layout != NULL' failed

(com.github.johnfactotum.Foliate:14456): Pango-CRITICAL **: 17:27:18.425: pango_layout_set_alignment: assertion 'layout != NULL' failed

(com.github.johnfactotum.Foliate:14456): Pango-CRITICAL **: 17:27:18.425: pango_layout_set_text: assertion 'layout != NULL' failed
Gjs-Message: 17:27:18.514: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 1806]: reference to undefined property "atEnd"
file:///home/xxxxx/github/foliate/fakeprefix/share/com.github.johnfactotum.Foliate/assets/epub.js:17386:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///home/xxxxx/github/foliate/fakeprefix/share/com.github.johnfactotum.Foliate/assets/epub.js:17386:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///home/xxxxx/github/foliate/fakeprefix/share/com.github.johnfactotum.Foliate/assets/epub.js:17386:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]

(com.github.johnfactotum.Foliate:14456): GLib-CRITICAL **: 17:28:29.152: g_source_set_ready_time: assertion 'source->priv != NULL' failed
```
The last one arise when I quit the program. I can annotate, choose colours and so on, but when I open it again annotations are lost.

**Comment by LoafingBunny** [comment]
btw I'm using meson 0.50 to build, with ninja 1.8.2
After upgrading to ninja 1.9.0 the error when closing is disappeared, although highlights are still not saved.

**Comment by johnfactotum** [comment]
Are bookmarks and reading progress saved? Are you seeing files in `~/.local/share/com.github.johnfactotum.Foliate`, and if so, what are their contents?

**Comment by LoafingBunny** [comment]
It just contains a json with only one line:
` {"lastLocation":"epubcfi(/6/4[id12]!/4/62/4/1:0)"}`
although every time I open the book, It always show me the first page

**Comment by johnfactotum** [comment]
Didn't try Ubuntu 18.04, but I've managed to reproduce this on elementary OS (which is based on Ubuntu 18.04).

I have removed the use of spread syntax and lowered the Meson version requirement in f0f8e67074f20cd0b6dd4090c63c2d8f2b023180; it should now build and run on Ubuntu 18.04 without transpiling.
