### ISSUE TITLE
[Request] Option for Zero Line Spacing

### ISSUE THREAD

**Issue by Webtooner000** [johnfactotum/foliate#743]
Hello,

I would like an option to remove line spacing. I am using foliate for epubs and cbz (comic book archive format). In certain cbz files, the comic is in a continuous vertical layout or webtoon format. The line spacing breaks the viewing experience by adding a page break between the images.

**Comment by johnfactotum** [comment]
You're talking about viewing comic books in continuous mode, right? I think we should probably just remove the spacing.
