### ISSUE TITLE
Book content not displayed/formatted properly ('Hawkwood's Voyage')

### ISSUE THREAD

**Issue by hipnoizz** [johnfactotum/foliate#744]
**Describe the bug**
I've bough 'Hawkwood's Voyage' on Amazon (AZW). The book is not equipped with any DRM, so it is easy to open it in any e-book viewer. I noticed two problems:
- Foliate takes quite a lot of time to open a book - abouts 12 seconds vs 3 seconds from Calibre Viewer (Calibre Viewer in general loads ebooks faster but here the difference is much more pronounced),
- the book context is not displayed/formatted properly - some characters are not shown, text which should be centered isn't etc - please see attached screenshots

**To Reproduce**
1. Open aforementioned e-book. Incorrectly formatted content will be visible from the get go.

**Expected behavior**
The content should be formatted correctly.

**Screenshots**
![foliate](https://user-images.githubusercontent.com/1545320/122277412-2a280d80-cee6-11eb-9580-0413dc67bd25.png)

![calibre_viewer](https://user-images.githubusercontent.com/1545320/122277446-31e7b200-cee6-11eb-942b-e9b7ac08be33.png)

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Ubuntu 20.04.2 LTS
 - Desktop environment: 3.36.8
 - Installation method: Flatpak (dl.flathub.org)

**Comment by johnfactotum** [comment]
Foliate uses [KindleUnpack](https://github.com/kevinhendricks/KindleUnpack) to convert Kindle files to EPUB files, and then uses Epub.js to display the EPUB file. So in order to to figure out where things went wrong, one needs to
1. Convert the file with KindleUnpack, and inspect the result (e.g. with Calibre). This will show whether it's a bug in KindleUnpack. If not,
2. Open the KindleUnpack converted file with Epub.js (see https://github.com/johnfactotum/foliate/wiki#my-book-is-not-displayed-properly). This will show whether it's a bug in Epub.js.

**Comment by hipnoizz** [comment]
Thank you for your answer.

I've run KindleUnpack on the e-book file, got some unpacked structure but then I'm not sure how to inspect the result in Calibre. I've tried to load the folder in Calibre editor, but it fails with 'calibre.ebooks.oeb.polish.container.InvalidEpub: No META-INF/container.xml in epub'. The folder that the e-book was extracted to contains OPF and NCX files so it seems to be EPUB-like to some degree at least. The original e-book is I think in the old AZW/MOBI format, so maybe it is somehow borked. Unfortunately I have little knowledge about e-books formats.

For what is worth when I convert this AZW to EPUB using Calibre the output EPUB seems to be displayed correctly by Foliate.

**Comment by johnfactotum** [comment]
>  I've tried to load the folder in Calibre editor, but it fails with 'calibre.ebooks.oeb.polish.container.InvalidEpub: No META-INF/container.xml in epub'.

Ah, ok. I wrongly assumed that Calibre would be able to open unpacked EPUB directories. In that case you can try [zipping the folder into an EPUB file](https://ebooks.stackexchange.com/questions/257/how-to-repack-an-epub-file-from-command-line).

> For what is worth when I convert this AZW to EPUB using Calibre the output EPUB seems to be displayed correctly by Foliate.

Hmm, so it seems the issue might be related KindleUnpack, after all. Perhaps unzipping the Calibre-converted EPUB and comparing it to the KindleUnpack output would reveal the problem.

**Comment by hipnoizz** [comment]
Is there a specific way Foliate run KindleUnpack? I used `python kindleunpack.py ~/Downloads/Hawkwood\'s\ Voyage\ \[Kearney\].azw /tmp/testbook/`.

I'm asking because I played a bit with KindleUnpack-ed file and compared it with an EPUB that Calibre created from AZW. Now, in general these two EPUBs are much too different. The first contains a single, big HTML file with all styling/formatting applied directly on HTML tags. The EPUB created by Calibre contains multiple HTML files and a CSS stylesheet. Anyway I added the missing `META-INF/container.xml` to the structure created by KindleUnpack, zipped the folder and tried to open it in Foliate. It sort of started opening it but it never loaded the content - I saw the book title being set on the Foliate window but the spinner was spinning and spinning. I loaded the structure into Calibre editor and after fixing various problems I managed to produce an EPUB file that Foliate was able to open. Not all errors were fixed, for example some paragraphs wasn't centered - I'm not sure if using `align="center"` is not supported by Epub.js, or maybe some other problems persisted. Anyway it seems that the way Foliate uses KindleUnpack produces an EPUB file that can be opened (with various errors are presented by the screenshots above, but still). Hence my question.

**Comment by johnfactotum** [comment]
> Is there a specific way Foliate runs KindleUnpack?

Ah, yes, it runs it with `--epub_version=3`, which forces it to output EPUB 3 (the default value is 2).

https://github.com/johnfactotum/foliate/blob/1f11b9bb918beea5da7268f72acb2cf1114ef27b/src/epubView.js#L1137

> The first contains a single, big HTML file with all styling/formatting applied directly on HTML tags. [...] It sort of started opening it but it never loaded the content - I saw the book title being set on the Foliate window but the spinner was spinning and spinning.

Foliate struggles when there's only one very long HTML page because pagination is achieved with CSS multi-columns in Epub.js, and CSS multicol performance is very poor especially in WebKit (which Foliate uses).

> Not all formatting issues were fixed, for example some paragraphs wasn't centered - I'm not sure if using `align="center"` is not supported by Epub.js, or maybe some other problems persisted

It's supported, but it has a specificity of zero, and so it's overridden by any CSS. And Foliate does set `text-align: justify;` on `<p>`s (or `'inherit` if "Full Justification" is disabled).

https://github.com/johnfactotum/foliate/blob/1f11b9bb918beea5da7268f72acb2cf1114ef27b/src/web/epub-viewer.js#L322-L324

So I guess that's probably why the aligment is broken in Foliate.

I wonder, though, what's causing what I presume is some sort of problem with encoding in your original screenshot, causing quotation marks to be rendered as question marks.

**Comment by hipnoizz** [comment]
I've added `--epub_version=3` to the way I run KindleUnpack but still the output structure cannot be opened by Foliate after compressing it to ZIP. I cloned KindleUnpack from its master branch.

The original HTML file contains `charset=windows-1252"`. But it seems that quotation marks are encoded correctly, at least Firefox show them correctly (but browsers can be pretty lenient in how they interpret HTML...) and also gedit seems to display them after setting encoding to windows-1252. So I'm not sure what is the problem with the encoding here.

I play a bit with the original HTML curious what makes Foliate fail to open the ebook. I cut the original content to following HTML:
```
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=windows-1252"/>
</head>
<body>
<a id="filepos418"/>
</body>
</html>
```
This won't open in Foliate (the spinner is spinning and spinning).

After changing `<a/>` to <a></a>` the file will open in Foliate.
```
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=windows-1252"/>
</head>
<body>
<a id="filepos418"></a>
</body>
</html>
```

**Comment by johnfactotum** [comment]
Can you test the book with the [new renderer](https://github.com/johnfactotum/foliate/issues/962)? You can try the new renderer with the [online reader](https://johnfactotum.github.io/foliate-js/reader.html) or the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.

**Comment by hipnoizz** [comment]
Hi. I tested the original AZW file with the online reader. See the screenshot below, but it looks OK now. Also the file was opened in practice instantaneously. I've scrolled through the book here and there, everything seems fine. So I would say great work with the new renderer!

Out of curiosity - https://github.com/johnfactotum/foliate-js says 'There's no support for continuous scrolling, however.' - is that still correct? The online reader can be switched into the 'Scrolled' mode.

![image](https://user-images.githubusercontent.com/1545320/197875450-7c3f796f-4610-4bd3-92a6-e1d421c106a4.png)

**Comment by johnfactotum** [comment]
Thanks for testing! I'll close this issue, then.

> The online reader can be switched into the 'Scrolled' mode.

Technically, that is what is referred to in the EPUB spec as `scrolled-doc`, which it does support. It does not, however, support the mode known as `scrolled-continuous`. Both are scrollable, but only the latter is continuous across the whole book (across documents/chapters).

**Comment by johnfactotum** [comment]
The text alignment issue is fixed with https://github.com/johnfactotum/foliate-js/commit/750458d4b7a541c19ff6a8dfd2397abd6ad8b94d and https://github.com/johnfactotum/foliate/commit/045b8be6f781a6ef42a8bba5490dd37e5fe68d9c
