### ISSUE TITLE
Tooltip flashes when hovering an item in the list of content menu

### ISSUE THREAD

**Issue by akamfoad** [johnfactotum/foliate#746]
**Describe the bug**
When hovering over an item in the table of content the tooltip flashes until you move off the item as shown in the video below.

**To Reproduce**
1. Open **list of content** popup
2. Hover on an item
4. Observe the how it flashes

**Expected behavior**
Show little popup when hovered over the item, then hide it after some time or when mouse hover ended.

**Screenshots**
https://user-images.githubusercontent.com/41629832/123524523-9a4b4600-d6d3-11eb-96b1-ac8454420bed.mp4

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Ubuntu 20.04
 - Desktop environment: GNOME 3.36
 - Installation method: Snap

**Additional context**
I thought it could be related to _auto hide header bar_ enabled option, so I turned it off, but the problem persisted as described before.

**Comment by johnfactotum** [comment]
I believe this was a GTK bug (might be related to https://gitlab.gnome.org/GNOME/gtk/-/issues/1371) that seems to have been fixed, or at least I seem to vaguely remember seeing this issue some time ago but can't reproduce anymore. In any case the tooltip is drawn by GTK and there's nothing to be done on our side.

**Comment by modexristo** [comment]
Fwiw, I was facing the same issue as @akamfoad until I discovered some leftover nvidia packages in my system, from when I switched to a radeon gpu. Once I removed those packages, the issue went away! 

I should mention that I'm on Ubuntu 20.04, kernel 5.11.0-27-generic on wayland with open source radeon drivers.

Hopefully, it'll be helpful to others.
