### ISSUE TITLE
Section marks and system themes

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#75]
Some themes cause problems with the chapter section marks. See the screenshot. The one below is adwaita, it completely covers the section marks.

![Untitled](https://user-images.githubusercontent.com/2698054/59565651-921c9280-9045-11e9-8824-e065cf406d66.png)

**Comment by johnfactotum** [comment]
You should open an issue with Adwaita: https://gitlab.gnome.org/GNOME/gtk/issues
