### ISSUE TITLE
Bad contrast in some elements in Dark mode

### ISSUE THREAD

**Issue by TheEvilSkeleton** [johnfactotum/foliate#757]
**Describe the bug**

Some elements have bad contrast in Dark mode.

**To Reproduce**
1. Change theme to "Dark" if you haven't.
1. Go to https://www.open.edu/openlearn/health-sports-psychology/understanding-adhd/content-section-0?active-tab=description-tab.
2. Click on "Epub 2" to download the Epub, or go to this direct link https://www.open.edu/openlearn/health-sports-psychology/understanding-adhd/altformat-epub.
3. Scroll down to page 41.
4. See bad contrast

**Expected behavior**
Should be good contrast

**Screenshots**

![Screenshot from 2021-07-06 18-26-02](https://user-images.githubusercontent.com/50847364/124674107-1be76480-de88-11eb-9dcf-796dd7a0137f.png)

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Fedora Silverblue 34
 - Desktop environment: GNOME 40
 - Installation method: Flatpak

**Additional context**

Here is a comparison of the same page in Inverted theme:

![Screenshot from 2021-07-06 18-26-10](https://user-images.githubusercontent.com/50847364/124674225-53eea780-de88-11eb-925f-bb6c8a79e9e0.png)

**Comment by johnfactotum** [comment]
The book needs to either hardcode both foreground and background, or change the background color depending on the `__ibooks_internal_theme` attribute or the `prefers-color-scheme` media query. It's not possible for Folaite to override the colors without breaking other legitimate cases. The "Invert" option is provided precisely as a workaround to this problem.

See the [wiki](https://github.com/johnfactotum/foliate/wiki#custom-style-isnt-applied-consistently), https://github.com/johnfactotum/foliate/issues/265, https://github.com/johnfactotum/foliate/issues/457, etc.
