### ISSUE TITLE
CPU spikes when left open

### ISSUE THREAD

**Issue by vsim3** [johnfactotum/foliate#76]
Hi! Thanks for foliate.

**Steps to reproduce the issue:**
Open a ebook, scroll some page then left it open for ~1h
![Screenshot_20190617_120546](https://user-images.githubusercontent.com/50333987/59579934-ac468700-90be-11e9-97bc-520fc18a2de2.png)

Version: 1.2 and git master
OS: Fedora 30

**Comment by itprojects** [comment]
Confirmed on Ubuntu 19.04, with spike of 25% CPU usage and large 80MB RAM usage for small 400kb file.

**Comment by johnfactotum** [comment]
Not sure what's causing this.

Using Web Inspector's Timeline tool, the only thing that's going on seems to be Epub.js polling for resize every 350ms.

If anyone wants to help test this, you can try deleting or commenting out line 4636 in `src/assets/epub.js`, and see if this still happens.

**Comment by itprojects** [comment]
Commenting out line 4636 most certainly helped. No known side effects, so far.

**Comment by itprojects** [comment]
Long testing over hours, with regular page flips confirms commenting out line 4636 in epub.js is a fix.

**Comment by vsim3** [comment]
Yes, delete line 4636 indeed fix the spikes. One of the things I've noticed is that dictionary lookup sometimes not working, can workaround by maximize foliate (not sure it was there before deleting line 4636).
