### ISSUE TITLE
Failed to add a specific book - No Manifest Found

### ISSUE THREAD

**Issue by jeffshee** [johnfactotum/foliate#763]
**Describe the bug**
There is one specific book (in mobi file format) that failed to be added to my library. The book doesn't seem to be corrupted, as I could open it with Kindle on my iPad, also with calibre on the PC. It outputs a warning as follows:
```
(com.github.johnfactotum.Foliate:2): Gjs-WARNING **: 09:09:11.927: JS ERROR: Error: No Manifest Found
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57
_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:886:22
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:476:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/app/bin/com.github.johnfactotum.Foliate:9:17
```
I can share the book if needed, **only for debugging purposes**. It was "bash Cookbook" purchased from here: https://www.humblebundle.com/books/definitive-programming-cookbooks-oreilly-books

**To Reproduce**
1. Try to add the mentioned book to the library, it fails.

**Expected behavior**
If there isn't an issue with the book, adding to the library should work fine.

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Fedora 34
 - Desktop environment: GNOME 40.2
 - Installation method: Flatpak

**Comment by itprojects** [comment]
Could it be that this book is DRM protected. If that is true then Foliate might **not** be able to open it.

What's the exact ISBN? (Maybe Kindle-app has this information)

Can you convert it to ePub?

Can you open it with _any_ **other** free linux ebook reader?

**Comment by jeffshee** [comment]
@itprojects Hi, thanks for the reply.
> What's the exact ISBN? (Maybe Kindle-app has this information)

9781491975336
> Can you convert it to ePub?

I have the epub version as well. The epub version works fine.
> Can you open it with _any_ **other** free linux ebook reader?

Yes, calibre works fine, but not foliate.

**Comment by itprojects** [comment]
Opens well in Calibre as `.mobi`, so _not_ DRM. Tested on Ubuntu (21.04) VM with flatpak.

**Comment by johnfactotum** [comment]
Can you test the book with the [new renderer](https://github.com/johnfactotum/foliate/issues/962)? You can try the new renderer with the [online reader](https://johnfactotum.github.io/foliate-js/reader.html) or the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.
