### ISSUE TITLE
Why mobi format is slow?

### ISSUE THREAD

**Issue by tonypachino** [johnfactotum/foliate#764]
**Question:**
Why mobi files opens up slower than the same book in epub format?

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: [Fedora 34]
 - Desktop environment: [Kde Plasma]
 - Installation method: [sudo dnf install foliate]

**Comment by johnfactotum** [comment]
See https://github.com/johnfactotum/foliate/issues/128#issuecomment-513423029

> The output of KindleUnpack for those books contains only a single html page containing all its contents. And a long html page in general takes Epub.js a long time to process.

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.
