### ISSUE TITLE
Cannot run foliate at all

### ISSUE THREAD

**Issue by flandriai** [johnfactotum/foliate#766]
**What have I done?**

I installed Foliate using Flatpak. The application installed just fine.

**Expected behaviour**

I click on Foliate's icon, but nothing happens. I expected the program will start, but it does not.

**Version:**
 - Foliate version: latest 
 - OS/Distribution and version: Rosa Fresh 11.1
 - Desktop environment: XFCE
 - Installation method: via Flatpak

**Additional context**

If I try to run Foliate by clicking on its icon absolutely nothing happens (no error message, nothing), when I try to run it from Terminal I get the following:

Unknown socket type fallback-x11, valid types are: x11, wayland, pulseaudio, session-bus, system-bus

**Comment by apandada1** [comment]
Does either of the following work?
```
flatpak run --socket=x11 com.github.johnfactotum.Foliate
```

```
flatpak run --socket=wayland com.github.johnfactotum.Foliate
```

Also, can you compile from source?

**Comment by flandriai** [comment]
Thank you, @apandada1 for the suggestions, but unfortunately they did not work.
In both cases I got the same error message:
"Unknown socket type fallback-x11, valid types are: x11, wayland, pulseaudio, session-bus, system-bus"

Unfortunately I am not experienced enough to know how to compile Foliate from source, that is why I decided to stick with Flatpak, which has been an easy way to add applications that are not available in the distro's repositories. Foliate was the first that failed to start after the installation

**Comment by apandada1** [comment]
You can find the instructions for compiling here. https://github.com/johnfactotum/foliate#building-manually-from-source

It may be a flatpak specific issue.

**Comment by flandriai** [comment]
I tried to compile Foliate from source, following the steps on the link above.
When entering: _ninja -C build_ I got the following error message:
ninja: Entering directory `build'

[1/1] Generating com.github.johnfactot....xml_data_merge with a custom command.
FAILED: data/com.github.johnfactotum.Foliate.metainfo.xml 
/usr/bin/meson --internal msgfmthelper ../data/com.github.johnfactotum.Foliate.metainfo.xml.in data/com.github.johnfactotum.Foliate.metainfo.xml xml ../data/../po
msgfmt: cannot locate ITS rules for ../data/com.github.johnfactotum.Foliate.metainfo.xml.in
ninja: build stopped: subcommand failed.

What have I done wrong?

**Comment by apandada1** [comment]
See [this](https://askubuntu.com/q/1273027/124466). You need to install `appstream` (or its equivalent package for your OS).

**Comment by flandriai** [comment]
> See [this](https://askubuntu.com/q/1273027/124466). You need to install `appstream` (or its equivalent package for your OS).

Thank you for the suggestion @apandada1! **Appstream** is available on my system too. I installed it from my OS's Software Center (version 0.11.2 was the latest available version) and after that I (again) tried to run _ninja -C build_, but unfortunately I got the exact same error message as  I have mentioned above.

**Comment by apandada1** [comment]
Also check if it works after installing `gettext` and `pkg-config` (alternatively, `pkgconf`).

**Comment by flandriai** [comment]
Thank you for your suggestions @apandada1 !
I did the following:

- I have checked whether **gettext** is installed. It's indeed installed - version 0.19.8.1. 
- The components that were listed as runtime requirements were the first I checked: as of **gjs** I have version 1.69.1 while the minimum has to be version 1.52 so that's also seems to be OK. The other necessary component is webkit2gtk. It is installed too (version 2.4.9).
- You've mentioned **pkgconfig**. This was installed too, version 0.29.2.
- I also checked the mentioned Fedora packages; as far as I can tell all the suggested packages are already present on my system.

Unfortunately the issue still persist.  It would be great if an Appimage would be available from Foliate...

**Comment by apandada1** [comment]
You can also try the snap package.

**Comment by flandriai** [comment]
Unfortunately the snap package is out of question, because this distro does not support snap, only flatpak.
Anyway, thanks for all your help @apandada1, I greatly appreciate it!
As I mentioned an Appimage would be great, hopefully in the future this will be available too.
I leave the thread open - maybe later a solution will come up to this issue.

**Comment by flandriai** [comment]
> There is an open issue for appimage #44
> 
> There is one more possible method.
> 
> Make sure you have `gjs` installed.
> 
> Download the .deb package from https://github.com/johnfactotum/foliate/releases/download/2.6.3/com.github.johnfactotum.foliate_2.6.3_all.deb and extract it.
> 
> Then extract the `data.tar.xz`. It will create a directory named `usr`. Now copy all the files in this directory to your `/usr`, which can be achieved by executing `sudo cp -rf * /usr/` inside the new `usr` directory.
> Finally run `sudo glib-compile-schemas /usr/share/glib-2.0/schemas/`, and Foliate should be installed.

I tried this method too, Foliate is indeed installed at the end, but when I click on its icon nothing happens just like in the case of using flatpak. When I now tried to run Foliate from Terminal, nothing happened (not even an error message appeared).
Thank you again @apandada1 for putting so much effort in helping me find a solution to this problem!
Hopefully there will be one in the future! It's also great news that a thread is open for Appimage.

**Comment by apandada1** [comment]
Just to clarify, no error message appears when you run the command `com.github.johnfactotum.Foliate` ?
If it does not work, I don't have any other workarounds.

(you don't need to thank me repeatedly)

**Comment by flandriai** [comment]
That's right, no error message appears - the terminal simply returns to the command prompt like nothing had happened. But the application does not start (neither from the Terminal nor by clicking on its icon), sadly.

**Comment by johnfactotum** [comment]
What version of Flatpak do you have? I think the problem is that older versions of Flatpak don't support the `fallback-x11` option.

**Comment by flandriai** [comment]
> What version of Flatpak do you have? I think the problem is that older versions of Flatpak don't support the `fallback-x11` option.

My Flatpak version is: 0.9.7

**Comment by johnfactotum** [comment]
I'm not familiar with Rosa Linux, but shouldn't you be getting Flatpak 1.10 on Desktop Fresh R11?

I guess if you can't upgrade Flatpak, maybe you can try building removing the line https://github.com/johnfactotum/foliate/blob/a52ffae008fc844ff9ef72b166dd9058fabef1b2/com.github.johnfactotum.Foliate.json#L11
and install it manually with `flatpak-builder`:
```
flatpak-builder --force-clean --install --user build com.github.johnfactotum.Foliate.json
```

**Comment by flandriai** [comment]
I've updated my Fatpak. Foliate installed just fine, but again it did not start. I tried to build and install it without the above mentioned line and got the same result. Foliate always seems to be installing just fine but does not want to start. Strange thing that when I was trying to start it from the Terminal I did not get any error message, but it still does not start.  I hope that an Appimage will be available from it sooner or later and that will solve this issue and it will work on my system too.

**Comment by apandada1** [comment]
Rosa uses RPM according to Distrowatch. Can you try installing the [Fedora package](https://koji.fedoraproject.org/koji/buildinfo?buildID=1730883)? 

https://kojipkgs.fedoraproject.org//packages/foliate/2.6.3/1.fc33/noarch/foliate-2.6.3-1.fc33.noarch.rpm

**Comment by flandriai** [comment]
> Rosa uses RPM according to Distrowatch. Can you try installing the [Fedora package](https://koji.fedoraproject.org/koji/buildinfo?buildID=1730883)?
> 
> https://kojipkgs.fedoraproject.org//packages/foliate/2.6.3/1.fc33/noarch/foliate-2.6.3-1.fc33.noarch.rpm

I downloaded the package you have linked, unfortunately the issue is the same with that one too: it installs fine, and then does not start.

**Comment by flandriai** [comment]
I do not know what was the problem, but the last major system update solved the issue, and after the update Foliate finally started.
