### ISSUE TITLE
Highlight/annotation not working

### ISSUE THREAD

**Issue by aadilayub** [johnfactotum/foliate#77]
![foliatebug](https://user-images.githubusercontent.com/31581044/59599228-75e92600-9117-11e9-9173-19267d466408.gif)

It looks like my copy of Foliate has somehow lost highlight/annotate functionality. I tried selecting the text, right-clicking, and clicking on the annotations button, but none of them produce the desired result of highlighting the text.

**Comment by johnfactotum** [comment]
Does it happen with every book? Are there any error messages?

**Comment by aadilayub** [comment]
It has happened with every book I've tried so far. Don't know about the error messages since I can't get it to run from the command line. Could you tell me the right command? I've tried running `flatpak run com.github.johnfactotum.foliate.Desktop` `com.github.johnfactotum.foliate.Desktop`, 'com.github.johnfactotum.foliate`, `flatpak run com.github.johnfactotum.foliate`, `foliate` ...

**Comment by johnfactotum** [comment]
Should be `flatpak run com.github.johnfactotum.Foliate`

**Comment by johnfactotum** [comment]
Does this happen after upgrading to 1.2.0 or 1.2.1? If so this is probably the same problem as #58 and #59.

**Comment by aadilayub** [comment]
Yep, looks like it's the same issue. Changing views then restarting the app worked!
