### ISSUE TITLE
annotations is not persistent

### ISSUE THREAD

**Issue by Pinche-Dev** [johnfactotum/foliate#770]
while using services such as Dropbox or Onedrive the annotations made by me is not persistent it is not recorded at all 

I noticed that the file is not modified at all so my saying here is that persistent annotatoins are always good....

there is a wayaround however importing and exporting all the annotations manually which can be redundant and cumbersome so "persistent annotations are good "

**Comment by Pinche-Dev** [comment]
The file change is not registered by either dropbox or Onedrive
both of them are installed from AUR and is latest version foliate is the latest too

**Comment by apandada1** [comment]
Annotations are not stored in the .epub. They are stored in .json files in `~/.local/share/com.github.johnfactotum.Foliate`. You can sync this directory across computers.

**Comment by Pinche-Dev** [comment]
oh nice Thankyou

**Comment by Pinche-Dev** [comment]
are annotations stored in .mobi format??? Thankyou

**Comment by apandada1** [comment]
> are annotations stored in .mobi format??? Thankyou

I don't think so. They are all stored in .json files located in `~/.local/share/com.github.johnfactotum.Foliate`
