### ISSUE TITLE
Custom background texture

### ISSUE THREAD

**Issue by eXConf** [johnfactotum/foliate#777]
I'm using GNU/Linux for about a year now and one of the software pieces I really like here is Foliate. The only thing I miss though is an ability to set not just background color, but custom background image as well (a seamless texture of course). Because for about 20 years of reading on a PC I get used to having an old book paper texture behind the text.

So, please consider adding such option and thanks for making this program :)

P.S.> if there is any 'hacky' way of setting custom texture in the current version, I would be glad to hear it.

**Comment by johnfactotum** [comment]
> P.S.> if there is any 'hacky' way of setting custom texture in the current version, I would be glad to hear it.

Currently you must edit the source code to modify the default stylesheet:
https://github.com/johnfactotum/foliate/blob/a52ffae008fc844ff9ef72b166dd9058fabef1b2/src/web/epub-viewer.js#L299

I guess in the future we could add support for user-defined stylesheets. Alternatively/additionally, we might consider including a texture option out of the box. It'd be an interesting addition to the skeuomorphic mode.

**Comment by johnfactotum** [comment]
Probably makes more sense to allow setting arbitrary styles. See #947.
