### ISSUE TITLE
Secure & Private Sandboxed Reading

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#78]
When Foliate loads an epub that has an external image like so:

`<img src="http://path/to/image.jpg"  width="100" height="200"/>`

The application goes online and fetches the image. This action would, however, reveal to the epub maker where the reader is currently located, and what is being read.

Could you please add options to disable image fetching and javascript disable.

Some WebKit related items:

WebKitSettings:enable-java,
The “enable-java” property

WebKitSettings:enable-javascript,
The “enable-javascript” property

WebKitSettings:javascript-can-access-clipboard,
The “javascript-can-access-clipboard” property

WebKitSettings:javascript-can-open-windows-automatically,
The “javascript-can-open-windows-automatically” property

**Comment by johnfactotum** [comment]
It should be possible to block external resources. It should also be possible to block `<script>` tags. 

It's not possible, however, to disable JavaScript, because JavaScript is required to load, process, and render the book.

**Comment by itprojects** [comment]
Blocking the external resources was the primary idea.

Is it really not possible to just ignore the epub's internal java-script, and just tell epub.js "you only see html+css+local_images"?

**Comment by johnfactotum** [comment]
What I mean is that it's not possible to just disable JavaScript in WebKit using the settings you listed. There is no such functionality built into Epub.js. Maybe it can be done with hooks, maybe not.

**Comment by johnfactotum** [comment]
Worth noting that in the "about this book" window, the book description can also contain arbitrary HTML. Would need to deal with that as well.

**Comment by itprojects** [comment]
Well spotted, eagle-eye @johnfactotum !

**Comment by johnfactotum** [comment]
Do you have an EPUB file that we can test with?

**Comment by itprojects** [comment]
@johnfactotum  Here is a test file: [basic-v3plus2.epub.zip](https://github.com/johnfactotum/foliate/files/3372185/basic-v3plus2.epub.zip)

It was taken from the user [bmaupin](https://github.com/bmaupin/epub-samples), and is in the public domain. You can use the script in that repository to make modified versions. The version from the first link was modified to include two images (in cover.xhtml). When the first image (src-from-https) is clicked, the second loads from JavaScript.

The original testing epub was lost.

Making an epub from websites that convert web pages into epubs, usually, has too much javascript and embedded images. Those, too, are worth looking into.

**Comment by johnfactotum** [comment]
External resources as well as inline JavaScript should now be blocked after 4db5ec96b5fa63b44a8157014fd32bc1f6e5c098.

Would need more testing to see if this is missing anything or if it breaks anything. I will add the option to re-enable unsafe resources later.
