### ISSUE TITLE
Slowdowns with 5 000+ page book

### ISSUE THREAD

**Issue by 31j** [johnfactotum/foliate#787]
**Describe the bug**
It seems like large page count books are quite taxing on the application. Particularly when they're opened and when one tries to turn pages. The application freezes / stutters a lot and tends to take a while to perform your commands. 

**To Reproduce**
0. Size 12 serif font, 1.5 spacing, 40 margins and 1400 width
1. Import a large book. [Cassell's Latin Dictionary](https://archive.org/details/cassellslatindic00marc) suffices. The epub
2. Try and interact with the book 
3. After a while the issues seem to improve to the point that it's usable. However rapidly turning a lot of pages still causes issues

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Fedora 34
 - Desktop environment: Gnome 40.4
 - Installation method: Flatpak

**Additional context**
I can definitely see this being a niche issue / hard to fix.

**Comment by johnfactotum** [comment]
For some reason I can't even open the book. With the [`gtk`](https://github.com/johnfactotum/foliate/tree/gtk4) branch, however, the book now opens fine without any issues, and navigation seems quite snappy.
