### ISSUE TITLE
Online catalogs are not loaded

### ISSUE THREAD

**Issue by jdiegoaez** [johnfactotum/foliate#789]
In the snap version for Ubuntu the online catalogs are not loaded
OS: Ubuntu 21.04
Desktop: Gnome 3.38.5
Snap aplication: Foliate 2.6.3
![IMG_00](https://user-images.githubusercontent.com/91395030/134787659-eaaf9141-1762-4997-9067-f3524c240829.png)

**Comment by BHALUU** [comment]
I am having the same issue too. My Online catalog keeps loading.
OS: POP!_OS 21.04
DE: GNOME 3.38.5
Flatpak aplication: Foliate 2.6.3

![Foliate Online catalog not Loading](https://user-images.githubusercontent.com/54549044/145676251-68c1c04f-b28c-4d74-ae45-608bb1205b7a.png)

**Comment by BeoXS** [comment]
Same issue as well.
OS: Ubuntu 20.04.3 LTS
DE: Ubuntu 3.36.8
Snap: 2.6.3
Flathub: 2.6.4

Snap will not connect to the catalog.
Flathub will not launch at all.
![foliate_issue_flatub](https://user-images.githubusercontent.com/18199290/152538584-4317ad3d-fa0f-45d4-aeae-418d0989911d.png)
![foliate_issue_snap](https://user-images.githubusercontent.com/18199290/152538585-4967610f-cd66-4491-ac73-40302731ec9e.png)

**Comment by johnfactotum** [comment]
If neither books nor catalogs are loading, then WebKitGTK probably isn't working for some reason. See https://github.com/johnfactotum/foliate/issues/707#issuecomment-817575114

**Comment by johnfactotum** [comment]
It looks like there are a couple of different issues here. The original Snap issue is probably the same as #923. The Flatpak issue is probably either nvidia or mixed locales. Closing as duplicate/not actionable.

**Comment by soumyaDghosh** [comment]
These are all fixed now. :tada:
