### ISSUE TITLE
Multiple instance issue

### ISSUE THREAD

**Issue by ghost** [johnfactotum/foliate#790]
**Describe the bug**
When a sub-window is opened in one instance,  can't do anything in other instance(s)

**To Reproduce**
1. Open two or more books.
2. Open a sub-window like "About this Book"  or "About Foliate" in one of them, keep it open.
3. Try to interact with the other book(s).

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Debian Bullseye
 - Desktop environment: Gnome 3.38.5
 - Installation method: deb package

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.
