### ISSUE TITLE
Hotkeys interfere with annoation search

### ISSUE THREAD

**Issue by Squidamatron** [johnfactotum/foliate#794]
**Describe the bug**
While searching annotations it is impossible to type the lowercase letters P and N. Instead of inputting the character into the search box, it will act on the defined keyboard shortcut moving to the Previous or Next page instead.

**To Reproduce**
1. Open the sidebar via shortcut (Ctrl+A) or GUI button
2. Type the letter P or N (lowercase)

**Expected behavior**
Typing the letters, and not shifting the page backwards or forwards.

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Arch Linux
 - Desktop environment: None - using BSPWM
 - Installation method: Official Repo - pacman

**Additional context**
The capital version of P and N _can_ be typed in the annotation search box, however, funnily enough, a separate issue is that you _cannot_ search with any capital letters. You will get no results with capital letters involved and results with the same search in lowercase. I can open a separate issue for that if need be.

I cannot recreate the issue in a Fedora 34 (GNOME) virtual machine and a different book. There, the UI appears mildly different and attempts at loading the book crash.

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch. Though there's a quirk: searching only finds annotations that aren't folded.
