### ISSUE TITLE
Error on FreeBSD 13.0 since update

### ISSUE THREAD

**Issue by qryptocracy** [johnfactotum/foliate#797]
Opening Foliate gives error: Could not open file Empty Response

Opening Foliate from terminal gives me the error:

(com.github.johnfactotum.Foliate:3030): Gjs-WARNING **: 12:56:33.042: JS ERROR: Error: Empty Response
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57
_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:886:22
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:476:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/local/bin/foliate:9:17

**Comment by greghab** [comment]
NixOS Unstable updated WebKitGTK to `2.34.1`, and it works fine now.
