### ISSUE TITLE
Move to Tracker 3

### ISSUE THREAD

**Issue by DimStar77** [johnfactotum/foliate#798]
**Describe the bug**
GNOME has moved for quite a while to Tracker 3; Tracker 2 and 3 do not share the file indexes, thus having an app require Tracker 2 would result in it either having an outdated file index or two file indexers running on the system.

It would be beneficial if foliate would move to Tracker 3 - Allowing users/distros to eliminate Tracker 2 for good.

**Comment by apandada1** [comment]
https://github.com/johnfactotum/foliate/blob/master/debian/control#L27

@johnfactotum The suggested dependency of the debian package should probably be updated to `gir1.2-tracker-3.0`, as `gir1.2-tracker-2.0` has been dropped from Ubuntu 21.10 and Debian 12 (testing).

**Comment by johnfactotum** [comment]
Ah yes, I forgot about that.
