### ISSUE TITLE
Missing and garbled fonts in Flatpak

### ISSUE THREAD

**Issue by eightfiftytwo** [johnfactotum/foliate#801]
**Describe the bug**
In flatpak, many fonts are missing from the "Pick a Font" dialogue. Some of the fonts that show up are garbled and unusable. Native version of this package works fine. 

**To Reproduce**
1. Run the flatpak
2. Try to change the font in the hamburger menu
3. Scroll around and see garbled fonts

**Expected behavior**
All fonts installed on the system are present and functioning correctly.

**Screenshots**
![Screenshot from 2021-10-15 17-06-08](https://user-images.githubusercontent.com/73746603/137468922-64bbc2a5-8be8-4b15-8d3c-86156670a2ed.png)
![Screenshot from 2021-06-06 01-03-30](https://user-images.githubusercontent.com/73746603/137468928-9ba08fd7-9031-4ea2-ab24-3244f9357730.png)
![Screenshot from 2021-06-06 01-03-15](https://user-images.githubusercontent.com/73746603/137468932-bd28175e-e6f3-495d-82a5-980be67b3828.png)

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Fedora 33
 - Desktop environment: GNOME Wayland 3.38
 - Installation method: Flatpak

**Additional context**
The native package in fedora repo works completely fine. The fonts that show up correctly are mostly system fonts. The fonts that I installed in ~/.fonts are the ones encountering this problem. I've tried granting more permission with Flatseal but it didn't help.

**Comment by johnfactotum** [comment]
AFAIK, Flatpak automatically mounts the fonts inside the sandbox, so there shouldn't normally be any issues with permission. At any rate, it's almost certainly not our bug, as fonts are handled by Flatpak and GTK.

**Comment by eightfiftytwo** [comment]
I finally figured it out. Here's the solution for posterity.
[Flatpak looks for fonts in ~/.local/share/fonts or ~/.fonts in this order, whichever one is found first.](https://github.com/flatpak/flatpak/issues/924#issuecomment-356231899)
The issue can be fixed by moving user-installed fonts from ~/.fonts to ~/.local/share/fonts, or use Flatseal to grant permission for Foliate to access ~/.fonts. It's probably better to do the former, [since ~/.fonts is deprecated and the right directory for fonts in the XDG specification is ~/.local/share/fonts.](https://wiki.archlinux.org/title/XDG_Base_Directory#Supported)
The "garbled" fonts were in fact not garbled, but icon fonts that Doom Emacs automatically installed which I totally forgot.
Sorry for bothering you with this
