### ISSUE TITLE
Can't open image converted   pdf files .

### ISSUE THREAD

**Issue by NuthanB** [johnfactotum/foliate#803]
<h1> The application is unable to locate or open a pdf file type , which was made by images and made into a pdf using Microsoft lens or any other image to pdf maker tool </h1>

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the pdf location 
2. Right click on the pdf to be opened
3. click on other application , and then choose Foliate to run that 

**Expected behavior**
It works great with other pdfs but when given an image converted to pdf , the application shows an error rather than showing the pdf , would request to make a little changes so that even image pdf files can be opened  .

**Screenshots**
The list of pdf that i have
![a](https://user-images.githubusercontent.com/64555950/138143581-18dbbd2b-87d7-490a-b744-dc3ee341ec06.png)

The application unable to show these pdfs
![Screenshot from 2021-10-20 23-04-00](https://user-images.githubusercontent.com/64555950/138143854-e5b6510a-478b-4c9d-b8a8-442f728b161e.png)

The error message when opened a file with images 
![Screenshot from 2021-10-20 23-18-51](https://user-images.githubusercontent.com/64555950/138144986-b9a1cc4c-e2e7-41eb-aa3e-744177aa5d6f.png)

Image of libreOffice Writer with the same pdf

![Screenshot from 2021-10-20 23-20-39](https://user-images.githubusercontent.com/64555950/138145144-8c34a475-4f47-4a45-a5f4-19f6fa4b4421.png)

**Version:**
 - Foliate version: latest snap version 
 - OS/Distribution and version: Ubuntu 20.04
 - Desktop environment: GNOME 4
 - Installation method: via snap

**Additional context**

**Comment by johnfactotum** [comment]
Foliate does not support PDF files, images or not. See #139.
