### ISSUE TITLE
Windows Version of Foliate

### ISSUE THREAD

**Issue by SakethKanchi** [johnfactotum/foliate#804]
Can you make a windows version of Foliate. There are only a few Epub readers available on Windows. Like Calibre, Sumatrapdf, etc. Which have extremely outdated UI. Foliate look really cool, Hope you make a Windows Version.

**Comment by zhangcheng** [comment]
Why not DIY? 😄

**Comment by haunt98** [comment]
Can I ask if Foliate will support macos in the future ?

**Comment by apandada1** [comment]
Duplicate of https://github.com/johnfactotum/foliate/issues/115.
You can run it in Windows with [some effort](https://github.com/johnfactotum/foliate/issues/115#issuecomment-830005534).
