### ISSUE TITLE
Add keyboard shortcut for translate feature

### ISSUE THREAD

**Issue by Ja7ad** [johnfactotum/foliate#806]
Please add keyboard shortcut for fast translation

**Comment by apandada1** [comment]
Do you want the whole book to be translated at once?

**Comment by Ja7ad** [comment]
> Do you want the whole book to be translated at once?

No just selected words.

To use the translate feature, right-click on a word is required, but it's better to add a keyboard shortcut.

for example `Ctrl + X` or `Ctrl + Z`

**Comment by johnfactotum** [comment]
Duplicate of #540
