### ISSUE TITLE
Trying to import annotations

### ISSUE THREAD

**Issue by kaia009** [johnfactotum/foliate#809]
**Question:**
Requesting help to import annotations (json) from two identical versions of Foliate (and OS)

**Version:**
 - Foliate version: 2.6.3 installed from a ppa (ppa:apandada1/foliate) 
 -  - OS/Distribution and version: [e.g. Ubuntu 18.04] Ubuntu 20.04 (fully updated)
 - Desktop environment: [e.g. GNOME 3.36] Gnome-shell 3.36.9
 - Installation method: [e.g. Flatpak]  from Ubuntu repository
 
Could somebody please tell me what I am doing wrong?
 
I have been moving between computers (both using the same OS/version and Foliate version) and am trying to take my Foliate annotations with me:
 So I export them (hamburger menu > Book > Export annotations > json) 
 and import them (hamburger menu > Book > Import annotations ) 
 A list of the annotations to import duly appears. I click the bright green "Import" button and It turns dark green, and after about 7 seconds, Foliate closes down. 
 Could this be due to metadata discrepancies? If so what metadata? 
 
I really hope there is a solution to this, because I regularly commute between two computers and know of no better ebook reader than Folitate.

**Comment by itprojects** [comment]
@kaia009 This could be a new bug.

Try importing after starting Foliate in terminal, to see if there are any errors.

`flatpak run com.github.johnfactotum.Foliate`

Otherwise you can copy the JSON file from one computer to the other.

`~/.var/app/com.github.johnfactotum.Foliate`

One temporary fix may be to synchronise the two computers with a sync/backup app for the flatpak user folder above (i.e. running rsync).

**Comment by kaia009** [comment]
Thank you (!) for your reply. 
I'm not familiar with flatpak. I installed it now, but must have done a poor job because when I ran 
flatpak run com.github.johnfactotum.Foliate, 
Foliate opened telling me "file not found" but allowed me to browse for and open an epub file. 

When I tried to import annotations, the result was exactly as described in my initial post. 

(By the way, I am reluctant to permanently switch to a Flatpak version of Foliate rather than the version in the Ubuntu repos, because the latter beautifully handles Russian text to speech, which is really very impressive.)

So if this is a bug, I hope a solution can be found for those of us who regularly need to switch between computers. Copying the JSON file is not really a solution, because it will (I assume) overwrite rather than merge with the previously existing JSON file.

**Comment by itprojects** [comment]
@kaia009 What were the error messages in the terminal window?

> When I tried to import annotations, the result was exactly as described in my initial post.

1.  flatpak run com.github.johnfactotum.Foliate
2. Open file
3. Close Foliate
4.  flatpak run com.github.johnfactotum.Foliate
5. import
6. Error messages in terminal window.

**Comment by kaia009** [comment]
When I ran Foliate from Terminal, I got : 

Gtk-Message: 12:16:21.341: Failed to load module "canberra-gtk-module"
Portal call failed: Failed to start command: Failed to execute child process “dict” (No such file or directory)

I'm attaching the terminal results from the "import"
![Screenshot from 2021-11-14 12-11-22](https://user-images.githubusercontent.com/77581948/141678577-3b81b3d8-a33b-4031-9fae-9fb7a9af32e7.png)

**Comment by kaia009** [comment]
![Screenshot from 2021-11-14 12-38-01](https://user-images.githubusercontent.com/77581948/141679284-78ef7e3b-fb64-42d2-903f-c6e250cad3ee.png)

**Comment by itprojects** [comment]
@kaia009 This is not a bug in Ubuntu 21.10, but it seems to be for you.

**Comment by kaia009** [comment]
Is there anything I can do about it other than upgrade to 21.10?

**Comment by itprojects** [comment]
@kaia009 Here are your options:

1. Install a previous working flatpak Foliate version. [One or two commits previous, not ancient.]

2. Patch the code for now and, until the bug disappears.

**Comment by johnfactotum** [comment]
In general importing annotations seems to be pretty broken at the moment. For now it's probably better to manually copy them (see https://github.com/johnfactotum/foliate/issues/531#issuecomment-660181248).
