### ISSUE TITLE
Add shortcut to open Library

### ISSUE THREAD

**Issue by lobaluna** [johnfactotum/foliate#810]
A shortcut will avoid the use of the mouse. It's faster ;D

**Comment by johnfactotum** [comment]
Duplicate of #631

**Comment by lobaluna** [comment]
Sorry, John, but it is not working:

 johnfactotum commented on Sep 15
Fixed with 42388fd

I am on Manjaro using Foliate and Ctrl-h does not open the Library.

**Comment by johnfactotum** [comment]
The fix is not included in the latest release yet.
