### ISSUE TITLE
Is Two-Column view possible?

### ISSUE THREAD

**Issue by shimeike** [johnfactotum/foliate#811]
**Question:**
I am probably missing something obvious, but I cannot enable two-column view. Advanced/Layout options that are available when viewing an epub file are: Automatic, Single Column, Scrolled, Continuous.

I'm pretty sure I remember this was possible previously, and a two-column view is highlighted in application screenshots and listed as a feature.

Any help/suggestions? Thanks!

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Manjaro Linux
 - Desktop environment: KDE Plasma
 - Installation method: pacman (same issue with foliate-git from AUR)

**Comment by johnfactotum** [comment]
It will show two columns automatically with the "Automatic" layout, but only if the window is wide enough to show two columns. The window needs to be at least 800px wide (which cannot be changed, currenlty), plus the width of the margins—so at least 840px, by default.

**Comment by johnfactotum** [comment]
Currently, no.

I do plan on changing "(max) width" to "(max) column width". Then we could add a "minimum column width" setting, or perhaps more accurately something like "minimum spread width". That would make it possible to e.g. set min width to 500 to achieve your desired effect.

**Comment by shimeike** [comment]
That sounds great!

Keyboard shortcuts, e.g. 'C-]' / 'C-[' for 'next' / 'prev' Layout option, would also work well for a keyboard-driven tiling setup.

**Comment by johnfactotum** [comment]
The `gtk4` branch now has options for both max column width and max number of columns. To make two columns with full width and single column with half width on a 1080px screen, you now just have to set max column width to anything higher than 540.
