### ISSUE TITLE
Page render are glitched out

### ISSUE THREAD

**Issue by RafayAK** [johnfactotum/foliate#817]
**Describe the bug**
The renders of pages seem to glitch out often, with dark gray patches. This issue became apparent within the last two weeks.
![image](https://user-images.githubusercontent.com/17025191/143991426-c72594b4-86fb-4f3a-ba8b-962d9f89ad23.png)

The patches can be removed by clicking on them or when trying highlight the text behind the patches. 

**To Reproduce**
1. open an `epub` book
2. navigate the pages,

**Expected behavior**
No dark gray patches hide the text

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Pop OS 21.04
 - Desktop environment: GNOME 3.38.5
 - Installation method: Flatpak

**Additional context**

**Comment by johnfactotum** [comment]
I think this is most likely a graphics issue. If it started two weeks ago it's probably related to some package you updated two weeks ago. At any rate this is almost certainly not our bug and there's nothing we can do.

**Comment by alsid** [comment]
I've got the same issue. It's quite annoying. Would be interesting to find out which part of graphics causes it.

**Comment by johnfactotum** [comment]
Closing as there's nothing we can do.
