### ISSUE TITLE
Foliate snap text in the UI has artefacts.

### ISSUE THREAD

**Issue by KristijanZic** [johnfactotum/foliate#820]
Foliate snap has artefacts in the UI fonts:

![Screenshot from 2021-12-04 19-01-36](https://user-images.githubusercontent.com/10299892/144720627-e17b37f9-3038-4495-8f78-68c8596cbd03.png)

I've found some discussion about this particular issue in Snap store here but no one actually definitely what was the issue or how they fixed it or is it a per app issue or the and issue with snappy itself:
https://bugs.launchpad.net/snap-store-desktop/+bug/1936747

```
OS: Ubuntu 21.10 x86_64 
Kernel: 5.13.0-22-generic 
Shell: bash 5.1.8 
Resolution: 1920x1200 
DE: GNOME 40.5 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen Threadripper 1900X (16) @ 3.800GHz
GPU: AMD ATI Radeon RX Vega 56/64 
Memory: 7867MiB / 15852MiB 
```

**Comment by edurojasr** [comment]
Hi!

Can confirm that in Ubuntu 21.10 Foliate have broken fonts:

![image](https://user-images.githubusercontent.com/35645729/156688835-89262633-95df-438d-9bc2-84fbb0ae0666.png)

**Comment by connerbw** [comment]
Same. Using Ubuntu 22.04 LTS, installed from the Ubuntu Software store, looks like:

![Screenshot from 2022-04-21 19-08-46](https://user-images.githubusercontent.com/812192/164566085-4fbac5f8-9a48-46a2-a3ca-c7d33fb5bead.png)

**Comment by johnfactotum** [comment]
The upstream issue has been fixed. So this can probably be closed now.

**Comment by KristijanZic** [comment]
> The upstream issue has been fixed. So this can probably be closed now.

I can confirm. Thanks!
