### ISSUE TITLE
Foliate snap does not work with Festival

### ISSUE THREAD

**Issue by KristijanZic** [johnfactotum/foliate#821]
Foliate snap doesn't work with Festival. Even tho the festival is installed and Flatpak woks fine with it, snap doesn't. I can click the play tts button but it just get's pressed and unpressed as soon as I let go of the mouse click.

**Comment by johnfactotum** [comment]
The Snap package only supports `espeak-ng` and the `mb-en1` voice at the moment. See #324.

**Comment by johnfactotum** [comment]
This should be fixed in the GTK 4 version now that it's using speech-dispatcher. It just needs to have permission to `$XDG_RUNTIME_DIR/speech-dispatcher/speechd.sock`. Also requires speech-dispatcher >= 0.11.4 installed on the host.

CC @soumyaDghosh

**Comment by soumyaDghosh** [comment]
@johnfactotum So, the `speech-dispatcher` needs to be added in the snap right?

**Comment by johnfactotum** [comment]
No, `speech-dispatcher` runs on the host. Foliate will use it by connecting to the socket at `$XDG_RUNTIME_DIR/speech-dispatcher/speechd.sock`. So it just needs readwrite access to the file.

**Comment by johnfactotum** [comment]
Note that currently it uses `GLib.get_user_runtime_dir()`, though: https://github.com/johnfactotum/foliate/blob/641a20c41dcb43e51cc2b83b55db92abd71867c4/src/speech.js#L21 And I'm not sure if it'd get the right path from that. It may need to be changed to something specific to Snap.

**Comment by soumyaDghosh** [comment]
> Note that currently it uses `GLib.get_user_runtime_dir()`, though:
> 
> https://github.com/johnfactotum/foliate/blob/641a20c41dcb43e51cc2b83b55db92abd71867c4/src/speech.js#L21
> And I'm not sure if it'd get the right path from that. It may need to be changed to something specific to Snap.

Can you explain me the way to test it?
