### ISSUE TITLE
the computer freezes after opening the book.

### ISSUE THREAD

**Issue by xverizex** [johnfactotum/foliate#826]
**Describe the bug**
I test on both computers and the computers freezes.

**To Reproduce**
1. Open a epub book

**Version:**
 - Foliate version:
 - OS/Distribution and version: openSuse tumbleeweed
 - Desktop environment: gnome-41
 - Installation method: flatpak

**Comment by KJ2ME** [comment]
I have the seme issue, when open any ebook the complete system is freezed, but reinstalling it works fine again (the ebooks info not was lost).

**Comment by johnfactotum** [comment]
Closing as *obsolete* with the release of the GTK 4 version. Feel free to open new issues if you have problems with the new version.
