### ISSUE TITLE
Better text-to-speech support

### ISSUE THREAD

**Issue by johnfactotum** [johnfactotum/foliate#829]
Currently text-to-speech (TTS) support is pretty bad. It should be improved.

Specifically, it should

- [ ] Use SpeechSynthesis API
- [ ] "Polyfill" SpeechSynthesis API (which isn't supported by WebKitGTK) by posting messages to the GJS process, which will call speech-dispatcher.
- [ ] Parse and handle assisting markups
  - [x] SSML
  - [ ] PLS
  - [ ] CSS speech? 
- [x] Segment text, with `Intl.Segmenter`
- [x] Highlight currently spoken word/sentence

  There is a "boundary" event on `SpeechSynthesisUtterance`. AFAICT there is no such event in speech-dispatcher. Instead we need to add SSML marks and read the `INDEX_MARK` event notification from speech-dispatcher. This is how Calibre does it, judging by its [source code](https://github.com/kovidgoyal/calibre/blob/dafa08e9213d3baad41c97e7598592bd0e06894d/src/calibre/gui2/tts/develop.py). Also, not all synthesizers supports this (or even SSML).

- [x] UI for controlling playback and configuring voice, speed, etc., and make the features more discoverable (see #672)

**Comment by tenleftfingers** [comment]
I've also come across a better sounding (IMO) TTS system than festival called mimic https://github.com/MycroftAI/mimic1

You can hear a samples comparing it to festival and espeak-ng here https://linuxreviews.org/Mimic
