### ISSUE TITLE
Settings not applying consistently / closing foliate resets settings

### ISSUE THREAD

**Issue by l4ssc** [johnfactotum/foliate#831]
**Describe the bug**
Title is self-explanatory I think, but below should have more details

**To Reproduce**
1. Install Foliate.
2. Open Foliate with a book.
3. Change settings such as theme, font, etc.
4. Close and re-open Foliate.
5. Settings should be reset to their prior state.

**Expected behavior**
Theme settings would apply to the top and bottom unfocused bars and theme settings would save on close.

**Screenshots**
Applying theme settings does not affect the top and bottom bars when they are unfocused:
![](https://i.imgur.com/UCgSUrT.png)

On restart:
![](https://i.imgur.com/Q33IQmx.png)

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Arch Linux, 2021.12.01
 - Desktop environment: awesome v4.3
 - Installation method: `pacman -S foliate`

**Additional context**
[Log from `foliate &`, I don't know where the actual file is if that exists (sorry)](https://pastebin.com/6BRGwEtp)

**Comment by johnfactotum** [comment]
> closing foliate resets settings

If you look at Foliate's settings with e.g. dconf-editor, are they saved at all? Or are they being reset when re-opening?

>  Applying theme settings does not affect the top and bottom bars when they are unfocused:

What GTK theme are you using? And do you have any styles in `gtk.css`? My guess would be that it's some kind of backdrop style. But in any case this wouldn't happen anymore in the `gtk4` branch, as the header and footer are now part of the webview and not GTK widgets anymore.

**Comment by johnfactotum** [comment]
Closing as obsolete with the release of the GTK 4 version. Feel free to open new issues if you have problems with the new version.
