### ISSUE TITLE
Can't change the theme.

### ISSUE THREAD

**Issue by vatsdimri** [johnfactotum/foliate#836]
**Describe the bug**
I recently installed the flatpak version of the foliate (In about section it's version is Foliate 2.6.3) on Ubuntu 21.10 (newly installed). when I try to change to theme(both pre-defined and custom) it just close the app and not change the theme.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a book
2. Go to Menu
2. Click on Theme
3. Click on any theme
4. It closes the app

**Version:**
 - Foliate version 2.6.3 flatpak:
 - OS/Distribution and version: Ubuntu 21.10
 - Desktop environment: GNOME 40.4.0
 - Installation method: Flatpak

Edit:
It seem to be working fine after uninstalling and reinstalling the app. But it's happening again after I rebooted the system.
Edit2: 
I have now installed snap version which is working fine.

**Comment by anthonyajumelles** [comment]
Noticing the same issue via the Flatpak on Fedora Silverblue 35.

**Comment by CaptainMorgan12** [comment]
Duplicate #719
