### ISSUE TITLE
problem saving a custom theme

### ISSUE THREAD

**Issue by cenkt** [johnfactotum/foliate#838]
**Describe the bug**
When I create a custom theme I can save it but after I quit and reopen the app the saved theme always comes back as white background and black fonts

**To Reproduce**
1. Create a custom theme with new colors
2. Save the new theme
3. close and reopen the app
4. the saved theme is white background and black fonts

**Expected behavior**
the saved theme should store the colors that I have created it with

**Screenshots**
![image](https://user-images.githubusercontent.com/6926806/147736052-24c070e0-21bb-4bd6-9afe-c052df9334f5.png)
****the very top theme

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Windows WSL Ubuntu 20.04.3 LTS
 - Desktop environment: GNOME Shell 3.36.9
 - Installation method: apt install

**Additional context**

**Comment by fathyar** [comment]
I can confirm that this issue still exists in Foliate v2.6.4 (installed via Ubuntu daily PPA).
