### ISSUE TITLE
Page content shifts progressively with page turns

### ISSUE THREAD

**Issue by afduggirala** [johnfactotum/foliate#840]
Hello.
The content of my books (text and others) is shifting to the right side as I turn pages. Every time (or on some occasions) I turn to the next page, the content moves a little to the right with respect to the window borders. Eventually this content starts being cut off by the margin on the right, and the cutoff content is shown on the left side on the next page turn.
Resizing the window will set things correctly again. I think changing chapters also resets the content position correctly.

A screenshot is here:
https://imgur.com/a/CpsYDbq

I'm on:
Foliate version: 2.6.3
Fedora 34
GNOME 40.5
Installation method: Fedora repository

**Comment by johnfactotum** [comment]
Can you try the new renderer (see #962)?

**Comment by afduggirala** [comment]
Hello John. I have not been having this issue for a while, I will test again to see if I can detect the issue again in my current installation 2.6.4 to see if I can reproduce it.

**Comment by johnfactotum** [comment]
As it's not reproducible, I'm going to go ahead and close this for now. But feel free to comment if you're still seeing the issue (especially if it happens with the `gtk4` branch, as I'm not working on the 2.x branch anymore).

**Comment by isaacbh2** [comment]
Resurrecting this, as I have this issue (I think) in Foliate 3.3.0 (flatpak). It happens with every book. Window size change will fix it, but it returns eventually while turning pages. I'm on Ubuntu 26.04.

See example:
https://imgur.com/a/Zyq0Weu
