### ISSUE TITLE
open last opened file on startup opens to library

### ISSUE THREAD

**Issue by executie** [johnfactotum/foliate#842]
When clicking on the icon on the dock, it doesn't open to the last opened file (set in preferences), but opens the library. The default action of "new-window" is being superseded by "library". To get it to work I changed my desktop file "com.github.johnfactotum.Foliate.desktop":

I changed
`Actions=new-window;`
to
`Actions=Library;`
and renamed
`[Desktop Action new-window]`
to
`[Desktop Action Library]`

Ubuntu 20.04 Gnome

**Comment by johnfactotum** [comment]
Hmm. I think currently it only opens the library window if you launch a new instance (in GNOME that would be middle clicking on the icon). When launching it for the first time, it does restore the last opened file. This is expected behavior, I believe.

**Comment by executie** [comment]
With the default desktop file and no other instances of it running, left clicking on the icon always opens the library even when "Open Last opened file on startup" is true.

I think, for many applications (unless they have coded [in the app] for the new-window option to do something else when an instance is already open), left clicking or right click New Window are the same thing if it is not already running. So, with the desktop file having the new-window action set to open the library, then left clicking will run new-window.

**Comment by johnfactotum** [comment]
> With the default desktop file and no other instances of it running, left clicking on the icon always opens the library even when "Open Last opened file on startup" is true.

I can't reproduce this on GNOME 40. I wonder if it's the old behavior or just Ubuntu doing its own thing. Or perhaps it's some extension that you installed.

**Comment by executie** [comment]
Yep. it's Ubuntu Dock.
