### ISSUE TITLE
Endlessly loading

### ISSUE THREAD

**Issue by aronkvh** [johnfactotum/foliate#848]
When I try to open the app or open a file it just shows the loading icon. the hamburger menu is responsive, If I open any file it opens a new window and loads endlessly. The library page opens

**Version:**
 - Foliate version: 2.6.3 Flatpak
Operating System: KDE neon 5.23
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.3
Kernel Version: 5.11.0-25-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770 CPU @ 3.40GHz
Memory: 27,1 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000
```
(com.github.johnfactotum.Foliate:2): Gtk-WARNING **: 15:43:04.091: Locale not supported by C library.
        Using the fallback 'C' locale.
Portal call failed: Failed to start command: Failed to execute child process ?dict? (No such file or directory)
Portal call failed: Failed to start command: Failed to execute child process ?sdcv? (No such file or directory)

(com.github.johnfactotum.Foliate:2): Gtk-WARNING **: 15:43:04.346: Theme directory apps/24 of theme breeze-extended-cinnamon has no size field


(com.github.johnfactotum.Foliate:2): Gtk-WARNING **: 15:43:04.357: Theme directory apps/24@2x of theme breeze-extended-cinnamon has no size field


(com.github.johnfactotum.Foliate:2): Gtk-WARNING **: 15:43:04.357: Theme directory apps/24@3x of theme breeze-extended-cinnamon has no size field

flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.
flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.
flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.
```

**Comment by flrnd** [comment]
Similar behaviour on Gnome 42. I've tried both flatpak and package version.

(com.github.johnfactotum.Foliate:6929): Gjs-WARNING **: 11:33:36.484: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  @/usr/bin/foliate:9:17

**Comment by jstrunk1982** [comment]
try the "clear cache" option from the menu dropdowns. Alternatively, try reloading the document. It will eventually open.

Same issue here on Fedora 36 beta with flatpak, rpm or snap.

**Comment by iambumblehead** [comment]
foliate on arch linux hangs at the loading animation when trying to load an ebook
```bash
$ foliate --version
2.6.4
$ foliate

(com.github.johnfactotum.Foliate:164851): Gjs-WARNING **: 22:27:00.782: JS ERROR: Error: Empty Response
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57
_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:886:22
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/foliate:9:17
```

**Comment by amadeusp** [comment]
I'm on Manjaro GNOME and after reading a couple of pages of any of my eBooks the app gets unresponsive.

The log says:
```
Portal call failed: Failed to start command: Failed to execute child process “dict” (No such file or directory)
Portal call failed: Failed to start command: Failed to execute child process “sdcv” (No such file or directory)
```

Have already tried all kinds of Flatseal "hacks" but so far nothing helped. Sometimes clearing cache helps, sometimes not.

My system configuration:
* OS: Manjaro 22.0.0 Sikaris
* Kernel: x86_64 Linux 6.0.6-1-MANJARO
* Shell: zsh 5.9
* Resolution: 1920x1080
* DE: GNOME 42.3
* WM: Mutter
* Disk: 417G / 920G (48%)
* CPU: AMD Ryzen 7 PRO 4750U with Radeon Graphics @ 16x 1.7GHz
* GPU: RENOIR (renoir, LLVM 14.0.6, DRM 3.48, 6.0.6-1-MANJARO)
* RAM: 8518MiB / 29806MiB
* Foliate version: 2.6.4 (flathub)

**Comment by in-in** [comment]
Same on Linux Mint 20.2 Cinnamon
Endless loading when adding a new book

![22337232425](https://user-images.githubusercontent.com/8797432/205460577-52d460bb-4dab-4221-ac05-d34b7ee8a488.png)
![22337232836](https://user-images.githubusercontent.com/8797432/205460807-4196b083-37e1-4676-81b1-24db96105dff.png)

![22337232655](https://user-images.githubusercontent.com/8797432/205460741-832552b0-172f-40e9-aa37-35834c57d936.png)

**Comment by johnfactotum** [comment]
Closing. See https://github.com/johnfactotum/foliate/issues/636#issuecomment-1572436701 and https://github.com/johnfactotum/foliate/issues/594#issuecomment-1572439868.
