### ISSUE TITLE
unknown compression error

### ISSUE THREAD

**Issue by cenkt** [johnfactotum/foliate#850]
**Describe the bug**
After the latest upgrade I keep getting this error:
`dpkg-deb: error: archive '/var/cache/apt/archives/foliate_2.6.4-1~ubuntu22.04.1_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/foliate_2.6.4-1~ubuntu22.04.1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/foliate_2.6.4-1~ubuntu22.04.1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**To Reproduce**
1. Go to 
`sudo update;
sudo apt install foliate`   

**Expected behavior**
should update and/or install the app
**Screenshots**
![image](https://user-images.githubusercontent.com/6926806/149612724-dcc6644b-ea9e-464a-9187-70a5d5e61f48.png)

**Version:**
 - Foliate version: 2.6.4-1 ubuntu
 - OS/Distribution and version: kali-linux 2021.4 kali-rolling
 - Desktop environment: dbus-run-session
 - Installation method: Ubuntu (PPA) stable

**Comment by johnfactotum** [comment]
Paging @apandada1

**Comment by apandada1** [comment]
Debian (and Kali) don't yet [support](https://unix.stackexchange.com/a/669008/55205) zst compression in apt packages, which was introduced in Ubuntu 22.04.

You can use the focal (20.04) repository instead of jammy. While they are built from the same source, and are the same version of Foliate, Launchpad builds focal packages with the traditional gz compression instead of zst.

**Comment by cenkt** [comment]
How am I going to do that? When I do 
` cat /etc/apt/sources.list`
I get only
` deb http://http.kali.org/kali kali-rolling main non-free contrib`

**Comment by apandada1** [comment]
There should be an entry for Foliate in the directory `/etc/apt/sources.list.d/`. Replace `jammy` with `focal` in that. Afterwards, run `sudo apt update` and `sudo apt install foliate`.

**Comment by cenkt** [comment]
Thnx it worked great....
