### ISSUE TITLE
Clarified PPA label change, so users can update again

### ISSUE THREAD

**Issue by Moonbase59** [johnfactotum/foliate#851]
I labelled this "question", seemed most appropriate.

The PPA’s label has changed between v2.6.3 and v2.6.4 ("Foliate ebook reader" → "Foliate").

For users on Debian-like systems, who use [the PPA](https://launchpad.net/~apandada1/+archive/ubuntu/foliate) (like I do), I explain how to get upgrades again on two of the more frequented e-reader forums:

- [MobileRead](https://www.mobileread.com/forums/showpost.php?p=4189781&postcount=5) (English)
- [E-Reader Forum](https://www.e-reader-forum.de/t/foliate-e-reader-fuer-linux.158123/#post-2441617) (German)

Reason: Users of GUI-based updaters are often not aware of how to handle situations like this one.

**Comment by apandada1** [comment]
I changed the label from "Foliate ebook reader" → "Foliate" at some point months ago (I don't even remember why I did so). Is it that much of a big deal?

**Comment by Moonbase59** [comment]
Not really. If you’re aware that you should read your GUI system updater’s messages. ;-)
Maybe we could somehow transfer the above quote posts into the Wiki or README, so users are aware. It’s just a "(Y)ES, I accept that" if updating from the terminal.

**Comment by johnfactotum** [comment]
See https://github.com/linuxmint/mintupdate/issues/622.

Apparently it's also a common problem when using `apt-get`: https://askubuntu.com/questions/989906/explicitly-accept-change-for-ppa-label

**Comment by Moonbase59** [comment]
Yup, should probably have mentioned that, too: Users are encouraged to use `apt` in place of `apt-get`. It is more modern and has better features.
