### ISSUE TITLE
Foliate not opening. Libsoup-ERROR

### ISSUE THREAD

**Issue by yousufAzadAyon** [johnfactotum/foliate#852]
**Describe the bug**
Foliate not opening in Archlinux. Gives me the following message: 
<pre>Gjs-<font color="#98971A"><b>Message</b></font>: <font color="#458588">00:52:35.899</font>: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 23]: Requiring WebKit2 but it has 2 versions available; use imports.gi.versions to pick one

(com.github.johnfactotum.Foliate:17025): libsoup-<font color="#CC241D"><b>ERROR</b></font> **: <font color="#458588">00:52:36.031</font>: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
[1]    17025 trace trap (core dumped)  foliate</pre>

**To Reproduce**
1. open terminal
2. type 'foliate'

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Arch Linux
 - Desktop environment: Gnome 41.3
 - Installation method: `sudo pacman -S foliate`

**Comment by yousufAzadAyon** [comment]
I just manually build from source. It works fine now. closing it. Thank you.

**Comment by chrisbrasington** [comment]
This bug is still present in the version provided by pacman (2.6.3-1) which causes it not to run on manjaro/arch.

Installing from get (or foliate-git) in AUR does work (2.6.4.r1.ged40d8b-1), but please update the pacman version. Thanks

**Comment by yousufAzadAyon** [comment]
@chrisbrasington  that's what I thought. pacman version(2.6.3-1) needs to be updated. I could not find any work around so decided to build from the source.
