### ISSUE TITLE
Build requirements and runtime requirements

### ISSUE THREAD

**Issue by kekePower** [johnfactotum/foliate#86]
Hi.

I'm thinking about packaging Foliate for Mageia and am wondering what would be the Build and Runtime requirements.

I've been able to build and run it because this is my dev computer. So far I have the packages mentioned in README.md, but are any of those also necessary at runtime?

Thanks in advance.

**Comment by johnfactotum** [comment]
Meson and gettext should be all that's required for building.

The rest listed in the readme are required at runtime. GJS and WebKitGTK are the main requirements. Libsoup is also required for now, although I'm planning on making it optional. It's only used for querying Wiktionary. Hyphenation rules are optional, and they are not used directly by Foliate; they are optional dependencies of WebKitGTK.

There is one more thing that I'm not about. Currently, Foliate requires the `org.gnome.desktop.peripherals.touchpad` schema. I'm not entirely sure whether this schema will be present if you don't have the GNOME desktop (or a least a part of it, anyway) installed. I guess I'll try to make that optional, but currently if that schema cannot be found, I believe Foliate would just crash.

**Comment by kekePower** [comment]
Thanks for the clarification @johnfactotum 
Much appreciated.
