### ISSUE TITLE
Library button and Bookmark button on the top bar

### ISSUE THREAD

**Issue by vatsdimri** [johnfactotum/foliate#863]
**Is your feature request related to a problem? Please describe.**
I think these two features are most used when reading a book it seems strange to me that the buttons for going to the library and adding a bookmark require more than on click at least the adding bookmark should be just one click away.

**Describe the solution you'd like**
Add a button for Library and adding a bookmark to the top bar. I am thinking buttons more like Save and Open buttons in gedit text editor.

**Comment by johnfactotum** [comment]
Fixed by 906d54c60f65cb44ba6f96dee398b0e3ceee8940.
