### ISSUE TITLE
Crash if touching brightness slider (Foliate 2.6.4 Flatpak on Pop!_OS)

### ISSUE THREAD

**Issue by truscellino** [johnfactotum/foliate#867]
Immediate crash if touching the brightness slider while reading an eBook.

Foliate 2.6.4 as flatpak (from Flathub) on Pop!_OS 21.10.

I started Foliate from the terminal with `flatpak run xxx --verbose` but I couldn't see anything interesting. Output of `journalctl --reverse` seems to be a better clue:

```
Feb 09 20:30:07 xxx systemd[1893]: app-flatpak-com.github.johnfactotum.Foliate-10895.scope: Consumed 2.225s CPU time.
Feb 09 20:30:07 xxx systemd[1893]: app-flatpak-com.github.johnfactotum.Foliate-10895.scope: Deactivated successfully.
Feb 09 20:30:07 xxx kernel: traps: com.github.john[10791] general protection fault ip:7fa843865fa7 sp:7ffe2f60abf0 error:0 in libgtk-3.so.0.2404.27[7fa84356f00>
Feb 09 20:29:56 xxx systemd[1893]: Started app-flatpak-com.github.johnfactotum.Foliate-10895.scope.
Feb 09 20:29:56 xxx systemd[1893]: app-flatpak-com.github.johnfactotum.Foliate-10874.scope: Deactivated successfully.
Feb 09 20:29:56 xxx systemd[1893]: Started app-flatpak-com.github.johnfactotum.Foliate-10874.scope.
```

Thanks

**Comment by revjasper** [comment]
On Zorin 16.1, I had the same issue.  Foliate 2.6.4 as flatpak, installed from the Zorin software center.

Looking closely at the same output on my machine, I saw "Failed to load module "canberra-gtk-module"" right before the fault appeared.  

Installed "libcanberra-gtk-module" and it's dependency through Synaptic, and the brightness slider now functions without crashing the program.

**Comment by Lippiece** [comment]
I'm facing the same issue on Arch with pacman, with snap, and with flatpak.

**Comment by johnfactotum** [comment]
Closing as <i>obsolete</i>; there isn't a brightness slider in the GTK 4 version.
