### ISSUE TITLE
Day/Night mode (theme) hotkey

### ISSUE THREAD

**Issue by icher** [johnfactotum/foliate#869]
Hi.

How about hotkey for switching preselected day/night color theme? For me, it's everyday routine, so it would be nice if I can do it easier (4 clicks for now 😐).

Ctrl-Alt-t (VSCode default) for example.

**Comment by johnfactotum** [comment]
Currently Foliate doesn't even support day/night modes. It only supports arbitrary themes. So the whole color theme preference needs to be reworked (and also integrated with the new freedesktop/libadwaita color scheme preference).

**Comment by johnfactotum** [comment]
- Switching between light and dark mode takes only 2 clicks now.
- There's no standard shortcut for this.
- A shortcut for a three state setting could be problematic, especially when two of the states look identical (the "follow system style" mode looks the same as either light or dark mode).
