### ISSUE TITLE
Flatpak distribution crashes

### ISSUE THREAD

**Issue by ndtoan96** [johnfactotum/foliate#87]
Version 1.3.0

I can open foliate, but can not open any epub file. As soon as it finished loading, it crashed. The terminal output is: 
`Gjs-Message: 21:44:21.404: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 1741]: reference to undefined property "isFullscreen"`

**Comment by johnfactotum** [comment]
Is this the whole output? Even though `isFullscreen` is undefined, this is just a warning, not an error. And even if an error was thrown there, the app would just be stuck at the loading spinner; it shouldn't have crashed the entire program.

**Comment by ndtoan96** [comment]
Seems like someone got the same problem with more specific output #88

**Comment by johnfactotum** [comment]
Thanks. I'll close this in favor of #88.
