### ISSUE TITLE
Header Bar and borders not following the Theme in Arch

### ISSUE THREAD

**Issue by Owl-Boy** [johnfactotum/foliate#872]
On changing themes (built-in or custom), the book itself changes its colors, but the header bar does not.

1. Go to Themes
2. Click on any theme (built-in or custom)
3. See that the header bar does not change its color

Expecting the title bar to match the background color

**Screenshots**
![image](https://user-images.githubusercontent.com/76904491/156407374-8d41fe5d-2cf9-4b6d-84f6-2cb0fe9faf5d.png)

 - Foliate version:2.6.4-1
 - Distro/OS: Arch Linux
 - DE/WM: Xmonad
 - Source: AUR

**Comment by johnfactotum** [comment]
What GTK theme are you using? From the screenshot, I would guess that either you've set a non-existent theme, or the theme doesn't support GTK 3. Both would break dark mode. Basically it's the same issue as #470. It's arguably a GTK 3 bug.

**Comment by Owl-Boy** [comment]
Oh yeah, this was the issue.
sorry for the late reply, got busy that past few days
