### ISSUE TITLE
Books always have full justification

### ISSUE THREAD

**Issue by master-of-zen** [johnfactotum/foliate#873]
Books are always fully justified, regardless of full justification settings.

**To Reproduce**
Open book
Select any layout
Set/unset full justification

**Screenshots**
![2022 03 03_18:47:44](https://user-images.githubusercontent.com/46526140/156611401-b8977d6f-7c5d-4c53-ae27-23d4813aa985.png)
![2022 03 03_18:47:20](https://user-images.githubusercontent.com/46526140/156611424-77bbe2e7-f466-45b5-9969-dd2257a00610.png)

Arch
Foliate git: https://github.com/johnfactotum/foliate/commit/811554d8db25b5069e10f0707b9f9e66c571a031

**Additional context**

**Comment by johnfactotum** [comment]
See the FAQ: https://github.com/johnfactotum/foliate/wiki#custom-style-isnt-applied-consistently

**Comment by master-of-zen** [comment]
@johnfactotum makes sense.
I'm coming from Moon+ Reader, it's really flexible in it's user settings, I love it)
Hopefully, wishfully, Foliate will be on same level)
