### ISSUE TITLE
Track reading time and show how long it would take to finish the book.

### ISSUE THREAD

**Issue by Firstbober** [johnfactotum/foliate#874]
Foliate could track how long user reads based on page changes and using this, it should show how long it will take to finish an entire book. This tracking would only apply to the current reading session and not globally.

**Comment by itprojects** [comment]
May be a duplicate. Check the other issues.

**Comment by Firstbober** [comment]
I searched, but I found nothing. Maybe the keywords ('time', 'track', etc.) I used were wrong.

**Comment by itprojects** [comment]
Your idea of using page flips is not identical, but is on the topic of the following.

Directly related to:

https://github.com/johnfactotum/foliate/issues/341

Others:

https://github.com/johnfactotum/foliate/issues/683

https://github.com/johnfactotum/foliate/issues/175

https://github.com/johnfactotum/foliate/issues/176

**Comment by Firstbober** [comment]
Hmm, I have hard time deciding if this issue should be closed due to this page flips idea (borrowed from KOReader).

**Comment by itprojects** [comment]
Yes, that's very true. It has been added to #341 as an optional feature request.

**Comment by Firstbober** [comment]
Great! Thanks for assistance!
