### ISSUE TITLE
Foliate crashes upon opening any ebook

### ISSUE THREAD

**Issue by SonephetR2** [johnfactotum/foliate#88]
Foliate worked perfectly a few weeks ago. I updated the application via Flatpack and it started crashing immediately upon opening any EPUB file. I uninstalled and then reinstalled the latest Flatpack release but the problem persists.

```
s###@S###:~$ flatpak run com.github.johnfactotum.Foliate
Gjs-Message: 00:07:52.195: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 1741]: reference to undefined property "isFullscreen"

(com.github.johnfactotum.Foliate:2): Gtk-WARNING **: 00:07:52.257: Theme parsing error: gtk.css:3415:30: The style property GtkButton:image-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(com.github.johnfactotum.Foliate:2): Gtk-WARNING **: 00:07:52.257: Theme parsing error: gtk.css:3416:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(com.github.johnfactotum.Foliate:2): Gjs-WARNING **: 00:07:52.281: JS ERROR: Error: 330 is not a valid value for enumeration Weight
bookDisplayed/<@resource:///com/github/johnfactotum/Foliate/js/main.js:1373:32
onViewChange@resource:///com/github/johnfactotum/Foliate/js/main.js:561:13
applyFont@resource:///com/github/johnfactotum/Foliate/js/main.js:459:9
setFont@resource:///com/github/johnfactotum/Foliate/js/main.js:475:9
loadSettings@resource:///com/github/johnfactotum/Foliate/js/main.js:645:9
bookDisplayed@resource:///com/github/johnfactotum/Foliate/js/main.js:1455:9
handleAction@resource:///com/github/johnfactotum/Foliate/js/main.js:1479:17
open/<@resource:///com/github/johnfactotum/Foliate/js/main.js:1244:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:2512:12
run@resource:///org/gnome/gjs/modules/package.js:225:12
@/app/bin/com.github.johnfactotum.Foliate:9:1
```

**Comment by johnfactotum** [comment]
This is odd. Seems like a problem with the font button widget.

Can you try building a Flatpak manually with f356a7c9184ef21343e19a6a9d19efa602e193af?

To do this,
1. Download https://github.com/johnfactotum/foliate/archive/f356a7c9184ef21343e19a6a9d19efa602e193af.zip
2. Edit `com.github.johnfactotum.Foliate.json`
```diff
24,25c24,25
<                     "type": "git",
<                     "url": "https://github.com/johnfactotum/foliate.git"
---
>                     "type": "dir",
>                     "path": "."
```
3. Run `flatpak-builder --force-clean --install --user _build com.github.johnfactotum.Foliate.json`

**Comment by SonephetR2** [comment]
Thanks! I followed the instructions, after installing flatpak-builder, but get the following:

```
~$ flatpak-builder --force-clean --install --user _build '/home/s###/Desktop/foliate/com.github.johnfactotum.Foliate.json' 

(flatpak-builder:311): flatpak-builder-WARNING **: 13:48:41.414: Unknown source type dir

(flatpak-builder:311): Json-WARNING **: 13:48:41.414: Failed to deserialize "sources" property of type "gpointer" for an object of type "BuilderModule"
Emptying app dir '_build'
Downloading sources
Starting build of com.github.johnfactotum.Foliate
Skipping module foliate (no sources)
Cache hit for cleanup, skipping
Cache miss, checking out last cache hit
Finishing app
Error: Command 'com.github.johnfactotum.Foliate' not found

```

**Comment by johnfactotum** [comment]
It seems flatpak-builder can't find the files ("`Skipping module foliate (no sources)`"). Did you edit the manifest properly?

**Comment by SonephetR2** [comment]
Install now works but Foliate still crashes immediately upon trying to load any EPUB file:

```
$ flatpak run com.github.johnfactotum.Foliate
Gjs-Message: 15:39:07.572: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 1738]: reference to undefined property "isFullscreen"

(com.github.johnfactotum.Foliate:2): Gtk-WARNING **: 15:39:07.629: Theme parsing error: gtk.css:3415:30: The style property GtkButton:image-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(com.github.johnfactotum.Foliate:2): Gtk-WARNING **: 15:39:07.629: Theme parsing error: gtk.css:3416:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(com.github.johnfactotum.Foliate:2): Gjs-WARNING **: 15:39:07.648: JS ERROR: Error: 330 is not a valid value for enumeration Weight
bookDisplayed/<@resource:///com/github/johnfactotum/Foliate/js/main.js:1370:32
onViewChange@resource:///com/github/johnfactotum/Foliate/js/main.js:558:13
applyFont@resource:///com/github/johnfactotum/Foliate/js/main.js:456:9
setFont@resource:///com/github/johnfactotum/Foliate/js/main.js:472:9
loadSettings@resource:///com/github/johnfactotum/Foliate/js/main.js:642:9
bookDisplayed@resource:///com/github/johnfactotum/Foliate/js/main.js:1452:9
handleAction@resource:///com/github/johnfactotum/Foliate/js/main.js:1476:17
open/<@resource:///com/github/johnfactotum/Foliate/js/main.js:1241:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:2509:12
run@resource:///org/gnome/gjs/modules/package.js:225:12
@/app/bin/com.github.johnfactotum.Foliate:9:1
```

I'll try Gnome Builder

**Comment by johnfactotum** [comment]
So I guess it doesn't have anything to do with `use_font`... Maybe you can try with a73d7ec3e36e74ed494abe6c444e77fece63419b. I don't really know what's causing the problem.

What's the font you're using? What happens if you reset the font setting?

**Comment by ndtoan96** [comment]
I finally can pinpoint the problem, it starts appearing at https://github.com/johnfactotum/foliate/commit/de9746914b26439d2c2daaf00907a7601d02e165.

**Comment by johnfactotum** [comment]
Thanks for taking the time to test this!

Unfortunately, I still don't know what's going on. Maybe it's something to do with your particular setup? Which distro and Flatpak version are you using? Because I can't reproduce this, and I don't really see anything wrong in that commit that could have caused this mysterious error, or crashing without any error, which is even more mysterious. If possible, maybe you can also try fiddling with the code to pinpoint what exactly is causing this.

**Comment by SonephetR2** [comment]
Thanks for looking so deeply into this.

The font I am using is Noto Sans. Resetting the font setting doesn't change the error message however.

My specs: Linux Mint 19.1 Tessa; Flatpak 1.0.8 (the issue persists now that I manually updated to version 1.4.1). 

Not too sure of the version of Foliate I was using before updating. I installed it 20 days ago (at the time of https://github.com/johnfactotum/foliate/issues/9).

**Comment by ndtoan96** [comment]
I deleted all the brightness stuff from main.js and managed to run version 1.3.0 without problem. I'll mess around with it some more to see what's wrong.

**Comment by johnfactotum** [comment]
Just tried Linux Mint 19.1 in a VM. Installed Foliate 1.3.0 from Flathub and everything works for me.

**Comment by ndtoan96** [comment]
Found it, the problem is at line 1459 main.js `settings.get_double('brightness')`. Comment it out and everything is fine, except that my brightness is 120% by default.

**Comment by johnfactotum** [comment]
Doesn't make sense. Maybe it's a problem with the schema? But if that's the problem, you should get `Settings schema 'com.github.johnfactotum.Foliate' does not contain a key named 'brightness'` or something like that. Does it crash if you do `settings.get_double('brightness')` from elsewhere in the code?

Or maybe it's not getting the value, but setting the slider with the value. What happens if you just replace `settings.get_double('brightness')` with `1`?

**Comment by ndtoan96** [comment]
Well, it seems the true problem is at a first few times running the app, after I comment out line 1459, build it and run it several times, then uncomment line 1459, build it again and run. Voila, it works. After that, the flathub pakage which never works before, now works as it should.

**Comment by ndtoan96** [comment]
Weird, the value which makes the app crashes is 1. I replace `settings.get_double('brightness')` by many different values and it always crashes at 1 (1.0 makes no difference, 1.01 works).

**Comment by johnfactotum** [comment]
That's weird. The value is already set to 1 in https://github.com/johnfactotum/foliate/blob/master/src/main.js#L597. Maybe that's the problem?

**Comment by ndtoan96** [comment]
It seems like `this._brightnessSlider.set_value(1)` has no effect, I changed it to 1.1 and replaced `settings.get_double('brightness')` by 0.9. The real brightness was 0.9 and slider also pointed at 0.9.

**Comment by ndtoan96** [comment]
I know the exact problem here, somehow we cannot set the same value to `this._brightnessSlider.value`. I tried to change its value at constructor to 0.6 then the crash-value change to 0.6.
This might be a bug with flatpak or something because it's really dump.

**Comment by johnfactotum** [comment]
@SonephetR2 Does deleting line 597 in main.js work for you also?

But this is strange. Calling `set_value()` twice with the same value shouldn't crash, right? Sounds like a bug in GTK or something else.

**Comment by ndtoan96** [comment]
Yes, I tried calling `set_value()` twice, nothing wrong. It's only goes wrong when one was called inside constructor and one outside with the same value.

**Comment by johnfactotum** [comment]
No, I cannot reproduce at all. Are you using Linux Mint 19.1 like @SonephetR2 or Ubuntu 18.04 like @terrestrian? But then I did try in Linux Mint 19.1, and it worked fine for me. Maybe it has something to do with your hardware setup?

Maybe you can try and see if you can reproduce this with a minimum Gjs app containing only code for the slider.

**Comment by ndtoan96** [comment]
I'm using Ubuntu 19.10. I'll take time to try the slider thing later since I need to learn javascript and Gjs first.
But as I said, delete (or comment out) line 597 works for me.

**Comment by ndtoan96** [comment]
Hmm, just tried to build from source, it worked fine. Only flatpak got this problem.

**Comment by SonephetR2** [comment]
At this stage, I haven't managed to build Foliate from source. Indeed, in the Mint repo Meson is not version >= 5.0.0 and I haven't managed to install the most recent version from Github as of yet. I am not sure I have managed to install Foliate with line 597 removed from main.js either.

**Comment by SonephetR2** [comment]
At this stage, I haven't managed to build Foliate from source. Indeed, in the Mint repo Meson is not version >= 5.0.0 and I haven't managed to install the most recent version from Github as of yet. I am not sure I have managed to install Foliate with line 597 removed from main.js either.

**Comment by ndtoan96** [comment]
You can install meson 0.5.1 from pip `pip3 install --upgrade meson`, after that, you may need to install `libglib2.0-dev` and you can build it from source. But as I said, the problem won't appear with building from source.
You can try the flatpak-builder thing with this two commit:
- 76f999af066985208ef58d6e76b79b06dd3b8d01 <-- work fine
- de9746914b26439d2c2daaf00907a7601d02e165 <-- crash

**Comment by SonephetR2** [comment]
Thanks a lot!! `76f999a` now launches and opens EPUB files perfectly... but the highlighter tool doesn't appear anymore. Do you believe this can be connected in any way or should I open a new issue?

**Comment by ndtoan96** [comment]
I don't know, 76f999a is a commit from the past so the highlighter tool may not be implemented yet. In my case, I can build the latest commit (version 1.3.0) from source with all the features intact. Only the app built from flatpak-builder crashes, but deleting line 597 and rebuilding works.

**Comment by johnfactotum** [comment]
Removed line 597. Feel free to reopen, if the crash persists, or open a new issue, if anything else isn't working.

**Comment by afrfb09ba** [comment]
I had the same problem with Foliate being installed but failing to load the books.
FYI, I had this problem on both Fedora 33 and 34 on KDE Plasma 5.20 or later. On the same cases I installed using flatpak.

Now, I installed on Fedora 33 KDE Plasma using Fedora's dnf - 'sudo dnf install foliate' and no problems.
It seems the problem has to do with flatpak installation.

**Comment by putzwasser** [comment]
I have the same problem with Manjaro. Pacman installs v 2.6.3-1. It crashes with the following output:

```
foliate 
Gjs-Message: 18:15:12.371: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 23]: Requiring WebKit2 but it has 2 versions available; use imports.gi.versions to pick one

** (com.github.johnfactotum.Foliate:24360): CRITICAL **: 18:15:12.604: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:24360): CRITICAL **: 18:15:12.604: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:24360): CRITICAL **: 18:15:12.604: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:24360): CRITICAL **: 18:15:12.604: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:24360): CRITICAL **: 18:15:12.604: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:24360): CRITICAL **: 18:15:12.604: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:24360): CRITICAL **: 18:15:12.604: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:24360): CRITICAL **: 18:15:12.604: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:24360): CRITICAL **: 18:15:12.604: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:24360): CRITICAL **: 18:15:12.604: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:24360): CRITICAL **: 18:15:12.604: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:24360): CRITICAL **: 18:15:12.604: g_irepository_find_by_name: assertion 'typelib != NULL' failed

(com.github.johnfactotum.Foliate:24360): GLib-GObject-WARNING **: 18:15:12.604: cannot register existing type 'TrackerSparqlConnection'

(com.github.johnfactotum.Foliate:24360): GLib-CRITICAL **: 18:15:12.604: g_once_init_leave: assertion 'result != 0' failed

(com.github.johnfactotum.Foliate:24360): GLib-GObject-CRITICAL **: 18:15:12.604: g_type_register_static: assertion 'parent_type > 0' failed

(com.github.johnfactotum.Foliate:24360): GLib-GObject-WARNING **: 18:15:12.604: cannot add private field to invalid (non-instantiatable) type '<invalid>'

(com.github.johnfactotum.Foliate:24360): GLib-CRITICAL **: 18:15:12.604: g_once_init_leave: assertion 'result != 0' failed

(com.github.johnfactotum.Foliate:24360): GLib-GObject-CRITICAL **: 18:15:12.605: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(com.github.johnfactotum.Foliate:24360): Tracker-CRITICAL **: 18:15:12.605: tracker_sparql_backend_load_plugins: assertion 'self != NULL' failed
```
