### ISSUE TITLE
How to build this project for Apple Silicon M1 Mac?

### ISSUE THREAD

**Issue by ashwinbalaji0811** [johnfactotum/foliate#882]
I have an M1 Mac Macbook Pro and wish to help build this awesome tool for mac users. But I'm no expert and wish some getting started steps.

**Comment by johnfactotum** [comment]
See #503

**Comment by liiyee** [comment]
I used docker desktop as a way to run foliate on macOS, but it crashes occasionally, wish there was another way to run it on macOS.
