### ISSUE TITLE
Various Reading Themes Not Functional in Debian Bookworm

### ISSUE THREAD

**Issue by Odyssian** [johnfactotum/foliate#883]
**Describe the bug**
After uploading a book into Foliate, it works fine with default settings; however, any attempt to switch to an alternative reading theme causes the program to automatically quit. I did not expect this to happen. 

 - Foliate version: 2.6.4
 - OS/Distribution and version: Debian Bookworm
 - Desktop environment: KDE 5.24.4
 - Installation method: Flatpak & Snap

**Comment by CaptainMorgan12** [comment]
Duplicate #719
