### ISSUE TITLE
Mobile touchscreen paging swipe doesn't work

### ISSUE THREAD

**Issue by CaptainMorgan12** [johnfactotum/foliate#890]
Environment: phosh 0.17.0-1pureos1, 720x1440 screen 200% scaling, touchscreen device mobile.

Add swipe gesture support to page back and forth within a book.

Workaround: Click on left or right side of the screen to turn pages.

Swiping should occur when moving finger to left anywhere on screen or to the right (horizontally) and after moving finger off of the screen.

**Comment by johnfactotum** [comment]
Swiping should work. See #591. If it doesn't then it's a bug.

**Comment by CaptainMorgan12** [comment]
> Swiping should work. See #591. If it doesn't then it's a bug.

**Comment by johnfactotum** [comment]
> Sorry for the noise i am so used to swiping left and right that i didnt notice swipe up and down actually pages through the book.

Swiping left and right should also work.

> For example if i hold and swipe slowly the text is selected.

Interesting. Didn't know it were possible to select text by swiping on a touchscreen.

The support for touchscreen selection is pretty poor in WebKitGTK. Swiping should never be used to activate selection as it would conflict with scrolling and paging.

But even then, swiping should still work. For me, on a non-touchscreen, when "Simulate touchscreen" is enabled, swiping both selects text and turns page.

> Reqhuired swiping speed is basically a bit too high not sure that can be adjusted though

If you can build it from source, try adjusting the sensitivity constant: https://github.com/johnfactotum/foliate/blob/84e1af7d1f2948685241cdeaf27f011113c671e8/src/epubView.js#L45

**Comment by johnfactotum** [comment]
I went ahead and reduced the threshold in the `gtk4` branch (6f04e1cfabccddf24e59e842452f9d4cafe49eb8).
