### ISSUE TITLE
N command stops working after first page advance

### ISSUE THREAD

**Issue by rgreen5** [johnfactotum/foliate#892]
**Describe the bug**
After opening an ebook in Foliate at the cover page (i.e. first page), the N (following) command only takes you to the next page, then stops working. You can only get it to work proerly by using the slider to move it to the main body of text.

1. Open the attached epub in Foliate. It should open on the cover page. 
[Kropotkin - Mutual Aid.zip](https://github.com/johnfactotum/foliate/files/8556112/Kropotkin.-.Mutual.Aid.zip)

2. Press N several times

RESULT: N stops working after the first page advance.

3. Use the slider to advance the viewport into the main body of text, then try the N and P commands.

RESULT: They work as expected.

**Expected behavior**
N and P commands should work no matter what page you start from.

**Version:**
 - Foliate version: 2.6.3 and 2.6.4
 - OS/Distribution and version: Linux Mint 20.1
 - Desktop environment: Cinnamon 4.8.6
 - Installation method: PPA (Stable)

**Comment by johnfactotum** [comment]
Okay, this is actually the same as #941. Closing this one as that one has more details.
