### ISSUE TITLE
mobi: Error ( The string did not match the expected pattern )

### ISSUE THREAD

**Issue by zzzsyyy** [johnfactotum/foliate#893]
When I open a **.mobi** book, it take a long time, and show "could not open file"
 
this is the message after `foliate --verbose` 

```bash
Gjs-Message: 16:31:52.884: JS LOG: run_javascript: open(
                    decodeURI("/tmp/.CGOXK1/mobi8/"),
                    decodeURI("C-pointer"),
                    'directory',
                    'viewer',
                    {"width":"100...
Gjs-Message: 16:31:52.889: JS LOG: book-error

(com.github.johnfactotum.Foliate:9202): Gjs-WARNING **: 16:31:52.889: JS ERROR: Error: The string did not match the expected pattern.
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57
_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:886:22
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/foliate:9:17
```

**Version:**
 - Foliate version: from AUR 2.6.4-1
 -  Arch Linux 
 - WM: i3

**Comment by rahulTPatil** [comment]
Hi @zzzsyyy - I did tried opening .mobi file and it is working fine for me. Try the following solution and see if that works for you. 

[https://github.com/johnfactotum/foliate/issues/878#issuecomment-1079727273](url)

**Comment by zzzsyyy** [comment]
Thank you and the solution worked -- I can open the book but there's an err shows on the first page 
```
This page contains the following errors:

error on line 805 at column 12: Entity 'hoge' not defined
error on line 995 at column 25: Entity 'hoge' not defined
error on line 2071 at column 34: EntityRef: expecting ';'
Below is a rendering of the page up to the first error.
```

This is the e-book file if needed
[here](https://mega.nz/file/DkEUnJRS#OWu21jZb-bCAPz3x1gGw1OAnRjHkIkYmLPVBS3XvpG4)
Merci d'avance

**Comment by rahulTPatil** [comment]
Tried opening the attached book and got the exact same error on the first page as you got. However, the rest of the book loads till the 43rd page.

**Comment by johnfactotum** [comment]
For the problem with entities, see #699.
