### ISSUE TITLE
Removing book should also clear last opened file

### ISSUE THREAD

**Issue by afduggirala** [johnfactotum/foliate#898]
Hello,
I experienced a bug when removing a book. I click on remove book and the book appears to be removed from my library. Then I open Foliate again and the book which I just removed is opened again, automatically. This happens when the option is set to open the last opened file.

**Comment by johnfactotum** [comment]
Closing as there's no option to reopen the last opened file anymore.

If that option is ever brought back one might consider getting the last modified book data .json file to get the last opened file. Or it should store the last file's identifier.
