### ISSUE TITLE
Change theme accroding to System Theme

### ISSUE THREAD

**Issue by snpefk** [johnfactotum/foliate#901]
**Is your feature request related to a problem? Please describe.**
Foliate has different themes, and depending on the time I manually change them for better readability and eye comfort.

**Describe the solution you'd like**
Change theme according to a System Theme. Other apps (like Firefox or Nautilus) can do that.

**Describe alternatives you've considered**
Just do it manually. 

**Additional context**
🐬

**Comment by johnfactotum** [comment]
This has long been fixed in the gtk4 branch.
