### ISSUE TITLE
Minimum Font size Option

### ISSUE THREAD

**Issue by gurpreet3737** [johnfactotum/foliate#906]
Some epub E-books have defined x-small or xx-small font size for some sections in their style.css, which makes it unreadable compare to normal font size.

![image](https://user-images.githubusercontent.com/48869845/170816132-3ff77af2-8c80-4a45-8d9b-d0c773f6e295.png)

Please add minimum font size option so as to make these fonts larger. FB reader has this option in their settings.

Thanks

**Comment by johnfactotum** [comment]
Hmm, yes, I think we should be able to set the `minimum-font-size` property on the webview. And unlike CSS overrides it doesn't seem to trigger #941.

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.
