### ISSUE TITLE
Change number of columns when window is resized

### ISSUE THREAD

**Issue by emes81** [johnfactotum/foliate#907]
First, thanks for this app - it's by far the best ebook reader I know on any platform.

Sometimes I use the app full-screen, in those instances a two-column arrangement makes sense. At other times, I snap the window to one side with the browser or a note-taking app snapped to the other side; it would be amazing if Foliate could aromatically switch to a single column when the window is sized down past a certain threshold.

**Comment by johnfactotum** [comment]
It already does that, but the threshold is hardcoded at 800px (Epub.js default) plus margins. See https://github.com/johnfactotum/foliate/issues/811
