### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by ghost** [johnfactotum/foliate#909]
**Navigation via Table of Contents**
While navigating, if want to jump to different chapter or section, sometimes is works and sometimes it doesn't. Started this problem recently.

**To Reproduce**
1. Go to Table of contents
2. Try to go to sections inside the chapters, ie.  sub-contents.

**Expected behavior**
When clicked on subsections, it should take where it is supposed to be.

**Version:**
 - Foliate version: 2.6.4
 - Pop-os 22.04
 - GNOME 42.1
 - Flatpak via pop-shop

**Comment by tomicakorac** [comment]
@mauryarprabhat while I don't have a solution for you, I'd like to draw your attention to this topic here: https://github.com/johnfactotum/foliate/issues/879. To me it sounds like the exact same problem. Can you please confirm?

**Comment by mauryarprabhat** [comment]
I think yes

**Comment by johnfactotum** [comment]
Closing as a duplicate.
