### ISSUE TITLE
Add keyboard shortcut

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#91]
Pressing the Space key moves to the displayed book to the next page.
It would be nice to have the option for the Back-space to go back to the previous page.

**Comment by johnfactotum** [comment]
I think backspace should maybe got back to the previous location, as in browsers.

Does Evince have a backspace shortcut? In general I've tried to be consistent with Evince for navigation shortcuts.

**Comment by itprojects** [comment]
Yes, Evince allows Back-space to return to previous page. In Foliate (in two page mode) it would be good to also return two pages back, because space moves two pages forward.
