### ISSUE TITLE
Resizing or full screen epub window causes segmentation fault

### ISSUE THREAD

**Issue by ghost** [johnfactotum/foliate#915]
**Describe the bug**
This is specific to Wayland. When resizing the window / fullscreen / Maximizing the epub window, force closes itself
Verbosing outputs `segmentation fault (core dumped)` while resize/maximize event

**To Reproduce**
1. Open an epub
2. Resize/Maximize the window

**Expected behavior**
Should work without any force closes.

**Screenshots**
Will provide on demand.

**Version:**
 - Foliate version: v2.6.4
 - OS/Distribution and version: Arch Linux 5.18.6-arch1-1 x86_64
 - Desktop environment: GNOME 42 / Wayland
 - Installation method: pacman

**Additional context**
The issue is specific only for Wayland session. No issues on X11.

**Comment by johnfactotum** [comment]
Probably a bug somewhere in GTK, WebKit, or GNOME and not something to be done here. And the user is a ghost now so there's not getting more info. Either way, this is not actionable.
