### ISSUE TITLE
UI suggestion

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#92]
What are your thoughts about making the theme selection (from the button in the header bar, not in the preferences) from radio buttons to drop down menu, to save space?

**Comment by johnfactotum** [comment]
Radio buttons works better when there are only a handful of themes with short names. Originally the plan was to switch to a menu when the user adds more custom themes.

**Comment by itprojects** [comment]
Even with just four theme, a menu looks nicer. Custom themes add lets say two to three and the radio buttons cannot cope.

**Comment by itprojects** [comment]
@johnfactotum How does this UI look? ![Screenshot](https://user-images.githubusercontent.com/2698054/61577562-a1757c80-aad8-11e9-8a76-1e7f6ddec975.png)

**Comment by johnfactotum** [comment]
I think ideally it should display a small preview using the colors of the theme, a bit like:

Pantheon Terminal
![image](https://user-images.githubusercontent.com/50942278/62510292-08e03b80-b7fe-11e9-9e8e-971b1b4456d5.png)

Reader view in Firefox
![image](https://user-images.githubusercontent.com/50942278/62510381-5eb4e380-b7fe-11e9-8e35-2acdaf800d96.png)

Gedit
![image](https://user-images.githubusercontent.com/50942278/62510519-c66b2e80-b7fe-11e9-90af-ae3eb3479146.png)

In our case, it would have horizontal scroll to cope with additional custom themes.

**Comment by itprojects** [comment]
@johnfactotum The horizontal scrollbar in a popup will look very strange. Maybe (3-by-n-rows) gtk.grid? However the idea of moving some of the theme customization to Preferences > Theme is not that bad. The Firefox Reader menu is best left to Firefox.

What do we do with the brightness slider? In gnome-shell panel, that meter is available in a menu, as it is a quick access item. Maybe removing that feature is one option? Leaving the system to handle the brightness.

**Comment by itprojects** [comment]
Due to the redesign, this can be closed
