### ISSUE TITLE
Snap: translation tool doesn't work

### ISSUE THREAD

**Issue by T-nfd** [johnfactotum/foliate#920]
**Question:**
Hi,

Can you please help me with how to use the google translator feature?
I select  a text and click on "Translate", but this error occurs:
![image](https://user-images.githubusercontent.com/84374136/180634702-eefd605c-f352-444c-b8aa-537949f61cf5.png)

**Version:**
 - Foliate version: [2.6.3]
 - OS/Distribution and version: [Ubuntu 22.04 LTS]
 - Desktop environment: [GNOME 42.2]
 - Installation method: [Snap store]

**Comment by johnfactotum** [comment]
See #206. According to the comments, it might be a snap-specific bug. Will need to investigate further.

**Comment by johnfactotum** [comment]
It appears to me that the Snap doesn't have network access at all, which would also explain #923. But that makes no sense. It has the network plug enabled.

**Comment by soumyaDghosh** [comment]
@johnfactotum Can you give me some idea on how to check that or reproduce this issue?

**Comment by johnfactotum** [comment]
Select some text and choose "Translate" from the popover menu. Last time I checked other things that required network didn't work either, so that includes Dictionary and Wikipedia lookup, and the Catalogs which you can access from the sidebar of the Library view.
