### ISSUE TITLE
OPDS is not working (GDBus.Error:org.freedesktop.portal.Error.NotAllowed: This call is not available inside the sandbox)

### ISSUE THREAD

**Issue by azazar** [johnfactotum/foliate#923]
**Describe the bug**

OPDS catalogs refuse to load

**To Reproduce**

1. `# snap install foliate`
2. Attempt to open any OPDS catalog

**Screenshots**
![2022-07-28_09-49](https://user-images.githubusercontent.com/2816075/181439570-31201094-8c26-46f2-bfd6-e668e4a1c925.png)

**Version:**
 - Foliate version: 2.6.3l
 - OS/Distribution and version: Ubuntu 22.04 LTS
 - Desktop environment: Xfce4
 - Installation method: snap

**Additional context**

    (com.github.johnfactotum.Foliate:41246): Gtk-WARNING **: 09:48:41.590: Duplicate child name in GtkStack: loaded
    
    ** (WebKitWebProcess:43275): WARNING **: 09:48:41.895: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied
    
    ** (WebKitWebProcess:43275): WARNING **: 09:48:41.896: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
    
    (com.github.johnfactotum.Foliate:41246): Gjs-WARNING **: 09:48:41.912: JS ERROR: Error: TypeError: GDBus.Error:org.freedesktop.portal.Error.NotAllowed: This call is not available inside the sandbox
    _handleAction@resource:///com/github/johnfactotum/Foliate/js/opds.js:485:50
    OpdsClient/<@resource:///com/github/johnfactotum/Foliate/js/opds.js:470:13
    main@resource:///com/github/johnfactotum/Foliate/js/main.js:476:12
    run@resource:///org/gnome/gjs/modules/package.js:225:12
    @/snap/foliate/1167/usr/bin/com.github.johnfactotum.Foliate:9:1

**Comment by johnfactotum** [comment]
Same of #920
