### ISSUE TITLE
Custom styles for FB2 tags and EPUB elements

### ISSUE THREAD

**Issue by natewind** [johnfactotum/foliate#930]
Please add separate styles for FB2 tags in the settings. And, ideally, the same for EPUB if you can detect semantics from it somehow.

E. g. I read books in Garamond Premier Pro, and I’d like to use the Subhead variant for titles.

**Comment by johnfactotum** [comment]
Closing in favor of #947

**Comment by johnfactotum** [comment]
As of efc2dd4be4aeebf35475708ca6d182dee2e21eb1, custom stylesheet can be set by creating `~/.config/com.github.johnfactotum.Foliate/user-stylesheet.css`. FB2 tags can be targeted using classes (e.g. `.date` for `<date>`).
