### ISSUE TITLE
Chapter 1 text stuck on screen (Touch screen)

### ISSUE THREAD

**Issue by PKMpl** [johnfactotum/foliate#932]
This problem doesn't occur with a mouse. Basically, when I fold my HP Spectre and use it as a tablet, "Chapter X" always remains somewhere on screen if I try to resize/move the page. Same thing happens with the mouse cursor, but you can move it off screen. When I resize I try to make the letters fill the screen for comfort, so that text is always there. It also overlaps other apps, like Chrome.

Ubuntu 22.04, HP Spectre 2017

Thank you for this app, apart from this little issue it's great.

**Comment by johnfactotum** [comment]
Can you post some screenshots or a screen recording? Sounds like some kind of graphics problem that probably needs to be fixed elsewhere and not in Foliate.

**Comment by PKMpl** [comment]
Sorry about a late reply, I don't use github very often. It's hard for me to take a screenshot because the keyboard doesn't work in tablet mode. Basically, with a mouse you can move it off screen, but with a touch cursor it remains in place after using it, causing the text to appear.  At least that's why idea.

**Comment by johnfactotum** [comment]
I'm not sure I understand the issue. Are you saying that you're positioning the window so that the footer is off screen? And that you can't do it when using the touch screen?

**Comment by tomicakorac** [comment]
> Sorry about a late reply, I don't use github very often. It's hard for me to take a screenshot because the keyboard doesn't work in tablet mode. Basically, with a mouse you can move it off screen, but with a touch cursor it remains in place after using it, causing the text to appear. At least that's why idea.

It might be helpful to even take a video with your mobile phone and post it for us to see. I must admit it's difficult for me to understand from your description what exactly is the issue.

**Comment by johnfactotum** [comment]
Closing this as stale. If you're still experiencing problems, feel free to comment or open a new issue.
