### ISSUE TITLE
Crashing when changing theme (Arch - Steam OS 3)

### ISSUE THREAD

**Issue by Senseal** [johnfactotum/foliate#957]
**Describe the bug**
Crashes when changing theme 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a book
2. Click on the burger menu in the top right 
3. Then click  'Theme'
4. Then click any theme 
4. Then the program just dies mate 

**Expected behaviour**
Program switches to the correct theme and does not crash

**Screenshots**
https://cdn.discordapp.com/attachments/722446780154773555/1026598244937117746/8mb.video-FEt-DnNHSbzQ.mp4

**Version:**
 - Foliate version:  2.6.4
 - SteamOS (Arch) 3.3.1
 - KDE Plasma 5.23.5
 - Flatpak

**Additional context**
Crashed whether or not its connected to an external display

**Comment by johnfactotum** [comment]
Duplicate o #719
