### ISSUE TITLE
Allow contributions from Hacktoberfest event

### ISSUE THREAD

**Issue by nunatix** [johnfactotum/foliate#958]
**Question:**

Is it possible to add the Hacktoberfest event labels to the project topics?

*(PS: Thank you for the great work and contribution.)*

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Fedora Linux 36
 - Desktop environment: KDE Plasma 5.25.5
 - Installation method: RPM Package from Official Repository

**Comment by johnfactotum** [comment]
Ok.
