### ISSUE TITLE
Annotations/Highlights Missplacement

### ISSUE THREAD

**Issue by MatteoCarotta** [johnfactotum/foliate#96]
Version 1.3.1 on Ubuntu 19.04, X11, GNOME 3.32.0

When I change the the layout mode after I annotated some text the highlighter strokes get pushed to the top of the page out of place.
Only in Scrolled mode the highlighter strokes are visualized in the correct position.
![Screenshot-20190702003213-1920x1053](https://user-images.githubusercontent.com/11245492/60470937-9b6f4700-9c62-11e9-9d3b-8adb42b111b4.png)
![Screenshot-20190702003203-1920x1053](https://user-images.githubusercontent.com/11245492/60470943-a0cc9180-9c62-11e9-8e65-d37b7aa42983.png)
![Screenshot-20190702003153-1920x1053](https://user-images.githubusercontent.com/11245492/60470953-ae821700-9c62-11e9-964e-313edc02d118.png)

**Comment by johnfactotum** [comment]
Thanks for opening the issue. This has been fixed in 5ffeb5bc4523ac5b0f28bce6500d66458bae3acc.
