### ISSUE TITLE
public key not available in ppa

### ISSUE THREAD

**Issue by brainchild0** [johnfactotum/foliate#963]
# Description

The PPA is not usable due to no public key being available.

# Steps to Reproduce

On an installation of Linux Mint 21, run the following commands:

1. `sudo add-apt-repository ppa:apandada1/foliate`
1. `sudo apt update`

# Expected behavior

The command `apt update` completes without error or warning.

# Actual behavior

The following is the end of the output from running `sudo apt update`:

```
W: GPG error: http://ppa.launchpad.net/apandada1/foliate/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A507B2BBA7803E3B
E: The repository 'http://ppa.launchpad.net/apandada1/foliate/ubuntu jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by johnfactotum** [comment]
@apandada1

**Comment by apandada1** [comment]
I could not reproduce this on an Ubuntu live session. Might be a Mint specific issue/network issue due to Mint unable to download the key. Can you try the following?

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A507B2BBA7803E3B
sudo apt update
sudo apt install foliate
```

**Comment by brainchild0** [comment]
The invocation of `apt-key` resolved the problem.

Would any advice be available on how to tweak the local system to avoid an unexpected problem of the same kind in the future?

**Comment by apandada1** [comment]
To troubleshoot, can you check if such error happens for any other ppa?
If that happens, consider creating a post in the Mint forum

**Comment by brainchild0** [comment]
The problem has occurred for multiple PPAs.

**Comment by apandada1** [comment]
I would suggest asking a question in the Mint Forum (https://forums.linuxmint.com/) or https://unix.stackexchange.com/. I don't know how to fix it (it might be either a Mint bug or an issue with your network), but the workaround is to use apt-key.

@johnfactotum  It is not a Foliate PPA bug. The issue can be closed.
