### ISSUE TITLE
navigation in epub - rejected promises

### ISSUE THREAD

**Issue by O-ovo-O** [johnfactotum/foliate#967]
This bug might be a combination of two bugs. 
1. Occasionally - the book cannot be scrolled further, using page down or mouse. It stops loading next pages, clicking on the "progress bar" navigation does not solve the issue, reopening the application does.
2. Much more often but not 100% of the time, when reading a book and scrolling - sometimes it jumps back a few pages.
Same case with jumping multiple pages.
Page can remain blank in that case, "progress bar" can be set, vertical scroll bar can be dragged, but pages will not load.

**To Reproduce**
open big (1000 pages?) epub. Scroll using either mouse wheel, or multiple  "page down" key from keyboard, or down arrow keys, possibly a mixture of those.

**Expected behavior**
any method of "scrolling" should be reliable. It seems that for example pressing "End" on the keyboard will take user to the end of lazy loaded section, not to the end of the epub.  
Jumping pages should always work.

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: 22.04.1
 - Desktop environment: Gnome 42.0
 - Installation method: apt

**Additional context**
What's worth mentioning - when running from gjs -d and 'c'-ontinuing on exceptions - the pages are loaded

```
Promise 1 fulfilled after 0.091 ms
Promise 2 rejected after 2.662 ms with [object GLib_Error]
{
    "stack": "execCommand/<@resource:///com/github/johnfactotum/Foliate/js/utils.js:306:35\nexecCommand@resource:///com/github/johnfactotum/Foliate/js/utils.js:289:5\n@resource:///com/github/johnfactotum/Foliate/js/lookup.js:318:12\n@resource:///com/github/johnfactotum/Foliate/js/window.js:26:57\n@resource:///com/github/johnfactotum/Foliate/js/main.js:44:20\n@/usr/bin/com.github.johnfactotum.Foliate:9:1\n",
    "fileName": "resource:///com/github/johnfactotum/Foliate/js/utils.js",
    "lineNumber": 306,
    "columnNumber": 35
}

 Gjs-WARNING   Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  execCommand@resource:///com/github/johnfactotum/Foliate/js/utils.js:289:5
  @resource:///com/github/johnfactotum/Foliate/js/lookup.js:318:12
  @resource:///com/github/johnfactotum/Foliate/js/window.js:26:57
  @resource:///com/github/johnfactotum/Foliate/js/main.js:44:20
  @/usr/bin/com.github.johnfactotum.Foliate:9:1
  
  Gjs-CRITICAL  Promise 2 Handler attached to rejected promise that wasn't previously marked as unhandled or that we wrongly reported as unhandled
Promise 4 started from @resource:///com/github/johnfactotum/Foliate/js/lookup.js:322:6
Promise 5 rejected after 1.982 ms with [object GLib_Error]
```

Apparently those above are from startup

```
Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  set epub/<@resource:///com/github/johnfactotum/Foliate/js/window.js:165:37
  _handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:920:22
  _init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18
  main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  @/usr/bin/com.github.johnfactotum.Foliate:9:17
```

and each time it stops, and is able to continue through, this one happens:

```
Gtk-CRITICAL gtk_tree_store_get_value: assertion 'VALID_ITER (iter, tree_store)' failed

GLib-GObject-CRITICAL  g_value_type_transformable: assertion 'src_type' failed

GLib-GObject-CRITICAL g_value_type_transformable: assertion 'src_type' failed
Unwinding due to exception. (Type 'c' to continue unwinding.)
#0    <anonymous>([object GObject_Object]) at resource:///com/github/johnfactotum/Foliate/js/contents.js:139:36
   139	                const value = store.get_value(iter, 0)
Exception value is:
$3 = [object Error]
Error: Don't know how to convert GType (null) to JavaScript object
db> c

Gjs-CRITICAL JS ERROR: Error: Don't know how to convert GType (null) to JavaScript object
set epub/<@resource:///com/github/johnfactotum/Foliate/js/contents.js:139:37
_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:947:22
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/com.github.johnfactotum.Foliate:9:17

```

**Comment by johnfactotum** [comment]
Thanks for the detailed report.

Continuous scrolling is problematic in many ways, both in Epub.js and in general. In the `gtk4` branch, instead of Epub.js, it now uses a new renderer (see https://github.com/johnfactotum/foliate/issues/962), which does not support continuous scrolling at all (yet) (though it does support non-continuous, i.e. in chapter scrolling).

As for last error, it looks like it's related to selecting the active TOC item. To be honest I'm not really interested in looking into it; the list view in GTK 4 has a much nicer way of working with trees and I'd really rather not deal with tree iters again.

> It seems that for example pressing "End" on the keyboard will take user to the end of lazy loaded section, not to the end of the epub.

Technically, this is https://github.com/johnfactotum/foliate/issues/458, as without such a shortcut, the pressing "End" will just trigger the default action handled by the WebView.
