### ISSUE TITLE
Foliate is running but there is no icon

### ISSUE THREAD

**Issue by aasril** [johnfactotum/foliate#97]
I'm on Ubuntu 18.04, installed Foliate (1.3.1) from Flathub. Foliate works fine but there is no icon shows up both in applications menu and on taskbar.

**Comment by johnfactotum** [comment]
I can reproduce this on Linux Mint 19.01. But it works on Ubuntu 19.04. Not sure what's causing this. My guess is that it's not our bug.

**Comment by aasril** [comment]
@johnfactotum, did you push an update yesterday on Flathub? Because the issue fixed itself yesterday. Either that or system update from Ubuntu fixed the problem.

**Comment by johnfactotum** [comment]
Nope, 1.3.1 is the latest release, so probably the latter. Thanks for the info.
