### ISSUE TITLE
Add "removable-media" connector plug to the Edge Channel Snap of Foliate

### ISSUE THREAD

**Issue by stone2forge** [johnfactotum/foliate#973]
**Is your feature request related to a problem? Please describe.**
Snap Foliate in the Edge channel does not have the `removable-media` connector when the Stable channel has it. 

**Describe the solution you'd like**
Enable the `removable-media` connector in the Edge Channel. 

**Additional context**
The Stable channel on most snap apps have a font rendering problem (including Foliate) which seems to be easily resolved by switching to an Edge Channel.  

Foliate also has a font rendering problem when using the Stable channel but this is also easily resolved by installing the Edge Channel, the thing is that this channel does not have the `removable-media ` connector as opposed to the Stable Channel.

**Comment by johnfactotum** [comment]
That would be a bug. There isn't supposed to be any difference in terms of `removable-media` between channels. The the build is failing for some reason, so the stable channel is stuck at 2.6.3 (see #911). But the edge channel's version is 1.5.3, which to be honest I'm not sure how it happened or why it's even possible.  But if it's really 1.5.3, that would explain why it doesn't have `removable-media`. Anyway, I've promoted the stable channel build to the edge build. Now both should be using 2.6.3 and should both have `removable-media` now.
