### ISSUE TITLE
Increase scroll speed

### ISSUE THREAD

**Issue by rdgh8** [johnfactotum/foliate#976]
**Is your feature request related to a problem? Please describe.**

I find the scroll speed of Foliate to be very slow compared to Calibre. 

**Describe the solution you'd like**

Ideally, scroll speed should be increased or parametrized in the settings. The scrolling speed/physics of Firefox are perfect imo, if that would be possible. 

**Describe alternatives you've considered**

**Additional context**

As a side note, is there a way to force text selection to behave like in a browser? I want the menu to show up when I right click while I have text selected, not immediately after I select the text, as that locks the scrolling up.

**Comment by johnfactotum** [comment]
Scrolling is (and should be) handled by WebKitGTK. So this is a wontfix / not our bug.
