### ISSUE TITLE
Disable Cmd+W

### ISSUE THREAD

**Issue by boehs** [johnfactotum/foliate#983]
**Is your feature request related to a problem? Please describe.**

I often split screen between a browser and foliate, and today I tried to close a browser tab, but foliate was focused. When I did `Cmd+W`, foliate closed. This shortcut is uneeded, because foliate doesn't have tabs. If I wanted to close foliate, I would do `Cmd+Q`

**Describe the solution you'd like**

Disabling Cmd+W

**Describe alternatives you've considered**

- Getting better at using my computer

**Comment by johnfactotum** [comment]
Ctrl+W is the standard shortcut for closing either the current tab or window. See https://developer.gnome.org/hig/reference/keyboard.html. Foliate is a multi-window application so Ctrl+W is different from Ctrl+Q.

**Comment by boehs** [comment]
> Ctrl+W is the standard shortcut for closing either the current tab or window. See [developer.gnome.org/hig/reference/keyboard.html](https://developer.gnome.org/hig/reference/keyboard.html). Foliate is a multi-window application so Ctrl+W is different from Ctrl+Q.

Ah, multi-window. Fair enough
