### ISSUE TITLE
can't add/open books on ubuntu mate 20.04

### ISSUE THREAD

**Issue by dizzy314** [johnfactotum/foliate#986]
**Describe the bug**
Can't open/add books to the Library with the '+' button or the OpenBook and AddBooks menus.

Other dialogs work correctly (Open Catalog, Add Catalog, Catalogs).

**To Reproduce**
0. snap install foliate
1. Open foliate from the terminal
2. Click on '+' or Menu->OpenBook... or Menu->AddBooks...
3. nothing happens but prints this errors in the terminal:
Gtk-Message: 16:38:19.524: Failed to load module "appmenu-gtk-module"
Gtk-Message: 16:38:19.525: Failed to load module "canberra-gtk-module"
(com.github.johnfactotum.Foliate:83251): GLib-GIO-WARNING **: 16:38:24.014: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
(com.github.johnfactotum.Foliate:83251): Gtk-WARNING **: 16:38:24.097: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

**Expected behavior**
Should open some dialog to add/open books.

**Version:**
 - Foliate version: 2.6.3
 - Ubuntu Mate 20.04
 - Mate Desktop Environment
 - Installation method: snap

**Comment by johnfactotum** [comment]
Looks like #725 and #815.
