### ISSUE TITLE
Changing Theme Crash

### ISSUE THREAD

**Issue by soundprojects** [johnfactotum/foliate#987]
**Describe the bug**
When trying to change the theme through the settings dropdown, Foliate crashes immediately

**To Reproduce**
2. Click on 'Theme'
3. Click Any other theme 
4. Crash

**Expected behavior**
Theme should change

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: PopOs Latest
 - Installation method: Flatpak

**Additional context**
Tried both Flatpak and PopOs Store versions

**Comment by BabaJi-0** [comment]
Duplicate of #719
