### ISSUE TITLE
Can't read / interact with main window when 'keyboard shortcuts' is open

### ISSUE THREAD

**Issue by sigio** [johnfactotum/foliate#988]
**Describe the bug**
Can't read a book, scroll or change page when the keyboard shortcuts window/help is open.

**Version:**
 - Foliate version: com.github.johnfactotum.foliate_2.6.4_all.deb
 - OS/Distribution and version: Debian Stable
 - Desktop environment: Gnome 3.38.5
 - Installation method: deb package

**Comment by johnfactotum** [comment]
This is by design. The window is modal. I can't find any specific reference on this, but as of GNOME 43, all GNOME apps (Files, Text Editor, Console, Web, Calculator, etc.) have modal keyboard shortcuts windows.

**Comment by sigio** [comment]
Highly irritating if you don't know them yet... I ended up making a screenshot of the window, closing it, and opening the screenshot in an imageviewer..
