### ISSUE TITLE
Crashing after a few minutes of use

### ISSUE THREAD

**Issue by uditsehra** [johnfactotum/foliate#989]
**Describe the bug**
App keeps crashing after a few minutes of use.

**To Reproduce**
I just opened an ebook and after reading it for a minute or two, the app suddenly crashed without any prompt.

**Expected behavior**
It shouldn't crash/close without the user clicking on the close button.

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Ubuntu 22.10
 - Desktop environment: Gnome 43.1
 - Installation method: Flatpak

**Additional context**

**Comment by johnfactotum** [comment]
Can you provide more information?
