### ISSUE TITLE
Some ePub not loading, loads metadata them hang on waiting page

### ISSUE THREAD

**Issue by EL-File4138** [johnfactotum/foliate#991]
**Describe the bug**
Some ePub files (With non-fatal error, correctly parsed by Ocular and **Epub.js**) won't load after reaching the loading state. Loading animation would hang and not proceed.
Not crashing or freezing, hamburger menu worked just fine.
Clearing book cache, restarting GDM, rebooting are all not helping.
Essentially the same with #636, just restricted to certain books.

**To Reproduce**
Same with #636.

**Expected behavior**
Same with #636.

**Screenshots**
![截图 2023-02-09 21-08-53](https://user-images.githubusercontent.com/28867264/217821788-04aeac34-d671-4f35-ac2e-a310ae5c66bc.png)

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Fedora 37 6.1.8-200.fc37.x86_64
 - Desktop environment: GNOME 43.2 Mutter
 - Installation method: RPM package (official)

**Additional context**
Some differences from the previous cases with various reasons:
- RPM native package rather than flatpak;
- Able to open most ePub rather fine, only limited on certain files;

Dug into the stderr log and made a controlled comparison with a normal opening behavior on essentially the same file content. The only noticeable difference is this:

```log
Gjs-Message: HH:MM:SS.sss: JS LOG: layout
*Gjs-Message: HH:MM:SS.sss: JS LOG: book-displayed
*Gjs-Message: HH:MM:SS.sss: JS LOG: relocated
*Gjs-Message: HH:MM:SS.sss: JS LOG: epubcfi(/6/60!/4/2/2/1:0)
Gjs-Message: HH:MM:SS.sss: JS LOG: writing to /home/<user>/.local/share/com.github.johnfactotum.Foliate/urn%3Auuid%3<REDACTED>.json
```

With the asterisked line not presenting in an erroneous opening session.
I believe this has to be where the bug is presented.

**Comment by AesaraB** [comment]
Have you tried [disabling power saving mode](969)?

**Comment by EL-File4138** [comment]
> Have you tried [disabling power saving mode](969)?

I'm using a desktop PC and never enabled this. I believe this is not the issue.

**Comment by johnfactotum** [comment]
Can you try the new renderer or the gtk4 branch?

**Comment by EL-File4138** [comment]
> Can you try the new renderer or the gtk4 branch?

Tested. Seems working well on the new branch.
I'm closing this and will wait for the merge.
