### ISSUE TITLE
zoom change affects all open books

### ISSUE THREAD

**Issue by joeyh** [johnfactotum/foliate#993]
**Describe the bug**

I have two books open. I'm using the publisher's fonts. In one book, the font is too small, so I press + to zoom it. But this affects the other book. Now the font used for that one is too large. So each time I switch back and forth between books I have to re-adjust the zoom setting.

**Expected behavior**

I would expect zooming to only affect one window or one book.

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: debian unstable
 - Desktop environment: xfce
 - Installation method: apt

**Comment by johnfactotum** [comment]
Good point. I guess I always thought of it as a permanent setting, and since there's no per-book preferences, it always applies to all books. But probably makes sense to make the zoom change temporary, similar to how browsers work.

**Comment by johnfactotum** [comment]
Fixed by 0b6929c3912ea983e5f37ec2e7a2d05a0aa0142a in the `gtk4` branch.
