### ISSUE TITLE
Reading position gets cut instead of chaper title when chapter title is too long

### ISSUE THREAD

**Issue by ivzave** [johnfactotum/foliate#996]
**Describe the bug**
In case of footer are is not enough to display both chapter title and reading position latter gets replaced with "..." instead of cutting down chapter title text.

**To Reproduce**
1. Open book.
2. Shrink window or reduce reading area of window by opening TOC.

**Expected behavior**
Reading position in footer is always visible because it's more important to be observable than last words of title.

**Screenshots**
![image](https://user-images.githubusercontent.com/1228526/223877027-d77eb7d3-2970-4622-a482-2b2ef446d1bd.png)

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Fedora 37
 - Desktop environment: 43.3
 - Installation method: dnf

**Comment by johnfactotum** [comment]
As it is now, one could argue that whatever you choose to be the left footer is always treated as the more important one. By default the left footer is the location, and the right one the section title. Somewhat accidentally, the section title also makes more sense on the right because the page itself is laid from the left, and so the left page often already has a title within the page.

**Comment by ivzave** [comment]
> By default the left footer is the location, and the right one the section title.

Somehow I got the opposite in my installation (maybe changed it in the past and don't remember) and was sure this is the default.

In my opinion footers could adjust their priority based on information chosen to display and less important footer could cut its text in case of need.

But nevermind, since only users who changed the default are affected maybe it doesn't worth much attention. Please close if you don't mind changing this behaviour.

**Comment by johnfactotum** [comment]
Currently, on the `gtk4` branch, the chapter title is shown at the top, together with the book's title when there are more than one columns:

![image](https://user-images.githubusercontent.com/50942278/224212560-c57cd0b6-a1ef-451f-8082-7be2383acc30.png)

But it only shows the chapter title when there's one column.

![image](https://user-images.githubusercontent.com/50942278/224212859-09628f3b-b1cb-4a58-b1c2-d41d6a217932.png)

The footer always shows the location, except if the book has a page list, in which case the page number (of the actual printed book) is always shown at the right. It cannot show the page number on the left, as it currently only computes the page number for the end of the visible range (same as the chapter title).

![image](https://user-images.githubusercontent.com/50942278/224213428-c61f8a7b-8f38-475a-84dc-a6bbdea50ced.png)

Now currently, unlike the stable version, all this is not configurable by the user. For now it just says that the chapter title is more important, but it might not be, depending on the situation. But to make this customizable, it would go from 2 choices in the stable version (left footer and right footer), to a whopping 6 (left header, right header, preferred header, left footer, left footer, preferred footer). And this is not counting if you want to get back the old behavior where two footers are shown together.

I think one possible solution would be to only make the right header/footer configurable. The left header would always be the book's title, and the left footer will always be the location. Then, when there is only one column, only show the right header/footer. This would solve both problems (showing chapter/page only on the right, and keeping the number of options in control while always showing the more important information).
