### ISSUE TITLE
Upon failing to open a book from history, we should return to the HIstory page.

### ISSUE THREAD

**Issue by ben2talk** [johnfactotum/foliate#999]
**Is your feature request related to a problem? Please describe.**
I recently tidied a few files - yet a record persists on the history page. 

**Describe the solution you'd like**
My first reaction would be to 'escape' or with an option to remove the record, or simply return to the history page and remove that item.

The problem is that we are trapped - if we don't wish to open a new file. 

The Library style history page is wonderful apart from this issue.

**Comment by johnfactotum** [comment]
In the `gtk4` branch it shows a button to take you back to the library page:

![image](https://user-images.githubusercontent.com/50942278/226175053-5579b283-7015-4e29-906d-4feb5080c78c.png)
